<?php declare(strict_types=1);$escape=static fn(string $v):string=>htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8'); ?>
<?php if($directoryPage->properties===[]): ?>
<div class="gateway-empty-state"><h2 class="gateway-empty-state__title">No properties found.</h2><p class="gateway-empty-state__message">Property records will appear here when available.</p></div>
<?php else: ?>
<div class="table-responsive gateway-directory-table-wrap"><table class="table gateway-directory-table gateway-property-table"><thead><tr><th scope="col">PropID</th><th scope="col">Name</th><th scope="col">Address</th><th scope="col">Phone</th><th scope="col">IVR</th><th scope="col">Manager</th><?php if($hr): ?><th scope="col">Action</th><?php endif; ?></tr></thead><tbody>
<?php foreach($directoryPage->properties as $property): ?><tr><td data-label="PropID"><?= $property->propId ?></td><td data-label="Name"><?= $escape($property->name) ?></td><td data-label="Address"><span class="gateway-property-address"><?= $escape($property->address) ?></span></td><td data-label="Phone"><?= $escape($property->phone) ?></td><td data-label="IVR"><?= $escape($property->ivr) ?></td><td data-label="Manager"><?= $escape($property->manager) ?></td><?php if($hr): ?><td data-label="Action"><a class="gateway-directory-action" href="/human-resources/properties/<?= $escape($property->publicId) ?>/edit">Edit</a></td><?php endif; ?></tr><?php endforeach; ?>
</tbody></table></div>
<?php $query=['search'=>$directoryPage->criteria->search,'sort'=>$directoryPage->criteria->sort,'direction'=>$directoryPage->criteria->direction,'per_page'=>(string)$directoryPage->criteria->perPage,'page'=>'__PAGE__'];$base=$hr?'/human-resources/properties':'/properties';$pageUrlPattern=$base.'?'.str_replace('__PAGE__','%d',http_build_query($query));$currentPage=$directoryPage->currentPage;$totalPages=$directoryPage->totalPages;require __DIR__.'/pagination.php'; ?>
<?php endif; ?>
