<?php
declare(strict_types=1);
namespace NpmGateway\Http;
use NpmGateway\Http\Controllers\AuthenticationController;
use NpmGateway\Http\Controllers\DashboardController;
use NpmGateway\Http\Middleware\RequireAuthenticationMiddleware;
use NpmGateway\Http\Controllers\EmployeeWorkspaceController;
use NpmGateway\Http\Controllers\PropertyWorkspaceController;
use NpmGateway\Http\Controllers\HumanResourcesController;
use NpmGateway\Http\Controllers\HrEmployeeController;
use NpmGateway\Http\Controllers\AdminController;
use NpmGateway\Http\Controllers\NotificationController;
use NpmGateway\Http\Controllers\CompanyNoticeController;
use NpmGateway\Http\Controllers\StorageController;
use NpmGateway\Http\Controllers\CorporateWorkspaceController;
use NpmGateway\Http\Controllers\EmployeeEmergencyContactController;
use NpmGateway\Http\Controllers\HrEmergencyContactController;
use NpmGateway\Http\Controllers\ManagerMaintenanceEmergencyContactController;
use NpmGateway\Http\Controllers\CommunityActionsController;
use NpmGateway\Http\Controllers\ApplicationReviewController;
use NpmGateway\Http\Controllers\CorporateApplicationReviewController;
use NpmGateway\Http\Controllers\CreditCardPurchaseController;
use NpmGateway\Http\Controllers\CorporateCreditCardPurchaseController;
use NpmGateway\Http\Controllers\RmCorrectionController;
use NpmGateway\Http\Controllers\CorporateRmCorrectionController;
use NpmGateway\Http\Controllers\OperationsOverviewController;
use NpmGateway\Http\Controllers\OperationsRmAuditPdfController;
use NpmGateway\Http\Controllers\RmAuditController;
use NpmGateway\Http\Controllers\CorporateRmAuditController;
use NpmGateway\Http\Controllers\SupplyOrderController;
use NpmGateway\Http\Controllers\MarketingFlyerController;
use NpmGateway\Http\Controllers\CallLogController;
use NpmGateway\Http\Controllers\CallLogReportController;
final class WebKernel
{
 public function __construct(private readonly AuthenticationController $authentication,private readonly DashboardController $dashboard,private readonly RequireAuthenticationMiddleware $middleware,private readonly ?EmployeeWorkspaceController $employees=null,private readonly ?PropertyWorkspaceController $properties=null,private readonly ?HumanResourcesController $hr=null,private readonly ?HrEmployeeController $hrEmployees=null,private readonly ?AdminController $admin=null,private readonly ?NotificationController $notifications=null,private readonly ?CompanyNoticeController $companyNotices=null,private readonly ?StorageController $storage=null,private readonly ?CorporateWorkspaceController $corporate=null,private readonly ?EmployeeEmergencyContactController $emergencyContact=null,private readonly ?HrEmergencyContactController $hrEmergencyContacts=null,private readonly ?ManagerMaintenanceEmergencyContactController $managerMaintenanceEmergencyContact=null,private readonly ?CommunityActionsController $communityActions=null,private readonly ?ApplicationReviewController $applicationReviews=null,private readonly ?CorporateApplicationReviewController $corporateApplicationReviews=null,private readonly ?CreditCardPurchaseController $creditCardPurchases=null,private readonly ?CorporateCreditCardPurchaseController $corporateCreditCardPurchases=null,private readonly ?RmCorrectionController $rmCorrections=null,private readonly ?CorporateRmCorrectionController $corporateRmCorrections=null,private readonly ?OperationsOverviewController $operationsOverview=null,private readonly ?RmAuditController $rmAudits=null,private readonly ?CorporateRmAuditController $corporateRmAudits=null,private readonly ?OperationsRmAuditPdfController $operationsRmAuditPdf=null,private readonly ?SupplyOrderController $supplyOrders=null,private readonly ?MarketingFlyerController $marketingFlyers=null,private readonly ?CallLogController $callLogs=null,private readonly ?CallLogReportController $callLogReports=null){}
 public function handle(Request $request,\DateTimeImmutable $now):Response
 {
  if($request->path==='/')return Response::redirect('/login');
  if($request->path==='/login'&&$request->method==='GET')return $this->authentication->loginForm();
  if($request->path==='/login'&&$request->method==='POST')return $this->authentication->login($request,$now);
  if($request->path==='/dashboard'&&$request->method==='GET')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->dashboard->index($c),$now);
  if($request->path==='/corporate/marketing/flyers'&&$this->marketingFlyers)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$request->method==='POST'?$this->marketingFlyers->store($request,$c):$this->marketingFlyers->index($request,$c),$now);
  if($request->path==='/corporate/marketing/flyers/new'&&$request->method==='GET'&&$this->marketingFlyers)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$this->marketingFlyers->create($c),$now);
  if(preg_match('#^/corporate/marketing/flyers/([0-9A-HJKMNP-TV-Z]{26})/(view|download)$#',$request->path,$m)&&$request->method==='GET'&&$this->marketingFlyers)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$this->marketingFlyers->asset($m[1],$m[2],$c),$now);
  if(preg_match('#^/corporate/marketing/flyers/([0-9A-HJKMNP-TV-Z]{26})/replace$#',$request->path,$m)&&$this->marketingFlyers)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$request->method==='POST'?$this->marketingFlyers->replace($request,$m[1],$c):$this->marketingFlyers->replaceForm($m[1],$c),$now);
  if(preg_match('#^/corporate/marketing/flyers/([0-9A-HJKMNP-TV-Z]{26})/delete$#',$request->path,$m)&&$request->method==='POST'&&$this->marketingFlyers)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$this->marketingFlyers->delete($request,$m[1],$c),$now);
  if(preg_match('#^/corporate/marketing/flyers/([0-9A-HJKMNP-TV-Z]{26})$#',$request->path,$m)&&$request->method==='GET'&&$this->marketingFlyers)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$this->marketingFlyers->show($m[1],$c),$now);
  if(preg_match('#^/community-actions/([a-z0-9-]+)/flyers/([0-9A-HJKMNP-TV-Z]{26})/download$#',$request->path,$m)&&$request->method==='GET'&&$this->marketingFlyers)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$this->marketingFlyers->managerDownload($m[1],$m[2],$c),$now);
  if(preg_match('#^/community-actions/([a-z0-9-]+)/rm-audits$#',$request->path,$m)&&$request->method==='GET'&&$this->rmAudits)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$this->rmAudits->index($request,$m[1],$c),$now);
  if(preg_match('#^/community-actions/([a-z0-9-]+)/rm-audits/([0-9A-HJKMNP-TV-Z]{26})$#',$request->path,$m)&&$request->method==='GET'&&$this->rmAudits)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$this->rmAudits->show($m[1],$m[2],$c),$now);
  if(preg_match('#^/community-actions/([a-z0-9-]+)/rm-audits/([0-9A-HJKMNP-TV-Z]{26})/complete$#',$request->path,$m)&&$request->method==='POST'&&$this->rmAudits)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$this->rmAudits->complete($request,$m[1],$m[2],$c),$now);
  if(preg_match('#^/community-actions/([a-z0-9-]+)/supply-orders/create$#',$request->path,$m)&&$request->method==='GET'&&$this->supplyOrders)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$this->supplyOrders->create($m[1],$c),$now);
  if(preg_match('#^/community-actions/([a-z0-9-]+)/supply-orders/([0-9A-HJKMNP-TV-Z]{26})$#',$request->path,$m)&&$request->method==='GET'&&$this->supplyOrders)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$this->supplyOrders->show($m[1],$m[2],$c),$now);
  if(preg_match('#^/community-actions/([a-z0-9-]+)/supply-orders$#',$request->path,$m)&&$this->supplyOrders)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$request->method==='POST'?$this->supplyOrders->store($request,$m[1],$c):$this->supplyOrders->index($m[1],$c),$now);
  if($request->path==='/corporate/rm-audits'&&$this->corporateRmAudits)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$request->method==='POST'?$this->corporateRmAudits->store($request,$c):$this->corporateRmAudits->index($request,$c),$now);
  if($request->path==='/corporate/rm-audits/create'&&$request->method==='GET'&&$this->corporateRmAudits)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$this->corporateRmAudits->create($c),$now);
  if(preg_match('#^/corporate/rm-audits/([0-9A-HJKMNP-TV-Z]{26})$#',$request->path,$m)&&$request->method==='GET'&&$this->corporateRmAudits)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$this->corporateRmAudits->show($m[1],$c),$now);
  if(preg_match('#^/corporate/rm-audits/([0-9A-HJKMNP-TV-Z]{26})/return$#',$request->path,$m)&&$request->method==='POST'&&$this->corporateRmAudits)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$this->corporateRmAudits->returnAudit($request,$m[1],$c),$now);
  if($request->path==='/corporate/credit-card-purchases'&&$this->corporateCreditCardPurchases){if($request->method==='GET')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->corporateCreditCardPurchases->index($request,$c),$now);if($request->method==='POST')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->corporateCreditCardPurchases->store($request,$c),$now);}
  if($request->path==='/corporate/credit-card-purchases/create'&&$request->method==='GET'&&$this->corporateCreditCardPurchases)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->corporateCreditCardPurchases->create($c),$now);
  if(preg_match('#^/corporate/credit-card-purchases/([0-9A-HJKMNP-TV-Z]{26})/edit$#',$request->path,$m)===1&&$this->corporateCreditCardPurchases){if($request->method==='GET')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->corporateCreditCardPurchases->edit($m[1],$c),$now);if($request->method==='POST')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->corporateCreditCardPurchases->correct($request,$m[1],$c),$now);}
  if(preg_match('#^/corporate/credit-card-purchases/([0-9A-HJKMNP-TV-Z]{26})/receipt$#',$request->path,$m)===1&&$request->method==='POST'&&$this->corporateCreditCardPurchases)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->corporateCreditCardPurchases->uploadReceipt($request,$m[1],$c),$now);
  if(preg_match('#^/corporate/credit-card-purchases/([0-9A-HJKMNP-TV-Z]{26})/receipts/([0-9A-HJKMNP-TV-Z]{26})/(view|download)$#',$request->path,$m)===1&&$request->method==='GET'&&$this->corporateCreditCardPurchases)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$m[3]==='download'?$this->corporateCreditCardPurchases->downloadReceipt($m[1],$m[2],$c):$this->corporateCreditCardPurchases->viewReceipt($m[1],$m[2],$c),$now);
  if(preg_match('#^/corporate/credit-card-purchases/([0-9A-HJKMNP-TV-Z]{26})$#',$request->path,$m)===1&&$request->method==='GET'&&$this->corporateCreditCardPurchases)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->corporateCreditCardPurchases->show($m[1],$c),$now);
  if($request->path==='/community-actions'&&$request->method==='GET'&&$this->communityActions)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->communityActions->index($c),$now);
  if(preg_match('#^/community-actions/([a-z0-9]+(?:-[a-z0-9]+)*)/rm-corrections/create$#',$request->path,$m)===1&&$request->method==='GET'&&$this->rmCorrections)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->rmCorrections->create($m[1],$c),$now);
  if(preg_match('#^/community-actions/([a-z0-9]+(?:-[a-z0-9]+)*)/rm-corrections/([0-9A-HJKMNP-TV-Z]{26})/respond$#',$request->path,$m)===1&&$this->rmCorrections){if($request->method==='GET')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->rmCorrections->respondForm($m[1],$m[2],$c),$now);if($request->method==='POST')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->rmCorrections->respond($request,$m[1],$m[2],$c),$now);}
  if(preg_match('#^/community-actions/([a-z0-9]+(?:-[a-z0-9]+)*)/rm-corrections/([0-9A-HJKMNP-TV-Z]{26})$#',$request->path,$m)===1&&$request->method==='GET'&&$this->rmCorrections)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->rmCorrections->show($m[1],$m[2],$c),$now);
  if(preg_match('#^/community-actions/([a-z0-9]+(?:-[a-z0-9]+)*)/rm-corrections$#',$request->path,$m)===1&&$this->rmCorrections){if($request->method==='GET')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->rmCorrections->index($request,$m[1],$c),$now);if($request->method==='POST')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->rmCorrections->store($request,$m[1],$c),$now);}
  if(preg_match('#^/community-actions/([a-z0-9]+(?:-[a-z0-9]+)*)/application-reviews/create$#',$request->path,$m)===1&&$request->method==='GET'&&$this->applicationReviews)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->applicationReviews->create($m[1],$c),$now);
  if(preg_match('#^/community-actions/([a-z0-9]+(?:-[a-z0-9]+)*)/application-reviews/([0-9A-HJKMNP-TV-Z]{26})$#',$request->path,$m)===1&&$request->method==='GET'&&$this->applicationReviews)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->applicationReviews->show($m[1],$m[2],$c),$now);
  if(preg_match('#^/community-actions/([a-z0-9]+(?:-[a-z0-9]+)*)/application-reviews$#',$request->path,$m)===1&&$this->applicationReviews){if($request->method==='GET')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->applicationReviews->index($request,$m[1],$c),$now);if($request->method==='POST')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->applicationReviews->store($request,$m[1],$c),$now);}
  if(preg_match('#^/community-actions/([a-z0-9]+(?:-[a-z0-9]+)*)/credit-card-purchases/create$#',$request->path,$m)===1&&$request->method==='GET'&&$this->creditCardPurchases)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->creditCardPurchases->create($m[1],$c),$now);
  if(preg_match('#^/community-actions/([a-z0-9]+(?:-[a-z0-9]+)*)/credit-card-purchases/([0-9A-HJKMNP-TV-Z]{26})/edit$#',$request->path,$m)===1&&$request->method==='GET'&&$this->creditCardPurchases)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->creditCardPurchases->edit($m[1],$m[2],$c),$now);
  if(preg_match('#^/community-actions/([a-z0-9]+(?:-[a-z0-9]+)*)/credit-card-purchases/([0-9A-HJKMNP-TV-Z]{26})/receipts/([0-9A-HJKMNP-TV-Z]{26})/(view|download)$#',$request->path,$m)===1&&$request->method==='GET'&&$this->creditCardPurchases)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$m[4]==='download'?$this->creditCardPurchases->downloadReceipt($m[1],$m[2],$m[3],$c):$this->creditCardPurchases->viewReceipt($m[1],$m[2],$m[3],$c),$now);  if(preg_match('#^/community-actions/([a-z0-9]+(?:-[a-z0-9]+)*)/credit-card-purchases/([0-9A-HJKMNP-TV-Z]{26})/receipt$#',$request->path,$m)===1&&$this->creditCardPurchases){if($request->method==='GET')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->creditCardPurchases->receipt($m[1],$m[2],$c),$now);if($request->method==='POST')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->creditCardPurchases->uploadReceipt($request,$m[1],$m[2],$c),$now);}
  if(preg_match('#^/community-actions/([a-z0-9]+(?:-[a-z0-9]+)*)/credit-card-purchases/([0-9A-HJKMNP-TV-Z]{26})$#',$request->path,$m)===1&&$this->creditCardPurchases){if($request->method==='GET')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->creditCardPurchases->show($m[1],$m[2],$c),$now);if($request->method==='POST')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->creditCardPurchases->correct($request,$m[1],$m[2],$c),$now);}
  if(preg_match('#^/community-actions/([a-z0-9]+(?:-[a-z0-9]+)*)/credit-card-purchases$#',$request->path,$m)===1&&$this->creditCardPurchases){if($request->method==='GET')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->creditCardPurchases->index($request,$m[1],$c),$now);if($request->method==='POST')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->creditCardPurchases->store($request,$m[1],$c),$now);}
  if(preg_match('#^/community-actions/([a-z0-9]+(?:-[a-z0-9]+)*)/([a-z0-9]+(?:-[a-z0-9]+)*)$#',$request->path,$m)===1&&$request->method==='GET'&&$this->communityActions)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->communityActions->action($m[1],$m[2],$c),$now);
  if(preg_match('#^/community-actions/([a-z0-9]+(?:-[a-z0-9]+)*)$#',$request->path,$m)===1&&$request->method==='GET'&&$this->communityActions)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->communityActions->show($m[1],$c),$now);
  if($request->path==='/my/emergency-contact'&&$request->method==='GET'&&$this->emergencyContact)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->emergencyContact->edit($c),$now);
  if($request->path==='/my/emergency-contact'&&$request->method==='POST'&&$this->emergencyContact)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->emergencyContact->save($request,$c),$now);
  if(preg_match('#^/manager/maintenance/([0-9A-HJKMNP-TV-Z]{26})/emergency-contact$#',$request->path,$m)===1&&$this->managerMaintenanceEmergencyContact){if($request->method==='GET')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->managerMaintenanceEmergencyContact->edit($m[1],$c),$now);if($request->method==='POST')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->managerMaintenanceEmergencyContact->save($request,$m[1],$c),$now);}
  if($request->path==='/corporate/human-resources/emergency-contacts'&&$request->method==='GET'&&$this->hrEmergencyContacts)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->hrEmergencyContacts->index($request,$c),$now);
  if(preg_match('#^/corporate/human-resources/emergency-contacts/([0-9A-HJKMNP-TV-Z]{26})/remind$#',$request->path,$m)===1&&$request->method==='POST'&&$this->hrEmergencyContacts)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->hrEmergencyContacts->remind($request,$m[1],$c),$now);
  if(preg_match('#^/corporate/human-resources/emergency-contacts/([0-9A-HJKMNP-TV-Z]{26})$#',$request->path,$m)===1&&$request->method==='GET'&&$this->hrEmergencyContacts)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->hrEmergencyContacts->show($m[1],$c),$now);
  if($this->corporate&&$request->method==='GET'){$method=match($request->path){'/corporate/operations'=>'operations','/corporate/operations/inventory-cf'=>'inventoryCf','/corporate/operations/inventory-hr'=>'inventoryHr','/corporate/operations/development'=>'development','/corporate/finance'=>'finance','/corporate/marketing'=>'marketing','/corporate/marketing/flyers'=>'flyers',default=>null};if($method!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->corporate->{$method}($c),$now);}
  if($request->path==='/corporate/application-reviews'&&$request->method==='GET'&&$this->corporateApplicationReviews)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->corporateApplicationReviews->index($request,$c),$now);
  if(preg_match('#^/corporate/application-reviews/([0-9A-HJKMNP-TV-Z]{26})/decision$#',$request->path,$m)===1&&$request->method==='POST'&&$this->corporateApplicationReviews)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->corporateApplicationReviews->decide($request,$m[1],$c),$now);
  if(preg_match('#^/corporate/application-reviews/([0-9A-HJKMNP-TV-Z]{26})$#',$request->path,$m)===1&&$request->method==='GET'&&$this->corporateApplicationReviews)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->corporateApplicationReviews->show($m[1],$c),$now);
  if($request->path==='/corporate/rm-corrections'&&$request->method==='GET'&&$this->corporateRmCorrections)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->corporateRmCorrections->index($request,$c),$now);
  if($request->path==='/corporate/operations/overview'&&$request->method==='GET'&&$this->operationsOverview)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->operationsOverview->index($c),$now);
  if($request->path==='/corporate/operations/overview/rm-corrections'&&$request->method==='GET'&&$this->operationsOverview)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->operationsOverview->rmCorrections($request,$c),$now);
  if(preg_match('#^/corporate/operations/overview/rm-corrections/([0-9A-HJKMNP-TV-Z]{26})$#',$request->path,$m)===1&&$request->method==='GET'&&$this->operationsOverview)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->operationsOverview->rmCorrection($m[1],$request,$c),$now);
  if($request->path==='/corporate/operations/overview/rm-audits'&&$request->method==='GET'&&$this->operationsOverview)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->operationsOverview->rmAudits($request,$c),$now);
  if($request->path==='/corporate/operations/overview/rm-audits/pdf'&&$request->method==='GET'&&$this->operationsRmAuditPdf)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->operationsRmAuditPdf->download($request,$c),$now);
  if(preg_match('#^/corporate/operations/overview/rm-audits/([0-9A-HJKMNP-TV-Z]{26})$#',$request->path,$m)===1&&$request->method==='GET'&&$this->operationsOverview)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->operationsOverview->rmAudit($m[1],$request,$c),$now);
  if(preg_match('#^/corporate/rm-corrections/([0-9A-HJKMNP-TV-Z]{26})/decision$#',$request->path,$m)===1&&$request->method==='POST'&&$this->corporateRmCorrections)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->corporateRmCorrections->decide($request,$m[1],$c),$now);
  if(preg_match('#^/corporate/rm-corrections/([0-9A-HJKMNP-TV-Z]{26})$#',$request->path,$m)===1&&$request->method==='GET'&&$this->corporateRmCorrections)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->corporateRmCorrections->show($m[1],$c),$now);
  if(preg_match('#^/storage/([0-9A-HJKMNP-TV-Z]{26})(/image)?$#',$request->path,$m)===1&&$request->method==='GET'&&$this->storage)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->storage->download($m[1],isset($m[2])&&$m[2]==='/image',$c),$now);
  if($request->path==='/notifications'&&$request->method==='GET'&&$this->notifications!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->notifications->index($request,$c),$now);
  if(preg_match('#^/notifications/([0-9A-HJKMNP-TV-Z]{26})$#',$request->path,$m)===1&&$request->method==='GET'&&$this->notifications!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->notifications->show($m[1],$c),$now);
  if(preg_match('#^/notifications/([0-9A-HJKMNP-TV-Z]{26})/acknowledge$#',$request->path,$m)===1&&$request->method==='POST'&&$this->notifications!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->notifications->acknowledge($request,$m[1],$c),$now);
  if($request->path==='/company-notices'&&$request->method==='GET'&&$this->companyNotices)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->companyNotices->index($c),$now);
  if($request->path==='/company-notices/create'&&$request->method==='GET'&&$this->companyNotices)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->companyNotices->create($request,$c),$now);
  if($request->path==='/company-notices/preview'&&$request->method==='POST'&&$this->companyNotices)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->companyNotices->preview($request,$c),$now);
  if($request->path==='/company-notices/discard'&&$request->method==='POST'&&$this->companyNotices)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->companyNotices->discard($request,$c),$now);
  if($request->path==='/company-notices/uploads/attachments'&&$request->method==='POST'&&$this->companyNotices)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->companyNotices->upload($request,'attachment',$c),$now);
  if($request->path==='/company-notices/uploads/images'&&$request->method==='POST'&&$this->companyNotices)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->companyNotices->upload($request,'embedded_image',$c),$now);
  if(preg_match('#^/company-notices/uploads/([0-9A-HJKMNP-TV-Z]{26})/remove$#',$request->path,$m)===1&&$request->method==='POST'&&$this->companyNotices)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->companyNotices->removeUpload($request,$m[1],$c),$now);
  if(preg_match('#^/company-notices/uploads/([0-9A-HJKMNP-TV-Z]{26})/(preview|download)$#',$request->path,$m)===1&&$request->method==='GET'&&$this->companyNotices)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->companyNotices->temporary($m[1],$m[2]==='preview',$request,$c),$now);
  if($request->path==='/company-notices/publish'&&$request->method==='POST'&&$this->companyNotices)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->companyNotices->publish($request,$c),$now);
  if(preg_match('#^/company-notices/([0-9A-HJKMNP-TV-Z]{26})$#',$request->path,$m)===1&&$request->method==='GET'&&$this->companyNotices)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->companyNotices->show($m[1],$c),$now);
  if($request->path==='/admin'&&$request->method==='GET'&&$this->admin!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->admin->index($c),$now);
  if($request->path==='/admin/call-logs'&&$request->method==='GET'&&$this->callLogs!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->callLogs->index($request,$c),$now);
  if($request->path==='/admin/call-logs/upload'&&$this->callLogs!==null){if($request->method==='GET')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->callLogs->upload($c),$now);if($request->method==='POST')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->callLogs->store($request,$c),$now);}
  if($request->path==='/admin/call-log-reports'&&$request->method==='GET'&&$this->callLogReports!==null)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$this->callLogReports->index($c),$now);
  if($request->path==='/admin/call-log-reports/facebook-performance'&&$request->method==='GET'&&$this->callLogReports!==null)return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$this->callLogReports->facebookPerformance($request,$c),$now);
  if($request->path==='/admin/category-access'&&$request->method==='GET'&&$this->admin!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->admin->categoryAccess($c),$now);
  if($request->path==='/admin/category-access'&&$request->method==='POST'&&$this->admin!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->admin->save($request,$c),$now);
  if($request->path==='/corporate/admin/property-access'&&$request->method==='GET'&&$this->admin!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->admin->propertyAccess($c),$now);
  if($request->path==='/corporate/admin/property-access'&&$request->method==='POST'&&$this->admin!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->admin->savePropertyAccess($request,$c),$now);
  if($request->path==='/employees'&&$request->method==='GET'&&$this->employees!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->employees->index($request,$c),$now);
  if($request->path==='/properties'&&$request->method==='GET'&&$this->properties!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->properties->directory($request,$c),$now);
  if($request->path==='/human-resources'&&$request->method==='GET'&&$this->hr!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->hr->index($c),$now);
  if($request->path==='/human-resources/employees'&&$request->method==='GET'&&$this->hrEmployees!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->hrEmployees->index($request,$c),$now);
  if($request->path==='/human-resources/employees/create'&&$request->method==='GET'&&$this->hrEmployees!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->hrEmployees->create($c),$now);
  if($request->path==='/human-resources/employees'&&$request->method==='POST'&&$this->hrEmployees!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->hrEmployees->store($request,$c),$now);
  if($request->path==='/human-resources/properties'&&$request->method==='GET'&&$this->properties!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->properties->hrDirectory($request,$c),$now);
  if($request->path==='/human-resources/properties/create'&&$request->method==='GET'&&$this->properties!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->properties->create($c),$now);
  if(preg_match('#^/human-resources/properties/([0-9A-HJKMNP-TV-Z]{26})/edit$#',$request->path,$m)===1&&$this->properties!==null){if($request->method==='GET')return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$this->properties->edit($m[1],$c),$now);if($request->method==='POST')return$this->middleware->handle($request,fn(AuthenticatedRequestContext$c):Response=>$this->properties->update($request,$m[1],$c),$now);}
  if($request->path==='/human-resources/properties'&&$request->method==='POST'&&$this->properties!==null)return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->properties->store($request,$c),$now);
  if($request->path==='/logout'&&$request->method==='GET')return new Response(405,'Method Not Allowed',['Allow'=>'POST']);
  if($request->path==='/logout'&&$request->method==='POST')return $this->middleware->handle($request,fn(AuthenticatedRequestContext $c):Response=>$this->authentication->logout($request,$c->rawToken,$now),$now);
  return new Response(404,'Not Found');
 }
}
