<?php
declare(strict_types=1);
namespace NpmGateway\Services;
use NpmGateway\Exceptions\Domain\InvalidApartmentsWorkbookException;
use NpmGateway\Support\PhoneFormatter;
use PhpOffice\PhpSpreadsheet\IOFactory;
final readonly class ApartmentsWorkbookParser
{
 public const CALL_HEADERS=['Property Name','Date/Time','Caller Phone Number','Ring-To Number','Tracking Number','Call Duration','Call Recording','Status'];
 public const EMAIL_HEADERS=['Property Name','Date/Time','Renter Name','Renter Phone Number','Renter Email'];
 public function __construct(private PhoneFormatter$phones){}
 public function parse(array$file):array
 {
  if((int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new InvalidApartmentsWorkbookException('Choose an Apartments.com workbook (.xlsx) to upload.');$path=(string)($file['tmp_name']??'');$name=basename((string)($file['name']??''));if(!is_file($path)||filesize($path)<1)throw new InvalidApartmentsWorkbookException('The uploaded Apartments.com file is empty or unavailable.');if(strtolower(pathinfo($name,PATHINFO_EXTENSION))!=='xlsx')throw new InvalidApartmentsWorkbookException('Upload the Apartments.com workbook in .xlsx format.');try{$type=IOFactory::identify($path);}catch(\Throwable){throw new InvalidApartmentsWorkbookException('The file is not a readable Apartments.com Excel workbook.');}if($type!=='Xlsx')throw new InvalidApartmentsWorkbookException('The uploaded file is not a genuine Excel .xlsx workbook.');try{$reader=IOFactory::createReader('Xlsx');$reader->setReadDataOnly(false);$book=$reader->load($path);}catch(\Throwable){throw new InvalidApartmentsWorkbookException('The Apartments.com workbook could not be read safely.');}
  try{$calls=[];$emails=[];$callSheets=[];$emailSheets=[];foreach($book->getWorksheetIterator()as$sheet){if(preg_match('/^Phone Calls - ([0-9]+)$/D',$sheet->getTitle(),$m))$callSheets[]=[$sheet,(int)$m[1]];elseif(preg_match('/^Emails - ([0-9]+)$/D',$sheet->getTitle(),$m))$emailSheets[]=[$sheet,(int)$m[1]];}if(count($callSheets)!==1)throw new InvalidApartmentsWorkbookException('The workbook must contain exactly one "Phone Calls - count" worksheet.');if(count($emailSheets)!==1)throw new InvalidApartmentsWorkbookException('The workbook must contain exactly one "Emails - count" worksheet.');[$callSheet,$callExpected]=$callSheets[0];[$emailSheet,$emailExpected]=$emailSheets[0];$this->headers($callSheet,self::CALL_HEADERS);$this->headers($emailSheet,self::EMAIL_HEADERS);$calls=$this->calls($callSheet);$emails=$this->emails($emailSheet);if(count($calls)!==$callExpected)throw new InvalidApartmentsWorkbookException("Phone worksheet count {$callExpected} does not match ".count($calls).' populated rows.');if(count($emails)!==$emailExpected)throw new InvalidApartmentsWorkbookException("Email worksheet count {$emailExpected} does not match ".count($emails).' populated rows.');if($calls===[]&&$emails===[])throw new InvalidApartmentsWorkbookException('The Apartments.com workbook contains no records.');$dates=[...array_column($calls,'occurred_at'),...array_column($emails,'occurred_at')];return['original_filename'=>$name,'file_sha256'=>hash_file('sha256',$path),'calls'=>$calls,'email_leads'=>$emails,'source_started_at'=>min($dates),'source_ended_at'=>max($dates)];}finally{$book->disconnectWorksheets();}
 }
 private function headers(object$sheet,array$expected):void{$actual=[];for($c=1;$c<=count($expected);$c++)$actual[]=trim((string)$sheet->getCell([$c,1])->getValue());$last=$sheet->getHighestDataColumn(1);$expectedLast=chr(64+count($expected));if($actual!==$expected||$last!==$expectedLast)throw new InvalidApartmentsWorkbookException($sheet->getTitle().' must contain exactly: '.implode(', ',$expected).'.');}
 private function calls(object$sheet):array{$rows=[];foreach($this->businessRows($sheet,8)as[$r,$v]){$required=[0,1,2,3,4,5,7];foreach($required as$i)if($v[$i]==='')throw new InvalidApartmentsWorkbookException("Phone row {$r} is missing a required value.");$rows[]=['source_property_name'=>$this->safe($v[0],150,$r,'Property Name'),'occurred_at'=>$this->time($v[1],$r),'caller_phone_raw'=>$this->safe($v[2],100,$r,'Caller Phone Number'),'caller_phone_normalized'=>$this->phones->normalize($v[2]),'ring_to_number_raw'=>$this->safe($v[3],100,$r,'Ring-To Number'),'ring_to_number_normalized'=>$this->phones->normalize($v[3]),'tracking_number_raw'=>$this->safe($v[4],100,$r,'Tracking Number'),'tracking_number_normalized'=>$this->phones->normalize($v[4]),'call_duration_seconds'=>$this->duration($v[5],$r),'call_recording_value'=>$v[6]===''?null:$this->safe($v[6],100,$r,'Call Recording'),'status'=>$this->safe($v[7],50,$r,'Status')];}return$rows;}
 private function emails(object$sheet):array{$rows=[];foreach($this->businessRows($sheet,5)as[$r,$v]){foreach([0,1,2,4]as$i)if($v[$i]==='')throw new InvalidApartmentsWorkbookException("Email row {$r} is missing a required value.");$phone=$v[3]===''?null:$this->safe($v[3],100,$r,'Renter Phone Number');$rows[]=['source_property_name'=>$this->safe($v[0],150,$r,'Property Name'),'occurred_at'=>$this->time($v[1],$r),'renter_name'=>$this->safe($v[2],200,$r,'Renter Name'),'renter_phone_raw'=>$phone,'renter_phone_normalized'=>$phone===null?null:$this->phones->normalize($phone),'renter_email'=>$this->safe($v[4],320,$r,'Renter Email')];}return$rows;}
 private function businessRows(object$sheet,int$columns):array{$rows=[];for($r=2;$r<=$sheet->getHighestDataRow();$r++){$values=[];for($c=1;$c<=$columns;$c++)$values[]=trim((string)$sheet->getCell([$c,$r])->getFormattedValue());if(array_filter($values,static fn($v)=>$v!=='')===[])continue;$rows[]=[$r,$values];}return$rows;}
 private function time(string$value,int$row):string{$date=\DateTimeImmutable::createFromFormat('!m/d/Y h:i:s A',$value);$errors=\DateTimeImmutable::getLastErrors();if($date===false||($errors!==false&&($errors['warning_count']>0||$errors['error_count']>0)))throw new InvalidApartmentsWorkbookException("Row {$row} has an invalid Date/Time.");return$date->format('Y-m-d H:i:s');}
 private function duration(string$value,int$row):int{if(preg_match('/^(\d+):([0-5]\d)$/D',$value,$m)===1)return(int)$m[1]*60+(int)$m[2];if(preg_match('/^(\d+):([0-5]\d):([0-5]\d)$/D',$value,$m)===1)return(int)$m[1]*3600+(int)$m[2]*60+(int)$m[3];throw new InvalidApartmentsWorkbookException("Phone row {$row} has an invalid Call Duration.");}
 private function safe(string$value,int$max,int$row,string$field):string{if($value===''||strlen($value)>$max||preg_match('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/',$value))throw new InvalidApartmentsWorkbookException("Row {$row} has an unsafe or oversized {$field}.");return$value;}
}
