<?php
declare(strict_types=1);
namespace NpmGateway\Services;
use NpmGateway\Contracts\CategoryAccessStoreInterface;
use NpmGateway\Contracts\ClockInterface;
use NpmGateway\Contracts\InitializationTransactionInterface;
use NpmGateway\Support\PublicIdGenerator;
use NpmGateway\ValueObjects\AuthenticatedUser;
final class CategoryAccessAdministrationService
{
    public function __construct(private readonly CategoryAccessStoreInterface $store,private readonly InitializationTransactionInterface $transaction,private readonly AuditService $audits,private readonly PublicIdGenerator $ids,private readonly ClockInterface $clock,private readonly array $categories,private readonly ?ProtectedPrincipalService $protected=null){}
    public function matrix():array
    {
        $members=[];foreach($this->store->memberships() as $row)$members[(int)$row['user_id']][(string)$row['category']]=true;$rows=[];foreach($this->store->allUsers() as $user){$user['categories']=array_keys($members[(int)$user['id']]??[]);$user=$this->protected?->decorate($user)??($user+['protected'=>false,'protected_categories'=>[]]);unset($user['id'],$user['employee_id'],$user['employee_public_id'],$user['employment_status']);$rows[]=$user;}return ['categories'=>$this->categories,'users'=>$rows];
    }
    public function applyChanges(array $input,AuthenticatedUser $actor):int
    {
        $submitted=$input['users']??null;$selected=$input['access']??null;if(!is_array($submitted)||!is_array($selected)||!array_is_list($submitted)||count($submitted)!==count(array_unique($submitted)))throw new \InvalidArgumentException('Invalid category access submission.');$all=$this->store->allUsers();$byPublic=[];foreach($all as $user)$byPublic[(string)$user['public_id']]=$user;if(array_keys($this->categories)!==['operations','human-resources','company-notices','application-reviews','rm-corrections','rm-audit','finance','marketing','admin','credit-cards'])throw new \InvalidArgumentException('Invalid category configuration.');if(count($submitted)!==count($byPublic)||array_diff($submitted,array_keys($byPublic))!==[]||array_diff(array_keys($byPublic),$submitted)!==[])throw new \InvalidArgumentException('One or more submitted users could not be validated.');foreach(array_keys($selected) as $publicId)if(!is_string($publicId)||!in_array($publicId,$submitted,true))throw new \InvalidArgumentException('One or more submitted users could not be validated.');
        $current=[];foreach($this->store->memberships() as $row)$current[(int)$row['user_id']][(string)$row['category']]=true;$desired=$current;foreach($submitted as $publicId){$user=$byPublic[$publicId];$desired[(int)$user['id']]=[];$categories=$selected[$publicId]??[];if(!is_array($categories))throw new \InvalidArgumentException('Invalid category selection.');foreach($categories as $category=>$checked){if(!is_string($category)||!array_key_exists($category,$this->categories))throw new \InvalidArgumentException('An unknown category was submitted.');if($checked!==true)throw new \InvalidArgumentException('Invalid category checkbox value.');$desired[(int)$user['id']][$category]=true;}}
        foreach($submitted as $publicId)$this->protected?->assertCategoryBaseline($byPublic[$publicId],$desired[(int)$byPublic[$publicId]['id']]??[],$actor);$actorDesired=$desired[$actor->id]??[];if(isset($current[$actor->id]['admin'])&&!isset($actorDesired['admin']))throw new \InvalidArgumentException('You cannot remove your own Admin access.');$activeAdmins=0;foreach($all as $user)if($user['status']==='active'&&isset($desired[(int)$user['id']]['admin']))$activeAdmins++;if($activeAdmins===0)throw new \InvalidArgumentException('At least one active Gateway user must retain Admin access.');
        $changes=0;$timestamp=$this->clock->now()->format('Y-m-d H:i:s');$this->transaction->begin();try{$fresh=[];foreach($this->store->allUsers() as $row)$fresh[(string)$row['public_id']]=$row;$freshCurrent=[];foreach($this->store->memberships() as $row)$freshCurrent[(int)$row['user_id']][(string)$row['category']]=true;foreach($submitted as $publicId)$this->protected?->assertCategoryBaseline($fresh[$publicId]??$byPublic[$publicId],$desired[(int)$byPublic[$publicId]['id']]??[],$actor);foreach($submitted as $publicId){$target=$byPublic[$publicId];$id=(int)$target['id'];foreach(array_keys($this->categories) as $category){$had=isset($freshCurrent[$id][$category]);$has=isset($desired[$id][$category]);if($had===$has)continue;if($has)$this->store->grant(['public_id'=>$this->ids->generate(),'user_id'=>$id,'category'=>$category,'granted_by_user_id'=>$actor->id,'granted_at'=>$timestamp]);else $this->store->revoke($id,$category);$changes++;$this->audits->record($has?'admin.category_access_granted':'admin.category_access_revoked',$actor->id,$actor->employeeId,$actor->publicId,$has?'Corporate category access granted.':'Corporate category access revoked.',['target_user_public_id'=>$target['public_id'],'target_username'=>$target['username'],'category'=>$category,'actor_user_public_id'=>$actor->publicId,'resulting_category_count'=>count($desired[$id])],$timestamp);}}if($changes>0)$this->audits->record('admin.category_access_updated',$actor->id,$actor->employeeId,$actor->publicId,'Corporate category access matrix updated.',['actor_user_public_id'=>$actor->publicId,'change_count'=>$changes],$timestamp);$this->transaction->commit();}catch(\Throwable $e){$this->transaction->rollback();throw $e;}return $changes;
    }
}
