<?php
declare(strict_types=1);namespace NpmGateway\Services;
use NpmGateway\Contracts\ClockInterface;use NpmGateway\Contracts\InitializationTransactionInterface;use NpmGateway\Exceptions\Domain\CommunityActionPropertyForbiddenException;use NpmGateway\Exceptions\Domain\InvalidCreditCardPurchaseException;use NpmGateway\Http\AuthenticatedRequestContext;use NpmGateway\Repositories\CreditCardPurchaseRepository;use NpmGateway\Support\PublicIdGenerator;use NpmGateway\ValueObjects\CommunityActionContext;
final class CreditCardPurchaseService{public function __construct(private readonly CreditCardPurchaseRepository $repo,private readonly CreditCardPurchaseValidator $validator,private readonly InitializationTransactionInterface $tx,private readonly PublicIdGenerator $ids,private readonly ClockInterface $clock,private readonly AuditService $audits,private readonly PropertyAccessService $access,private readonly GatewayStorageService $storage,private readonly \NpmGateway\Contracts\StorageObjectStoreInterface $objects){}
 public function list(int $propertyId,string $search,string $receiptStatus):array{return $this->repo->list($propertyId,$search,$receiptStatus);}
 public function summary(int $propertyId,string $search,string $receiptStatus):array{return $this->repo->summary($propertyId,$search,$receiptStatus);}
 public function eligibleEmployees(int $propertyId):array{return $this->repo->eligibleEmployees($propertyId);}
 public function detail(string $publicId,int $propertyId):?array{return $this->repo->detail($publicId,$propertyId);}
 public function receiptDocument(string $purchasePublicId,string $receiptPublicId,int $propertyId):?array{return $this->repo->currentReceiptDocument($purchasePublicId,$receiptPublicId,$propertyId);}
 public function publishedReceipt(array $purchase):?array{if(!is_string($purchase['storage_public_id']??null))return null;$object=$this->objects->findByPublicId($purchase['storage_public_id']);return $object&&$object['lifecycle_state']==='published'?$object:null;}
 public function post(CommunityActionContext $c,array $post,array $files):array{$data=$this->validator->validate($post,$this->clock->now());$file=(array)($files['receipt']??[]);$hasFile=(int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_NO_FILE;if($hasFile&&$data['receipt_missing'])throw new InvalidCreditCardPurchaseException(['receipt'=>'Upload a receipt or confirm that the receipt is unavailable, not both.'],$data);if(!$hasFile&&!$data['receipt_missing'])throw new InvalidCreditCardPurchaseException(['receipt'=>'Upload a receipt or confirm that the receipt is unavailable.'],$data);$upload=null;if($hasFile){$ext=strtolower((string)pathinfo((string)($file['name']??''),PATHINFO_EXTENSION));if(!in_array($ext,['pdf','jpg','jpeg','png'],true))throw new InvalidCreditCardPurchaseException(['receipt'=>'Upload a PDF, JPEG, or PNG receipt.'],$data);try{$upload=$this->storage->upload($file,'credit_card_receipt',$c->user,0,0);}catch(\InvalidArgumentException $e){throw new InvalidCreditCardPurchaseException(['receipt'=>$e->getMessage()],$data);}}
  $eligible=$this->repo->eligibleEmployees($c->propertyId);$purchaser=null;foreach($eligible as $employee)if(hash_equals((string)$employee['public_id'],$data['purchased_by_employee_public_id']))$purchaser=$employee;if(!$purchaser)throw new InvalidCreditCardPurchaseException(['purchased_by_employee_public_id'=>'Choose an active employee assigned to this property.'],$data);$public=$this->ids->generate();$at=$this->clock->now()->format('Y-m-d H:i:s');$this->tx->begin();try{if(!$this->access->canAccessProperty(new AuthenticatedRequestContext($c->user,''),$c->propertyId))throw new CommunityActionPropertyForbiddenException();$fresh=false;foreach($this->repo->eligibleEmployees($c->propertyId) as $employee)if((int)$employee['id']===(int)$purchaser['id'])$fresh=true;if(!$fresh)throw new InvalidCreditCardPurchaseException(['purchased_by_employee_public_id'=>'The selected employee is no longer eligible.'],$data);$status=$upload?'attached':'missing';$id=$this->repo->insert(['public_id'=>$public,'property_id'=>$c->propertyId,'card_last_four'=>$data['card_last_four'],'purchase_date'=>$data['purchase_date'],'amount'=>$data['amount'],'purchaser_id'=>$purchaser['id'],'submitter_id'=>$c->userId,'vendor'=>$data['vendor'],'description'=>$data['description'],'receipt_status'=>$status,'missing_reason'=>$status==='missing'?$data['missing_receipt_reason']:null,'timestamp'=>$at]);if($upload){$this->repo->linkReceipt($id,(int)$upload['id'],$c->userId,$this->ids->generate(),$at);if(!$this->objects->markPublished((int)$upload['id'],$at))throw new \RuntimeException('Receipt publication failed.');}$this->repo->history($id,$this->ids->generate(),'posted',$c->userId,['receipt_status'=>$status],null,$at);$this->audits->record('credit_card_purchase.posted',$c->userId,$c->employeeId,$c->userPublicId,'Credit card purchase posted.',['purchase_public_id'=>$public,'property_public_id'=>$c->propertyPublicId,'purchaser_employee_public_id'=>$purchaser['public_id'],'submitter_user_public_id'=>$c->userPublicId,'card_last_four'=>$data['card_last_four'],'amount'=>$data['amount'],'purchase_date'=>$data['purchase_date'],'receipt_status'=>$status],$at);if($status==='missing')$this->audits->record('credit_card_purchase.receipt_missing',$c->userId,$c->employeeId,$c->userPublicId,'Receipt documented as unavailable.',['purchase_public_id'=>$public,'property_public_id'=>$c->propertyPublicId,'receipt_status'=>'missing'],$at);$this->tx->commit();return ['public_id'=>$public,'receipt_status'=>$status];}catch(\Throwable $e){$this->tx->rollback();throw $e;}}
 public function addReceipt(CommunityActionContext $c,string $public,array $file):void{$purchase=$this->repo->detail($public,$c->propertyId);if(!$purchase)throw new \OutOfBoundsException();if($purchase['receipt_status']==='attached')throw new \InvalidArgumentException('A receipt is already attached.');$ext=strtolower((string)pathinfo((string)($file['name']??''),PATHINFO_EXTENSION));if(!in_array($ext,['pdf','jpg','jpeg','png'],true))throw new \InvalidArgumentException('Upload a PDF, JPEG, or PNG receipt.');$upload=$this->storage->upload($file,'credit_card_receipt',$c->user,0,0);$at=$this->clock->now()->format('Y-m-d H:i:s');$this->tx->begin();try{if(!$this->access->canAccessProperty(new AuthenticatedRequestContext($c->user,''),$c->propertyId))throw new CommunityActionPropertyForbiddenException();$locked=$this->repo->detail($public,$c->propertyId,true);if(!$locked)throw new \OutOfBoundsException();$this->repo->attachReceipt((int)$locked['id'],(int)$upload['id'],$c->userId,$this->ids->generate(),$at);if(!$this->objects->markPublished((int)$upload['id'],$at))throw new \RuntimeException('Receipt publication failed.');$this->repo->history((int)$locked['id'],$this->ids->generate(),'receipt_uploaded',$c->userId,[],null,$at);$this->audits->record('credit_card_purchase.receipt_uploaded',$c->userId,$c->employeeId,$c->userPublicId,'Credit card purchase receipt uploaded.',['purchase_public_id'=>$public,'property_public_id'=>$c->propertyPublicId,'receipt_status'=>'attached'],$at);$this->tx->commit();}catch(\Throwable $e){$this->tx->rollback();throw $e;}}
}
