<?php
declare(strict_types=1);
namespace NpmGateway\Services;
use NpmGateway\Contracts\ClockInterface;
use NpmGateway\Notifications\EciReminderEmailSender;
use NpmGateway\Repositories\AuditRepository;
use NpmGateway\Repositories\EmployeeEmergencyContactRepository;
use NpmGateway\ValueObjects\AuthenticatedUser;
final class EciReminderService
{
 public function __construct(private readonly EmployeeEmergencyContactRepository $contacts,private readonly GatewayNotificationRecipientEligibilityPolicy $policy,private readonly EciReminderEmailSender $email,private readonly AuditRepository $auditRepository,private readonly AuditService $audits,private readonly ClockInterface $clock){}
 public function availability(string $employeePublicId):array{$employee=$this->contacts->reminderRoutingCandidate($employeePublicId);if($employee===null)return ['status'=>'not_found'];if($employee['employment_status']!=='active')return ['status'=>'inactive'];if($this->contacts->existsForEmployee((int)$employee['id']))return ['status'=>'completed'];$since=$this->clock->now()->modify('-24 hours')->format('Y-m-d H:i:s');if($this->auditRepository->existsEventForEntitySince('employee.emergency_contact_reminder_sent',$employeePublicId,$since))return ['status'=>'cooldown'];$class=(string)$employee['employee_class'];if($class==='corporate'){if(!$this->policy->isEligibleUser($employee))return ['status'=>'ineligible'];$destination=strtolower(trim((string)$employee['business_email']));if(filter_var($destination,FILTER_VALIDATE_EMAIL)===false)return ['status'=>'missing_email'];return ['status'=>'available','routing_type'=>'employee_business_email','destination'=>$destination,'employee'=>$employee];}if(in_array($class,['manager','maintenance'],true)){if(empty($employee['property_public_id']))return ['status'=>'missing_property'];$destination=strtolower(trim((string)$employee['manager_email']));if(filter_var($destination,FILTER_VALIDATE_EMAIL)===false)return ['status'=>'missing_manager_mailbox'];return ['status'=>'available','routing_type'=>'property_manager_mailbox','destination'=>$destination,'employee'=>$employee];}return ['status'=>'ineligible'];}
 public function send(string $employeePublicId,AuthenticatedUser $actor):array{$route=$this->availability($employeePublicId);if($route['status']!=='available')return $route;$employee=$route['employee'];if(!$this->email->send((string)$route['destination'],$employee))return ['status'=>'failed'];$at=$this->clock->now()->format('Y-m-d H:i:s');$metadata=['subject_employee_public_id'=>$employeePublicId,'acting_user_public_id'=>$actor->publicId,'employee_class'=>$employee['employee_class'],'routing_type'=>$route['routing_type'],'delivery_result_category'=>'sent'];if(!empty($employee['property_public_id']))$metadata['property_public_id']=$employee['property_public_id'];$this->audits->recordEmployee('employee.emergency_contact_reminder_sent',$actor->id,$actor->employeeId,(int)$employee['id'],$employeePublicId,'ECI completion reminder sent.',$metadata,$at);return ['status'=>'sent'];}
}
