<?php
declare(strict_types=1);
namespace NpmGateway\Services;
use NpmGateway\Contracts\ClockInterface;
use NpmGateway\Contracts\InitializationTransactionInterface;
use NpmGateway\Contracts\PropertyAccessStoreInterface;
use NpmGateway\Http\AuthenticatedRequestContext;
use NpmGateway\Support\PublicIdGenerator;
use NpmGateway\ValueObjects\AuthenticatedUser;
final class PropertyAccessService
{
 public function __construct(private readonly PropertyAccessStoreInterface $store,private readonly InitializationTransactionInterface $transaction,private readonly AuditService $audits,private readonly PublicIdGenerator $ids,private readonly ClockInterface $clock){}
 public function canAccessProperty(AuthenticatedRequestContext $context,int $propertyId):bool{return $propertyId>0&&$this->store->hasEffectiveAccess($context->user->id,$propertyId);}
 public function accessibleActiveProperties(AuthenticatedRequestContext $context):array{return $this->store->accessibleActiveProperties($context->user->id);}
 public function resolveAccessibleProperty(AuthenticatedRequestContext $context,string $slug):array{$property=$this->store->activePropertyBySlug($slug);if($property===null)return ['status'=>'not_found','property'=>null];return $this->canAccessProperty($context,(int)$property['id'])?['status'=>'authorized','property'=>$property]:['status'=>'forbidden','property'=>null];}
 public function accessMatrix():array{$members=[];foreach($this->store->memberships() as $row)$members[(int)$row['user_id']][(int)$row['property_id']]=true;$properties=$this->store->activeProperties();$employees=[];foreach($this->store->employeesForMatrix() as $row){$assignable=$row['employee_class']!=='maintenance'&&$row['employment_status']==='active'&&$row['user_id']!==null&&$row['user_status']==='active';$row['assignable']=$assignable;$row['reason']=$assignable?'':($row['employment_status']!=='active'?'Inactive':'No Gateway access');$row['properties']=$row['user_id']===null?[]:array_keys($members[(int)$row['user_id']]??[]);unset($row['employee_id'],$row['user_id']);$employees[]=$row;}return ['properties'=>$properties,'employees'=>$employees];}
 public function applyChanges(array $input,AuthenticatedUser $actor):int
 {
  $submitted=$input['employees']??null;$selected=$input['access']??null;if(!is_array($submitted)||!array_is_list($submitted)||!is_array($selected)||count($submitted)!==count(array_unique($submitted)))throw new \InvalidArgumentException('Invalid Property Access submission.');$employees=$this->store->employeesForMatrix();$byPublic=[];foreach($employees as $employee)$byPublic[(string)$employee['employee_public_id']]=$employee;if(count($submitted)!==count($byPublic)||array_diff($submitted,array_keys($byPublic))!==[]||array_diff(array_keys($byPublic),$submitted)!==[])throw new \InvalidArgumentException('One or more submitted employees could not be validated.');$properties=$this->store->activeProperties();$propertiesByPublic=[];foreach($properties as $property)$propertiesByPublic[(string)$property['public_id']]=$property;foreach(array_keys($selected) as $employeePublic)if(!is_string($employeePublic)||!in_array($employeePublic,$submitted,true))throw new \InvalidArgumentException('One or more submitted employees could not be validated.');
  $current=[];foreach($this->store->memberships() as $row)$current[(int)$row['user_id']][(int)$row['property_id']]=true;$desired=$current;foreach($submitted as $employeePublic){$employee=$byPublic[$employeePublic];$assignable=$employee['employee_class']!=='maintenance'&&$employee['employment_status']==='active'&&$employee['user_id']!==null&&$employee['user_status']==='active';$choices=$selected[$employeePublic]??[];if(!is_array($choices))throw new \InvalidArgumentException('Invalid property selection.');if(!$assignable&&$choices!==[])throw new \InvalidArgumentException('Property Access cannot be assigned to this employee.');if($employee['user_id']===null)continue;$desired[(int)$employee['user_id']]=[];foreach($choices as $propertyPublic=>$checked){if(!is_string($propertyPublic)||!isset($propertiesByPublic[$propertyPublic])||$checked!==true)throw new \InvalidArgumentException('An unknown or inactive property was submitted.');$desired[(int)$employee['user_id']][(int)$propertiesByPublic[$propertyPublic]['id']]=true;}}
  $changes=0;$at=$this->clock->now()->format('Y-m-d H:i:s');$this->transaction->begin();try{foreach($submitted as $employeePublic){$target=$byPublic[$employeePublic];if($target['user_id']===null)continue;$userId=(int)$target['user_id'];foreach($properties as $property){$propertyId=(int)$property['id'];$had=isset($current[$userId][$propertyId]);$has=isset($desired[$userId][$propertyId]);if($had===$has)continue;if($has)$this->store->grant(['public_id'=>$this->ids->generate(),'user_id'=>$userId,'property_id'=>$propertyId,'granted_by_user_id'=>$actor->id,'granted_at'=>$at]);else $this->store->revoke($userId,$propertyId);$changes++;$this->audits->record($has?'property_access.granted':'property_access.revoked',$actor->id,$actor->employeeId,$actor->publicId,$has?'Property access granted.':'Property access revoked.',['target_user_public_id'=>$target['user_public_id'],'property_public_id'=>$property['public_id'],'actor_user_public_id'=>$actor->publicId,'operation'=>$has?'grant':'revoke'],$at);}}$this->transaction->commit();}catch(\Throwable $e){$this->transaction->rollback();throw $e;}return $changes;
 }
}
