<?php
declare(strict_types=1);
namespace NpmGateway\Services;
final class RichTextSanitizer
{
 private const TAGS=['p','br','strong','em','ul','ol','li','a','img'];
 private const LEGACY_IMAGE_WIDTHS=['small'=>25,'medium'=>50,'large'=>75,'full'=>100];
 public function sanitize(string $html):string
 {
  if(strlen($html)>50000)throw new \InvalidArgumentException('Notice message is too long.');if(preg_match('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/',$html))throw new \InvalidArgumentException('Notice message contains invalid characters.');$dom=new \DOMDocument('1.0','UTF-8');$previous=libxml_use_internal_errors(true);$dom->loadHTML('<?xml encoding="UTF-8"><div id="gateway-root">'.$html.'</div>',LIBXML_HTML_NOIMPLIED|LIBXML_HTML_NODEFDTD);libxml_clear_errors();libxml_use_internal_errors($previous);$root=$dom->getElementById('gateway-root');if(!$root)return '';$this->clean($root);$out='';foreach(iterator_to_array($root->childNodes) as $child)$out.=$dom->saveHTML($child);$out=trim($out);if(trim(strip_tags($out))===''&&!str_contains($out,'<img'))throw new \InvalidArgumentException('Notice message is required.');return $out;
 }
 public function imageReferences(string $html):array{$dom=new \DOMDocument();@$dom->loadHTML('<div>'.$html.'</div>',LIBXML_HTML_NOIMPLIED|LIBXML_HTML_NODEFDTD);$refs=[];foreach($dom->getElementsByTagName('img') as $img){$id=$img->getAttribute('data-storage-object-public-id');$alt=trim($img->getAttribute('alt'));$width=$this->imageWidth($img);$align=$this->imageAlignment($img);if(!preg_match('/^[0-9A-HJKMNP-TV-Z]{26}$/D',$id)||$alt===''||$width===null||$align===null)throw new \InvalidArgumentException('Every embedded image requires a valid upload, meaningful alt text, approved width, and approved alignment.');$refs[$id]=['alt'=>$alt,'width'=>$width,'align'=>$align];}return $refs;}
 public function renderImageWidths(string $html):string{return (string)preg_replace_callback('/<img\b[^>]*>/i',function(array $match):string{$tag=$match[0];$width=$this->widthFromTag($tag);$tag=(string)preg_replace('/\s+(?:style|width|height)="[^"]*"/i','',$tag);return rtrim(substr($tag,0,-1)).' style="width:'.$width.'%;max-width:100%;height:auto;" >';},$html);}
 public function plainText(string $html):string{$dom=new \DOMDocument();@$dom->loadHTML('<div>'.$html.'</div>',LIBXML_HTML_NOIMPLIED|LIBXML_HTML_NODEFDTD);foreach($dom->getElementsByTagName('a') as $a)$a->appendChild($dom->createTextNode(' ('.$a->getAttribute('href').')'));foreach($dom->getElementsByTagName('li') as $li)$li->insertBefore($dom->createTextNode('- '),$li->firstChild);foreach(['p','li','br'] as $tag)foreach(iterator_to_array($dom->getElementsByTagName($tag)) as $node)$node->appendChild($dom->createTextNode("\n"));return trim((string)preg_replace('/\n{3,}/',"\n\n",html_entity_decode(strip_tags($dom->saveHTML()),ENT_QUOTES|ENT_HTML5,'UTF-8')));}
 private function clean(\DOMNode $parent):void{foreach(iterator_to_array($parent->childNodes) as $node){if($node instanceof \DOMElement){$tag=strtolower($node->tagName);if(!in_array($tag,self::TAGS,true)){if(in_array($tag,['script','style','iframe','object','embed','svg','video','audio','form','input','button'],true)){$parent->removeChild($node);continue;}while($node->firstChild)$parent->insertBefore($node->firstChild,$node);$parent->removeChild($node);continue;}$allowed=match($tag){'a'=>['href','title'],'img'=>['src','alt','data-storage-object-public-id','data-gateway-image-width','data-gateway-image-size','data-gateway-image-align'],default=>[]};foreach(iterator_to_array($node->attributes) as $attribute)if(!in_array(strtolower($attribute->name),$allowed,true))$node->removeAttribute($attribute->name);if($tag==='a'){if(!$this->safeLink($node->getAttribute('href')))$node->removeAttribute('href');}if($tag==='img'){$id=$node->getAttribute('data-storage-object-public-id');$width=$this->imageWidth($node);$align=$this->imageAlignment($node);if(!preg_match('/^[0-9A-HJKMNP-TV-Z]{26}$/D',$id)||$node->getAttribute('src')!=='gateway-storage:'.$id||$width===null||$align===null){$parent->removeChild($node);continue;}$node->removeAttribute('data-gateway-image-size');$node->setAttribute('data-gateway-image-width',(string)$width);$node->setAttribute('data-gateway-image-align',$align);}$this->clean($node);}}
 }
 private function imageWidth(\DOMElement $image):?int{$raw=$image->getAttribute('data-gateway-image-width');if($raw!=='')return preg_match('/^(?:[1-9][0-9]|100)$/D',$raw)?(int)$raw:null;$legacy=strtolower($image->getAttribute('data-gateway-image-size'));return self::LEGACY_IMAGE_WIDTHS[$legacy]??($legacy===''?50:null);}
 private function imageAlignment(\DOMElement $image):?string{$alignment=strtolower($image->getAttribute('data-gateway-image-align')?:'left');return in_array($alignment,['left','center','right'],true)?$alignment:null;}
 private function widthFromTag(string $tag):int{if(preg_match('/\bdata-gateway-image-width="((?:[1-9][0-9]|100))"/i',$tag,$match))return (int)$match[1];if(preg_match('/\bdata-gateway-image-size="(small|medium|large|full)"/i',$tag,$match))return self::LEGACY_IMAGE_WIDTHS[strtolower($match[1])];return 50;}
 private function safeLink(string $url):bool{if($url===''||str_starts_with($url,'//')||preg_match('/[\x00-\x20\x7F]/',$url))return false;$parts=parse_url($url);if(!is_array($parts)||isset($parts['user'])||isset($parts['pass']))return false;return in_array(strtolower((string)($parts['scheme']??'')),['http','https','mailto'],true);}
}
