<?php
declare(strict_types=1);
namespace NpmGateway\Services;
use NpmGateway\Contracts\ClockInterface;
use NpmGateway\Contracts\InitializationTransactionInterface;
use NpmGateway\Exceptions\Domain\CommunityActionPropertyForbiddenException;
use NpmGateway\Exceptions\Domain\RmCorrectionStateConflictException;
use NpmGateway\Http\AuthenticatedRequestContext;
use NpmGateway\Notifications\RmCorrectionEmailSender;
use NpmGateway\Repositories\RmCorrectionRepository;
use NpmGateway\Support\PublicIdGenerator;
use NpmGateway\ValueObjects\AuthenticatedUser;
use NpmGateway\ValueObjects\CommunityActionContext;
final class RmCorrectionService
{
 public function __construct(private readonly RmCorrectionRepository $repo,private readonly RmCorrectionValidator $validator,private readonly InitializationTransactionInterface $tx,private readonly PublicIdGenerator $ids,private readonly ClockInterface $clock,private readonly AuditService $audit,private readonly RmCorrectionEmailSender $email,private readonly PropertyAccessService $access){}
 public function submit(CommunityActionContext $c,array $post):array{$d=$this->validator->submission($post);$at=$this->now();$public=$this->ids->generate();$this->tx->begin();try{if(!$this->access->canAccessProperty(new AuthenticatedRequestContext($c->user,''),$c->propertyId))throw new CommunityActionPropertyForbiddenException();$id=$this->repo->insert(['public_id'=>$public,'property_id'=>$c->propertyId,'actor_id'=>$c->userId]+$d+['timestamp'=>$at]);$this->event($id,'submitted',$c->userId,null,$at);$this->audit->record('rm_correction.submitted',$c->userId,$c->employeeId,$c->userPublicId,'RM correction submitted.',['request_public_id'=>$public,'property_public_id'=>$c->propertyPublicId,'actor_public_id'=>$c->userPublicId,'status_transition'=>'new_to_pending_review','event_type'=>'submitted'],$at);$this->tx->commit();}catch(\Throwable $e){$this->tx->rollback();throw $e;}$r=$this->repo->managerDetail($public,$c->propertyId);return ['public_id'=>$public,'email_sent'=>$r!==null&&$this->email->submission($r)];}
 public function decide(string $public,array $post,AuthenticatedUser $actor):array{$d=$this->validator->decision($post);$at=$this->now();$this->tx->begin();try{$r=$this->repo->corporateDetail($public,true);if($r===null)throw new \OutOfBoundsException();if($r['status']!=='pending_review'||!$this->repo->transition((int)$r['id'],'pending_review',$d['decision'],$actor->id,$at))throw new RmCorrectionStateConflictException('This request is no longer pending review.');$this->event((int)$r['id'],$d['decision'],$actor->id,$d['comments'],$at);$this->audit->record('rm_correction.decision_recorded',$actor->id,$actor->employeeId,$actor->publicId,'RM correction decision recorded.',['request_public_id'=>$public,'property_public_id'=>$r['property_public_id'],'actor_public_id'=>$actor->publicId,'status_transition'=>'pending_review_to_'.$d['decision'],'event_type'=>$d['decision']],$at);$this->tx->commit();}catch(\Throwable $e){$this->tx->rollback();throw $e;}$done=$this->repo->corporateDetail($public);return ['email_sent'=>$done!==null&&$this->email->decision($done,$d['comments'])];}
 public function respond(CommunityActionContext $c,string $public,array $post):array{$d=$this->validator->response($post);$at=$this->now();$this->tx->begin();try{if(!$this->access->canAccessProperty(new AuthenticatedRequestContext($c->user,''),$c->propertyId))throw new CommunityActionPropertyForbiddenException();$r=$this->repo->managerDetail($public,$c->propertyId,true);if($r===null)throw new \OutOfBoundsException();if($r['status']!=='more_information_needed'||!$this->repo->respond((int)$r['id'],$at))throw new RmCorrectionStateConflictException('This request no longer needs additional information.');$this->event((int)$r['id'],'manager_responded',$c->userId,$d['additional_information'],$at);$this->audit->record('rm_correction.manager_responded',$c->userId,$c->employeeId,$c->userPublicId,'RM correction manager response recorded.',['request_public_id'=>$public,'property_public_id'=>$c->propertyPublicId,'actor_public_id'=>$c->userPublicId,'status_transition'=>'more_information_needed_to_pending_review','event_type'=>'manager_responded'],$at);$this->tx->commit();}catch(\Throwable $e){$this->tx->rollback();throw $e;}$updated=$this->repo->managerDetail($public,$c->propertyId);return ['email_sent'=>$updated!==null&&$this->email->response($updated,$d['additional_information'])];}
 private function event(int $id,string $type,int $actor,?string $comments,string $at):void{$this->repo->historyInsert(['public_id'=>$this->ids->generate(),'request_id'=>$id,'event_type'=>$type,'actor_id'=>$actor,'comments'=>$comments,'timestamp'=>$at]);}
 private function now():string{return $this->clock->now()->format('Y-m-d H:i:s');}
}
