<?php
declare(strict_types=1);
namespace NpmGateway\Services;
final readonly class StorageConfiguration
{
 public function __construct(public string $endpoint,public string $region,public string $container,public string $accessKey,public string $secretKey,public string $attachmentPrefix,public string $imagePrefix,public string $testPrefix,public string $environment='testing',public string $creditCardReceiptsPrefix='credit-card-receipts/',public string $creditCardReceiptsTestPrefix='credit-card-receipts/test/',public bool $creditCardReceiptRealStorageTesting=false)
 {
  $host=parse_url($endpoint,PHP_URL_HOST);if(parse_url($endpoint,PHP_URL_SCHEME)!=='https'||!is_string($host)||$host===''||parse_url($endpoint,PHP_URL_USER)!==null||parse_url($endpoint,PHP_URL_PASS)!==null)throw new \InvalidArgumentException('Storage endpoint configuration is invalid.');foreach(['region'=>$region,'container'=>$container,'access key'=>$accessKey,'secret key'=>$secretKey] as $label=>$value)if(trim($value)==='')throw new \InvalidArgumentException("Storage {$label} is missing.");foreach([$attachmentPrefix,$imagePrefix,$testPrefix] as $prefix)$this->validatePrefix($prefix);if($attachmentPrefix===$imagePrefix)throw new \InvalidArgumentException('Storage attachment and image prefixes must differ.');
 }
 public static function fromArray(array $config):self{$flag=strtolower(trim((string)($config['credit_card_receipt_real_storage_testing']??'')));if(!in_array($flag,['','0','1','false','true'],true))throw new \InvalidArgumentException('Credit card receipt storage testing flag is invalid.');return new self(rtrim((string)($config['endpoint']??''),'/'),(string)($config['region']??''),(string)($config['container']??''),(string)($config['access_key']??''),(string)($config['secret_key']??''),(string)($config['attachment_prefix']??''),(string)($config['image_prefix']??''),(string)($config['test_prefix']??''),strtolower((string)($config['environment']??'production')),(string)($config['credit_card_receipts_prefix']??''),(string)($config['credit_card_receipts_test_prefix']??''),in_array($flag,['1','true'],true));}
 public function endpointHost():string{return (string)parse_url($this->endpoint,PHP_URL_HOST);}
 public function creditCardReceiptUploadPrefix():string{$this->validatePrefix($this->creditCardReceiptsPrefix);if(!$this->creditCardReceiptRealStorageTesting)return $this->creditCardReceiptsPrefix;if(!in_array($this->environment,['local','development'],true))throw new \RuntimeException('Real receipt storage testing is restricted to local/development environments.');$this->validatePrefix($this->creditCardReceiptsTestPrefix);if($this->creditCardReceiptsTestPrefix===$this->creditCardReceiptsPrefix||!str_starts_with($this->creditCardReceiptsTestPrefix,$this->creditCardReceiptsPrefix))throw new \RuntimeException('Credit card receipt test prefix is not safely isolated.');return $this->creditCardReceiptsTestPrefix;}
 private function validatePrefix(string $prefix):void{if($prefix===''||str_starts_with($prefix,'/')||!str_ends_with($prefix,'/')||str_ends_with($prefix,'//')||str_contains($prefix,'\\')||str_contains($prefix,'..')||str_contains($prefix,"\0")||str_contains($prefix,'://')||!preg_match('#^[A-Za-z0-9/_-]+/$#D',$prefix))throw new \InvalidArgumentException('Storage prefix configuration is invalid.');}
}
