<?php
declare(strict_types=1);
namespace NpmGateway\Services;
use NpmGateway\Contracts\{ClockInterface,InitializationTransactionInterface};use NpmGateway\Exceptions\Domain\InvalidZillowWorkbookException;use NpmGateway\Repositories\ZillowRepository;use NpmGateway\Support\PublicIdGenerator;use NpmGateway\ValueObjects\AuthenticatedUser;
final readonly class ZillowService
{
 public function __construct(private ZillowWorkbookParser$parser,private ZillowRepository$repo,private InitializationTransactionInterface$tx,private PublicIdGenerator$ids,private ClockInterface$clock,private AuditService$audit,private ZillowReportCriteriaFactory$criteria){}
 public function history():array{return$this->repo->history();}public function report(array$query):array{$properties=$this->repo->reportProperties();$criteria=$this->criteria->fromQuery($query,$properties,$this->repo->mostRecentRange());$report=$criteria->valid()?$this->repo->report($criteria,$properties):['rows'=>array_map(static fn(array$p):array=>$p+['total'=>0,'phone'=>0,'email'=>0,'percent'=>null],$properties),'totals'=>['total'=>0,'phone'=>0,'email'=>0],'details'=>[],'records'=>0,'page'=>1,'pages'=>1,'per_page'=>$criteria->perPage,'from'=>0,'to'=>0];return$report+['criteria'=>$criteria,'properties'=>$properties];}
 public function import(array$file,AuthenticatedUser$user):array{$parsed=$this->parser->parse($file);if($this->repo->hashExists($parsed['file_sha256']))throw new InvalidZillowWorkbookException('This Zillow.com file has already been imported.');$names=array_values(array_unique(array_column($parsed['rows'],'source_listing_name')));$map=$this->repo->mappings($names);$unknown=array_values(array_diff($names,array_keys($map)));sort($unknown,SORT_NATURAL|SORT_FLAG_CASE);if($unknown!==[])throw new InvalidZillowWorkbookException('The file contains Zillow.com listing names that are not configured in Gateway: '.implode(', ',$unknown));$total=count($parsed['rows']);$phone=count(array_filter($parsed['rows'],static fn(array$r):bool=>$r['lead_type']==='phone'));$email=$total-$phone;$public=$this->ids->generate();$at=$this->clock->now()->format('Y-m-d H:i:s');$this->tx->begin();try{$import=$this->repo->insertImport(['public_id'=>$public,'original_filename'=>$parsed['original_filename'],'file_sha256'=>$parsed['file_sha256'],'user_id'=>$user->id,'source_started_at'=>$parsed['source_started_at'],'source_ended_at'=>$parsed['source_ended_at'],'total'=>$total,'phone'=>$phone,'email'=>$email,'at'=>$at]);$this->repo->insertLeads($import,$parsed['rows'],$map,$at,fn():string=>$this->ids->generate());$this->audit->record('admin.zillow_imported',$user->id,$user->employeeId,$user->publicId,'Zillow.com workbook imported.',['import_public_id'=>$public,'total_leads'=>$total,'phone_leads'=>$phone,'email_leads'=>$email,'source_started_at'=>$parsed['source_started_at'],'source_ended_at'=>$parsed['source_ended_at'],'original_filename'=>$parsed['original_filename']],$at);$this->tx->commit();return['total'=>$total,'phone'=>$phone,'email'=>$email];}catch(\Throwable$e){$this->tx->rollback();throw$e;}}
}
