<?php
declare(strict_types=1);
namespace NpmGateway\Services;
use NpmGateway\Exceptions\Domain\InvalidZillowWorkbookException;
use PhpOffice\PhpSpreadsheet\IOFactory;
final readonly class ZillowWorkbookParser
{
 public const HEADERS=['Listing Name','Date','Type','From Email','From Phone','Name'];
 public function __construct(private ZillowPhoneNormalizer$phones){}
 public function parse(array$file):array
 {
  if((int)($file['error']??UPLOAD_ERR_NO_FILE)!==UPLOAD_ERR_OK)throw new InvalidZillowWorkbookException('Choose a Zillow.com workbook (.xls) to upload.');$path=(string)($file['tmp_name']??'');$name=basename((string)($file['name']??''));if(!is_file($path)||filesize($path)<1)throw new InvalidZillowWorkbookException('The uploaded Zillow.com file is empty or unavailable.');if(strtolower(pathinfo($name,PATHINFO_EXTENSION))!=='xls')throw new InvalidZillowWorkbookException('Upload the Zillow.com workbook in .xls format.');try{$type=IOFactory::identify($path);}catch(\Throwable){throw new InvalidZillowWorkbookException('The file is not a readable Zillow.com Excel workbook.');}if($type!=='Xls')throw new InvalidZillowWorkbookException('The uploaded file is not a genuine Excel .xls workbook.');try{$reader=IOFactory::createReader('Xls');$reader->setReadDataOnly(true);$book=$reader->load($path);}catch(\Throwable){throw new InvalidZillowWorkbookException('The Zillow.com workbook could not be read safely.');}
  try{if($book->getSheetCount()!==1||$book->getSheet(0)->getTitle()!=='Leads')throw new InvalidZillowWorkbookException('The workbook must contain exactly one "Leads" worksheet.');$sheet=$book->getSheet(0);$headers=$sheet->rangeToArray('A1:F1',null,true,true,false)[0];$headers=array_map(static fn(mixed$v):string=>trim((string)$v),$headers);if($headers!==self::HEADERS||$sheet->getHighestDataColumn(1)!=='F')throw new InvalidZillowWorkbookException('The Leads worksheet must contain exactly: '.implode(', ',self::HEADERS).'.');$rows=[];for($r=2;$r<=$sheet->getHighestDataRow();$r++){$raw=$sheet->rangeToArray("A{$r}:F{$r}",null,true,true,false)[0];$v=array_map(static fn(mixed$x):string=>trim((string)$x),$raw);if(implode('',$v)==='')continue;if($v[0]===''||$v[1]===''||$v[2]==='')throw new InvalidZillowWorkbookException("Lead row {$r} is missing Listing Name, Date, or Type.");$leadType=strtolower($v[2]);if(!in_array($leadType,['phone','email'],true))throw new InvalidZillowWorkbookException("Lead row {$r} has an unsupported Type.");$sourceDate=$sheet->getCell("B{$r}")->getValue();if(is_int($sourceDate)||is_float($sourceDate)){$native=\PhpOffice\PhpSpreadsheet\Shared\Date::excelToDateTimeObject((float)$sourceDate,new \DateTimeZone('UTC'));$date=\DateTimeImmutable::createFromMutable($native);}else{$date=\DateTimeImmutable::createFromFormat('!m/d/Y H:i',$v[1]);$errors=\DateTimeImmutable::getLastErrors();if($date===false||($errors!==false&&($errors['warning_count']>0||$errors['error_count']>0)))$date=false;}if($date===false)throw new InvalidZillowWorkbookException("Lead row {$r} has an invalid Date.");foreach([[0,150,'Listing Name'],[3,320,'From Email'],[4,100,'From Phone'],[5,200,'Name']]as[$i,$max,$label])if(strlen($v[$i])>$max||preg_match('/[\x00-\x08\x0B\x0C\x0E-\x1F\x7F]/',$v[$i]))throw new InvalidZillowWorkbookException("Lead row {$r} has an unsafe or oversized {$label}.");$rows[]=['source_listing_name'=>$v[0],'occurred_at'=>$date->format('Y-m-d H:i:s'),'lead_type'=>$leadType,'prospect_email'=>$v[3]===''?null:$v[3],'prospect_phone_raw'=>$v[4]===''?null:$v[4],'prospect_phone_normalized'=>$this->phones->normalize($v[4]),'prospect_name'=>$v[5]===''?null:$v[5]];}if($rows===[])throw new InvalidZillowWorkbookException('The Zillow.com workbook contains no lead records.');$dates=array_column($rows,'occurred_at');return['original_filename'=>$name,'file_sha256'=>hash_file('sha256',$path),'rows'=>$rows,'source_started_at'=>min($dates),'source_ended_at'=>max($dates)];}finally{$book->disconnectWorksheets();}
 }
}
