<?php
declare(strict_types=1);
namespace NpmGateway\Notifications;
use NpmGateway\ValueObjects\CompanyAnnouncementEmail;
final class CompanyAnnouncementEmailRenderer
{
 /** @return array{html:string,text:string} */
 public function render(CompanyAnnouncementEmail $message):array{return ['html'=>$this->html($message),'text'=>$this->text($message)];}
 private function html(CompanyAnnouncementEmail $m):string
 {
  $e=static fn(string $v):string=>htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');$rows='';foreach($m->fields as $field){$value=$e($field['value']);if(($field['type']??'')==='email'&&filter_var($field['value'],FILTER_VALIDATE_EMAIL)!==false)$value='<a href="mailto:'.$value.'" style="color:#0b5f7a;text-decoration:underline;word-break:break-all;">'.$value.'</a>';$rows.='<tr><th scope="row" style="width:34%;padding:14px 16px;text-align:left;vertical-align:top;color:#26384a;background:#f8f4e9;border-bottom:1px solid #dde3e9;font-family:Arial,sans-serif;font-size:15px;line-height:1.45;font-weight:700;">'.$e($field['label']).'</th><td style="padding:14px 16px;vertical-align:top;color:#253246;background:#ffffff;border-bottom:1px solid #dde3e9;font-family:Arial,sans-serif;font-size:15px;line-height:1.45;overflow-wrap:anywhere;word-break:break-word;">'.$value.'</td></tr>';}
  return '<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><title>'.$e($m->title).'</title></head><body style="margin:0;padding:0;background:#eef1f4;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;background:#eef1f4;"><tr><td align="center" style="padding:24px 12px;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:760px;background:#ffffff;border-collapse:collapse;"><tr><td style="padding:30px 34px;background:#071b34;border-bottom:4px solid #c59a45;"><p style="margin:0 0 5px;color:#cfae66;font-family:Arial,sans-serif;font-size:12px;line-height:1.4;font-weight:700;letter-spacing:1.5px;">'.$e(strtoupper($m->brandLabel)).'</p><p style="margin:0 0 18px;color:#d9c28d;font-family:Arial,sans-serif;font-size:11px;line-height:1.4;font-weight:700;letter-spacing:1.3px;">'.$e(strtoupper($m->category)).'</p><h1 style="margin:0;color:#ffffff;font-family:Arial,sans-serif;font-size:30px;line-height:1.2;font-weight:700;">'.$e($m->title).'</h1></td></tr><tr><td style="padding:30px 34px 12px;"><p style="margin:0;color:#425168;font-family:Arial,sans-serif;font-size:16px;line-height:1.6;">'.$e($m->introduction).'</p></td></tr><tr><td style="padding:16px 34px 10px;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;border-collapse:collapse;border:1px solid #dde3e9;table-layout:fixed;">'.$rows.'</table></td></tr><tr><td style="padding:20px 34px 34px;"><p style="margin:0;color:#253246;font-family:Arial,sans-serif;font-size:16px;line-height:1.6;">'.$e($m->closing).'</p></td></tr><tr><td style="padding:20px 34px;color:#6b7788;background:#f6f8fa;border-top:1px solid #dde3e9;font-family:Arial,sans-serif;font-size:12px;line-height:1.5;text-align:center;">'.$e($m->footer).'</td></tr></table></td></tr></table></body></html>';
 }
 private function text(CompanyAnnouncementEmail $m):string{$lines=[strtoupper($m->brandLabel),strtoupper($m->category),'',strtoupper($m->title),'',$m->introduction,''];foreach($m->fields as $field)$lines[]=$field['label'].': '.$field['value'];$lines[]='';$lines[]=$m->closing;$lines[]='';$lines[]=$m->footer;return implode("\n",$lines);}
}
