<?php
declare(strict_types=1);
namespace NpmGateway\Notifications;
use NpmGateway\Contracts\StorageAdapterInterface;
use NpmGateway\Services\HrEmployeeNotificationConfig;
use NpmGateway\Support\CompanyNoticePresentation;
use PHPMailer\PHPMailer\PHPMailer;
final class CompanyNoticeEmailSender
{
 public function __construct(private readonly ?HrEmployeeNotificationConfig $config,private readonly CompanyAnnouncementEmailRenderer $renderer,private readonly ?\Closure $factory=null,private readonly ?StorageAdapterInterface $storage=null,private readonly string $appUrl=''){}
 public function send(string $email,array $notice):bool
 {
  $temporary=[];try{
   if($this->config===null)return false;$mail=$this->factory?($this->factory)():new PHPMailer(true);$mail->isSMTP();$mail->Host=$this->config->host;$mail->Port=$this->config->port;$mail->SMTPAuth=true;$mail->Username=$this->config->username;$mail->Password=$this->config->password;$mail->SMTPSecure=$this->config->secure==='ssl'?PHPMailer::ENCRYPTION_SMTPS:PHPMailer::ENCRYPTION_STARTTLS;$mail->CharSet=PHPMailer::CHARSET_UTF8;$mail->setFrom($this->config->fromAddress,$this->config->fromName);$mail->addAddress($email);$mail->Subject=mb_substr('Company Notice — '.$notice['title'],0,200);
   $html=(string)($notice['rich_message_html']??'<p>'.htmlspecialchars((string)$notice['message'],ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8').'</p>');$html=(string)preg_replace_callback('/<img\b[^>]*>/i',static function(array $match):string{$tag=$match[0];$percent=50;if(preg_match('/\bdata-gateway-image-width="((?:[1-9][0-9]|100))"/i',$tag,$widthMatch))$percent=(int)$widthMatch[1];elseif(preg_match('/\bdata-gateway-image-size="(small|medium|large|full)"/i',$tag,$sizeMatch))$percent=['small'=>25,'medium'=>50,'large'=>75,'full'=>100][strtolower($sizeMatch[1])];$alignment='left';if(preg_match('/\bdata-gateway-image-align="(left|center|right)"/i',$tag,$alignMatch))$alignment=strtolower($alignMatch[1]);$margins=['left'=>'margin-left:0;margin-right:auto;','center'=>'margin-left:auto;margin-right:auto;','right'=>'margin-left:auto;margin-right:0;'][$alignment];$pixels=(int)round(640*$percent/100);return rtrim(substr($tag,0,-1)).' width="'.$pixels.'" style="display:block;width:'.$percent.'%;max-width:100%;height:auto;'.$margins.'" >';},$html);$html=(string)preg_replace('/<p>/i','<p style="margin:0 0 11px;">',$html);$html='<div style="font-family:Arial,sans-serif;font-size:16px;line-height:1.6;">'.$html.'</div>';$attachments=[];
   foreach((array)($notice['assets']??[]) as $asset){if(($asset['asset_role']??'')==='attachment'){$attachments[]=$asset;continue;}if(($asset['asset_role']??'')!=='embedded_image'||$this->storage===null)return false;$cid='gateway-'.strtolower((string)$asset['public_id']);$stream=$this->storage->openReadStream((string)$asset['provider_container'],(string)$asset['object_key']);$path=tempnam(sys_get_temp_dir(),'npm-cid-');if($path===false||!is_resource($stream))return false;$out=fopen($path,'wb');if(!is_resource($out)){fclose($stream);return false;}stream_copy_to_stream($stream,$out);fclose($stream);fclose($out);$temporary[]=$path;$mail->addEmbeddedImage($path,$cid,(string)$asset['display_filename'],'base64',(string)$asset['mime_type']);$html=str_replace('gateway-storage:'.$asset['public_id'],'cid:'.$cid,$html);}
   if(str_contains($html,'gateway-storage:'))return false;$e=static fn(string $v):string=>htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');$attachmentHtml='';$attachmentText='';
   if($attachments!==[]){$attachmentHtml='<h2 style="margin:26px 0 14px;font-family:Arial,sans-serif;font-size:20px;">Attachments</h2>';foreach($attachments as $asset){$url=rtrim($this->appUrl,'/').'/storage/'.$asset['public_id'];$name=$e((string)$asset['display_filename']);$type=$e(CompanyNoticePresentation::typeLabel($asset));$size=$e(CompanyNoticePresentation::fileSize((int)$asset['byte_size']));$safeUrl=$e($url);$attachmentHtml.='<div style="margin:0 0 18px;padding:14px 16px;background:#f6f8fa;border:1px solid #dde3e9;"><strong style="font-family:Arial,sans-serif;">'.$name.'</strong><br><span style="color:#667085;font-family:Arial,sans-serif;font-size:14px;">'.$type.' · '.$size.'</span><br><a href="'.$safeUrl.'" style="font-family:Arial,sans-serif;">Download from NPM Gateway</a></div>';$attachmentText.="\n".$asset['display_filename']."\n".CompanyNoticePresentation::typeLabel($asset).' · '.CompanyNoticePresentation::fileSize((int)$asset['byte_size'])."\n".$url."\n";}$attachmentHtml.='<p style="font-family:Arial,sans-serif;">You may be asked to sign in to NPM Gateway before downloading attachments.</p>';$attachmentText.="\nYou may be asked to sign in to NPM Gateway before downloading attachments.\n";}
   $priority=ucfirst((string)($notice['priority']??'normal'));$metadata='<table role="presentation" width="100%" cellspacing="0" cellpadding="0" style="margin:24px 0;border-collapse:collapse;background:#f6f8fa;border:1px solid #dde3e9;"><tr><th scope="row" style="padding:10px 14px;text-align:left;vertical-align:top;font-family:Arial,sans-serif;">Published by</th><td style="padding:10px 14px;font-family:Arial,sans-serif;">'.$e((string)$notice['published_by']).'</td></tr><tr><th scope="row" style="padding:10px 14px;text-align:left;vertical-align:top;font-family:Arial,sans-serif;">Published</th><td style="padding:10px 14px;font-family:Arial,sans-serif;">'.$e((string)$notice['published_at']).'</td></tr><tr><th scope="row" style="padding:10px 14px;text-align:left;vertical-align:top;font-family:Arial,sans-serif;">Priority</th><td style="padding:10px 14px;font-family:Arial,sans-serif;">'.$e($priority).'</td></tr></table>';$footer='<footer style="padding:18px;text-align:center;color:#667085;background:#f6f8fa;border-top:1px solid #dde3e9;font-family:Arial,sans-serif;font-size:12px;">NPM Gateway — Internal company communication</footer>';
   $mail->isHTML(true);$mail->Body='<!doctype html><html><body><div style="background:#071b34;color:#fff;padding:24px"><strong>NPM GATEWAY · COMPANY ANNOUNCEMENT</strong><h1>'.$e((string)$notice['title']).'</h1></div><main style="padding:24px">'.$html.$metadata.$attachmentHtml.'</main>'.$footer.'</body></html>';$mail->AltBody="NPM GATEWAY\nCOMPANY ANNOUNCEMENT\n\n".$notice['title']."\n\n".$notice['message']."\n\nPublished by\n".$notice['published_by']."\n\nPublished\n".$notice['published_at']."\n\nPriority\n".$priority.($attachments!==[]?"\n\nATTACHMENTS\n".$attachmentText:'')."\n\nNPM Gateway — Internal company communication";$mail->send();return true;
  }catch(\Throwable){return false;}finally{foreach($temporary as $path)if(is_file($path))@unlink($path);}
 }
}
