<?php
declare(strict_types=1);
namespace NpmGateway\Notifications;
use NpmGateway\ValueObjects\GatewayEmailMessage;
class GatewayEmailRenderer
{
 /** @return array{html:string,text:string,url:string} */
 public function render(GatewayEmailMessage $message):array
 {
  $e=static fn(string $value):string=>htmlspecialchars($value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
  $rows='';foreach($message->summaryRows as $row){$weight=($row['emphasized']??false)===true?'700':'400';$rows.='<tr><th align="left" valign="top" style="width:38%;padding:11px 14px;color:#53657a;background:#f7f9fb;border-bottom:1px solid #dde3e9;font-family:Arial,sans-serif;font-size:12px;line-height:1.45;font-weight:700;letter-spacing:.3px;">'.$e($row['label']).'</th><td valign="top" style="padding:11px 14px;color:#172033;border-bottom:1px solid #dde3e9;font-family:Arial,sans-serif;font-size:15px;line-height:1.5;font-weight:'.$weight.';word-break:break-word;">'.$e($row['value']).'</td></tr>';}
  $sections='';foreach($message->sections as $section){$body=$section['body']??$section['plain_text'];if(trim($body)==='')continue;$renderedBody=array_key_exists('trusted_sanitized_html',$section)?'<div style="margin:0;color:#253246;font-family:Arial,sans-serif;font-size:15px;line-height:1.6;word-break:break-word;">'.$section['trusted_sanitized_html'].'</div>':'<p style="margin:0;color:#253246;font-family:Arial,sans-serif;font-size:15px;line-height:1.6;white-space:pre-line;word-break:break-word;">'.$e($body).'</p>';$sections.='<tr><td style="padding:8px 32px 18px;"><h2 style="margin:0 0 8px;color:#071b34;font-family:Arial,sans-serif;font-size:17px;line-height:1.35;">'.$e($section['title']).'</h2>'.$renderedBody.'</td></tr>';}
  $status='';if($message->statusLabel!==null){[$color,$background,$border]=match($message->statusTone){'pending'=>['#664d03','#fff3cd','#e6c75f'],'success'=>['#0f5132','#d1e7dd','#8bc4a7'],'danger'=>['#842029','#f8d7da','#d99aa0'],'informational'=>['#084298','#cfe2ff','#8bb7f0'],default=>['#172033','#eef2f6','#c5ced9']};$status='<div style="margin:14px 0 0;"><span style="display:inline-block;padding:7px 12px;color:'.$color.';background:'.$background.';border:1px solid '.$border.';border-radius:999px;font-family:Arial,sans-serif;font-size:13px;line-height:1.2;font-weight:700;">'.$e($message->statusLabel).'</span></div>';}
  $action='';$url=$message->primaryActionUrl??'';if($message->primaryActionLabel!==null&&$message->primaryActionUrl!==null){$safeUrl=$e($message->primaryActionUrl);$label=$e($message->primaryActionLabel);$action='<tr><td align="left" style="padding:12px 32px 10px;"><!--[if mso]><v:roundrect xmlns:v="urn:schemas-microsoft-com:vml" href="'.$safeUrl.'" style="height:44px;v-text-anchor:middle;width:210px;" arcsize="12%" stroke="f" fillcolor="#0d6efd"><w:anchorlock xmlns:w="urn:schemas-microsoft-com:office:word"/><center style="color:#ffffff;font-family:Arial,sans-serif;font-size:15px;font-weight:bold;">'.$label.'</center></v:roundrect><![endif]--><!--[if !mso]><!--><a href="'.$safeUrl.'" style="display:inline-block;padding:12px 20px;color:#ffffff;background:#0d6efd;border-radius:6px;font-family:Arial,sans-serif;font-size:15px;line-height:20px;font-weight:700;text-decoration:none;" aria-label="'.$label.'">'.$label.'</a><!--<![endif]--></td></tr><tr><td style="padding:8px 32px 26px;color:#667085;font-family:Arial,sans-serif;font-size:12px;line-height:1.5;word-break:break-all;">If the button does not work, copy and paste this address into your browser:<br><a href="'.$safeUrl.'" style="color:#0d6efd;">'.$safeUrl.'</a></td></tr>';}
  $subtitle=$message->subtitle!==null?'<p style="margin:13px 0 0;color:#667085;font-family:Arial,sans-serif;font-size:16px;line-height:1.5;">'.$e($message->subtitle).'</p>':'';$preheader=$e($message->preheader);$year=(new \DateTimeImmutable())->format('Y');$footerNote=$message->footerNote!==null?'<p style="margin:0 0 8px;">'.$e($message->footerNote).'</p>':'';
  $html='<!doctype html><html><head><meta name="viewport" content="width=device-width,initial-scale=1"><meta http-equiv="Content-Type" content="text/html; charset=UTF-8"><title>'.$e($message->title).'</title><style>@media only screen and (max-width:600px){.gateway-email-shell{padding:0!important}.gateway-email-card{width:100%!important}.gateway-email-content{padding-left:20px!important;padding-right:20px!important}}</style></head><body style="margin:0;padding:0;background:#eef2f6;"><div style="display:none;max-height:0;overflow:hidden;opacity:0;color:transparent;">'.$preheader.'</div><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;background:#eef2f6;"><tr><td class="gateway-email-shell" align="center" style="padding:24px 12px;"><table class="gateway-email-card" role="presentation" width="640" cellspacing="0" cellpadding="0" border="0" style="width:100%;max-width:640px;background:#ffffff;border-collapse:collapse;"><tr><td style="padding:25px 32px;background:#071b34;border-bottom:4px solid #c59a45;"><p style="margin:0;color:#ffffff;font-family:Arial,sans-serif;font-size:20px;line-height:1.3;font-weight:700;">NPM Gateway</p><p style="margin:4px 0 0;color:#d9c28d;font-family:Arial,sans-serif;font-size:11px;line-height:1.4;font-weight:700;letter-spacing:1.1px;text-transform:uppercase;">Internal Workflow Notification</p></td></tr><tr><td class="gateway-email-content" style="padding:28px 32px 8px;"><p style="margin:0 0 7px;color:#85662d;font-family:Arial,sans-serif;font-size:11px;line-height:1.4;font-weight:700;letter-spacing:1.3px;">'.$e(strtoupper($message->eyebrow)).'</p><h1 style="margin:0;color:#071b34;font-family:Arial,sans-serif;font-size:27px;line-height:1.25;font-weight:700;">'.$e($message->title).'</h1>'.$status.$subtitle.'</td></tr>'.($rows!==''?'<tr><td style="padding:8px 32px 22px;"><table role="presentation" width="100%" cellspacing="0" cellpadding="0" border="0" style="width:100%;border:1px solid #dde3e9;border-collapse:collapse;table-layout:fixed;">'.$rows.'</table></td></tr>':'').$sections.$action.'<tr><td style="padding:28px 32px 24px;color:#667085;background:#f4f6f8;border-top:2px solid #c5ced9;font-family:Arial,sans-serif;font-size:12px;line-height:1.55;text-align:center;">'.$footerNote.'<p style="margin:0 0 3px;color:#071b34;font-family:Arial,sans-serif;font-size:15px;line-height:1.4;font-weight:700;">NPM Gateway</p><p style="margin:0 0 16px;color:#667085;font-family:Arial,sans-serif;font-size:11px;line-height:1.4;font-weight:700;letter-spacing:.7px;text-transform:uppercase;">Internal Workflow Notification</p>This message was generated automatically by NPM Gateway.<br>Please do not reply to this email.<br><br>&copy; '.$year.' NPM Properties Inc.</td></tr></table></td></tr></table></body></html>';
  $textLines=['NPM GATEWAY','Internal Workflow Notification','',strtoupper($message->eyebrow),$message->title];if($message->subtitle!==null)$textLines[]=$message->subtitle;if($message->statusLabel!==null){$textLines[]='';$textLines[]='Status: '.$message->statusLabel;}if($message->summaryRows!==[])$textLines[]='';foreach($message->summaryRows as $row)$textLines[]=$row['label'].': '.$row['value'];foreach($message->sections as $section){$body=$section['body']??$section['plain_text'];if(trim($body)==='')continue;$textLines[]='';$textLines[]=$section['title'].':';$textLines[]=$body;}if($message->primaryActionLabel!==null&&$message->primaryActionUrl!==null){$textLines[]='';$textLines[]=$message->primaryActionLabel.':';$textLines[]=$message->primaryActionUrl;}$textLines[]='';if($message->footerNote!==null)$textLines[]=$message->footerNote;$textLines[]='This message was generated automatically by NPM Gateway.';$textLines[]='Please do not reply.';$textLines[]='© '.$year.' NPM Properties Inc.';
  $html=str_replace('border-top:2px solid #c5ced9;font-family:Arial,sans-serif;font-size:12px;line-height:1.55;text-align:center;','border-top:2px solid #c5ced9;font-family:Arial,sans-serif;font-size:12px;line-height:1.55;text-align:left;',$html);
  return ['html'=>$html,'text'=>implode("\n",$textLines),'url'=>$url];
 }
}
