<?php

declare(strict_types=1);

return [
    '/login' => ['methods' => ['GET', 'POST'], 'controller' => 'authentication'],
    '/logout' => ['methods' => ['POST'], 'controller' => 'authentication'],
    '/dashboard' => ['methods' => ['GET'], 'controller' => 'dashboard', 'middleware' => ['authentication']],
    '/community-actions' => ['name'=>'community-actions.index','methods'=>['GET'],'controller'=>'community-actions','middleware'=>['authentication']],
    '/community-actions/{propertySlug}' => ['name'=>'community-actions.show','methods'=>['GET'],'controller'=>'community-actions','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/application-reviews' => ['names'=>['GET'=>'community-actions.application-reviews','POST'=>'community-actions.application-reviews.store'],'methods'=>['GET','POST'],'controller'=>'application-reviews','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/application-reviews/create' => ['name'=>'community-actions.application-reviews.create','methods'=>['GET'],'controller'=>'application-reviews','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/application-reviews/{reviewPublicId}' => ['name'=>'community-actions.application-reviews.show','methods'=>['GET'],'controller'=>'application-reviews','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/credit-card-purchases' => ['names'=>['GET'=>'community-actions.credit-card-purchases','POST'=>'community-actions.credit-card-purchases.store'],'methods'=>['GET','POST'],'controller'=>'credit-card-purchases','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/credit-card-purchases/create' => ['name'=>'community-actions.credit-card-purchases.create','methods'=>['GET'],'controller'=>'credit-card-purchases','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/credit-card-purchases/{purchasePublicId}' => ['names'=>['GET'=>'community-actions.credit-card-purchases.show','POST'=>'community-actions.credit-card-purchases.update'],'methods'=>['GET','POST'],'controller'=>'credit-card-purchases','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/credit-card-purchases/{purchasePublicId}/edit' => ['name'=>'community-actions.credit-card-purchases.edit','methods'=>['GET'],'controller'=>'credit-card-purchases','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/credit-card-purchases/{purchasePublicId}/receipt' => ['names'=>['GET'=>'community-actions.credit-card-purchases.receipt','POST'=>'community-actions.credit-card-purchases.receipt.store'],'methods'=>['GET','POST'],'controller'=>'credit-card-purchases','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/credit-card-purchases/{purchasePublicId}/receipts/{receiptPublicId}/view' => ['name'=>'community-actions.credit-card-purchases.receipts.view','methods'=>['GET'],'controller'=>'credit-card-purchases','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/credit-card-purchases/{purchasePublicId}/receipts/{receiptPublicId}/download' => ['name'=>'community-actions.credit-card-purchases.receipts.download','methods'=>['GET'],'controller'=>'credit-card-purchases','middleware'=>['authentication']],
    '/corporate/credit-card-purchases' => ['names'=>['GET'=>'corporate.credit-card-purchases.index','POST'=>'corporate.credit-card-purchases.store'],'methods'=>['GET','POST'],'controller'=>'corporate-credit-card-purchases','middleware'=>['authentication','credit-cards-access']],
    '/corporate/credit-card-purchases/create' => ['name'=>'corporate.credit-card-purchases.create','methods'=>['GET'],'controller'=>'corporate-credit-card-purchases','middleware'=>['authentication','credit-cards-access']],
    '/corporate/credit-card-purchases/{purchasePublicId}' => ['name'=>'corporate.credit-card-purchases.show','methods'=>['GET'],'controller'=>'corporate-credit-card-purchases','middleware'=>['authentication','credit-cards-access']],
    '/corporate/credit-card-purchases/{purchasePublicId}/edit' => ['names'=>['GET'=>'corporate.credit-card-purchases.edit','POST'=>'corporate.credit-card-purchases.correct'],'methods'=>['GET','POST'],'controller'=>'corporate-credit-card-purchases','middleware'=>['authentication','credit-cards-access']],
    '/corporate/credit-card-purchases/{purchasePublicId}/receipt' => ['name'=>'corporate.credit-card-purchases.receipt.store','methods'=>['POST'],'controller'=>'corporate-credit-card-purchases','middleware'=>['authentication','credit-cards-access']],
    '/corporate/credit-card-purchases/{purchasePublicId}/receipts/{receiptPublicId}/view' => ['name'=>'corporate.credit-card-purchases.receipts.view','methods'=>['GET'],'controller'=>'corporate-credit-card-purchases','middleware'=>['authentication','credit-cards-access']],
    '/corporate/credit-card-purchases/{purchasePublicId}/receipts/{receiptPublicId}/download' => ['name'=>'corporate.credit-card-purchases.receipts.download','methods'=>['GET'],'controller'=>'corporate-credit-card-purchases','middleware'=>['authentication','credit-cards-access']],
    '/community-actions/{propertySlug}/rm-corrections' => ['names'=>['GET'=>'community-actions.rm-corrections','POST'=>'community-actions.rm-corrections.store'],'methods'=>['GET','POST'],'controller'=>'rm-corrections','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/rm-corrections/create' => ['name'=>'community-actions.rm-corrections.create','methods'=>['GET'],'controller'=>'rm-corrections','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/rm-corrections/{requestPublicId}' => ['name'=>'community-actions.rm-corrections.show','methods'=>['GET'],'controller'=>'rm-corrections','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/rm-corrections/{requestPublicId}/respond' => ['names'=>['GET'=>'community-actions.rm-corrections.respond','POST'=>'community-actions.rm-corrections.response'],'methods'=>['GET','POST'],'controller'=>'rm-corrections','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/renovation-requests' => ['name'=>'community-actions.renovation-request','methods'=>['GET'],'controller'=>'community-actions','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/request-appliances' => ['name'=>'community-actions.request-appliances','methods'=>['GET'],'controller'=>'community-actions','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/appliance-distribution' => ['name'=>'community-actions.appliance-distribution','methods'=>['GET'],'controller'=>'community-actions','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/hvac-service-requests' => ['name'=>'community-actions.hvac-service-request','methods'=>['GET'],'controller'=>'community-actions','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/order-supplies' => ['name'=>'community-actions.order-supplies','methods'=>['GET'],'controller'=>'community-actions','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/eviction-checks' => ['name'=>'community-actions.eviction-checks','methods'=>['GET'],'controller'=>'community-actions','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/rm-audits' => ['name'=>'community-actions.rm-audits','methods'=>['GET'],'controller'=>'rm-audits','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/rm-audits/{auditPublicId}' => ['name'=>'community-actions.rm-audits.show','methods'=>['GET'],'controller'=>'rm-audits','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/rm-audits/{auditPublicId}/complete' => ['name'=>'community-actions.rm-audits.complete','methods'=>['POST'],'controller'=>'rm-audits','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/supply-orders'=>['names'=>['GET'=>'community-actions.supply-orders','POST'=>'community-actions.supply-orders.store'],'methods'=>['GET','POST'],'controller'=>'supply-orders','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/supply-orders/create'=>['name'=>'community-actions.supply-orders.create','methods'=>['GET'],'controller'=>'supply-orders','middleware'=>['authentication']],
    '/community-actions/{propertySlug}/supply-orders/{supplyOrderPublicId}'=>['name'=>'community-actions.supply-orders.show','methods'=>['GET'],'controller'=>'supply-orders','middleware'=>['authentication']],
    '/my/emergency-contact' => ['names'=>['GET'=>'my.emergency-contact.edit','POST'=>'my.emergency-contact.save'],'methods'=>['GET','POST'],'controller'=>'employee-emergency-contact','middleware'=>['authentication']],
    '/manager/maintenance/{employeePublicId}/emergency-contact' => ['names'=>['GET'=>'manager.maintenance.emergency-contact.edit','POST'=>'manager.maintenance.emergency-contact.save'],'methods'=>['GET','POST'],'controller'=>'manager-maintenance-emergency-contact','middleware'=>['authentication']],
    '/corporate/operations'=>['name'=>'corporate.operations.index','methods'=>['GET'],'controller'=>'corporate-workspace','middleware'=>['authentication','operations-access']],
    '/corporate/operations/inventory-cf'=>['name'=>'corporate.operations.inventory-cf','methods'=>['GET'],'controller'=>'corporate-workspace','middleware'=>['authentication','operations-access']],
    '/corporate/operations/inventory-hr'=>['name'=>'corporate.operations.inventory-hr','methods'=>['GET'],'controller'=>'corporate-workspace','middleware'=>['authentication','operations-access']],
    '/corporate/operations/development'=>['name'=>'corporate.operations.development','methods'=>['GET'],'controller'=>'corporate-workspace','middleware'=>['authentication','operations-access']],
    '/corporate/operations/overview'=>['name'=>'corporate.operations.overview','methods'=>['GET'],'controller'=>'operations-overview','middleware'=>['authentication','operations-access']],
    '/corporate/operations/overview/rm-corrections'=>['name'=>'corporate.operations.overview.rm-corrections','methods'=>['GET'],'controller'=>'operations-overview','middleware'=>['authentication','operations-access']],
    '/corporate/operations/overview/rm-corrections/{requestPublicId}'=>['name'=>'corporate.operations.overview.rm-corrections.show','methods'=>['GET'],'controller'=>'operations-overview','middleware'=>['authentication','operations-access']],
    '/corporate/operations/overview/rm-audits'=>['name'=>'corporate.operations.overview.rm-audits','methods'=>['GET'],'controller'=>'operations-overview','middleware'=>['authentication','operations-access']],
    '/corporate/operations/overview/rm-audits/pdf'=>['name'=>'corporate.operations.overview.rm-audits.pdf','methods'=>['GET'],'controller'=>'operations-rm-audits-pdf','middleware'=>['authentication','operations-access']],
    '/corporate/operations/overview/rm-audits/{auditPublicId}'=>['name'=>'corporate.operations.overview.rm-audits.show','methods'=>['GET'],'controller'=>'operations-overview','middleware'=>['authentication','operations-access']],
    '/corporate/finance'=>['name'=>'corporate.finance.index','methods'=>['GET'],'controller'=>'corporate-workspace','middleware'=>['authentication','finance-access']],
    '/corporate/application-reviews'=>['name'=>'corporate.application-reviews.index','methods'=>['GET'],'controller'=>'corporate-application-reviews','middleware'=>['authentication','application-reviews-access']],
    '/corporate/application-reviews/{reviewPublicId}'=>['name'=>'corporate.application-reviews.show','methods'=>['GET'],'controller'=>'corporate-application-reviews','middleware'=>['authentication','application-reviews-access']],
    '/corporate/application-reviews/{reviewPublicId}/decision'=>['name'=>'corporate.application-reviews.decision','methods'=>['POST'],'controller'=>'corporate-application-reviews','middleware'=>['authentication','application-reviews-access']],
    '/corporate/rm-corrections'=>['name'=>'corporate.rm-corrections.index','methods'=>['GET'],'controller'=>'corporate-rm-corrections','middleware'=>['authentication','rm-corrections-access']],
    '/corporate/rm-corrections/{requestPublicId}'=>['name'=>'corporate.rm-corrections.show','methods'=>['GET'],'controller'=>'corporate-rm-corrections','middleware'=>['authentication','rm-corrections-access']],
    '/corporate/rm-corrections/{requestPublicId}/decision'=>['name'=>'corporate.rm-corrections.decision','methods'=>['POST'],'controller'=>'corporate-rm-corrections','middleware'=>['authentication','rm-corrections-access']],
    '/corporate/rm-audits'=>['names'=>['GET'=>'corporate.rm-audits.index','POST'=>'corporate.rm-audits.store'],'methods'=>['GET','POST'],'controller'=>'corporate-rm-audits','middleware'=>['authentication','rm-audit-access']],
    '/corporate/rm-audits/create'=>['name'=>'corporate.rm-audits.create','methods'=>['GET'],'controller'=>'corporate-rm-audits','middleware'=>['authentication','rm-audit-access']],
    '/corporate/rm-audits/{auditPublicId}'=>['name'=>'corporate.rm-audits.show','methods'=>['GET'],'controller'=>'corporate-rm-audits','middleware'=>['authentication','rm-audit-access']],
    '/corporate/rm-audits/{auditPublicId}/return'=>['name'=>'corporate.rm-audits.return','methods'=>['POST'],'controller'=>'corporate-rm-audits','middleware'=>['authentication','rm-audit-access']],
    '/corporate/marketing'=>['name'=>'corporate.marketing.index','methods'=>['GET'],'controller'=>'corporate-workspace','middleware'=>['authentication','marketing-access']],
    '/corporate/marketing/flyers'=>['names'=>['GET'=>'corporate.marketing.flyers','POST'=>'corporate.marketing.flyers.store'],'methods'=>['GET','POST'],'controller'=>'marketing-flyers','middleware'=>['authentication','marketing-access']],
    '/corporate/marketing/flyers/new'=>['name'=>'corporate.marketing.flyers.create','methods'=>['GET'],'controller'=>'marketing-flyers','middleware'=>['authentication','marketing-access']],
    '/corporate/marketing/flyers/{flyerPublicId}'=>['name'=>'corporate.marketing.flyers.show','methods'=>['GET'],'controller'=>'marketing-flyers','middleware'=>['authentication','marketing-access']],
    '/corporate/marketing/flyers/{flyerPublicId}/view'=>['name'=>'corporate.marketing.flyers.view','methods'=>['GET'],'controller'=>'marketing-flyers','middleware'=>['authentication','marketing-access']],
    '/corporate/marketing/flyers/{flyerPublicId}/download'=>['name'=>'corporate.marketing.flyers.download','methods'=>['GET'],'controller'=>'marketing-flyers','middleware'=>['authentication','marketing-access']],
    '/corporate/marketing/flyers/{flyerPublicId}/replace'=>['names'=>['GET'=>'corporate.marketing.flyers.replace','POST'=>'corporate.marketing.flyers.update'],'methods'=>['GET','POST'],'controller'=>'marketing-flyers','middleware'=>['authentication','marketing-access']],
    '/corporate/marketing/flyers/{flyerPublicId}/delete'=>['name'=>'corporate.marketing.flyers.delete','methods'=>['POST'],'controller'=>'marketing-flyers','middleware'=>['authentication','marketing-access']],
    '/community-actions/{propertySlug}/flyers/{flyerPublicId}/download'=>['name'=>'community-actions.flyers.download','methods'=>['GET'],'controller'=>'marketing-flyers','middleware'=>['authentication']],
    '/notifications' => ['name'=>'notifications.index','methods'=>['GET'],'controller'=>'notifications','middleware'=>['authentication']],
    '/notifications/{notificationPublicId}' => ['name'=>'notifications.show','methods'=>['GET'],'controller'=>'notifications','middleware'=>['authentication']],
    '/notifications/{notificationPublicId}/acknowledge' => ['name'=>'notifications.acknowledge','methods'=>['POST'],'controller'=>'notifications','middleware'=>['authentication']],
    '/storage/{storageObjectPublicId}' => ['name'=>'storage.download','methods'=>['GET'],'controller'=>'storage','middleware'=>['authentication']],
    '/storage/{storageObjectPublicId}/image' => ['name'=>'storage.image','methods'=>['GET'],'controller'=>'storage','middleware'=>['authentication']],
    '/company-notices' => ['name'=>'company-notices.index','methods'=>['GET'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/create' => ['name'=>'company-notices.create','methods'=>['GET'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/preview' => ['name'=>'company-notices.preview','methods'=>['POST'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/discard' => ['name'=>'company-notices.discard','methods'=>['POST'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/uploads/attachments' => ['name'=>'company-notices.upload-attachment','methods'=>['POST'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/uploads/images' => ['name'=>'company-notices.upload-image','methods'=>['POST'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/uploads/{storageObjectPublicId}/remove' => ['name'=>'company-notices.remove-upload','methods'=>['POST'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/uploads/{storageObjectPublicId}/preview' => ['name'=>'company-notices.preview-upload','methods'=>['GET'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/uploads/{storageObjectPublicId}/download' => ['name'=>'company-notices.download-upload','methods'=>['GET'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/publish' => ['name'=>'company-notices.publish','methods'=>['POST'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/{notificationPublicId}' => ['name'=>'company-notices.show','methods'=>['GET'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/admin' => ['name'=>'admin.index','methods'=>['GET'],'controller'=>'admin','middleware'=>['authentication','corporate-access']],
    '/admin/category-access' => ['names'=>['GET'=>'admin.category-access.index','POST'=>'admin.category-access.update'],'methods'=>['GET','POST'],'controller'=>'admin','middleware'=>['authentication','corporate-access']],
    '/admin/call-logs' => ['name'=>'admin.call-logs.index','methods'=>['GET'],'controller'=>'call-logs','middleware'=>['authentication','protected-principal']],
    '/admin/call-logs/upload' => ['names'=>['GET'=>'admin.call-logs.upload','POST'=>'admin.call-logs.store'],'methods'=>['GET','POST'],'controller'=>'call-logs','middleware'=>['authentication','protected-principal']],
    '/admin/call-log-reports' => ['name'=>'admin.call-log-reports.index','methods'=>['GET'],'controller'=>'call-log-reports','middleware'=>['authentication','protected-principal']],
    '/admin/call-log-reports/facebook-performance' => ['name'=>'admin.call-log-reports.facebook-performance','methods'=>['GET'],'controller'=>'call-log-reports','middleware'=>['authentication','protected-principal']],
    '/admin/apartments' => ['name'=>'admin.apartments.index','methods'=>['GET'],'controller'=>'apartments','middleware'=>['authentication','protected-principal']],
    '/admin/apartments/import-history' => ['name'=>'admin.apartments.history','methods'=>['GET'],'controller'=>'apartments','middleware'=>['authentication','protected-principal']],
    '/admin/apartments/upload' => ['names'=>['GET'=>'admin.apartments.upload','POST'=>'admin.apartments.store'],'methods'=>['GET','POST'],'controller'=>'apartments','middleware'=>['authentication','protected-principal']],
    '/corporate/admin/property-access' => ['names'=>['GET'=>'admin.property-access.index','POST'=>'admin.property-access.update'],'methods'=>['GET','POST'],'controller'=>'admin','middleware'=>['authentication','admin-access']],
    '/employees' => ['name' => 'employees.index', 'methods' => ['GET'], 'controller' => 'employee-workspace', 'middleware' => ['authentication']],
    '/properties' => ['name'=>'properties.index','methods'=>['GET'],'controller'=>'property-workspace','middleware'=>['authentication']],
    '/human-resources' => ['name'=>'hr.index','methods'=>['GET'],'controller'=>'human-resources','middleware'=>['authentication','corporate-access']],
    '/corporate/human-resources/emergency-contacts'=>['name'=>'hr.emergency-contacts.index','methods'=>['GET'],'controller'=>'hr-emergency-contacts','middleware'=>['authentication','human-resources-access']],
    '/corporate/human-resources/emergency-contacts/{employeePublicId}'=>['name'=>'hr.emergency-contacts.show','methods'=>['GET'],'controller'=>'hr-emergency-contacts','middleware'=>['authentication','human-resources-access']],
    '/corporate/human-resources/emergency-contacts/{employeePublicId}/remind'=>['methods'=>['POST'],'controller'=>'hr-emergency-contacts','middleware'=>['authentication','human-resources-access']],
    '/human-resources/properties' => ['names'=>['GET'=>'hr.properties.index','POST'=>'hr.properties.store'],'methods'=>['GET','POST'],'controller'=>'property-workspace','middleware'=>['authentication','corporate-access']],
    '/human-resources/properties/create' => ['name'=>'hr.properties.create','methods'=>['GET'],'controller'=>'property-workspace','middleware'=>['authentication','corporate-access']],
    '/human-resources/properties/{propertyPublicId}/edit' => ['names'=>['GET'=>'hr.properties.edit','POST'=>'hr.properties.update'],'methods'=>['GET','POST'],'controller'=>'property-workspace','middleware'=>['authentication','corporate-access']],
    '/human-resources/employees' => ['names'=>['GET'=>'hr.employees.index','POST'=>'hr.employees.store'],'methods'=>['GET','POST'],'controller'=>'hr-employee','middleware'=>['authentication','corporate-access']],
    '/human-resources/employees/create' => ['name'=>'hr.employees.create','methods'=>['GET'],'controller'=>'hr-employee','middleware'=>['authentication','corporate-access']],
    '/component-showcase' => [
        'view' => 'pages/component-showcase.php',
        'environments' => ['local', 'development'],
    ],
];
