<?php

declare(strict_types=1);

return [
    '/login' => ['methods' => ['GET', 'POST'], 'controller' => 'authentication'],
    '/logout' => ['methods' => ['POST'], 'controller' => 'authentication'],
    '/dashboard' => ['methods' => ['GET'], 'controller' => 'dashboard', 'middleware' => ['authentication']],
    '/corporate/operations'=>['name'=>'corporate.operations.index','methods'=>['GET'],'controller'=>'corporate-workspace','middleware'=>['authentication','operations-access']],
    '/corporate/operations/inventory-cf'=>['name'=>'corporate.operations.inventory-cf','methods'=>['GET'],'controller'=>'corporate-workspace','middleware'=>['authentication','operations-access']],
    '/corporate/operations/inventory-hr'=>['name'=>'corporate.operations.inventory-hr','methods'=>['GET'],'controller'=>'corporate-workspace','middleware'=>['authentication','operations-access']],
    '/corporate/operations/development'=>['name'=>'corporate.operations.development','methods'=>['GET'],'controller'=>'corporate-workspace','middleware'=>['authentication','operations-access']],
    '/corporate/marketing'=>['name'=>'corporate.marketing.index','methods'=>['GET'],'controller'=>'corporate-workspace','middleware'=>['authentication','marketing-access']],
    '/corporate/marketing/flyers'=>['name'=>'corporate.marketing.flyers','methods'=>['GET'],'controller'=>'corporate-workspace','middleware'=>['authentication','marketing-access']],
    '/notifications' => ['name'=>'notifications.index','methods'=>['GET'],'controller'=>'notifications','middleware'=>['authentication']],
    '/notifications/{notificationPublicId}' => ['name'=>'notifications.show','methods'=>['GET'],'controller'=>'notifications','middleware'=>['authentication']],
    '/notifications/{notificationPublicId}/acknowledge' => ['name'=>'notifications.acknowledge','methods'=>['POST'],'controller'=>'notifications','middleware'=>['authentication']],
    '/storage/{storageObjectPublicId}' => ['name'=>'storage.download','methods'=>['GET'],'controller'=>'storage','middleware'=>['authentication']],
    '/storage/{storageObjectPublicId}/image' => ['name'=>'storage.image','methods'=>['GET'],'controller'=>'storage','middleware'=>['authentication']],
    '/company-notices' => ['name'=>'company-notices.index','methods'=>['GET'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/create' => ['name'=>'company-notices.create','methods'=>['GET'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/preview' => ['name'=>'company-notices.preview','methods'=>['POST'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/discard' => ['name'=>'company-notices.discard','methods'=>['POST'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/uploads/attachments' => ['name'=>'company-notices.upload-attachment','methods'=>['POST'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/uploads/images' => ['name'=>'company-notices.upload-image','methods'=>['POST'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/uploads/{storageObjectPublicId}/remove' => ['name'=>'company-notices.remove-upload','methods'=>['POST'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/uploads/{storageObjectPublicId}/preview' => ['name'=>'company-notices.preview-upload','methods'=>['GET'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/uploads/{storageObjectPublicId}/download' => ['name'=>'company-notices.download-upload','methods'=>['GET'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/publish' => ['name'=>'company-notices.publish','methods'=>['POST'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/company-notices/{notificationPublicId}' => ['name'=>'company-notices.show','methods'=>['GET'],'controller'=>'company-notices','middleware'=>['authentication','company-notices-access']],
    '/admin' => ['name'=>'admin.index','methods'=>['GET'],'controller'=>'admin','middleware'=>['authentication','corporate-access']],
    '/admin/category-access' => ['names'=>['GET'=>'admin.category-access.index','POST'=>'admin.category-access.update'],'methods'=>['GET','POST'],'controller'=>'admin','middleware'=>['authentication','corporate-access']],
    '/employees' => ['name' => 'employees.index', 'methods' => ['GET'], 'controller' => 'employee-workspace', 'middleware' => ['authentication']],
    '/properties' => ['name'=>'properties.index','methods'=>['GET'],'controller'=>'property-workspace','middleware'=>['authentication']],
    '/human-resources' => ['name'=>'hr.index','methods'=>['GET'],'controller'=>'human-resources','middleware'=>['authentication','corporate-access']],
    '/human-resources/properties' => ['names'=>['GET'=>'hr.properties.index','POST'=>'hr.properties.store'],'methods'=>['GET','POST'],'controller'=>'property-workspace','middleware'=>['authentication','corporate-access']],
    '/human-resources/properties/create' => ['name'=>'hr.properties.create','methods'=>['GET'],'controller'=>'property-workspace','middleware'=>['authentication','corporate-access']],
    '/human-resources/employees' => ['names'=>['GET'=>'hr.employees.index','POST'=>'hr.employees.store'],'methods'=>['GET','POST'],'controller'=>'hr-employee','middleware'=>['authentication','corporate-access']],
    '/human-resources/employees/create' => ['name'=>'hr.employees.create','methods'=>['GET'],'controller'=>'hr-employee','middleware'=>['authentication','corporate-access']],
    '/component-showcase' => [
        'view' => 'pages/component-showcase.php',
        'environments' => ['local', 'development'],
    ],
];
