<?php
declare(strict_types=1);
namespace NpmGateway\Container;
use DateTimeZone;
use mysqli;
use NpmGateway\Contracts\AuditStoreInterface;
use NpmGateway\Contracts\ClockInterface;
use NpmGateway\Contracts\CredentialNotifierInterface;
use NpmGateway\Contracts\EmployeeStoreInterface;
use NpmGateway\Contracts\PasswordGeneratorInterface;
use NpmGateway\Contracts\UserStoreInterface;
use NpmGateway\Contracts\SystemInitializationInterface;
use NpmGateway\Contracts\InitializationTransactionInterface;
use NpmGateway\Contracts\SessionTokenGeneratorInterface;
use NpmGateway\Contracts\AuthenticationServiceInterface;
use NpmGateway\Contracts\SessionServiceInterface;
use NpmGateway\Configuration\AuthenticationConfig;
use NpmGateway\Configuration\ProtectedPrincipalConfig;
use NpmGateway\Database\DatabaseProfiles;
use NpmGateway\Database\MySqlConnectionFactory;
use NpmGateway\Database\MySqlInitializationTransaction;
use NpmGateway\Repositories\SessionRepository;
use NpmGateway\Repositories\LoginAttemptRepository;
use NpmGateway\Security\AuthenticationHasher;
use NpmGateway\Services\SessionService;
use NpmGateway\Services\LoginThrottleService;
use NpmGateway\Services\AuthenticationService;
use NpmGateway\Support\SecureSessionTokenGenerator;
use NpmGateway\Notifications\DisabledCredentialNotifier;
use NpmGateway\Repositories\AuditRepository;
use NpmGateway\Repositories\EmployeeRepository;
use NpmGateway\Repositories\EmployeeEmergencyContactRepository;
use NpmGateway\Notifications\EciReminderEmailSender;
use NpmGateway\Services\EciReminderService;
use NpmGateway\Repositories\UserRepository;
use NpmGateway\Repositories\DashboardSummaryRepository;
use NpmGateway\Services\DashboardSummaryService;
use NpmGateway\Services\DashboardHomeService;
use NpmGateway\Services\UniversalToolProvider;
use NpmGateway\Contracts\UniversalToolProviderInterface;
use NpmGateway\Contracts\CorporateToolsProviderInterface;
use NpmGateway\Contracts\EmployeeDirectoryStoreInterface;
use NpmGateway\Services\EmployeeDirectoryService;
use NpmGateway\Services\EmployeeDirectoryCriteriaFactory;
use NpmGateway\Services\CorporateToolsProvider;
use NpmGateway\Services\CorporateAccessService;
use NpmGateway\Contracts\DashboardSummaryStoreInterface;
use NpmGateway\Services\AuditService;
use NpmGateway\Services\GatewayNotificationRecipientEligibilityPolicy;
use NpmGateway\Services\NotificationRecipientResolver;
use NpmGateway\Services\EmployeeService;
use NpmGateway\Services\EmployeeEmergencyContactService;
use NpmGateway\Services\ManagerMaintenanceEciAccessService;
use NpmGateway\Services\NotificationService;
use NpmGateway\Services\PasswordService;
use NpmGateway\Services\SystemInitializationService;
use NpmGateway\Services\UserService;
use NpmGateway\Support\PublicIdGenerator;
use NpmGateway\Support\SecurePasswordGenerator;
use NpmGateway\Support\SystemClock;
use NpmGateway\Contracts\PropertyDirectoryStoreInterface;
use NpmGateway\Contracts\PropertyStoreInterface;
use NpmGateway\Contracts\PropertyTransactionInterface;
use NpmGateway\Database\MySqlPropertyTransaction;
use NpmGateway\Repositories\PropertyRepository;
use NpmGateway\Repositories\PropertyAccessRepository;
use NpmGateway\Contracts\PropertyAccessStoreInterface;
use NpmGateway\Services\PropertyAccessService;
use NpmGateway\Services\PropertyAccessPayloadParser;
use NpmGateway\Services\CommunityActionContextResolver;
use NpmGateway\Services\CommunityActionProvider;
use NpmGateway\Services\PropertyAdministrationService;
use NpmGateway\Services\PropertyDirectoryCriteriaFactory;
use NpmGateway\Services\PropertyQueryService;
use NpmGateway\Services\PropertyValidator;
use NpmGateway\Support\PhoneFormatter;
use NpmGateway\Support\PropertyAddressFormatter;
use NpmGateway\Contracts\CorporateContextStoreInterface;
use NpmGateway\Services\CorporateContextService;
use NpmGateway\Services\CorporateContextSeeder;
use NpmGateway\Contracts\HrEmployeeStoreInterface;
use NpmGateway\Contracts\HrEmployeeNotifierInterface;
use NpmGateway\Notifications\DisabledHrEmployeeNotifier;
use NpmGateway\Services\HrEmployeeValidator;
use NpmGateway\Services\HrEmployeeNotificationService;
use NpmGateway\Services\HrEmployeeCreationService;
use NpmGateway\Services\HrEmployeeNotificationConfig;
use NpmGateway\Notifications\SmtpEmployeeNotificationSender;
use NpmGateway\Contracts\CategoryAccessStoreInterface;
use NpmGateway\Repositories\CategoryAccessRepository;
use NpmGateway\Services\CategoryAccessAdministrationService;
use NpmGateway\Services\ProtectedPrincipalService;
use NpmGateway\Services\CategoryAccessBackfillService;
use NpmGateway\Services\OperationsAccessBackfillService;
use NpmGateway\Services\CategoryAccessPayloadParser;
use NpmGateway\Contracts\NotificationPublisherInterface;
use NpmGateway\Contracts\CompanyAnnouncementEmailSenderInterface;
use NpmGateway\Repositories\NotificationRepository;
use NpmGateway\Repositories\NotificationRecipientRepository;
use NpmGateway\Services\NotificationPublisher;
use NpmGateway\Services\NotificationQueryService;
use NpmGateway\Services\NotificationAcknowledgmentService;
use NpmGateway\Services\EmployeeAnnouncementFactory;
use NpmGateway\Services\CompanyAnnouncementDispatchService;
use NpmGateway\Notifications\CompanyAnnouncementEmailSender;
use NpmGateway\Notifications\DisabledCompanyAnnouncementEmailSender;
use NpmGateway\Notifications\CompanyAnnouncementEmailRenderer;
use NpmGateway\Notifications\GatewayEmailRenderer;
use NpmGateway\Services\EmployeeAnnouncementEmailBuilder;
use NpmGateway\Services\NotificationPresentationService;
use NpmGateway\Support\CompanyDateFormatter;
use NpmGateway\Notifications\CompanyNoticeEmailSender;
use NpmGateway\Services\CompanyNoticeValidator;
use NpmGateway\Services\CompanyNoticePublicationService;
  use NpmGateway\Services\CompanyNoticeQueryService;
use NpmGateway\Services\CompanyNoticeDiagnosticLogger;
use NpmGateway\Contracts\StorageAdapterInterface;
use NpmGateway\Contracts\StorageObjectStoreInterface;
use NpmGateway\Repositories\StorageObjectRepository;
use NpmGateway\Repositories\NotificationStorageObjectRepository;
use NpmGateway\Services\StorageConfiguration;
use NpmGateway\Services\StorageObjectKeyGenerator;
use NpmGateway\Services\StorageUploadValidator;
use NpmGateway\Services\CompanyNoticeZipValidator;
use NpmGateway\Services\GatewayStorageService;
use NpmGateway\Services\CompanyNoticeComposeStore;
use NpmGateway\Services\CompanyNoticeAssetService;
use NpmGateway\Services\CompanyNoticeDraftDiscardService;
use NpmGateway\Services\CompanyNoticeReviewStore;
use NpmGateway\Services\TemporaryStorageDeletionService;
use NpmGateway\Services\TemporaryStorageCleanupService;
use NpmGateway\Services\RichTextSanitizer;
use NpmGateway\Storage\WasabiStorageAdapter;
use NpmGateway\Services\PublishedStorageService;
use NpmGateway\Repositories\ApplicationReviewRepository;
use NpmGateway\Repositories\CreditCardPurchaseRepository;
use NpmGateway\Services\ApplicationReviewValidator;
use NpmGateway\Services\ApplicationReviewService;
use NpmGateway\Services\CreditCardPurchaseService;
use NpmGateway\Services\CreditCardPurchaseValidator;
use NpmGateway\Services\CreditCardReceiptTestCleanupService;
use NpmGateway\Services\ApplicationReviewQueryService;
use NpmGateway\Notifications\ApplicationReviewEmailSender;
use NpmGateway\Repositories\RmCorrectionRepository;
use NpmGateway\Services\RmCorrectionValidator;
use NpmGateway\Services\RmCorrectionQueryService;
use NpmGateway\Services\RmCorrectionService;
use NpmGateway\Services\OperationsRmCorrectionOverviewService;
use NpmGateway\Services\OperationsRmAuditOverviewService;
use NpmGateway\Contracts\GatewayPdfRendererInterface;
use NpmGateway\Services\Pdf\DompdfGatewayPdfRenderer;
use NpmGateway\Notifications\RmCorrectionEmailSender;
use NpmGateway\Repositories\RmAuditRepository;
use NpmGateway\Services\RmAuditRichTextSanitizer;
use NpmGateway\Services\RmAuditValidator;
use NpmGateway\Services\RmAuditQueryService;
use NpmGateway\Services\RmAuditService;
use NpmGateway\Notifications\RmAuditEmailSender;
final class ServiceProvider
{
    /** @param array<string, mixed> $application */
    public static function build(array $application): Container
    {
        $container = new Container();
        $root = (string) $application['root'];
        $app = (array) $application['config']['app'];
        $notice = require $root . '/config/credential-notification.php';
        $hrNotice = require $root . '/config/hr-employee-notification.php';
        $corporateAccess = require $root . '/config/corporate-access.php';
        $protectedPrincipal = require $root . '/config/protected-principal.php';
        $storage = require $root . '/config/storage.php';
        $applicationReviews = require $root . '/config/application-reviews.php';
        $rmCorrections = require $root . '/config/rm-corrections.php';
        $rmAudits = require $root . '/config/rm-audits.php';
        /** @var AuthenticationConfig $authentication */
        $authentication = require $root . '/config/authentication.php';
        $container->instance('config.notification', $notice);
        $container->instance('config.hr-employee-notification',$hrNotice);
        $container->instance('config.corporate-access', $corporateAccess);
        $container->instance(ProtectedPrincipalConfig::class,ProtectedPrincipalConfig::fromArray($protectedPrincipal,(array)$corporateAccess['categories']));
        $container->instance('config.storage',$storage);
        $container->instance('config.application-reviews',$applicationReviews);
        $container->instance('config.rm-corrections',$rmCorrections);
        $container->instance('config.rm-audits',$rmAudits);
        $container->instance(AuthenticationConfig::class, $authentication);
        $container->set(mysqli::class, static fn (): mysqli => MySqlConnectionFactory::connect(DatabaseProfiles::load('application', $root)));
        $container->set(PasswordGeneratorInterface::class, static fn (): PasswordGeneratorInterface => new SecurePasswordGenerator());
        $container->set(ClockInterface::class, static fn (): ClockInterface => new SystemClock(new DateTimeZone((string) ($app['timezone'] ?? 'UTC'))));
        $container->set(CredentialNotifierInterface::class, static fn (): CredentialNotifierInterface => new DisabledCredentialNotifier());
        $container->set(HrEmployeeNotifierInterface::class,static function(Container $c):HrEmployeeNotifierInterface{try{return new SmtpEmployeeNotificationSender(HrEmployeeNotificationConfig::fromArray($c->get('config.hr-employee-notification')));}catch(\Throwable){return new DisabledHrEmployeeNotifier();}});
        $container->set(PublicIdGenerator::class, static fn (): PublicIdGenerator => new PublicIdGenerator());
        $container->set(StorageConfiguration::class,static fn(Container $c):StorageConfiguration=>StorageConfiguration::fromArray($c->get('config.storage')));
        $container->set(StorageAdapterInterface::class,static fn(Container $c):StorageAdapterInterface=>WasabiStorageAdapter::create($c->get(StorageConfiguration::class)->endpoint,$c->get(StorageConfiguration::class)->region,$c->get(StorageConfiguration::class)->accessKey,$c->get(StorageConfiguration::class)->secretKey));
        $container->set(StorageObjectRepository::class,static fn(Container $c):StorageObjectRepository=>new StorageObjectRepository($c->get(mysqli::class)));
        $container->set(StorageObjectStoreInterface::class,static fn(Container $c):StorageObjectStoreInterface=>$c->get(StorageObjectRepository::class));
        $container->set(NotificationStorageObjectRepository::class,static fn(Container $c):NotificationStorageObjectRepository=>new NotificationStorageObjectRepository($c->get(mysqli::class)));
        $container->set(StorageObjectKeyGenerator::class,static fn():StorageObjectKeyGenerator=>new StorageObjectKeyGenerator());
        $container->set(CompanyNoticeZipValidator::class,static fn():CompanyNoticeZipValidator=>new CompanyNoticeZipValidator());
        $container->set(StorageUploadValidator::class,static fn(Container $c):StorageUploadValidator=>new StorageUploadValidator($c->get(CompanyNoticeZipValidator::class)));
        $container->set(RichTextSanitizer::class,static fn():RichTextSanitizer=>new RichTextSanitizer());
        $container->set(CompanyNoticeComposeStore::class,static function(Container $c):CompanyNoticeComposeStore{return new CompanyNoticeComposeStore($_SESSION,$c->get(PublicIdGenerator::class));});
        $container->set(CompanyNoticeReviewStore::class,static function(Container $c):CompanyNoticeReviewStore{return new CompanyNoticeReviewStore($_SESSION,$c->get(PublicIdGenerator::class));});
        $container->set(SessionTokenGeneratorInterface::class, static fn (): SessionTokenGeneratorInterface => new SecureSessionTokenGenerator());
        $container->set(AuthenticationHasher::class, static fn(Container $c):AuthenticationHasher=>new AuthenticationHasher($c->get(AuthenticationConfig::class)));
        $container->set(EmployeeRepository::class,static fn(Container $c):EmployeeRepository=>new EmployeeRepository($c->get(mysqli::class)));
        $container->set(EmployeeEmergencyContactRepository::class,static fn(Container $c):EmployeeEmergencyContactRepository=>new EmployeeEmergencyContactRepository($c->get(mysqli::class)));
        $container->set(ManagerMaintenanceEciAccessService::class,static fn(Container $c):ManagerMaintenanceEciAccessService=>new ManagerMaintenanceEciAccessService($c->get(EmployeeEmergencyContactRepository::class)));
        $container->set(EciReminderEmailSender::class,static function(Container $c)use($app):EciReminderEmailSender{try{$config=HrEmployeeNotificationConfig::fromArray($c->get('config.hr-employee-notification'));}catch(\Throwable){$config=null;}return new EciReminderEmailSender($config,(string)($app['url']??''));});
        $container->set(EciReminderService::class,static fn(Container $c):EciReminderService=>new EciReminderService($c->get(EmployeeEmergencyContactRepository::class),$c->get(GatewayNotificationRecipientEligibilityPolicy::class),$c->get(EciReminderEmailSender::class),$c->get(AuditRepository::class),$c->get(AuditService::class),$c->get(ClockInterface::class)));
        $container->set(EmployeeStoreInterface::class, static fn (Container $c): EmployeeStoreInterface => $c->get(EmployeeRepository::class));
        $container->set(HrEmployeeStoreInterface::class,static fn(Container $c):HrEmployeeStoreInterface=>$c->get(EmployeeRepository::class));
        $container->set(EmployeeDirectoryStoreInterface::class,static fn(Container $c):EmployeeDirectoryStoreInterface=>$c->get(EmployeeRepository::class));
        $container->set(EmployeeDirectoryCriteriaFactory::class,static fn():EmployeeDirectoryCriteriaFactory=>new EmployeeDirectoryCriteriaFactory());
        $container->set(EmployeeDirectoryService::class,static fn(Container $c):EmployeeDirectoryService=>new EmployeeDirectoryService($c->get(EmployeeDirectoryStoreInterface::class),$c->get(PhoneFormatter::class)));
        $container->set(UserStoreInterface::class, static fn (Container $c): UserStoreInterface => new UserRepository($c->get(mysqli::class)));
        $container->set(AuditStoreInterface::class, static fn (Container $c): AuditStoreInterface => new AuditRepository($c->get(mysqli::class)));
        $container->set(AuditRepository::class,static fn(Container $c):AuditRepository=>new AuditRepository($c->get(mysqli::class)));
        $container->set(SessionRepository::class,static fn(Container $c):SessionRepository=>new SessionRepository($c->get(mysqli::class)));
        $container->set(LoginAttemptRepository::class,static fn(Container $c):LoginAttemptRepository=>new LoginAttemptRepository($c->get(mysqli::class)));
        $container->set(DashboardSummaryRepository::class,static fn(Container $c):DashboardSummaryRepository=>new DashboardSummaryRepository($c->get(mysqli::class)));
        $container->set(DashboardSummaryStoreInterface::class,static fn(Container $c):DashboardSummaryStoreInterface=>$c->get(DashboardSummaryRepository::class));
        $container->set(DashboardSummaryService::class,static fn(Container $c):DashboardSummaryService=>new DashboardSummaryService($c->get(DashboardSummaryStoreInterface::class)));
        $container->set(UniversalToolProviderInterface::class,static fn():UniversalToolProviderInterface=>new UniversalToolProvider());
        $container->set(CorporateToolsProviderInterface::class,static fn(Container $c):CorporateToolsProviderInterface=>new CorporateToolsProvider($c->get(CorporateAccessService::class)));
        $container->set(CategoryAccessRepository::class,static fn(Container $c):CategoryAccessRepository=>new CategoryAccessRepository($c->get(mysqli::class)));
        $container->set(CategoryAccessStoreInterface::class,static fn(Container $c):CategoryAccessStoreInterface=>$c->get(CategoryAccessRepository::class));
        $container->set(CorporateAccessService::class,static fn(Container $c):CorporateAccessService=>new CorporateAccessService($c->get(CategoryAccessStoreInterface::class),(array)$c->get('config.corporate-access')['categories']));
        $container->set(PropertyRepository::class,static fn(Container $c):PropertyRepository=>new PropertyRepository($c->get(mysqli::class)));
        $container->set(PropertyAccessRepository::class,static fn(Container $c):PropertyAccessRepository=>new PropertyAccessRepository($c->get(mysqli::class)));
        $container->set(ApplicationReviewRepository::class,static fn(Container $c):ApplicationReviewRepository=>new ApplicationReviewRepository($c->get(mysqli::class)));
        $container->set(RmCorrectionRepository::class,static fn(Container $c):RmCorrectionRepository=>new RmCorrectionRepository($c->get(mysqli::class)));
        $container->set(RmAuditRepository::class,static fn(Container $c):RmAuditRepository=>new RmAuditRepository($c->get(mysqli::class)));
        $container->set(CreditCardPurchaseRepository::class,static fn(Container $c):CreditCardPurchaseRepository=>new CreditCardPurchaseRepository($c->get(mysqli::class)));
        $container->set(PropertyAccessStoreInterface::class,static fn(Container $c):PropertyAccessStoreInterface=>$c->get(PropertyAccessRepository::class));
        $container->set(PropertyStoreInterface::class,static fn(Container $c):PropertyStoreInterface=>$c->get(PropertyRepository::class));
        $container->set(PropertyDirectoryStoreInterface::class,static fn(Container $c):PropertyDirectoryStoreInterface=>$c->get(PropertyRepository::class));
        $container->set(CorporateContextStoreInterface::class,static fn(Container $c):CorporateContextStoreInterface=>$c->get(PropertyRepository::class));
        $container->set(PropertyTransactionInterface::class,static fn(Container $c):PropertyTransactionInterface=>new MySqlPropertyTransaction($c->get(mysqli::class)));
        $container->set(PhoneFormatter::class,static fn():PhoneFormatter=>new PhoneFormatter());
        $container->set(CompanyDateFormatter::class,static fn():CompanyDateFormatter=>new CompanyDateFormatter());
        $container->set(CompanyAnnouncementEmailRenderer::class,static fn():CompanyAnnouncementEmailRenderer=>new CompanyAnnouncementEmailRenderer());
        $container->set(GatewayEmailRenderer::class,static fn():GatewayEmailRenderer=>new GatewayEmailRenderer());
        $container->set(EmployeeAnnouncementEmailBuilder::class,static fn(Container $c):EmployeeAnnouncementEmailBuilder=>new EmployeeAnnouncementEmailBuilder($c->get(CompanyDateFormatter::class),$c->get(PhoneFormatter::class)));
        $container->set(NotificationPresentationService::class,static fn(Container $c):NotificationPresentationService=>new NotificationPresentationService($c->get(CompanyDateFormatter::class),$c->get(PhoneFormatter::class)));
        $container->set(CompanyNoticeValidator::class,static fn(Container $c):CompanyNoticeValidator=>new CompanyNoticeValidator($c->get(RichTextSanitizer::class)));
        $container->set(CompanyNoticeQueryService::class,static fn(Container $c):CompanyNoticeQueryService=>new CompanyNoticeQueryService($c->get(NotificationRepository::class),$c->get(NotificationStorageObjectRepository::class)));
        $container->set(CompanyNoticeDiagnosticLogger::class,static fn():CompanyNoticeDiagnosticLogger=>new CompanyNoticeDiagnosticLogger());
        $container->set(CompanyNoticeEmailSender::class,static function(Container $c)use($app):CompanyNoticeEmailSender{try{$config=HrEmployeeNotificationConfig::fromArray($c->get('config.hr-employee-notification'));$storage=$c->get(StorageAdapterInterface::class);}catch(\Throwable){$config=null;$storage=null;}return new CompanyNoticeEmailSender($config,$c->get(CompanyAnnouncementEmailRenderer::class),null,$storage,(string)($app['url']??''));});
        $container->set(CompanyNoticePublicationService::class,static fn(Container $c):CompanyNoticePublicationService=>new CompanyNoticePublicationService($c->get(NotificationRepository::class),$c->get(NotificationRecipientRepository::class),$c->get(InitializationTransactionInterface::class),$c->get(PublicIdGenerator::class),$c->get(ClockInterface::class),$c->get(CompanyNoticeValidator::class),$c->get(CompanyNoticeEmailSender::class),$c->get(AuditService::class),$c->get(CompanyDateFormatter::class),$c->get(CompanyNoticeDiagnosticLogger::class),$c->get(CompanyNoticeAssetService::class),$c->get(NotificationStorageObjectRepository::class),$c->get(StorageObjectStoreInterface::class),$c->get(RichTextSanitizer::class),$c->get(NotificationRecipientResolver::class)));
        $container->set(PropertyAddressFormatter::class,static fn():PropertyAddressFormatter=>new PropertyAddressFormatter());
        $container->set(PropertyDirectoryCriteriaFactory::class,static fn():PropertyDirectoryCriteriaFactory=>new PropertyDirectoryCriteriaFactory());
        $container->set(PropertyQueryService::class,static fn(Container $c):PropertyQueryService=>new PropertyQueryService($c->get(PropertyDirectoryStoreInterface::class),$c->get(PropertyAddressFormatter::class),$c->get(PhoneFormatter::class)));
        $container->set(PropertyValidator::class,static fn(Container $c):PropertyValidator=>new PropertyValidator($c->get(PropertyStoreInterface::class),$c->get(PhoneFormatter::class)));
        $container->set(CorporateContextService::class,static fn(Container $c):CorporateContextService=>new CorporateContextService($c->get(CorporateContextStoreInterface::class),$c->get(PublicIdGenerator::class),$c->get(AuditService::class),$c->get(ClockInterface::class)));
        $container->set(CorporateContextSeeder::class,static fn(Container $c):CorporateContextSeeder=>new CorporateContextSeeder($c->get(PropertyTransactionInterface::class),$c->get(CorporateContextService::class)));
        $container->set(DashboardHomeService::class,static fn(Container $c):DashboardHomeService=>new DashboardHomeService($c->get(DashboardSummaryService::class),$c->get(UniversalToolProviderInterface::class),$c->get(CorporateToolsProviderInterface::class),$c->get(CorporateAccessService::class)));
        $container->set(InitializationTransactionInterface::class, static fn (Container $c): InitializationTransactionInterface => new MySqlInitializationTransaction($c->get(mysqli::class)));
        $container->set(PasswordService::class, static fn (Container $c): PasswordService => new PasswordService($c->get(PasswordGeneratorInterface::class)));
        $container->set(HrEmployeeValidator::class,static fn(Container $c):HrEmployeeValidator=>new HrEmployeeValidator($c->get(HrEmployeeStoreInterface::class),$c->get(UserStoreInterface::class),$c->get(PhoneFormatter::class),$c->get(ClockInterface::class)));
        $container->set(HrEmployeeNotificationService::class,static fn(Container $c):HrEmployeeNotificationService=>new HrEmployeeNotificationService($c->get(HrEmployeeNotifierInterface::class),$c->get('config.hr-employee-notification')));
        $container->set(NotificationRepository::class,static fn(Container $c):NotificationRepository=>new NotificationRepository($c->get(mysqli::class)));
        $container->set(NotificationRecipientRepository::class,static fn(Container $c):NotificationRecipientRepository=>new NotificationRecipientRepository($c->get(mysqli::class)));
        $container->set(GatewayNotificationRecipientEligibilityPolicy::class,static fn():GatewayNotificationRecipientEligibilityPolicy=>new GatewayNotificationRecipientEligibilityPolicy());
        $container->set(NotificationRecipientResolver::class,static fn(Container $c):NotificationRecipientResolver=>new NotificationRecipientResolver($c->get(NotificationRecipientRepository::class),$c->get(GatewayNotificationRecipientEligibilityPolicy::class)));
        $container->set(NotificationQueryService::class,static fn(Container $c):NotificationQueryService=>new NotificationQueryService($c->get(mysqli::class),$c->get(NotificationStorageObjectRepository::class)));
        $container->set(NotificationAcknowledgmentService::class,static fn(Container $c):NotificationAcknowledgmentService=>new NotificationAcknowledgmentService($c->get(mysqli::class),$c->get(NotificationQueryService::class),$c->get(AuditService::class),$c->get(ClockInterface::class)));
        $container->set(EmployeeAnnouncementFactory::class,static fn():EmployeeAnnouncementFactory=>new EmployeeAnnouncementFactory());
        $container->set(NotificationPublisherInterface::class,static fn(Container $c):NotificationPublisherInterface=>new NotificationPublisher($c->get(NotificationRepository::class),$c->get(NotificationRecipientRepository::class),$c->get(InitializationTransactionInterface::class),$c->get(PublicIdGenerator::class),$c->get(ClockInterface::class),$c->get(AuditService::class),$c->get(NotificationRecipientResolver::class)));
        $container->set(CompanyAnnouncementEmailSenderInterface::class,static function(Container $c):CompanyAnnouncementEmailSenderInterface{try{return new CompanyAnnouncementEmailSender(HrEmployeeNotificationConfig::fromArray($c->get('config.hr-employee-notification')),$c->get(EmployeeAnnouncementEmailBuilder::class),$c->get(CompanyAnnouncementEmailRenderer::class));}catch(\Throwable){return new DisabledCompanyAnnouncementEmailSender();}});
        $container->set(CompanyAnnouncementDispatchService::class,static fn(Container $c):CompanyAnnouncementDispatchService=>new CompanyAnnouncementDispatchService($c->get(NotificationRecipientRepository::class),$c->get(CompanyAnnouncementEmailSenderInterface::class),$c->get(ClockInterface::class),$c->get(AuditService::class)));
        $container->set(HrEmployeeCreationService::class,static fn(Container $c):HrEmployeeCreationService=>new HrEmployeeCreationService($c->get(HrEmployeeValidator::class),$c->get(HrEmployeeStoreInterface::class),$c->get(InitializationTransactionInterface::class),$c->get(UserService::class),$c->get(PasswordService::class),$c->get(AuditService::class),$c->get(HrEmployeeNotificationService::class),$c->get(PublicIdGenerator::class),$c->get(ClockInterface::class),$c->get('config.hr-employee-notification'),$c->get(EmployeeAnnouncementFactory::class),$c->get(NotificationPublisherInterface::class),$c->get(CompanyAnnouncementDispatchService::class)));
        $container->set(EmployeeService::class, static fn (Container $c): EmployeeService => new EmployeeService($c->get(EmployeeStoreInterface::class), $c->get(PublicIdGenerator::class)));
        $container->set(EmployeeEmergencyContactService::class,static fn(Container $c):EmployeeEmergencyContactService=>new EmployeeEmergencyContactService($c->get(EmployeeEmergencyContactRepository::class),$c->get(InitializationTransactionInterface::class),$c->get(PublicIdGenerator::class),$c->get(ClockInterface::class),$c->get(PhoneFormatter::class),$c->get(AuditService::class)));
        $container->set(UserService::class, static fn (Container $c): UserService => new UserService($c->get(UserStoreInterface::class), $c->get(PublicIdGenerator::class)));
        $container->set(AuditService::class, static fn (Container $c): AuditService => new AuditService($c->get(AuditStoreInterface::class), $c->get(PublicIdGenerator::class)));
        $container->set(GatewayStorageService::class,static fn(Container $c):GatewayStorageService=>new GatewayStorageService($c->get(StorageConfiguration::class),$c->get(StorageAdapterInterface::class),$c->get(StorageObjectStoreInterface::class),$c->get(StorageObjectKeyGenerator::class),$c->get(StorageUploadValidator::class),$c->get(PublicIdGenerator::class),$c->get(ClockInterface::class),$c->get(AuditService::class)));
        $container->set(TemporaryStorageDeletionService::class,static fn(Container $c):TemporaryStorageDeletionService=>new TemporaryStorageDeletionService($c->get(StorageObjectStoreInterface::class),$c->get(StorageAdapterInterface::class),$c->get(AuditService::class)));
        $container->set(TemporaryStorageCleanupService::class,static fn(Container $c):TemporaryStorageCleanupService=>new TemporaryStorageCleanupService($c->get(StorageObjectStoreInterface::class),$c->get(StorageAdapterInterface::class),$c->get(AuditService::class),new DateTimeZone((string)($app['timezone']??'UTC'))));
        $container->set(CompanyNoticeAssetService::class,static fn(Container $c):CompanyNoticeAssetService=>new CompanyNoticeAssetService($c->get(CompanyNoticeComposeStore::class),$c->get(StorageObjectStoreInterface::class),$c->get(GatewayStorageService::class),$c->get(TemporaryStorageDeletionService::class)));
        $container->set(CompanyNoticeDraftDiscardService::class,static fn(Container $c):CompanyNoticeDraftDiscardService=>new CompanyNoticeDraftDiscardService($c->get(CompanyNoticeComposeStore::class),$c->get(CompanyNoticeAssetService::class),$c->get(CompanyNoticeReviewStore::class),$c->get(AuditService::class),$c->get(ClockInterface::class)));
        $container->set(PublishedStorageService::class,static fn(Container $c):PublishedStorageService=>new PublishedStorageService($c->get(StorageObjectRepository::class),$c->get(CorporateAccessService::class),$c->get(GatewayStorageService::class)));
        $container->set(PropertyAdministrationService::class,static fn(Container $c):PropertyAdministrationService=>new PropertyAdministrationService($c->get(PropertyValidator::class),$c->get(PropertyStoreInterface::class),$c->get(PropertyTransactionInterface::class),$c->get(PublicIdGenerator::class),$c->get(AuditService::class),$c->get(ClockInterface::class)));
        $container->set(PropertyAccessService::class,static fn(Container $c):PropertyAccessService=>new PropertyAccessService($c->get(PropertyAccessStoreInterface::class),$c->get(InitializationTransactionInterface::class),$c->get(AuditService::class),$c->get(PublicIdGenerator::class),$c->get(ClockInterface::class)));
        $container->set(PropertyAccessPayloadParser::class,static fn():PropertyAccessPayloadParser=>new PropertyAccessPayloadParser());
        $container->set(CommunityActionContextResolver::class,static fn(Container $c):CommunityActionContextResolver=>new CommunityActionContextResolver($c->get(PropertyAccessService::class)));
        $container->set(CommunityActionProvider::class,static fn(Container $c):CommunityActionProvider=>new CommunityActionProvider($c->get(RmAuditQueryService::class)));
        $container->set(ApplicationReviewValidator::class,static fn():ApplicationReviewValidator=>new ApplicationReviewValidator());
        $container->set(ApplicationReviewQueryService::class,static fn(Container $c):ApplicationReviewQueryService=>new ApplicationReviewQueryService($c->get(ApplicationReviewRepository::class)));
        $container->set(ApplicationReviewEmailSender::class,static fn(Container $c):ApplicationReviewEmailSender=>new ApplicationReviewEmailSender((array)$c->get('config.application-reviews'),null,$c->get(GatewayEmailRenderer::class)));
        $container->set(ApplicationReviewService::class,static fn(Container $c):ApplicationReviewService=>new ApplicationReviewService($c->get(ApplicationReviewRepository::class),$c->get(ApplicationReviewValidator::class),$c->get(InitializationTransactionInterface::class),$c->get(PublicIdGenerator::class),$c->get(ClockInterface::class),$c->get(AuditService::class),$c->get(ApplicationReviewEmailSender::class),$c->get(PropertyAccessService::class)));
        $container->set(RmCorrectionValidator::class,static fn():RmCorrectionValidator=>new RmCorrectionValidator());
        $container->set(RmCorrectionQueryService::class,static fn(Container $c):RmCorrectionQueryService=>new RmCorrectionQueryService($c->get(RmCorrectionRepository::class)));
        $container->set(OperationsRmCorrectionOverviewService::class,static fn(Container $c):OperationsRmCorrectionOverviewService=>new OperationsRmCorrectionOverviewService($c->get(RmCorrectionRepository::class)));
        $container->set(OperationsRmAuditOverviewService::class,static fn(Container $c):OperationsRmAuditOverviewService=>new OperationsRmAuditOverviewService($c->get(RmAuditRepository::class)));
        $container->set(GatewayPdfRendererInterface::class,static fn(Container $c):GatewayPdfRendererInterface=>new DompdfGatewayPdfRenderer($root.'/resources/views/pdf'));
        $container->set(RmCorrectionEmailSender::class,static fn(Container $c):RmCorrectionEmailSender=>new RmCorrectionEmailSender((array)$c->get('config.rm-corrections'),null,$c->get(GatewayEmailRenderer::class)));
        $container->set(RmCorrectionService::class,static fn(Container $c):RmCorrectionService=>new RmCorrectionService($c->get(RmCorrectionRepository::class),$c->get(RmCorrectionValidator::class),$c->get(InitializationTransactionInterface::class),$c->get(PublicIdGenerator::class),$c->get(ClockInterface::class),$c->get(AuditService::class),$c->get(RmCorrectionEmailSender::class),$c->get(PropertyAccessService::class)));
        $container->set(RmAuditRichTextSanitizer::class,static fn():RmAuditRichTextSanitizer=>new RmAuditRichTextSanitizer());
        $container->set(RmAuditValidator::class,static fn(Container $c):RmAuditValidator=>new RmAuditValidator($c->get(RmAuditRichTextSanitizer::class)));
        $container->set(RmAuditQueryService::class,static fn(Container $c):RmAuditQueryService=>new RmAuditQueryService($c->get(RmAuditRepository::class)));
        $container->set(RmAuditEmailSender::class,static fn(Container $c):RmAuditEmailSender=>new RmAuditEmailSender((array)$c->get('config.rm-audits'),null,$c->get(GatewayEmailRenderer::class)));
        $container->set(RmAuditService::class,static fn(Container $c):RmAuditService=>new RmAuditService($c->get(RmAuditRepository::class),$c->get(RmAuditValidator::class),$c->get(InitializationTransactionInterface::class),$c->get(PublicIdGenerator::class),$c->get(ClockInterface::class),$c->get(AuditService::class),$c->get(RmAuditEmailSender::class),$c->get(PropertyAccessService::class)));
        $container->set(CreditCardPurchaseValidator::class,static fn():CreditCardPurchaseValidator=>new CreditCardPurchaseValidator());
        $container->set(CreditCardReceiptTestCleanupService::class,static fn(Container $c):CreditCardReceiptTestCleanupService=>new CreditCardReceiptTestCleanupService($c->get(StorageConfiguration::class),$c->get(StorageAdapterInterface::class),$c->get(StorageObjectRepository::class)));
        $container->set(CreditCardPurchaseService::class,static fn(Container $c):CreditCardPurchaseService=>new CreditCardPurchaseService($c->get(CreditCardPurchaseRepository::class),$c->get(CreditCardPurchaseValidator::class),$c->get(InitializationTransactionInterface::class),$c->get(PublicIdGenerator::class),$c->get(ClockInterface::class),$c->get(AuditService::class),$c->get(PropertyAccessService::class),$c->get(GatewayStorageService::class),$c->get(StorageObjectStoreInterface::class)));
        $container->set(ProtectedPrincipalService::class,static fn(Container $c):ProtectedPrincipalService=>new ProtectedPrincipalService($c->get(ProtectedPrincipalConfig::class),$c->get(CategoryAccessStoreInterface::class),$c->get(AuditService::class),$c->get(ClockInterface::class)));
        $container->set(CategoryAccessAdministrationService::class,static fn(Container $c):CategoryAccessAdministrationService=>new CategoryAccessAdministrationService($c->get(CategoryAccessStoreInterface::class),$c->get(InitializationTransactionInterface::class),$c->get(AuditService::class),$c->get(PublicIdGenerator::class),$c->get(ClockInterface::class),(array)$c->get('config.corporate-access')['categories'],$c->get(ProtectedPrincipalService::class)));
        $container->set(CategoryAccessPayloadParser::class,static fn(Container $c):CategoryAccessPayloadParser=>new CategoryAccessPayloadParser((array)$c->get('config.corporate-access')['categories']));
        $container->set(CategoryAccessBackfillService::class,static fn(Container $c):CategoryAccessBackfillService=>new CategoryAccessBackfillService($c->get(CategoryAccessStoreInterface::class),$c->get(InitializationTransactionInterface::class),$c->get(AuditService::class),$c->get(PublicIdGenerator::class),$c->get(ClockInterface::class),(array)$c->get('config.corporate-access')['categories']));
        $container->set(OperationsAccessBackfillService::class,static fn(Container $c):OperationsAccessBackfillService=>new OperationsAccessBackfillService($c->get(CategoryAccessStoreInterface::class),$c->get(InitializationTransactionInterface::class),$c->get(AuditService::class),$c->get(PublicIdGenerator::class),$c->get(ClockInterface::class),(array)$c->get('config.corporate-access')['categories']));
        $container->set(NotificationService::class, static fn (Container $c): NotificationService => new NotificationService($c->get(CredentialNotifierInterface::class), $c->get('config.notification')));
        $container->set(SessionService::class,static fn(Container $c):SessionService=>new SessionService($c->get(SessionRepository::class),$c->get(UserStoreInterface::class),$c->get(SessionTokenGeneratorInterface::class),$c->get(AuthenticationHasher::class),$c->get(PublicIdGenerator::class),$c->get(AuthenticationConfig::class),$c->get(AuditService::class)));
        $container->set(LoginThrottleService::class,static fn(Container $c):LoginThrottleService=>new LoginThrottleService($c->get(LoginAttemptRepository::class),$c->get(AuthenticationConfig::class)));
        $container->set(AuthenticationService::class,static fn(Container $c):AuthenticationService=>new AuthenticationService($c->get(InitializationTransactionInterface::class),$c->get(UserStoreInterface::class),$c->get(LoginAttemptRepository::class),$c->get(LoginThrottleService::class),$c->get(SessionService::class),$c->get(AuditService::class),$c->get(AuthenticationHasher::class),$c->get(PublicIdGenerator::class),$c->get(AuthenticationConfig::class)));
        $container->set(AuthenticationServiceInterface::class,static fn(Container $c):AuthenticationServiceInterface=>$c->get(AuthenticationService::class));
        $container->set(SessionServiceInterface::class,static fn(Container $c):SessionServiceInterface=>$c->get(SessionService::class));
        $container->set(SystemInitializationService::class, static fn (Container $c): SystemInitializationService => new SystemInitializationService(
            $c->get(InitializationTransactionInterface::class), $c->get(UserStoreInterface::class), $c->get(EmployeeService::class),
            $c->get(UserService::class), $c->get(PasswordService::class), $c->get(AuditService::class),
            $c->get(NotificationService::class), $c->get(ClockInterface::class), $c->get('config.notification'),$c->get(CorporateContextService::class),
            $c->get(CategoryAccessStoreInterface::class),(array)$c->get('config.corporate-access')['categories'],$c->get(PublicIdGenerator::class)
        ));
        $container->set(SystemInitializationInterface::class, static fn (Container $c): SystemInitializationInterface => $c->get(SystemInitializationService::class));
        return $container;
    }
}
