<?php
declare(strict_types=1);
namespace NpmGateway\Container;
use DateTimeZone;
use mysqli;
use NpmGateway\Contracts\AuditStoreInterface;
use NpmGateway\Contracts\ClockInterface;
use NpmGateway\Contracts\CredentialNotifierInterface;
use NpmGateway\Contracts\EmployeeStoreInterface;
use NpmGateway\Contracts\PasswordGeneratorInterface;
use NpmGateway\Contracts\UserStoreInterface;
use NpmGateway\Contracts\SystemInitializationInterface;
use NpmGateway\Contracts\InitializationTransactionInterface;
use NpmGateway\Contracts\SessionTokenGeneratorInterface;
use NpmGateway\Contracts\AuthenticationServiceInterface;
use NpmGateway\Contracts\SessionServiceInterface;
use NpmGateway\Configuration\AuthenticationConfig;
use NpmGateway\Database\DatabaseProfiles;
use NpmGateway\Database\MySqlConnectionFactory;
use NpmGateway\Database\MySqlInitializationTransaction;
use NpmGateway\Repositories\SessionRepository;
use NpmGateway\Repositories\LoginAttemptRepository;
use NpmGateway\Security\AuthenticationHasher;
use NpmGateway\Services\SessionService;
use NpmGateway\Services\LoginThrottleService;
use NpmGateway\Services\AuthenticationService;
use NpmGateway\Support\SecureSessionTokenGenerator;
use NpmGateway\Notifications\DisabledCredentialNotifier;
use NpmGateway\Repositories\AuditRepository;
use NpmGateway\Repositories\EmployeeRepository;
use NpmGateway\Repositories\UserRepository;
use NpmGateway\Repositories\DashboardSummaryRepository;
use NpmGateway\Services\DashboardSummaryService;
use NpmGateway\Services\DashboardHomeService;
use NpmGateway\Services\UniversalToolProvider;
use NpmGateway\Contracts\UniversalToolProviderInterface;
use NpmGateway\Contracts\CorporateToolsProviderInterface;
use NpmGateway\Contracts\EmployeeDirectoryStoreInterface;
use NpmGateway\Services\EmployeeDirectoryService;
use NpmGateway\Services\EmployeeDirectoryCriteriaFactory;
use NpmGateway\Services\CorporateToolsProvider;
use NpmGateway\Services\CorporateAccessService;
use NpmGateway\Contracts\DashboardSummaryStoreInterface;
use NpmGateway\Services\AuditService;
use NpmGateway\Services\EmployeeService;
use NpmGateway\Services\NotificationService;
use NpmGateway\Services\PasswordService;
use NpmGateway\Services\SystemInitializationService;
use NpmGateway\Services\UserService;
use NpmGateway\Support\PublicIdGenerator;
use NpmGateway\Support\SecurePasswordGenerator;
use NpmGateway\Support\SystemClock;
use NpmGateway\Contracts\PropertyDirectoryStoreInterface;
use NpmGateway\Contracts\PropertyStoreInterface;
use NpmGateway\Contracts\PropertyTransactionInterface;
use NpmGateway\Database\MySqlPropertyTransaction;
use NpmGateway\Repositories\PropertyRepository;
use NpmGateway\Services\PropertyAdministrationService;
use NpmGateway\Services\PropertyDirectoryCriteriaFactory;
use NpmGateway\Services\PropertyQueryService;
use NpmGateway\Services\PropertyValidator;
use NpmGateway\Support\PhoneFormatter;
use NpmGateway\Support\PropertyAddressFormatter;
use NpmGateway\Contracts\CorporateContextStoreInterface;
use NpmGateway\Services\CorporateContextService;
use NpmGateway\Services\CorporateContextSeeder;
use NpmGateway\Contracts\HrEmployeeStoreInterface;
use NpmGateway\Contracts\HrEmployeeNotifierInterface;
use NpmGateway\Notifications\DisabledHrEmployeeNotifier;
use NpmGateway\Services\HrEmployeeValidator;
use NpmGateway\Services\HrEmployeeNotificationService;
use NpmGateway\Services\HrEmployeeCreationService;
use NpmGateway\Services\HrEmployeeNotificationConfig;
use NpmGateway\Notifications\SmtpEmployeeNotificationSender;
final class ServiceProvider
{
    /** @param array<string, mixed> $application */
    public static function build(array $application): Container
    {
        $container = new Container();
        $root = (string) $application['root'];
        $app = (array) $application['config']['app'];
        $notice = require $root . '/config/credential-notification.php';
        $hrNotice = require $root . '/config/hr-employee-notification.php';
        $corporateAccess = require $root . '/config/corporate-access.php';
        /** @var AuthenticationConfig $authentication */
        $authentication = require $root . '/config/authentication.php';
        $container->instance('config.notification', $notice);
        $container->instance('config.hr-employee-notification',$hrNotice);
        $container->instance('config.corporate-access', $corporateAccess);
        $container->instance(AuthenticationConfig::class, $authentication);
        $container->set(mysqli::class, static fn (): mysqli => MySqlConnectionFactory::connect(DatabaseProfiles::load('application', $root)));
        $container->set(PasswordGeneratorInterface::class, static fn (): PasswordGeneratorInterface => new SecurePasswordGenerator());
        $container->set(ClockInterface::class, static fn (): ClockInterface => new SystemClock(new DateTimeZone((string) ($app['timezone'] ?? 'UTC'))));
        $container->set(CredentialNotifierInterface::class, static fn (): CredentialNotifierInterface => new DisabledCredentialNotifier());
        $container->set(HrEmployeeNotifierInterface::class,static function(Container $c):HrEmployeeNotifierInterface{try{return new SmtpEmployeeNotificationSender(HrEmployeeNotificationConfig::fromArray($c->get('config.hr-employee-notification')));}catch(\Throwable){return new DisabledHrEmployeeNotifier();}});
        $container->set(PublicIdGenerator::class, static fn (): PublicIdGenerator => new PublicIdGenerator());
        $container->set(SessionTokenGeneratorInterface::class, static fn (): SessionTokenGeneratorInterface => new SecureSessionTokenGenerator());
        $container->set(AuthenticationHasher::class, static fn(Container $c):AuthenticationHasher=>new AuthenticationHasher($c->get(AuthenticationConfig::class)));
        $container->set(EmployeeRepository::class,static fn(Container $c):EmployeeRepository=>new EmployeeRepository($c->get(mysqli::class)));
        $container->set(EmployeeStoreInterface::class, static fn (Container $c): EmployeeStoreInterface => $c->get(EmployeeRepository::class));
        $container->set(HrEmployeeStoreInterface::class,static fn(Container $c):HrEmployeeStoreInterface=>$c->get(EmployeeRepository::class));
        $container->set(EmployeeDirectoryStoreInterface::class,static fn(Container $c):EmployeeDirectoryStoreInterface=>$c->get(EmployeeRepository::class));
        $container->set(EmployeeDirectoryCriteriaFactory::class,static fn():EmployeeDirectoryCriteriaFactory=>new EmployeeDirectoryCriteriaFactory());
        $container->set(EmployeeDirectoryService::class,static fn(Container $c):EmployeeDirectoryService=>new EmployeeDirectoryService($c->get(EmployeeDirectoryStoreInterface::class)));
        $container->set(UserStoreInterface::class, static fn (Container $c): UserStoreInterface => new UserRepository($c->get(mysqli::class)));
        $container->set(AuditStoreInterface::class, static fn (Container $c): AuditStoreInterface => new AuditRepository($c->get(mysqli::class)));
        $container->set(SessionRepository::class,static fn(Container $c):SessionRepository=>new SessionRepository($c->get(mysqli::class)));
        $container->set(LoginAttemptRepository::class,static fn(Container $c):LoginAttemptRepository=>new LoginAttemptRepository($c->get(mysqli::class)));
        $container->set(DashboardSummaryRepository::class,static fn(Container $c):DashboardSummaryRepository=>new DashboardSummaryRepository($c->get(mysqli::class)));
        $container->set(DashboardSummaryStoreInterface::class,static fn(Container $c):DashboardSummaryStoreInterface=>$c->get(DashboardSummaryRepository::class));
        $container->set(DashboardSummaryService::class,static fn(Container $c):DashboardSummaryService=>new DashboardSummaryService($c->get(DashboardSummaryStoreInterface::class)));
        $container->set(UniversalToolProviderInterface::class,static fn():UniversalToolProviderInterface=>new UniversalToolProvider());
        $container->set(CorporateToolsProviderInterface::class,static fn():CorporateToolsProviderInterface=>new CorporateToolsProvider());
        $container->set(CorporateAccessService::class,static fn(Container $c):CorporateAccessService=>new CorporateAccessService($c->get('config.corporate-access')));
        $container->set(PropertyRepository::class,static fn(Container $c):PropertyRepository=>new PropertyRepository($c->get(mysqli::class)));
        $container->set(PropertyStoreInterface::class,static fn(Container $c):PropertyStoreInterface=>$c->get(PropertyRepository::class));
        $container->set(PropertyDirectoryStoreInterface::class,static fn(Container $c):PropertyDirectoryStoreInterface=>$c->get(PropertyRepository::class));
        $container->set(CorporateContextStoreInterface::class,static fn(Container $c):CorporateContextStoreInterface=>$c->get(PropertyRepository::class));
        $container->set(PropertyTransactionInterface::class,static fn(Container $c):PropertyTransactionInterface=>new MySqlPropertyTransaction($c->get(mysqli::class)));
        $container->set(PhoneFormatter::class,static fn():PhoneFormatter=>new PhoneFormatter());
        $container->set(PropertyAddressFormatter::class,static fn():PropertyAddressFormatter=>new PropertyAddressFormatter());
        $container->set(PropertyDirectoryCriteriaFactory::class,static fn():PropertyDirectoryCriteriaFactory=>new PropertyDirectoryCriteriaFactory());
        $container->set(PropertyQueryService::class,static fn(Container $c):PropertyQueryService=>new PropertyQueryService($c->get(PropertyDirectoryStoreInterface::class),$c->get(PropertyAddressFormatter::class),$c->get(PhoneFormatter::class)));
        $container->set(PropertyValidator::class,static fn(Container $c):PropertyValidator=>new PropertyValidator($c->get(PropertyStoreInterface::class),$c->get(PhoneFormatter::class)));
        $container->set(CorporateContextService::class,static fn(Container $c):CorporateContextService=>new CorporateContextService($c->get(CorporateContextStoreInterface::class),$c->get(PublicIdGenerator::class),$c->get(AuditService::class),$c->get(ClockInterface::class)));
        $container->set(CorporateContextSeeder::class,static fn(Container $c):CorporateContextSeeder=>new CorporateContextSeeder($c->get(PropertyTransactionInterface::class),$c->get(CorporateContextService::class)));
        $container->set(DashboardHomeService::class,static fn(Container $c):DashboardHomeService=>new DashboardHomeService($c->get(DashboardSummaryService::class),$c->get(UniversalToolProviderInterface::class),$c->get(CorporateToolsProviderInterface::class),$c->get(CorporateAccessService::class)));
        $container->set(InitializationTransactionInterface::class, static fn (Container $c): InitializationTransactionInterface => new MySqlInitializationTransaction($c->get(mysqli::class)));
        $container->set(PasswordService::class, static fn (Container $c): PasswordService => new PasswordService($c->get(PasswordGeneratorInterface::class)));
        $container->set(HrEmployeeValidator::class,static fn(Container $c):HrEmployeeValidator=>new HrEmployeeValidator($c->get(HrEmployeeStoreInterface::class),$c->get(UserStoreInterface::class),$c->get(PhoneFormatter::class)));
        $container->set(HrEmployeeNotificationService::class,static fn(Container $c):HrEmployeeNotificationService=>new HrEmployeeNotificationService($c->get(HrEmployeeNotifierInterface::class),$c->get('config.hr-employee-notification')));
        $container->set(HrEmployeeCreationService::class,static fn(Container $c):HrEmployeeCreationService=>new HrEmployeeCreationService($c->get(HrEmployeeValidator::class),$c->get(HrEmployeeStoreInterface::class),$c->get(InitializationTransactionInterface::class),$c->get(UserService::class),$c->get(PasswordService::class),$c->get(AuditService::class),$c->get(HrEmployeeNotificationService::class),$c->get(PublicIdGenerator::class),$c->get(ClockInterface::class),$c->get('config.hr-employee-notification')));
        $container->set(EmployeeService::class, static fn (Container $c): EmployeeService => new EmployeeService($c->get(EmployeeStoreInterface::class), $c->get(PublicIdGenerator::class)));
        $container->set(UserService::class, static fn (Container $c): UserService => new UserService($c->get(UserStoreInterface::class), $c->get(PublicIdGenerator::class)));
        $container->set(AuditService::class, static fn (Container $c): AuditService => new AuditService($c->get(AuditStoreInterface::class), $c->get(PublicIdGenerator::class)));
        $container->set(PropertyAdministrationService::class,static fn(Container $c):PropertyAdministrationService=>new PropertyAdministrationService($c->get(PropertyValidator::class),$c->get(PropertyStoreInterface::class),$c->get(PropertyTransactionInterface::class),$c->get(PublicIdGenerator::class),$c->get(AuditService::class),$c->get(ClockInterface::class)));
        $container->set(NotificationService::class, static fn (Container $c): NotificationService => new NotificationService($c->get(CredentialNotifierInterface::class), $c->get('config.notification')));
        $container->set(SessionService::class,static fn(Container $c):SessionService=>new SessionService($c->get(SessionRepository::class),$c->get(UserStoreInterface::class),$c->get(SessionTokenGeneratorInterface::class),$c->get(AuthenticationHasher::class),$c->get(PublicIdGenerator::class),$c->get(AuthenticationConfig::class),$c->get(AuditService::class)));
        $container->set(LoginThrottleService::class,static fn(Container $c):LoginThrottleService=>new LoginThrottleService($c->get(LoginAttemptRepository::class),$c->get(AuthenticationConfig::class)));
        $container->set(AuthenticationService::class,static fn(Container $c):AuthenticationService=>new AuthenticationService($c->get(InitializationTransactionInterface::class),$c->get(UserStoreInterface::class),$c->get(LoginAttemptRepository::class),$c->get(LoginThrottleService::class),$c->get(SessionService::class),$c->get(AuditService::class),$c->get(AuthenticationHasher::class),$c->get(PublicIdGenerator::class),$c->get(AuthenticationConfig::class)));
        $container->set(AuthenticationServiceInterface::class,static fn(Container $c):AuthenticationServiceInterface=>$c->get(AuthenticationService::class));
        $container->set(SessionServiceInterface::class,static fn(Container $c):SessionServiceInterface=>$c->get(SessionService::class));
        $container->set(SystemInitializationService::class, static fn (Container $c): SystemInitializationService => new SystemInitializationService(
            $c->get(InitializationTransactionInterface::class), $c->get(UserStoreInterface::class), $c->get(EmployeeService::class),
            $c->get(UserService::class), $c->get(PasswordService::class), $c->get(AuditService::class),
            $c->get(NotificationService::class), $c->get(ClockInterface::class), $c->get('config.notification'),$c->get(CorporateContextService::class)
        ));
        $container->set(SystemInitializationInterface::class, static fn (Container $c): SystemInitializationInterface => $c->get(SystemInitializationService::class));
        return $container;
    }
}
