<?php
declare(strict_types=1);
use NpmGateway\Configuration\AuthenticationConfig;
use NpmGateway\Container\ServiceProvider;
use NpmGateway\Contracts\ClockInterface;
use NpmGateway\Http\Controllers\AuthenticationController;
use NpmGateway\Http\Controllers\DashboardController;
use NpmGateway\Http\Middleware\RequireAuthenticationMiddleware;
use NpmGateway\Http\Request;
use NpmGateway\Http\SessionCookie;
use NpmGateway\Http\WebKernel;
use NpmGateway\Security\CsrfService;
use NpmGateway\Services\AuthenticationService;
use NpmGateway\Services\SessionService;
use NpmGateway\Services\DashboardHomeService;
use NpmGateway\Http\Controllers\EmployeeWorkspaceController;
use NpmGateway\Services\EmployeeDirectoryCriteriaFactory;
use NpmGateway\Services\EmployeeDirectoryService;
use NpmGateway\Services\CorporateAccessService;
use NpmGateway\Contracts\CorporateToolsProviderInterface;
use NpmGateway\Http\Controllers\AdminController;
use NpmGateway\Services\CategoryAccessAdministrationService;
use NpmGateway\Services\CategoryAccessPayloadParser;
use NpmGateway\Http\Controllers\PropertyWorkspaceController;
use NpmGateway\Http\Controllers\HumanResourcesController;
use NpmGateway\Services\PropertyAdministrationService;
use NpmGateway\Services\PropertyDirectoryCriteriaFactory;
use NpmGateway\Services\PropertyQueryService;
use NpmGateway\Support\FlashSession;
use NpmGateway\Http\Controllers\HrEmployeeController;
use NpmGateway\Services\HrEmployeeCreationService;
use NpmGateway\Services\EmployeeCreationSubmissionStore;
use NpmGateway\Http\Controllers\NotificationController;
use NpmGateway\Services\NotificationQueryService;
use NpmGateway\Services\NotificationAcknowledgmentService;
use NpmGateway\Services\NotificationPresentationService;
use NpmGateway\Http\Controllers\CompanyNoticeController;
use NpmGateway\Services\CompanyNoticeValidator;
use NpmGateway\Services\CompanyNoticeReviewStore;
use NpmGateway\Services\CompanyNoticePublicationService;
use NpmGateway\Services\CompanyNoticeQueryService;
use NpmGateway\Support\PublicIdGenerator;
use NpmGateway\Services\CompanyNoticeComposeStore;
use NpmGateway\Services\CompanyNoticeAssetService;
use NpmGateway\Services\GatewayStorageService;
use NpmGateway\Services\LoginReturnStore;
use NpmGateway\Services\PublishedStorageService;
use NpmGateway\Services\CompanyNoticeDraftDiscardService;
use NpmGateway\Http\Controllers\StorageController;
use NpmGateway\Http\Controllers\CorporateWorkspaceController;
use NpmGateway\Http\Controllers\EmployeeEmergencyContactController;
use NpmGateway\Http\Controllers\HrEmergencyContactController;
use NpmGateway\Http\Controllers\ManagerMaintenanceEmergencyContactController;
use NpmGateway\Repositories\EmployeeEmergencyContactRepository;
use NpmGateway\Services\EciReminderService;
use NpmGateway\Services\EmployeeEmergencyContactService;
use NpmGateway\Services\ManagerMaintenanceEciAccessService;
use NpmGateway\Support\PhoneFormatter;
use NpmGateway\Http\Controllers\CommunityActionsController;
use NpmGateway\Services\PropertyAccessService;
use NpmGateway\Services\PropertyAccessPayloadParser;
use NpmGateway\Services\CommunityActionContextResolver;
use NpmGateway\Services\CommunityActionProvider;
use NpmGateway\Http\Controllers\ApplicationReviewController;
use NpmGateway\Http\Controllers\CorporateApplicationReviewController;
use NpmGateway\Repositories\ApplicationReviewRepository;
use NpmGateway\Services\ApplicationReviewService;
use NpmGateway\Services\ApplicationReviewQueryService;
use NpmGateway\Http\Controllers\CreditCardPurchaseController;
use NpmGateway\Http\Controllers\CorporateCreditCardPurchaseController;
use NpmGateway\Services\CreditCardPurchaseService;
use NpmGateway\Http\Controllers\RmCorrectionController;
use NpmGateway\Http\Controllers\CorporateRmCorrectionController;
use NpmGateway\Services\RmCorrectionQueryService;
use NpmGateway\Services\RmCorrectionService;
use NpmGateway\Http\Controllers\OperationsOverviewController;
use NpmGateway\Services\OperationsRmCorrectionOverviewService;

$application=require dirname(__DIR__).'/bootstrap/app.php';$root=$application['root'];$environment=(string)$application['config']['app']['environment'];
$path=parse_url((string)($_SERVER['REQUEST_URI']??'/'),PHP_URL_PATH);$path=is_string($path)?rtrim($path,'/'):'/';$path=$path===''?'/':$path;
if($path==='/component-showcase'&&in_array($environment,['local','development'],true)){
 $responseStatus=200;$pageTitle='Component Showcase — Development Only';$navbarItems=[];$navbarUserLabel='User menu';ob_start();require $root.'/resources/views/pages/component-showcase.php';$contentHtml=(string)ob_get_clean();require $root.'/resources/views/layouts/app.php';return;
}
if($path==='/component-showcase'){
 $responseStatus=404;http_response_code(404);require $root.'/resources/views/errors/404.php';return;
}
$container=ServiceProvider::build($application);$authConfig=$container->get(AuthenticationConfig::class);
$nativeSession=require $root.'/config/session.php';$nativeSessionName=(string)$nativeSession['name'];
if(!preg_match('/^[A-Za-z][A-Za-z0-9_-]{1,63}$/',$nativeSessionName)||hash_equals($authConfig->cookieName,$nativeSessionName)){throw new RuntimeException('Native PHP and Gateway authentication cookie names must be valid and distinct.');}
if(session_status()!==PHP_SESSION_ACTIVE){ini_set('session.use_strict_mode','1');ini_set('session.use_only_cookies','1');session_name($nativeSessionName);session_set_cookie_params(['lifetime'=>0,'path'=>'/','secure'=>$authConfig->secure,'httponly'=>true,'samesite'=>$authConfig->sameSite]);session_start();}
$csrf=new CsrfService($_SESSION);$cookie=new SessionCookie($authConfig);$views=$root.'/resources/views';
$loginReturns=new LoginReturnStore($_SESSION);$authentication=new AuthenticationController($container->get(AuthenticationService::class),$container->get(SessionService::class),$cookie,$csrf,$views,$loginReturns);
$employees=new EmployeeWorkspaceController($container->get(EmployeeDirectoryCriteriaFactory::class),$container->get(EmployeeDirectoryService::class),$container->get(CorporateAccessService::class),$container->get(CorporateToolsProviderInterface::class),$csrf,$views);
$properties=new PropertyWorkspaceController($container->get(PropertyDirectoryCriteriaFactory::class),$container->get(PropertyQueryService::class),$container->get(PropertyAdministrationService::class),$container->get(CorporateAccessService::class),$container->get(CorporateToolsProviderInterface::class),$csrf,new FlashSession($_SESSION),$views);
$hr=new HumanResourcesController($container->get(CorporateAccessService::class),$container->get(CorporateToolsProviderInterface::class),$csrf,$views);
$hrEmployees=new HrEmployeeController($container->get(EmployeeDirectoryCriteriaFactory::class),$container->get(EmployeeDirectoryService::class),$container->get(HrEmployeeCreationService::class),new EmployeeCreationSubmissionStore($_SESSION,$container->get(PublicIdGenerator::class)),$container->get(CorporateAccessService::class),$container->get(CorporateToolsProviderInterface::class),$csrf,new FlashSession($_SESSION),$views);
$admin=new AdminController($container->get(CorporateAccessService::class),$container->get(CategoryAccessAdministrationService::class),$container->get(CategoryAccessPayloadParser::class),$container->get(CorporateToolsProviderInterface::class),$csrf,new FlashSession($_SESSION),$views,$container->get(PropertyAccessService::class),$container->get(PropertyAccessPayloadParser::class));
$notificationController=new NotificationController($container->get(NotificationQueryService::class),$container->get(NotificationAcknowledgmentService::class),$container->get(NotificationPresentationService::class),$container->get(CorporateAccessService::class),$container->get(CorporateToolsProviderInterface::class),$csrf,new FlashSession($_SESSION),$views);
$companyNoticeController=new CompanyNoticeController($container->get(CorporateAccessService::class),$container->get(CompanyNoticeQueryService::class),$container->get(CompanyNoticeValidator::class),$container->get(CompanyNoticeReviewStore::class),$container->get(CompanyNoticePublicationService::class),$container->get(CorporateToolsProviderInterface::class),$csrf,new FlashSession($_SESSION),$views,$container->get(CompanyNoticeComposeStore::class),$container->get(CompanyNoticeAssetService::class),$container->get(GatewayStorageService::class),$container->get(ClockInterface::class),$container->get(CompanyNoticeDraftDiscardService::class));
$corporate=new CorporateWorkspaceController($container->get(CorporateAccessService::class),$container->get(CorporateToolsProviderInterface::class),$csrf,$views);
$emergencyContact=new EmployeeEmergencyContactController($container->get(EmployeeEmergencyContactService::class),$container->get(CorporateToolsProviderInterface::class),$csrf,new FlashSession($_SESSION),$container->get(PhoneFormatter::class),$views);
$hrEmergencyContacts=new HrEmergencyContactController($container->get(CorporateAccessService::class),$container->get(EmployeeEmergencyContactRepository::class),$container->get(EmployeeEmergencyContactService::class),$container->get(EciReminderService::class),$container->get(CorporateToolsProviderInterface::class),$csrf,new FlashSession($_SESSION),$views);
$managerMaintenanceEmergencyContact=new ManagerMaintenanceEmergencyContactController($container->get(ManagerMaintenanceEciAccessService::class),$container->get(EmployeeEmergencyContactService::class),$container->get(CorporateToolsProviderInterface::class),$csrf,new FlashSession($_SESSION),$container->get(PhoneFormatter::class),$views);
$communityActions=new CommunityActionsController($container->get(PropertyAccessService::class),$container->get(CommunityActionContextResolver::class),$container->get(CommunityActionProvider::class),$container->get(CorporateToolsProviderInterface::class),$csrf,$views);
$applicationReviews=new ApplicationReviewController($container->get(CommunityActionContextResolver::class),$container->get(ApplicationReviewQueryService::class),$container->get(ApplicationReviewService::class),$container->get(CorporateToolsProviderInterface::class),$csrf,new FlashSession($_SESSION),$views);
$corporateApplicationReviews=new CorporateApplicationReviewController($container->get(CorporateAccessService::class),$container->get(ApplicationReviewQueryService::class),$container->get(ApplicationReviewService::class),$container->get(CorporateToolsProviderInterface::class),$csrf,new FlashSession($_SESSION),$views);
$creditCardPurchases=new CreditCardPurchaseController($container->get(CommunityActionContextResolver::class),$container->get(CreditCardPurchaseService::class),$container->get(GatewayStorageService::class),$container->get(CorporateToolsProviderInterface::class),$csrf,new FlashSession($_SESSION),$views);
$corporateCreditCardPurchases=new CorporateCreditCardPurchaseController($container->get(CorporateAccessService::class),$container->get(CreditCardPurchaseService::class),$container->get(GatewayStorageService::class),$container->get(CorporateToolsProviderInterface::class),$csrf,new FlashSession($_SESSION),$views);
$rmCorrections=new RmCorrectionController($container->get(CommunityActionContextResolver::class),$container->get(RmCorrectionQueryService::class),$container->get(RmCorrectionService::class),$container->get(CorporateToolsProviderInterface::class),$csrf,new FlashSession($_SESSION),$views);
$corporateRmCorrections=new CorporateRmCorrectionController($container->get(CorporateAccessService::class),$container->get(RmCorrectionQueryService::class),$container->get(RmCorrectionService::class),$container->get(CorporateToolsProviderInterface::class),$csrf,new FlashSession($_SESSION),$views);
$operationsOverview=new OperationsOverviewController($container->get(CorporateAccessService::class),$container->get(OperationsRmCorrectionOverviewService::class),$container->get(ClockInterface::class),$container->get(CorporateToolsProviderInterface::class),$csrf,$views);
$kernel=new WebKernel($authentication,new DashboardController($csrf,$container->get(DashboardHomeService::class),$views,$container->get(NotificationQueryService::class)),new RequireAuthenticationMiddleware($container->get(SessionService::class),$cookie,$loginReturns),$employees,$properties,$hr,$hrEmployees,$admin,$notificationController,$companyNoticeController,new StorageController($container->get(PublishedStorageService::class)),$corporate,$emergencyContact,$hrEmergencyContacts,$managerMaintenanceEmergencyContact,$communityActions,$applicationReviews,$corporateApplicationReviews,$creditCardPurchases,$corporateCreditCardPurchases,$rmCorrections,$corporateRmCorrections,$operationsOverview);
$request=new Request(strtoupper((string)($_SERVER['REQUEST_METHOD']??'GET')),$path,$_POST,array_map('strval',$_COOKIE),array_map('strval',$_SERVER),array_map('strval',$_GET),$_FILES);
$response=$kernel->handle($request,$container->get(ClockInterface::class)->now());http_response_code($response->status);
foreach($response->headers as $name=>$value)header($name.': '.$value);
foreach($response->cookies as $definition){$name=$definition['name'];$value=$definition['value'];unset($definition['name'],$definition['value']);setcookie($name,$value,$definition);}
if(!isset($response->headers['Content-Type']))header('Content-Type: text/html; charset=UTF-8');if(is_resource($response->stream)){stream_copy_to_stream($response->stream,fopen('php://output','wb'));fclose($response->stream);}else echo $response->body;
$container->get(mysqli::class)->close();
