<?php
declare(strict_types=1);
use NpmGateway\Database\{DatabaseProfiles,MySqlConnectionFactory,MySqlInitializationTransaction};
use NpmGateway\Repositories\{ApartmentsRepository,AuditRepository};
use NpmGateway\Services\{ApartmentsService,ApartmentsWorkbookParser,AuditService};
use NpmGateway\Support\{PhoneFormatter,PublicIdGenerator,SystemClock};
use NpmGateway\ValueObjects\AuthenticatedUser;
use PhpOffice\PhpSpreadsheet\IOFactory;
$app=require dirname(__DIR__,2).'/bootstrap/app.php';$path=(string)($argv[1]??'');if(!is_file($path)){fwrite(STDERR,"Usage: php tests/Integration/apartments_disposable.php <real-workbook.xlsx>\n");exit(2);}$config=DatabaseProfiles::load('migration',$app['root']);$db=MySqlConnectionFactory::connect($config);if($db->query('SELECT DATABASE()')->fetch_row()[0]!=='npmgateway_test'){fwrite(STDERR,"Certification requires npmgateway_test.\n");exit(2);}$hash=hash_file('sha256',$path);$employee=$user=0;$ids=new PublicIdGenerator();
$clearImport=static function()use($db,$hash):void{$imports=$db->query("SELECT id FROM apartments_imports WHERE file_sha256='".$db->real_escape_string($hash)."'")->fetch_all(MYSQLI_ASSOC);foreach($imports as$row){$id=(int)$row['id'];$db->query("DELETE FROM apartments_email_leads WHERE import_id={$id}");$db->query("DELETE FROM apartments_calls WHERE import_id={$id}");}$db->query("DELETE FROM apartments_imports WHERE file_sha256='".$db->real_escape_string($hash)."'");};
$cleanup=static function()use($db,&$employee,&$user,$clearImport):void{$clearImport();$found=$db->query("SELECT id,employee_id FROM users WHERE username='apartmentscert026'")->fetch_assoc();if($found){$user=(int)$found['id'];$employee=(int)$found['employee_id'];$db->query("DELETE FROM audit_logs WHERE user_id={$user}");$db->query("DELETE FROM users WHERE id={$user}");$db->query("DELETE FROM employees WHERE id={$employee}");}$db->query('DROP TRIGGER IF EXISTS apartments_cert_import_fail');$db->query('DROP TRIGGER IF EXISTS apartments_cert_call_fail');$db->query('DROP TRIGGER IF EXISTS apartments_cert_email_fail');};
try{$cleanup();$now='2026-08-15 12:00:00';$employeePublic=$ids->generate();$s=$db->prepare("INSERT INTO employees(public_id,employee_number,first_name,last_name,start_date,job_title,employment_status,employee_class,created_at,updated_at) VALUES(?,'NPM991026','Apartments','Certification','2026-01-01','Tester','active','corporate',?,?)");$s->bind_param('sss',$employeePublic,$now,$now);$s->execute();$employee=(int)$db->insert_id;$s->close();$userPublic=$ids->generate();$password=password_hash('Disposable-Only-026!',PASSWORD_DEFAULT);$s=$db->prepare("INSERT INTO users(public_id,employee_id,username,password_hash,status,created_at,updated_at) VALUES(?,?,'apartmentscert026',?,'active',?,?)");$s->bind_param('sisss',$userPublic,$employee,$password,$now,$now);$s->execute();$user=(int)$db->insert_id;$s->close();$actor=new AuthenticatedUser($user,$employee,$userPublic,$employeePublic,'apartmentscert026','Apartments Certification');$service=new ApartmentsService(new ApartmentsWorkbookParser(new PhoneFormatter()),new ApartmentsRepository($db),new MySqlInitializationTransaction($db),$ids,new SystemClock(new DateTimeZone('UTC')),new AuditService(new AuditRepository($db),$ids));$upload=['name'=>basename($path),'tmp_name'=>$path,'size'=>filesize($path),'error'=>UPLOAD_ERR_OK];
 $started=microtime(true);$result=$service->import($upload,$actor);$elapsed=microtime(true)-$started;if($result!==['calls'=>73,'email_leads'=>27])throw new RuntimeException('Real workbook totals mismatch.');$import=(int)$db->query("SELECT id FROM apartments_imports WHERE file_sha256='".$db->real_escape_string($hash)."'")->fetch_row()[0];$calls=[];foreach($db->query("SELECT p.display_name,COUNT(*) count FROM apartments_calls c JOIN properties p ON p.id=c.property_id WHERE c.import_id={$import} GROUP BY p.id,p.display_name")->fetch_all(MYSQLI_ASSOC)as$row)$calls[$row['display_name']]=(int)$row['count'];$emails=[];foreach($db->query("SELECT p.display_name,COUNT(*) count FROM apartments_email_leads l JOIN properties p ON p.id=l.property_id WHERE l.import_id={$import} GROUP BY p.id,p.display_name")->fetch_all(MYSQLI_ASSOC)as$row)$emails[$row['display_name']]=(int)$row['count'];$expectedCalls=['Crumley Farms'=>1,'Flamingo Flats'=>4,'Highridge'=>24,'Maplewind'=>6,'Pearce Pointe'=>10,'Pine Hill'=>21,'Sizemore'=>5,'Wunderpark'=>2];$expectedEmails=['Boulder Trails'=>3,'Crumley Farms'=>1,'Flamingo Flats'=>1,'Highridge'=>1,'Maplewind'=>4,'Pearce Pointe'=>6,'Pine Hill'=>5,'Sizemore'=>1,'Wunderpark'=>5];ksort($calls);ksort($expectedCalls);ksort($emails);ksort($expectedEmails);if($calls!==$expectedCalls||$emails!==$expectedEmails)throw new RuntimeException('Real workbook property counts mismatch.');$range=$db->query("SELECT source_started_at,source_ended_at FROM apartments_imports WHERE id={$import}")->fetch_assoc();try{$service->import($upload,$actor);throw new RuntimeException('Duplicate workbook accepted.');}catch(NpmGateway\Exceptions\Domain\InvalidApartmentsWorkbookException$e){if($e->getMessage()!=='This Apartments.com file has already been imported.')throw$e;}$clearImport();
 foreach(['import'=>'apartments_imports','call'=>'apartments_calls','email'=>'apartments_email_leads']as$stage=>$table){$trigger='apartments_cert_'.$stage.'_fail';$db->query("CREATE TRIGGER {$trigger} BEFORE INSERT ON {$table} FOR EACH ROW SIGNAL SQLSTATE '45000' SET MESSAGE_TEXT='forced certification failure'");try{$service->import($upload,$actor);throw new RuntimeException("Forced {$stage} failure was accepted.");}catch(mysqli_sql_exception){}finally{$db->query("DROP TRIGGER {$trigger}");}foreach(['apartments_imports','apartments_calls','apartments_email_leads']as$check)if((int)$db->query("SELECT COUNT(*) FROM {$check} WHERE ".($check==='apartments_imports'?"file_sha256='".$db->real_escape_string($hash)."'":'import_id IN (SELECT id FROM apartments_imports WHERE file_sha256=\''.$db->real_escape_string($hash).'\')'))->fetch_row()[0]!==0)throw new RuntimeException("{$stage} failure left residue in {$check}.");}
 $unknown=tempnam(sys_get_temp_dir(),'apartments-unknown-');$book=IOFactory::load($path);$book->getSheetByName('Phone Calls - 73')->setCellValue('A2','Example Property');(new PhpOffice\PhpSpreadsheet\Writer\Xlsx($book))->save($unknown);$book->disconnectWorksheets();try{$service->import(['name'=>'unknown.xlsx','tmp_name'=>$unknown,'size'=>filesize($unknown),'error'=>UPLOAD_ERR_OK],$actor);throw new RuntimeException('Unknown property workbook accepted.');}catch(NpmGateway\Exceptions\Domain\InvalidApartmentsWorkbookException$e){if(!str_contains($e->getMessage(),'Example Property'))throw$e;}finally{unlink($unknown);}if((int)$db->query("SELECT COUNT(*) FROM apartments_imports")->fetch_row()[0]!==0)throw new RuntimeException('Unknown property caused mutation.');
 echo'calls=73'.PHP_EOL.'email_leads=27'.PHP_EOL.'source_started_at='.$range['source_started_at'].PHP_EOL.'source_ended_at='.$range['source_ended_at'].PHP_EOL.'parse_import_seconds='.number_format($elapsed,3,'.','').PHP_EOL.'peak_memory_bytes='.memory_get_peak_usage(true).PHP_EOL.'duplicate=rejected'.PHP_EOL.'unknown_property=rejected_before_mutation'.PHP_EOL.'forced_rollbacks=import,calls,email_leads'.PHP_EOL.'property_counts=passed'.PHP_EOL;
}finally{$cleanup();$residue=(int)$db->query("SELECT (SELECT COUNT(*) FROM apartments_imports WHERE file_sha256='".$db->real_escape_string($hash)."')+(SELECT COUNT(*) FROM users WHERE username='apartmentscert026')")->fetch_row()[0];echo'fixture_residue='.$residue.PHP_EOL.'temp_file_residue=0'.PHP_EOL;$db->close();}
