<?php
declare(strict_types=1);
use NpmGateway\Container\ServiceProvider;
use NpmGateway\Database\{DatabaseProfiles,MySqlConnectionFactory};
use NpmGateway\Services\CallLogService;
use NpmGateway\ValueObjects\AuthenticatedUser;
use PhpOffice\PhpSpreadsheet\{Spreadsheet,Writer\Xls};
$app=require dirname(__DIR__,2).'/bootstrap/app.php';foreach(['application','migration']as$profile)if(DatabaseProfiles::load($profile,$app['root'])['database']!=='npmgateway_test'){fwrite(STDERR,"Call Logs certification requires npmgateway_test.\n");exit(2);}
$db=MySqlConnectionFactory::connect(DatabaseProfiles::load('application',$app['root']));$prefix='call-cert-';$file=tempnam(sys_get_temp_dir(),'call-cert-');$started=microtime(true);$employee=$user=0;
$cleanup=static function()use($db,$prefix,&$employee,&$user):int{$ids=$db->query("SELECT id FROM call_log_imports WHERE original_filename LIKE '{$prefix}%'")->fetch_all(MYSQLI_ASSOC);foreach($ids as$row){$id=(int)$row['id'];$db->query("DELETE FROM call_logs WHERE import_id={$id}");}$db->query("DELETE FROM call_log_imports WHERE original_filename LIKE '{$prefix}%'");$existing=$db->query("SELECT id,employee_id FROM users WHERE username='callcert024'")->fetch_assoc();if($existing){$user=(int)$existing['id'];$employee=(int)$existing['employee_id'];}$existingEmployee=$db->query("SELECT id FROM employees WHERE employee_number='NPM991024'")->fetch_assoc();if($existingEmployee)$employee=(int)$existingEmployee['id'];if($user){$db->query("DELETE FROM audit_logs WHERE user_id={$user}");$db->query("DELETE FROM users WHERE id={$user}");}if($employee)$db->query("DELETE FROM employees WHERE id={$employee}");$user=$employee=0;return(int)$db->query("SELECT (SELECT COUNT(*) FROM call_logs l JOIN call_log_imports i ON i.id=l.import_id WHERE i.original_filename LIKE '{$prefix}%')+(SELECT COUNT(*) FROM call_log_imports WHERE original_filename LIKE '{$prefix}%')")->fetch_row()[0];};
try{$cleanup();$ids=new NpmGateway\Support\PublicIdGenerator();$now='2026-08-14 12:00:00';$employeePublic=$ids->generate();$s=$db->prepare("INSERT INTO employees(public_id,employee_number,first_name,last_name,start_date,employment_status,employee_class,created_at,updated_at) VALUES(?,'NPM991024','Call','Certification','2026-01-01','active','corporate',?,?)");$s->bind_param('sss',$employeePublic,$now,$now);$s->execute();$employee=(int)$db->insert_id;$s->close();$userPublic=$ids->generate();$hash=password_hash('Disposable-Only-Password-024!',PASSWORD_DEFAULT);$s=$db->prepare("INSERT INTO users(public_id,employee_id,username,password_hash,status,created_at,updated_at) VALUES(?,?,'callcert024',?,'active',?,?)");$s->bind_param('sisss',$userPublic,$employee,$hash,$now,$now);$s->execute();$user=(int)$db->insert_id;$s->close();
 $book=new Spreadsheet();$sheet=$book->getActiveSheet();$sheet->setTitle('Detailed Report');$sheet->fromArray(NpmGateway\Services\CallLogWorkbookParser::HEADERS,null,'A1');$tns=['+12292317090','+13342038030','+12297928075'];for($i=0;$i<2500;$i++){$row=$i+2;$start=(new DateTimeImmutable('2098-07-01 00:00:00.000'))->modify("+{$i} seconds");$duration=$i%180;$release=$start->modify("+{$duration} seconds");$sheet->setCellValueExplicit("A{$row}",'+12292317979',PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING);$sheet->setCellValueExplicit("B{$row}",$tns[$i%3],PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING);$sheet->setCellValue("C{$row}",$start->format('m/d/Y h:i:s.v A'));$sheet->setCellValue("D{$row}",$release->format('m/d/Y h:i:s.v A'));$sheet->setCellValue("E{$row}",$duration);}(new Xls($book))->save($file);$book->disconnectWorksheets();
 $container=ServiceProvider::build($app);$actor=new AuthenticatedUser($user,$employee,$userPublic,$employeePublic,'callcert024','Call Certification');$service=$container->get(CallLogService::class);$count=$service->import(['name'=>$prefix.'2500.xls','tmp_name'=>$file,'size'=>filesize($file),'error'=>UPLOAD_ERR_OK],$actor);if($count!==2500)throw new RuntimeException('Representative import count mismatch.');$page=$service->page([]);if($page['total']<2500||count($page['rows'])!==500||$page['per_page']!==500)throw new RuntimeException('Default pagination mismatch.');foreach([100,250,500]as$size)if(count($service->page(['per_page'=>$size])['rows'])!==$size)throw new RuntimeException("Pagination {$size} mismatch.");
 $destinationNames=array_column($page['destinations'],'display_name');$sortedNames=$destinationNames;sort($sortedNames,SORT_NATURAL|SORT_FLAG_CASE);if($destinationNames!==$sortedNames||count($destinationNames)!==9||in_array('Pine Manor',$destinationNames,true)||in_array('Sizemore',$destinationNames,true)||!in_array('Suburban',$destinationNames,true))throw new RuntimeException('Active destination dropdown mismatch.');$destinationIds=array_column($page['destinations'],'public_id','display_name');
 foreach([['from'=>'2098-07-01'],['from'=>'2098-07-01','to'=>'2098-07-01']]as$query)if($service->page($query)['total']!==2500)throw new RuntimeException('Inclusive date boundary mismatch.');if($service->page(['from'=>'2098-07-02'])['total']!==0)throw new RuntimeException('Post-range date filter mismatch.');$expected=['Pine Hill'=>834,'Highridge'=>833,'Suburban'=>833];foreach($expected as$name=>$total){$actual=$service->page(['from'=>'2098-07-01','to'=>'2098-07-01','property'=>$destinationIds[$name]])['total'];if($actual!==$total)throw new RuntimeException("{$name} property filter mismatch: expected {$total}, got {$actual}.");}$combined=$service->page(['from'=>'2098-07-01','to'=>'2098-07-01','property'=>$destinationIds['Pine Hill'],'per_page'=>'100','page'=>'2']);if($combined['total']!==834||count($combined['rows'])!==100||$combined['page']!==2)throw new RuntimeException('Combined filter pagination mismatch.');for($i=1,$n=count($combined['rows']);$i<$n;$i++)if(strcmp($combined['rows'][$i-1]['started_at'],$combined['rows'][$i]['started_at'])<0)throw new RuntimeException('Filtered result ordering mismatch.');if($service->page(['from'=>'2098-07-02','to'=>'2098-07-01'])['criteria']->errors===[]||$service->page(['property'=>str_repeat('Z',26)])['criteria']->errors===[])throw new RuntimeException('Invalid filter accepted.');
 $names=array_column($db->query("SELECT DISTINCT COALESCE(p.display_name,d.external_display_name) name FROM call_logs l JOIN call_log_imports i ON i.id=l.import_id JOIN call_log_destinations d ON d.id=l.destination_id LEFT JOIN properties p ON p.id=d.property_id WHERE i.original_filename LIKE '{$prefix}%'")->fetch_all(MYSQLI_ASSOC),'name');sort($names);if($names!==['Highridge','Pine Hill','Suburban'])throw new RuntimeException('Destination attribution mismatch.');try{$service->import(['name'=>$prefix.'duplicate.xls','tmp_name'=>$file,'size'=>filesize($file),'error'=>UPLOAD_ERR_OK],$actor);throw new RuntimeException('Duplicate workbook accepted.');}catch(NpmGateway\Exceptions\Domain\InvalidCallLogWorkbookException$e){if($e->getMessage()!=='This Call Log file has already been imported.')throw$e;}$unknown=tempnam(sys_get_temp_dir(),'call-unknown-');$unknownBook=new Spreadsheet();$unknownSheet=$unknownBook->getActiveSheet();$unknownSheet->setTitle('Detailed Report');$unknownSheet->fromArray(NpmGateway\Services\CallLogWorkbookParser::HEADERS,null,'A1');$unknownSheet->setCellValueExplicit('A2','+12292317979',PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING);$unknownSheet->setCellValueExplicit('B2','+12290000000',PhpOffice\PhpSpreadsheet\Cell\DataType::TYPE_STRING);$unknownSheet->fromArray(['20260701 12:00:00.000','20260701 12:00:01.000',1],null,'C2');(new Xls($unknownBook))->save($unknown);$unknownBook->disconnectWorksheets();$beforeImports=(int)$db->query("SELECT COUNT(*) FROM call_log_imports WHERE original_filename LIKE '{$prefix}%'")->fetch_row()[0];$beforeCalls=(int)$db->query("SELECT COUNT(*) FROM call_logs l JOIN call_log_imports i ON i.id=l.import_id WHERE i.original_filename LIKE '{$prefix}%'")->fetch_row()[0];try{$service->import(['name'=>$prefix.'unknown.xls','tmp_name'=>$unknown,'size'=>filesize($unknown),'error'=>UPLOAD_ERR_OK],$actor);throw new RuntimeException('Unknown Called TN accepted.');}catch(NpmGateway\Exceptions\Domain\InvalidCallLogWorkbookException$e){if(!str_contains($e->getMessage(),'+12290000000'))throw$e;}finally{unlink($unknown);}if((int)$db->query("SELECT COUNT(*) FROM call_log_imports WHERE original_filename LIKE '{$prefix}%' ")->fetch_row()[0]!==$beforeImports||(int)$db->query("SELECT COUNT(*) FROM call_logs l JOIN call_log_imports i ON i.id=l.import_id WHERE i.original_filename LIKE '{$prefix}%'")->fetch_row()[0]!==$beforeCalls)throw new RuntimeException('Unknown Called TN caused partial mutation.');$elapsed=microtime(true)-$started;echo "rows_imported=2500\ndefault_page_size=500\npage_sizes=100,250,500\nactive_destinations=9\ndate_filters=inclusive\nproperty_filters=Pine Hill:834,Highridge:833,Suburban:833\ncombined_filter_pagination=passed\ndestinations=Pine Hill,Highridge,Suburban\nexact_file_duplicate=rejected\nunknown_called_tn=rejected_before_mutation\nseconds=".number_format($elapsed,3,'.','')."\npeak_memory_bytes=".memory_get_peak_usage(true)."\n";$container->get(mysqli::class)->close();}
finally{if(is_file($file))unlink($file);$residue=$cleanup();echo"fixture_residue={$residue}\n";$db->close();}
if($residue!==0)exit(1);
