<?php
declare(strict_types=1);
use NpmGateway\Container\ServiceProvider;
use NpmGateway\Database\DatabaseProfiles;
use NpmGateway\Database\MySqlConnectionFactory;
use NpmGateway\Exceptions\Domain\CorporateContextConflictException;
use NpmGateway\Services\CorporateContextSeeder;
use NpmGateway\Services\PropertyQueryService;
use NpmGateway\ValueObjects\PropertyDirectoryCriteria;
use PHPUnit\Framework\TestCase;
final class CorporateContextIntegrationTest extends TestCase
{
    public function testCorporateBackfillIsExactVisibleIdempotentAndConflictSafe():void
    {
        if(getenv('RUN_DB_INTEGRATION_TESTS')!=='true')self::markTestSkipped('Set RUN_DB_INTEGRATION_TESTS=true with both profiles on npmgateway_test.');$application=require dirname(__DIR__,2).'/bootstrap/app.php';foreach(['application','migration'] as $profile)self::assertSame('npmgateway_test',DatabaseProfiles::load($profile,$application['root'])['database']);$db=MySqlConnectionFactory::connect(DatabaseProfiles::load('migration',$application['root']));$this->clean($db);$db->close();
        try{$container=ServiceProvider::build($application);$seeder=$container->get(CorporateContextSeeder::class);$first=$seeder->seed('integration-test');self::assertTrue($first->created);$second=$seeder->seed('integration-test');self::assertFalse($second->created);$db=$container->get(mysqli::class);$row=$db->query("SELECT prop_id,property_code,slug,display_name,status,address_line_1,city,state,postal_code,timezone,office_phone,manager_email,website_url,ivr_number,ivr_routing_email FROM properties WHERE prop_id=1")->fetch_assoc();self::assertIsArray($row);self::assertSame('1',(string)$row['prop_id']);self::assertSame('CO',$row['property_code']);self::assertSame('corporate',$row['slug']);self::assertSame('Corporate',$row['display_name']);self::assertSame('active',$row['status']);self::assertSame('5021 River Rd., Ste. C',$row['address_line_1']);self::assertSame('Columbus',$row['city']);self::assertSame('GA',$row['state']);self::assertSame('31904',$row['postal_code']);self::assertSame('America/New_York',$row['timezone']);self::assertSame('+17065874386',$row['office_phone']);self::assertSame('noc@npmparks.com',$row['manager_email']);self::assertSame('https://npmpropertiesinc.com',$row['website_url']);self::assertNull($row['ivr_number']);self::assertNull($row['ivr_routing_email']);self::assertSame(1,(int)$db->query("SELECT COUNT(*) FROM properties WHERE prop_id=1 OR property_code='CO' OR slug='corporate'")->fetch_row()[0]);self::assertSame(1,(int)$db->query("SELECT COUNT(*) FROM audit_logs WHERE event_type='system.corporate_context_created'")->fetch_row()[0]);$query=$container->get(PropertyQueryService::class);$universal=$query->search(new PropertyDirectoryCriteria());$hr=$query->search(new PropertyDirectoryCriteria());self::assertEquals($universal,$hr);$display=$universal->properties[0];self::assertSame('5021 River Rd., Ste. C, Columbus, GA 31904',$display->address);self::assertSame('(706) 587-4386',$display->phone);self::assertSame('—',$display->ivr);self::assertSame('Not assigned',$display->manager);$db->close();
        }finally{$cleanup=MySqlConnectionFactory::connect(DatabaseProfiles::load('migration',$application['root']));$this->clean($cleanup);$cleanup->close();}
    }
    public function testConflictingIdentifierFailsWithoutMutation():void
    {
        if(getenv('RUN_DB_INTEGRATION_TESTS')!=='true')self::markTestSkipped('Set RUN_DB_INTEGRATION_TESTS=true with both profiles on npmgateway_test.');$application=require dirname(__DIR__,2).'/bootstrap/app.php';self::assertSame('npmgateway_test',DatabaseProfiles::load('application',$application['root'])['database']);$db=MySqlConnectionFactory::connect(DatabaseProfiles::load('migration',$application['root']));$this->clean($db);$public=str_repeat('X',26);$db->query("INSERT INTO properties(public_id,prop_id,property_code,slug,display_name,status,manager_email,address_line_1,city,state,postal_code,timezone) VALUES ('{$public}',1,'XX','other','Conflict','active','conflict@example.test','1 Test Way','Test','GA','30000','America/New_York')");$db->close();try{$container=ServiceProvider::build($application);try{$container->get(CorporateContextSeeder::class)->seed('integration-conflict');self::fail('Expected conflict.');}catch(CorporateContextConflictException $e){self::assertStringContainsString('PropID 1',$e->getMessage());}$db=$container->get(mysqli::class);self::assertSame(1,(int)$db->query('SELECT COUNT(*) FROM properties')->fetch_row()[0]);self::assertSame(0,(int)$db->query("SELECT COUNT(*) FROM audit_logs WHERE event_type='system.corporate_context_created'")->fetch_row()[0]);$db->close();}finally{$cleanup=MySqlConnectionFactory::connect(DatabaseProfiles::load('migration',$application['root']));$this->clean($cleanup);$cleanup->close();}
    }
    private function clean(mysqli $db):void{foreach(['audit_logs','employee_property_assignments','properties','user_sessions','login_attempts','users','employees'] as $table)$db->query("DELETE FROM `{$table}`");}
}
