<?php
declare(strict_types=1);
use NpmGateway\Database\DatabaseProfiles;
use NpmGateway\Database\Migration\MigrationException;
use NpmGateway\Database\MySqlConnectionFactory;
use PHPUnit\Framework\TestCase;
final class GatewayStorageMigrationIntegrationTest extends TestCase
{
 private mysqli $db;
 protected function setUp():void{if(getenv('RUN_DB_INTEGRATION_TESTS')!=='true')self::markTestSkipped('Set RUN_DB_INTEGRATION_TESTS=true with both profiles on npmgateway_test.');$app=require dirname(__DIR__,2).'/bootstrap/app.php';foreach(['application','migration'] as $profile)self::assertSame('npmgateway_test',DatabaseProfiles::load($profile,$app['root'])['database']);$this->db=MySqlConnectionFactory::connect(DatabaseProfiles::load('migration',$app['root']));$this->cleanup();}
 protected function tearDown():void{if(isset($this->db)){$this->cleanup();$migration=require dirname(__DIR__,2).'/database/migrations/202608020010_gateway_storage.php';$migration->up($this->db);$actor=require dirname(__DIR__,2).'/database/migrations/202608020011_storage_system_cleanup_actor.php';$actor->up($this->db);$this->db->close();}}
 public function testObjectCanBeReusedAcrossNoticesButNotDuplicatedWithinOneNotice():void{$migration=require dirname(__DIR__,2).'/database/migrations/202608020010_gateway_storage.php';$migration->up($this->db);[$user,$first,$second]=$this->fixtures();$object=$this->object($user);$this->link($first,$object,$user,str_repeat('L',25).'1');$this->link($second,$object,$user,str_repeat('L',25).'2');self::assertSame(2,$this->rowCount('notification_storage_objects'));try{$this->link($first,$object,$user,str_repeat('L',25).'3');self::fail('Duplicate notice/object link accepted.');}catch(mysqli_sql_exception){self::addToAssertionCount(1);}self::assertSame(1,$this->rowCount('storage_objects'));try{$migration->down($this->db);self::fail('Rollback accepted historical storage metadata.');}catch(MigrationException){self::addToAssertionCount(1);}}
 public function testEmptyMigrationRollsBackAndReapplies():void{$migration=require dirname(__DIR__,2).'/database/migrations/202608020010_gateway_storage.php';$migration->up($this->db);$migration->down($this->db);self::assertSame(0,$this->countInformationSchema('storage_objects'));self::assertSame(0,$this->countInformationSchema('notification_storage_objects'));$migration->up($this->db);self::assertSame(1,$this->countInformationSchema('storage_objects'));self::assertSame(1,$this->countInformationSchema('notification_storage_objects'));}
 private function fixtures():array{$employee=str_repeat('E',26);$this->db->query("INSERT INTO employees(public_id,employee_number,employee_class,first_name,last_name,job_title,employment_status,start_date) VALUES ('{$employee}','NPM900001','corporate','Storage','Tester','Tester','active','2026-08-02')");$employeeId=$this->db->insert_id;$hash=password_hash('test',PASSWORD_DEFAULT);$userPublic=str_repeat('U',26);$s=$this->db->prepare("INSERT INTO users(public_id,employee_id,username,password_hash,status) VALUES (?,?,'storagetest',?,'active')");$s->bind_param('sis',$userPublic,$employeeId,$hash);$s->execute();$user=$this->db->insert_id;$s->close();$ids=[];foreach(['1','2'] as $suffix){$public=str_repeat('N',25).$suffix;$source=str_repeat('S',25).$suffix;$s=$this->db->prepare("INSERT INTO notifications(public_id,notification_type,title,summary,payload,requires_acknowledgment,priority,source_entity_type,source_entity_public_id,created_by_user_id,published_at,status,created_at) VALUES (?,'company_notice','Storage test','Storage test',JSON_OBJECT('message','test'),0,'normal','company_notice',?,?,NOW(),'published',NOW())");$s->bind_param('ssi',$public,$source,$user);$s->execute();$ids[]=$this->db->insert_id;$s->close();}return [$user,$ids[0],$ids[1]];}
 private function object(int $user):int{$public=str_repeat('O',26);$sha=str_repeat('a',64);$s=$this->db->prepare("INSERT INTO storage_objects(public_id,provider,provider_container,object_key,original_filename,display_filename,mime_type,byte_size,sha256_hex,lifecycle_state,uploaded_by_user_id,published_at) VALUES (?,'wasabi','test-bucket','tests/commit015/object','file.pdf','file.pdf','application/pdf',100,?,'published',?,NOW())");$s->bind_param('ssi',$public,$sha,$user);$s->execute();$id=$this->db->insert_id;$s->close();return $id;}
 private function link(int $notice,int $object,int $user,string $public):void{$s=$this->db->prepare("INSERT INTO notification_storage_objects(public_id,notification_id,storage_object_id,asset_role,linked_by_user_id) VALUES (?,?,?,'attachment',?)");$s->bind_param('siii',$public,$notice,$object,$user);$s->execute();$s->close();}
 private function rowCount(string $table):int{return (int)$this->db->query("SELECT COUNT(*) FROM {$table}")->fetch_row()[0];}
 private function countInformationSchema(string $table):int{$s=$this->db->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$s->bind_param('s',$table);$s->execute();$count=(int)$s->get_result()->fetch_row()[0];$s->close();return $count;}
 private function cleanup():void{foreach(['notification_storage_objects','storage_objects'] as $table)$this->db->query("DROP TABLE IF EXISTS {$table}");foreach(['notification_recipients','notifications','user_category_access','audit_logs','employee_property_assignments','user_sessions','login_attempts','properties','users','employees'] as $table)$this->db->query("DELETE FROM {$table}");}
}
