<?php
declare(strict_types=1);
use NpmGateway\Contracts\ClockInterface;
use NpmGateway\Database\DatabaseProfiles;
use NpmGateway\Database\MySqlConnectionFactory;
use NpmGateway\Database\MySqlInitializationTransaction;
use NpmGateway\Repositories\AuditRepository;
use NpmGateway\Repositories\EmployeeEmergencyContactRepository;
use NpmGateway\Services\AuditService;
use NpmGateway\Services\EmployeeEmergencyContactService;
use NpmGateway\Support\PhoneFormatter;
use NpmGateway\Support\PublicIdGenerator;
use NpmGateway\ValueObjects\AuthenticatedUser;
use PHPUnit\Framework\TestCase;
final class ManagerMaintenanceEmergencyContactIntegrationTest extends TestCase
{
 private mysqli $db;private PublicIdGenerator $ids;
 protected function setUp():void{if(getenv('RUN_DB_INTEGRATION_TESTS')!=='true')self::markTestSkipped('Set RUN_DB_INTEGRATION_TESTS=true with both profiles on npmgateway_test.');$app=require dirname(__DIR__,2).'/bootstrap/app.php';foreach(['application','migration'] as $profile)self::assertSame('npmgateway_test',DatabaseProfiles::load($profile,$app['root'])['database']);$this->db=MySqlConnectionFactory::connect(DatabaseProfiles::load('migration',$app['root']));$this->ids=new PublicIdGenerator();$this->clean();}
 protected function tearDown():void{if(isset($this->db)){$this->clean();$this->db->close();}}
 public function testCurrentResponsibleManagerCreatesAndUpdatesSameMaintenanceRow():void{$manager=$this->person('Mara','Manager','manager1','manager');$outsider=$this->person('Otto','Outside','manager2','manager');$maintenance=$this->person('Max','Maintenance','maintenance1','maintenance');$other=$this->person('Mia','Other','maintenance2','maintenance');$corporate=$this->person('Cora','Corporate','corporate2','corporate');$property=$this->property('Authorized Property','manager@authority.test');$otherProperty=$this->property('Other Property','manager@other.test');$this->assignment($manager->employeeId,$property,'property_manager');$this->assignment($maintenance->employeeId,$property,'maintenance');$this->assignment($other->employeeId,$otherProperty,'maintenance');$repository=new EmployeeEmergencyContactRepository($this->db);$target=$repository->findAuthorizedMaintenanceForManager($manager->employeeId,$maintenance->employeePublicId);self::assertNotNull($target);self::assertNull($repository->findAuthorizedMaintenanceForManager($outsider->employeeId,$maintenance->employeePublicId));self::assertNull($repository->findAuthorizedMaintenanceForManager($manager->employeeId,$other->employeePublicId));self::assertNull($repository->findAuthorizedMaintenanceForManager($manager->employeeId,$corporate->employeePublicId));$service=$this->service();$created=$service->saveForMaintenanceByManager($manager,$target,['first_name'=>'Emergency','last_name'=>'Contact','relationship'=>'Parent','primary_phone'=>'5705550111','alternate_phone'=>'']);$updated=$service->saveForMaintenanceByManager($manager,$target,['first_name'=>'Updated','last_name'=>'Contact','relationship'=>'Parent','primary_phone'=>'5705550112','alternate_phone'=>'5705550113']);self::assertSame($created->publicId,$updated->publicId);self::assertSame(1,$this->scalar('SELECT COUNT(*) FROM employee_emergency_contacts'));self::assertSame(1,$this->scalar("SELECT COUNT(*) FROM audit_logs WHERE event_type='employee.emergency_contact_created_by_manager'"));self::assertSame(1,$this->scalar("SELECT COUNT(*) FROM audit_logs WHERE event_type='employee.emergency_contact_updated_by_manager'"));$audit=(string)$this->db->query("SELECT GROUP_CONCAT(after_data) FROM audit_logs WHERE event_type LIKE 'employee.emergency_contact_%_by_manager'")->fetch_row()[0];foreach(['Emergency','Updated','Contact','5705550111','5705550112','5705550113','Parent','manager@authority.test'] as $private)self::assertStringNotContainsString($private,$audit);self::assertSame(0,$this->scalar('SELECT COUNT(*) FROM notifications'));self::assertSame(0,$this->scalar('SELECT COUNT(*) FROM notification_recipients'));}
 private function service():EmployeeEmergencyContactService{$clock=new class implements ClockInterface{public function now():DateTimeImmutable{return new DateTimeImmutable('2026-08-04 12:00:00');}};return new EmployeeEmergencyContactService(new EmployeeEmergencyContactRepository($this->db),new MySqlInitializationTransaction($this->db),$this->ids,$clock,new PhoneFormatter(),new AuditService(new AuditRepository($this->db),$this->ids));}
 private function person(string $first,string $last,string $username,string $class):AuthenticatedUser{$ep=$this->ids->generate();$up=$this->ids->generate();$number='NPM'.str_pad((string)($this->scalar('SELECT COUNT(*) FROM employees')+960000),6,'0',STR_PAD_LEFT);$s=$this->db->prepare("INSERT INTO employees(public_id,employee_number,employee_class,first_name,last_name,job_title,employment_status,start_date) VALUES(?,?,?,?,?,'Tester','active','2026-08-01')");$s->bind_param('sssss',$ep,$number,$class,$first,$last);$s->execute();$employee=$this->db->insert_id;$s->close();$hash=password_hash('test',PASSWORD_DEFAULT);$s=$this->db->prepare("INSERT INTO users(public_id,employee_id,username,password_hash,status) VALUES(?,?,?,?,'active')");$s->bind_param('siss',$up,$employee,$username,$hash);$s->execute();$user=$this->db->insert_id;$s->close();return new AuthenticatedUser($user,$employee,$up,$ep,$username,$first.' '.$last,'Tester',$class);}
 private function property(string $name,string $managerEmail):array{$public=$this->ids->generate();$count=$this->scalar('SELECT COUNT(*) FROM properties');$propId=990000+$count;$code='Z'.chr(65+$count);$slug='disposable-'.$propId;$ivr='570555'.str_pad((string)(1000+$count),4,'0',STR_PAD_LEFT);$s=$this->db->prepare("INSERT INTO properties(public_id,prop_id,property_code,slug,display_name,manager_email,status,ivr_number,address_line_1,city,state,postal_code,timezone) VALUES(?,?,?,?,?,?,'active',?,'1 Test Way','Scranton','PA','18503','America/New_York')");$s->bind_param('sisssss',$public,$propId,$code,$slug,$name,$managerEmail,$ivr);$s->execute();$id=$this->db->insert_id;$s->close();return ['id'=>$id,'public_id'=>$public];}
 private function assignment(int $employeeId,array $property,string $type):void{$public=$this->ids->generate();$propertyId=(int)$property['id'];$s=$this->db->prepare("INSERT INTO employee_property_assignments(public_id,employee_id,property_id,assignment_type,is_primary,starts_on) VALUES(?,?,?,?,1,'2026-08-01')");$s->bind_param('siis',$public,$employeeId,$propertyId,$type);$s->execute();$s->close();}
 private function scalar(string $sql):int{return (int)$this->db->query($sql)->fetch_row()[0];}
 private function clean():void{foreach(['employee_emergency_contacts','notification_recipients','notifications','user_category_access','audit_logs','employee_property_assignments','user_sessions','login_attempts','properties','users','employees'] as $table){$exists=$this->scalar("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='{$table}'");if($exists)$this->db->query("DELETE FROM {$table}");}}
}
