<?php
declare(strict_types=1);
use NpmGateway\Contracts\ClockInterface;
use NpmGateway\Contracts\CompanyAnnouncementEmailSenderInterface;
use NpmGateway\Database\DatabaseProfiles;
use NpmGateway\Database\MySqlConnectionFactory;
use NpmGateway\Repositories\AuditRepository;
use NpmGateway\Repositories\NotificationRecipientRepository;
use NpmGateway\Repositories\NotificationRepository;
use NpmGateway\Services\AuditService;
use NpmGateway\Services\CompanyAnnouncementDispatchService;
use NpmGateway\Services\EmployeeAnnouncementFactory;
use NpmGateway\Services\NotificationAcknowledgmentService;
use NpmGateway\Services\NotificationPublisher;
use NpmGateway\Services\NotificationQueryService;
use NpmGateway\Database\MySqlInitializationTransaction;
use NpmGateway\Support\PublicIdGenerator;
use NpmGateway\ValueObjects\AuthenticatedUser;
use NpmGateway\ValueObjects\EmployeeAnnouncement;
use PHPUnit\Framework\TestCase;
require_once __DIR__.'/DisposableMigrationBoundary.php';
final class NotificationsIntegrationTest extends TestCase
{
 private mysqli $db; private PublicIdGenerator $ids;
 protected function setUp():void
 {
  if(getenv('RUN_DB_INTEGRATION_TESTS')!=='true')self::markTestSkipped('Set RUN_DB_INTEGRATION_TESTS=true with both profiles on npmgateway_test.');
  $app=require dirname(__DIR__,2).'/bootstrap/app.php';foreach(['application','migration'] as $profile)self::assertSame('npmgateway_test',DatabaseProfiles::load($profile,$app['root'])['database']);
  $this->db=MySqlConnectionFactory::connect(DatabaseProfiles::load('migration',$app['root']));$this->ids=new PublicIdGenerator();$this->clean();
 }
 protected function tearDown():void{if(isset($this->db)){$this->clean();$this->db->close();}}
 public function testPublicationAudienceDeliveryCountsViewsAcknowledgmentAndDeduplication():void
 {
  $chuck=$this->person('Chuck','Admin','chuck','active','active','chuck@example.test');$tim=$this->person('Tim','Corporate','tim','active','active','tim@example.test');$manager=$this->person('Pat','Manager','pat','active','active','manager@example.test');$inactiveEmployee=$this->person('Ian','Inactive','ian','inactive','active','ian@example.test');$inactiveUser=$this->person('Una','Disabled','una','active','disabled','una@example.test');$newHire=$this->person('Kathrina','Petty','kathrina','active','active','kathrina@example.test');
  $announcement=(new EmployeeAnnouncementFactory())->create($newHire['employee_public_id'],['first_name'=>'Kathrina','last_name'=>'Petty','job_title'=>'Property Manager <script>','start_date'=>'2026-08-02','company_phone'=>'+15551234567','business_email'=>'kathrina@example.test','context_name'=>'Highridge','date_of_birth'=>'1990-01-01','personal_email'=>'private@example.test','password'=>'NeverStore']);
  self::assertSame(['employee_name','job_title','start_date','company_phone','business_email','primary_property'],array_keys($announcement->payload));
  $clock=new class implements ClockInterface{public function now():DateTimeImmutable{return new DateTimeImmutable('2026-08-02 03:42:00');}};$audit=new AuditService(new AuditRepository($this->db),$this->ids);$recipientRepo=new NotificationRecipientRepository($this->db);$publisher=new NotificationPublisher(new NotificationRepository($this->db),$recipientRepo,new MySqlInitializationTransaction($this->db),$this->ids,$clock,$audit);
  $published=$publisher->publish($announcement,$chuck['user_id'],$chuck['employee_id'],$chuck['user_public_id']);self::assertFalse($published['already_published']);self::assertSame(4,$this->scalar('SELECT COUNT(*) FROM notification_recipients'));
  self::assertSame(0,$this->countRecipient($inactiveEmployee['user_id']));self::assertSame(0,$this->countRecipient($inactiveUser['user_id']));self::assertSame(1,$this->countRecipient($newHire['user_id']));
  $payload=json_decode((string)$this->db->query('SELECT payload FROM notifications')->fetch_row()[0],true,512,JSON_THROW_ON_ERROR);$expectedKeys=array_keys($announcement->payload);$actualKeys=array_keys($payload);sort($expectedKeys);sort($actualKeys);self::assertSame($expectedKeys,$actualKeys);self::assertStringNotContainsString('NeverStore',json_encode($payload,JSON_THROW_ON_ERROR));
  $before=$this->scalar('SELECT COUNT(*) FROM notification_recipients');$this->db->query("UPDATE employees SET job_title='Changed' WHERE id=".$manager['employee_id']);self::assertSame($before,$this->scalar('SELECT COUNT(*) FROM notification_recipients'));
  $sender=new class implements CompanyAnnouncementEmailSenderInterface{public array $sent=[];public function send(string $email,EmployeeAnnouncement $a):bool{$this->sent[]=['email'=>$email,'announcement'=>$a];return $email!=='manager@example.test';}};$dispatch=new CompanyAnnouncementDispatchService($recipientRepo,$sender,$clock,$audit);$result=$dispatch->dispatch($published['id'],$published['public_id'],$announcement,new AuthenticatedUser($chuck['user_id'],$chuck['employee_id'],$chuck['user_public_id'],$chuck['employee_public_id'],'chuck','Chuck Admin'));
  self::assertSame(['sent'=>3,'failed'=>1],$result);self::assertSame(3,$this->scalar("SELECT COUNT(*) FROM notification_recipients WHERE email_status='sent'"));self::assertSame(1,$this->scalar("SELECT COUNT(*) FROM notification_recipients WHERE email_status='failed' AND email_failure_code='transport_failure'"));
  $queries=new NotificationQueryService($this->db);self::assertSame(1,$queries->count($chuck['user_id'])->outstanding);self::assertSame(1,$queries->count($tim['user_id'])->outstanding);
  $acks=new NotificationAcknowledgmentService($this->db,$queries,$audit,$clock);$chuckUser=new AuthenticatedUser($chuck['user_id'],$chuck['employee_id'],$chuck['user_public_id'],$chuck['employee_public_id'],'chuck','Chuck Admin');$first=$acks->view($published['public_id'],$chuckUser);$second=$acks->view($published['public_id'],$chuckUser);self::assertSame($first['first_viewed_at'],$second['first_viewed_at']);self::assertSame(1,$queries->count($chuck['user_id'])->outstanding);self::assertSame(1,$this->scalar("SELECT COUNT(*) FROM audit_logs WHERE event_type='notification.first_viewed'"));
  $acks->acknowledge($published['public_id'],$chuckUser);$ackAt=$queries->detail($chuck['user_id'],$published['public_id'])['acknowledged_at'];$acks->acknowledge($published['public_id'],$chuckUser);self::assertSame($ackAt,$queries->detail($chuck['user_id'],$published['public_id'])['acknowledged_at']);self::assertSame(0,$queries->count($chuck['user_id'])->outstanding);self::assertSame(1,$queries->count($tim['user_id'])->outstanding);self::assertSame(1,$this->scalar("SELECT COUNT(*) FROM audit_logs WHERE event_type='notification.acknowledged'"));
  self::assertNull($queries->detail($inactiveUser['user_id'],$published['public_id']));$retry=$publisher->publish($announcement,$chuck['user_id'],$chuck['employee_id'],$chuck['user_public_id']);self::assertTrue($retry['already_published']);self::assertSame(1,$this->scalar('SELECT COUNT(*) FROM notifications'));self::assertSame(4,$this->scalar('SELECT COUNT(*) FROM notification_recipients'));
  $this->db->query("UPDATE notifications SET status='withdrawn'");self::assertSame(0,$queries->count($tim['user_id'])->outstanding);self::assertSame([],$queries->listing($tim['user_id'],false));$this->db->query("UPDATE notifications SET status='published',expires_at='2026-01-01 00:00:00'");self::assertSame(0,$queries->count($tim['user_id'])->outstanding);
  foreach(['notification.published','notification.first_viewed','notification.acknowledged','notification.email_dispatch_failed'] as $event)self::assertSame(1,$this->scalar("SELECT COUNT(*) FROM audit_logs WHERE event_type='{$event}'"));$auditJson=(string)$this->db->query("SELECT GROUP_CONCAT(COALESCE(after_data,'')) FROM audit_logs WHERE event_type LIKE 'notification.%'")->fetch_row()[0];foreach(['kathrina@example.test','NeverStore','smtp','Property Manager <script>'] as $forbidden)self::assertStringNotContainsString($forbidden,$auditJson);
 }
 public function testMissingEmailAndGroupedStatusBatch():void
 {
  $actor=$this->person('Chuck','Admin','chuck','active','active','chuck@example.test');$missing=$this->person('No','Email','noemail','active','active',null);$announcement=(new EmployeeAnnouncementFactory())->create($actor['employee_public_id'],['first_name'=>'Test','last_name'=>'Person','job_title'=>'Role','start_date'=>'2026-08-02','company_phone'=>'+15551234567','business_email'=>'test@example.test','context_name'=>'Corporate']);$clock=new class implements ClockInterface{public function now():DateTimeImmutable{return new DateTimeImmutable('2026-08-02 03:42:00');}};$repo=new NotificationRecipientRepository($this->db);$audit=new AuditService(new AuditRepository($this->db),$this->ids);$publisher=new NotificationPublisher(new NotificationRepository($this->db),$repo,new MySqlInitializationTransaction($this->db),$this->ids,$clock,$audit);$notice=$publisher->publish($announcement,$actor['user_id'],$actor['employee_id'],$actor['user_public_id']);self::assertSame(1,$this->scalar("SELECT COUNT(*) FROM notification_recipients WHERE user_id={$missing['user_id']} AND email_status='skipped_no_email'"));$sender=new class implements CompanyAnnouncementEmailSenderInterface{public function send(string $email,EmployeeAnnouncement $a):bool{return true;}};(new CompanyAnnouncementDispatchService($repo,$sender,$clock,$audit))->dispatch($notice['id'],$notice['public_id'],$announcement,new AuthenticatedUser($actor['user_id'],$actor['employee_id'],$actor['user_public_id'],$actor['employee_public_id'],'chuck','Chuck Admin'));self::assertSame(1,$this->scalar("SELECT COUNT(*) FROM notification_recipients WHERE email_status='sent'"));self::assertSame(1,$this->scalar("SELECT COUNT(*) FROM audit_logs WHERE event_type='notification.email_dispatch_completed'"));
 }
 public function testRollbackRefusesHistoricalRowsThenSucceedsWhenEmptyAndReapplies():void
 {
  $app=require dirname(__DIR__,2).'/bootstrap/app.php';$boundary=new DisposableMigrationBoundary($this->db,$app['root']);$boundary->atBoundary('202608020008_notifications',function():void{$actor=$this->person('Chuck','Admin','chuck','active','active','chuck@example.test');$announcement=(new EmployeeAnnouncementFactory())->create($actor['employee_public_id'],['first_name'=>'Test','last_name'=>'Person','job_title'=>'Role','start_date'=>'2026-08-02','company_phone'=>'+15551234567','business_email'=>'test@example.test','context_name'=>'Corporate']);$clock=new class implements ClockInterface{public function now():DateTimeImmutable{return new DateTimeImmutable('2026-08-02 03:42:00');}};$publisher=new NotificationPublisher(new NotificationRepository($this->db),new NotificationRecipientRepository($this->db),new MySqlInitializationTransaction($this->db),$this->ids,$clock,new AuditService(new AuditRepository($this->db),$this->ids));$publisher->publish($announcement,$actor['user_id'],$actor['employee_id'],$actor['user_public_id']);$migration=require dirname(__DIR__,2).'/database/migrations/202608020008_notifications.php';$companyNotices=require dirname(__DIR__,2).'/database/migrations/202608020009_company_notices_category.php';try{$migration->down($this->db);self::fail('Rollback should refuse historical notification rows.');}catch(\NpmGateway\Database\Migration\MigrationException){}self::assertSame(1,$this->scalar("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA='npmgateway_test' AND TABLE_NAME='notifications'"));self::assertSame(1,$this->scalar('SELECT COUNT(*) FROM notifications'));
  $this->db->query('DELETE FROM notification_recipients');$this->db->query('DELETE FROM notifications');$companyNotices->down($this->db);$migration->down($this->db);self::assertSame(0,$this->scalar("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA='npmgateway_test' AND TABLE_NAME IN ('notifications','notification_recipients')"));$migration->up($this->db);$companyNotices->up($this->db);self::assertSame(2,$this->scalar("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA='npmgateway_test' AND TABLE_NAME IN ('notifications','notification_recipients')"));});
 }
 private function person(string $first,string $last,string $username,string $employeeStatus,string $userStatus,?string $email):array{$ep=$this->ids->generate();$up=$this->ids->generate();$number='NPM'.str_pad((string)($this->scalar('SELECT COUNT(*) FROM employees')+1),6,'0',STR_PAD_LEFT);$s=$this->db->prepare('INSERT INTO employees(public_id,employee_number,employee_class,first_name,last_name,date_of_birth,business_email,company_phone,job_title,employment_status,start_date,comments) VALUES(?,?,\'corporate\',?,?,NULL,?,\'+15551234567\',\'Test Role\',?,\'2026-08-02\',NULL)');$s->bind_param('ssssss',$ep,$number,$first,$last,$email,$employeeStatus);$s->execute();$employeeId=$this->db->insert_id;$s->close();$hash=password_hash('Test-password-123!',PASSWORD_DEFAULT);$s=$this->db->prepare('INSERT INTO users(public_id,employee_id,username,password_hash,status) VALUES(?,?,?,?,?)');$s->bind_param('sisss',$up,$employeeId,$username,$hash,$userStatus);$s->execute();$userId=$this->db->insert_id;$s->close();return ['employee_id'=>$employeeId,'user_id'=>$userId,'employee_public_id'=>$ep,'user_public_id'=>$up];}
 private function countRecipient(int $userId):int{return $this->scalar("SELECT COUNT(*) FROM notification_recipients WHERE user_id={$userId}");}
 private function scalar(string $sql):int{return (int)$this->db->query($sql)->fetch_row()[0];}
 private function clean():void{foreach(['notification_recipients','notifications','user_category_access','audit_logs','employee_property_assignments','user_sessions','login_attempts','properties','users','employees'] as $table)$this->db->query("DELETE FROM {$table}");}
}
