<?php
declare(strict_types=1);
use NpmGateway\Container\ServiceProvider;
use NpmGateway\Contracts\CorporateToolsProviderInterface;
use NpmGateway\Database\DatabaseProfiles;
use NpmGateway\Database\MySqlConnectionFactory;
use NpmGateway\Http\AuthenticatedRequestContext;
use NpmGateway\Http\Controllers\CorporateWorkspaceController;
use NpmGateway\Security\CsrfService;
use NpmGateway\Services\CorporateAccessService;
use NpmGateway\ValueObjects\AuthenticatedUser;
$application=require dirname(__DIR__,2).'/bootstrap/app.php';foreach(['application','migration'] as $profile)if(DatabaseProfiles::load($profile,$application['root'])['database']!=='npmgateway_test'){fwrite(STDERR,"Operations disposable gate failed.\n");exit(2);}$db=MySqlConnectionFactory::connect(DatabaseProfiles::load('migration',$application['root']));$mode=$argv[1]??'';
$clean=static function(mysqli $db):void{foreach(['notification_storage_objects','storage_objects','notification_recipients','notifications','user_category_access','audit_logs','employee_property_assignments','user_sessions','login_attempts','properties','users','employees'] as $table){$exists=(int)$db->query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='{$table}'")->fetch_row()[0];if($exists)$db->query("DELETE FROM {$table}");}};
try{
 if($mode==='seed'){$clean($db);foreach([['C','NPM930001','Chuck','Disposable','chuck'],['T','NPM930002','Tim','Disposable','tim'],['U','NPM930003','Una','Ssigned','unassigned']] as [$char,$number,$first,$last,$username]){$employee=str_repeat($char,26);$user=str_repeat($char==='U'?'V':$char,26);$s=$db->prepare("INSERT INTO employees(public_id,employee_number,employee_class,first_name,last_name,job_title,employment_status,start_date) VALUES (?,?,'corporate',?,?,'Disposable','active','2026-08-03')");$s->bind_param('ssss',$employee,$number,$first,$last);$s->execute();$employeeId=$db->insert_id;$s->close();$hash=password_hash('Disposable-123!',PASSWORD_DEFAULT);$s=$db->prepare("INSERT INTO users(public_id,employee_id,username,password_hash,status) VALUES (?,?,?,?,'active')");$s->bind_param('siss',$user,$employeeId,$username,$hash);$s->execute();$s->close();}echo "fixtures=3\n";}
 elseif($mode==='verify'){$rows=$db->query("SELECT u.username,u.status FROM user_category_access a JOIN users u ON u.id=a.user_id WHERE a.category='operations' ORDER BY u.username")->fetch_all(MYSQLI_ASSOC);if(array_column($rows,'username')!==['chuck','tim']||array_unique(array_column($rows,'status'))!==['active'])throw new RuntimeException('Operations membership set is not exactly active Chuck and Tim.');$container=ServiceProvider::build($application);$access=$container->get(CorporateAccessService::class);$tools=$container->get(CorporateToolsProviderInterface::class);$session=[];$csrf=new CsrfService($session);$controller=new CorporateWorkspaceController($access,$tools,$csrf,$application['root'].'/resources/views');$users=[];foreach($db->query("SELECT u.id user_id,u.public_id user_public,e.id employee_id,e.public_id employee_public,u.username,CONCAT(e.first_name,' ',e.last_name) display_name FROM users u JOIN employees e ON e.id=u.employee_id")->fetch_all(MYSQLI_ASSOC) as $row)$users[$row['username']]=new AuthenticatedRequestContext(new AuthenticatedUser((int)$row['user_id'],(int)$row['employee_id'],$row['user_public'],$row['employee_public'],$row['username'],$row['display_name']),'disposable');foreach(['chuck','tim'] as $name){foreach(['operations','inventoryCf','inventoryHr','development'] as $method)if($controller->{$method}($users[$name])->status!==200)throw new RuntimeException("Authorized route failed for {$name}: {$method}");}$unassignedCards=$tools->tools($users['unassigned']);if($unassignedCards[0]->key!=='operations'||$unassignedCards[0]->enabled||$unassignedCards[0]->footerLabel!=='Access not assigned')throw new RuntimeException('Unassigned Operations card behavior failed.');if($controller->operations($users['unassigned'])->status!==403)throw new RuntimeException('Unauthorized Operations request did not return 403.');if($controller->flyers($users['unassigned'])->status!==403)throw new RuntimeException('Unauthorized Flyers request did not return 403.');echo "operations_members=chuck,tim\nauthorized_routes=200\nunauthorized_operations=403\nunauthorized_flyers=403\ncorporate_order=".implode(',',array_map(fn($card)=>$card->key,$tools->tools($users['chuck'])))."\n";$container->get(mysqli::class)->close();}
 elseif($mode==='remove-operations'){$count=(int)$db->query("SELECT COUNT(*) FROM user_category_access WHERE category='operations'")->fetch_row()[0];$db->query("DELETE FROM audit_logs WHERE event_type='admin.operations_access_backfilled'");$db->query("DELETE FROM user_category_access WHERE category='operations'");echo "operations_removed={$count}\n";}
 elseif($mode==='cleanup'){$clean($db);echo "fixtures_cleaned=yes\n";}
 elseif($mode==='residue'){$total=0;foreach(['notification_storage_objects','storage_objects','notification_recipients','notifications','user_category_access','audit_logs','employee_property_assignments','user_sessions','login_attempts','properties','users','employees'] as $table){$exists=(int)$db->query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='{$table}'")->fetch_row()[0];if($exists)$total+=(int)$db->query("SELECT COUNT(*) FROM {$table}")->fetch_row()[0];}echo "disposable_residue={$total}\n";if($total!==0)exit(1);}
 else throw new InvalidArgumentException('Unknown operations disposable mode.');
}catch(Throwable $e){fwrite(STDERR,str_replace(["\r","\n"],' ',$e->getMessage())."\n");exit(1);}finally{$db->close();}
