<?php
declare(strict_types=1);
use NpmGateway\Container\ServiceProvider;
use NpmGateway\Database\DatabaseProfiles;
use NpmGateway\Database\MySqlConnectionFactory;
use NpmGateway\Exceptions\Domain\InvalidPropertyDataException;
use NpmGateway\Services\PropertyAdministrationService;
use NpmGateway\Services\PropertyQueryService;
use NpmGateway\ValueObjects\AuthenticatedUser;
use NpmGateway\ValueObjects\PropertyDirectoryCriteria;
use PHPUnit\Framework\TestCase;
final class PropertiesWorkspaceIntegrationTest extends TestCase
{
    public function testBoulderTrailsCreationDirectoryAuditDuplicatesAndManagerInvariants():void
    {
        if(getenv('RUN_DB_INTEGRATION_TESTS')!=='true')self::markTestSkipped('Set RUN_DB_INTEGRATION_TESTS=true with both profiles on npmgateway_test.');$application=require dirname(__DIR__,2).'/bootstrap/app.php';foreach(['application','migration'] as $profile)self::assertSame('npmgateway_test',DatabaseProfiles::load($profile,$application['root'])['database']);$connection=MySqlConnectionFactory::connect(DatabaseProfiles::load('migration',$application['root']));$this->clean($connection);
        try{
            $employeePublic=str_repeat('E',26);$userPublic=str_repeat('U',26);$hash=password_hash('integration-only-secret',PASSWORD_DEFAULT);$connection->query("INSERT INTO employees(public_id,employee_number,employee_class,first_name,last_name,business_email,job_title,employment_status,hire_date) VALUES ('{$employeePublic}','NPM999998','corporate','Integration','Admin','integration.admin@example.test','Test Administrator','active','2026-01-01')");$employeeId=(int)$connection->insert_id;$statement=$connection->prepare("INSERT INTO users(public_id,employee_id,username,password_hash,status) VALUES (?,?, 'integrationadmin',?,'active')");$statement->bind_param('sis',$userPublic,$employeeId,$hash);$statement->execute();$userId=(int)$connection->insert_id;$statement->close();$connection->close();
            $container=ServiceProvider::build($application);$service=$container->get(PropertyAdministrationService::class);$query=$container->get(PropertyQueryService::class);$actor=new AuthenticatedUser($userId,$employeeId,$userPublic,$employeePublic,'integrationadmin','Integration Admin','Test Administrator','corporate');$fixture=$this->fixture();$service->create($fixture,$actor);
            $page=$query->search(new PropertyDirectoryCriteria());self::assertCount(1,$page->properties);$row=$page->properties[0];self::assertSame(1529,$row->propId);self::assertSame('Boulder Trails MHC',$row->name);self::assertSame('609 Dewey St., Sylvester, GA 31791',$row->address);self::assertSame('(229) 449-5184',$row->phone);self::assertSame('(229) 354-4477',$row->ivr);self::assertSame('Not assigned',$row->manager);self::assertEquals($page,$query->search(new PropertyDirectoryCriteria()));
            $db=$container->get(mysqli::class);$stored=$db->query('SELECT prop_id,property_code,slug FROM properties WHERE prop_id=1529')->fetch_assoc();self::assertSame('1529',(string)$stored['prop_id']);self::assertSame('BT',$stored['property_code']);self::assertSame('boulder-trails',$stored['slug']);self::assertSame(1,(int)$db->query("SELECT COUNT(*) FROM audit_logs WHERE event_type='hr.property_created' AND property_id IS NOT NULL")->fetch_row()[0]);
            foreach([['prop_id','1529','prop_id'],['property_code','BT','property_code'],['slug','boulder-trails','slug']] as [$field,$value,$expected]){$duplicate=$fixture;$duplicate['prop_id']='1530';$duplicate['property_code']='BX';$duplicate['slug']='boulder-x';$duplicate['manager_email']='other'.$field.'@example.test';$duplicate['ivr_number']='(229) 555-0101';$duplicate[$field]=$value;try{$service->create($duplicate,$actor);self::fail('Expected safe duplicate rejection.');}catch(InvalidPropertyDataException $e){self::assertArrayHasKey($expected,$e->errors);self::assertStringNotContainsString('SQL',implode(' ',$e->errors));}}
            $second=$fixture;$second['prop_id']='1729';$second['property_code']='CF';$second['slug']='crumley-farms';$second['display_name']='Crumley Farms';$second['manager_email']='manager@crumley.example.test';$second['ivr_number']='(229) 555-0202';$second['ivr_routing_email']='routing@crumley.example.test';$service->create($second,$actor);$propertyIds=$db->query('SELECT id,prop_id FROM properties ORDER BY prop_id')->fetch_all(MYSQLI_ASSOC);$firstId=(int)$propertyIds[0]['id'];$secondId=(int)$propertyIds[1]['id'];
            $manager1=$this->employee($db,'NPM999901','Manager','One');$manager2=$this->employee($db,'NPM999902','Manager','Two');$this->assignment($db,'A',$manager1,$firstId,1);$this->expectDuplicate(fn()=> $this->assignment($db,'B',$manager2,$firstId,1),'property');$this->expectDuplicate(fn()=> $this->assignment($db,'C',$manager1,$secondId,1),'employee');$this->assignment($db,'D',$manager1,$secondId,0);$this->assignment($db,'F',$manager2,$secondId,0);
            $managed=$query->search(new PropertyDirectoryCriteria());self::assertSame('Manager One',$managed->properties[0]->manager);self::assertSame('Not assigned',$managed->properties[1]->manager);$container->get(mysqli::class)->close();
        }finally{$cleanup=MySqlConnectionFactory::connect(DatabaseProfiles::load('migration',$application['root']));$this->clean($cleanup);$cleanup->close();}
    }
    private function fixture():array{return ['prop_id'=>'1529','property_code'=>'BT','display_name'=>'Boulder Trails MHC','slug'=>'boulder-trails','status'=>'active','address_line_1'=>'609 Dewey St.','city'=>'Sylvester','state'=>'GA','postal_code'=>'31791','timezone'=>'America/New_York','office_phone'=>'(229) 449-5184','manager_email'=>'manager@bouldertrailsmhc.com','website_url'=>'https://bouldertrailsmhc.com','ivr_number'=>'(229) 354-4477','ivr_routing_email'=>'2419@rentertext.com'];}
    private function employee(mysqli $db,string $number,string $first,string $last):int{$public=substr(str_pad($number,26,'X'),0,26);$s=$db->prepare("INSERT INTO employees(public_id,employee_number,employee_class,first_name,last_name,job_title,employment_status,hire_date) VALUES (?,?, 'manager',?,?,'Property Manager','active','2026-01-01')");$s->bind_param('ssss',$public,$number,$first,$last);$s->execute();$id=(int)$db->insert_id;$s->close();return $id;}
    private function assignment(mysqli $db,string $suffix,int $employee,int $property,int $primary):void{$public=str_repeat($suffix,26);$s=$db->prepare("INSERT INTO employee_property_assignments(public_id,employee_id,property_id,assignment_type,is_primary,starts_on) VALUES (?,?,?,'property_manager',?,'2026-01-01')");$s->bind_param('siii',$public,$employee,$property,$primary);$s->execute();$s->close();}
    private function expectDuplicate(callable $operation,string $scope):void{try{$operation();self::fail("Expected {$scope} cardinality rejection.");}catch(mysqli_sql_exception $e){self::assertSame(1062,$e->getCode());}}
    private function clean(mysqli $db):void{foreach(['audit_logs','employee_property_assignments','properties','user_sessions','login_attempts','users','employees'] as $table)$db->query("DELETE FROM `{$table}`");}
}
