<?php
declare(strict_types=1);
use NpmGateway\Container\ServiceProvider;
use NpmGateway\Contracts\CorporateToolsProviderInterface;
use NpmGateway\Database\DatabaseProfiles;
use NpmGateway\Database\MySqlConnectionFactory;
use NpmGateway\Http\AuthenticatedRequestContext;
use NpmGateway\Http\Controllers\AdminController;
use NpmGateway\Http\Controllers\CommunityActionsController;
use NpmGateway\Http\Request;
use NpmGateway\Repositories\PropertyAccessRepository;
use NpmGateway\Security\CsrfService;
use NpmGateway\Services\CategoryAccessAdministrationService;
use NpmGateway\Services\CategoryAccessPayloadParser;
use NpmGateway\Services\CorporateAccessService;
use NpmGateway\Services\PropertyAccessPayloadParser;
use NpmGateway\Services\PropertyAccessService;
use NpmGateway\Support\FlashSession;
use NpmGateway\Support\PublicIdGenerator;
use NpmGateway\ValueObjects\AuthenticatedUser;
$app=require dirname(__DIR__,2).'/bootstrap/app.php';foreach(['application','migration'] as $profile)if(DatabaseProfiles::load($profile,$app['root'])['database']!=='npmgateway_test'){fwrite(STDERR,"Property Access disposable certification gate failed.\n");exit(2);}$db=MySqlConnectionFactory::connect(DatabaseProfiles::load('migration',$app['root']));$mode=$argv[1]??'';$ids=new PublicIdGenerator();
$clean=static function(mysqli $db):void{foreach(['user_property_access','employee_emergency_contacts','notification_storage_objects','storage_objects','notification_recipients','notifications','user_category_access','audit_logs','employee_property_assignments','user_sessions','login_attempts','properties','users','employees'] as $table){$exists=(int)$db->query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='{$table}'")->fetch_row()[0];if($exists)$db->query("DELETE FROM {$table}");}};
$person=static function(mysqli $db,PublicIdGenerator $ids,string $first,string $last,string $class,string $number,?string $username):array{$employeePublic=$ids->generate();$s=$db->prepare("INSERT INTO employees(public_id,employee_number,employee_class,first_name,last_name,job_title,employment_status,start_date) VALUES(?,?,?,?,?,'Disposable Certification','active','2026-08-04')");$s->bind_param('sssss',$employeePublic,$number,$class,$first,$last);$s->execute();$employeeId=$db->insert_id;$s->close();$result=['employee_id'=>$employeeId,'employee_public_id'=>$employeePublic,'user_id'=>null,'user_public_id'=>null,'context'=>null];if($username!==null){$userPublic=$ids->generate();$hash=password_hash('Disposable-123!',PASSWORD_DEFAULT);$s=$db->prepare("INSERT INTO users(public_id,employee_id,username,password_hash,status) VALUES(?,?,?,?, 'active')");$s->bind_param('siss',$userPublic,$employeeId,$username,$hash);$s->execute();$userId=$db->insert_id;$s->close();$user=new AuthenticatedUser($userId,$employeeId,$userPublic,$employeePublic,$username,$first.' '.$last,'Disposable Certification',$class);$result+=[];$result['user_id']=$userId;$result['user_public_id']=$userPublic;$result['context']=new AuthenticatedRequestContext($user,'disposable');}return $result;};
$property=static function(mysqli $db,PublicIdGenerator $ids,string $code,string $slug,string $name,string $status,int $propId):array{$public=$ids->generate();$mail=$slug.'@example.test';$s=$db->prepare("INSERT INTO properties(public_id,prop_id,property_code,slug,display_name,status,manager_email,address_line_1,city,state,postal_code,timezone) VALUES(?,?,?,?,?,?,?,'1 Test Way','Test','PA','18503','America/New_York')");$s->bind_param('sisssss',$public,$propId,$code,$slug,$name,$status,$mail);$s->execute();$id=$db->insert_id;$s->close();return ['id'=>$id,'public_id'=>$public,'slug'=>$slug,'display_name'=>$name];};
try{
 if($mode==='certify'){
  $clean($db);$manager=$person($db,$ids,'Roving','Manager','manager','NPM978001','paroving');$other=$person($db,$ids,'Second','Manager','manager','NPM978002','pasecond');$maintenance=$person($db,$ids,'Maintenance','Employee','maintenance','NPM978003',null);$admin=$person($db,$ids,'Corporate','Administrator','corporate','NPM978004','paadmin');$cf=$property($db,$ids,'CF','cert-crumley-farms','Crumley Farms','active',978001);$hr=$property($db,$ids,'HR','cert-highridge','Highridge','active',978002);$inactive=$property($db,$ids,'ZZ','cert-inactive','Inactive Community','inactive',978003);
  $assignmentPublic=$ids->generate();$s=$db->prepare("INSERT INTO employee_property_assignments(public_id,employee_id,property_id,assignment_type,is_primary,starts_on,ends_on,created_by) VALUES(?,?,?,'property_manager',1,'2026-08-04',NULL,?)");$s->bind_param('siii',$assignmentPublic,$manager['employee_id'],$hr['id'],$admin['user_id']);$s->execute();$s->close();$assignmentBefore=json_encode($db->query("SELECT public_id,employee_id,property_id,assignment_type,is_primary,starts_on,ends_on,notes,created_by,updated_by FROM employee_property_assignments ORDER BY id")->fetch_all(MYSQLI_ASSOC),JSON_THROW_ON_ERROR);
  $categoryPublic=$ids->generate();$at='2026-08-04 12:00:00';$s=$db->prepare("INSERT INTO user_category_access(public_id,user_id,category,granted_by_user_id,granted_at) VALUES(?,?,'admin',?,?)");$s->bind_param('siis',$categoryPublic,$admin['user_id'],$admin['user_id'],$at);$s->execute();$s->close();$container=ServiceProvider::build($app);$service=$container->get(PropertyAccessService::class);$repository=$container->get(PropertyAccessRepository::class);$session=[];$csrf=new CsrfService($session);$community=new CommunityActionsController($service,$container->get(\NpmGateway\Services\CommunityActionContextResolver::class),$container->get(\NpmGateway\Services\CommunityActionProvider::class),$container->get(CorporateToolsProviderInterface::class),$csrf,$app['root'].'/resources/views');$adminController=new AdminController($container->get(CorporateAccessService::class),$container->get(CategoryAccessAdministrationService::class),$container->get(CategoryAccessPayloadParser::class),$container->get(CorporateToolsProviderInterface::class),$csrf,new FlashSession($session),$app['root'].'/resources/views',$service,new PropertyAccessPayloadParser());
  if((int)$db->query('SELECT COUNT(*) FROM user_property_access')->fetch_row()[0]!==0||$service->accessibleActiveProperties($manager['context'])!==[])throw new RuntimeException('Assignment alone created access.');if($community->show($hr['slug'],$manager['context'])->status!==403)throw new RuntimeException('Pre-grant HR route was not denied.');$matrix=$service->accessMatrix();if(array_column($matrix['properties'],'display_name')!==['Crumley Farms','Highridge'])throw new RuntimeException('Matrix active-property order failed.');if(count($matrix['employees'])!==4)throw new RuntimeException('Matrix employee population failed.');$maintenanceRow=array_values(array_filter($matrix['employees'],fn($row)=>$row['employee_public_id']===$maintenance['employee_public_id']))[0]??null;if(!is_array($maintenanceRow)||$maintenanceRow['assignable']||$maintenanceRow['reason']!=='No Gateway access')throw new RuntimeException('Maintenance matrix handling failed.');if($adminController->propertyAccess($admin['context'])->status!==200||$adminController->propertyAccess($manager['context'])->status!==403)throw new RuntimeException('Admin authorization failed.');
  $input=['employees'=>array_column($matrix['employees'],'employee_public_id'),'access'=>[]];foreach($matrix['employees'] as $row)$input['access'][$row['employee_public_id']]=[];$input['access'][$manager['employee_public_id']][$hr['public_id']]=true;if($service->applyChanges($input,$admin['context']->user)!==1)throw new RuntimeException('HR grant failed.');if((int)$db->query('SELECT COUNT(*) FROM user_property_access')->fetch_row()[0]!==1||array_column($service->accessibleActiveProperties($manager['context']),'display_name')!==['Highridge']||$community->show($hr['slug'],$manager['context'])->status!==200||$community->show($cf['slug'],$manager['context'])->status!==403)throw new RuntimeException('One-property result failed.');if($service->applyChanges($input,$admin['context']->user)!==0)throw new RuntimeException('Repeated grant was not idempotent.');
  $input['access'][$manager['employee_public_id']][$cf['public_id']]=true;if($service->applyChanges($input,$admin['context']->user)!==1)throw new RuntimeException('CF grant failed.');$accessible=$service->accessibleActiveProperties($manager['context']);if((int)$db->query('SELECT COUNT(*) FROM user_property_access')->fetch_row()[0]!==2||array_column($accessible,'display_name')!==['Crumley Farms','Highridge']||$community->show($cf['slug'],$manager['context'])->status!==200||$community->show($hr['slug'],$manager['context'])->status!==200)throw new RuntimeException('Two-property result failed.');$html=$community->index($manager['context'])->body;foreach($accessible as $row)if(str_contains($html,'/community-actions/'.$row['id']))throw new RuntimeException('Numeric property ID leaked into route.');$workspace=$community->show($hr['slug'],$manager['context'])->body;$segments=array_column($container->get(\NpmGateway\Services\CommunityActionProvider::class)->actions(),'route_segment');if(count($segments)!==10||substr_count($workspace,'data-tool-key=')!==10)throw new RuntimeException('Ten-card workspace failed.');foreach($segments as $segment){if($community->action($hr['slug'],$segment,$manager['context'])->status!==200)throw new RuntimeException('Authorized action route failed.');if($community->action($cf['slug'],$segment,$other['context'])->status!==403)throw new RuntimeException('Unauthorized action route failed.');if($community->action('unknown-property',$segment,$manager['context'])->status!==404)throw new RuntimeException('Unknown-property action route failed.');}
  $repository->grant(['public_id'=>$ids->generate(),'user_id'=>$manager['user_id'],'property_id'=>$inactive['id'],'granted_by_user_id'=>$admin['user_id'],'granted_at'=>$at]);if(str_contains($community->index($manager['context'])->body,'Inactive Community'))throw new RuntimeException('Inactive stale grant appeared.');$repository->revoke($manager['user_id'],$inactive['id']);unset($input['access'][$manager['employee_public_id']][$cf['public_id']]);if($service->applyChanges($input,$admin['context']->user)!==1||array_column($service->accessibleActiveProperties($manager['context']),'display_name')!==['Highridge']||$community->show($cf['slug'],$manager['context'])->status!==403||$community->show($hr['slug'],$manager['context'])->status!==200)throw new RuntimeException('CF revoke failed.');foreach($segments as $segment)if($community->action($cf['slug'],$segment,$manager['context'])->status!==403)throw new RuntimeException('Revoked action remained available.');$repository->grant(['public_id'=>$ids->generate(),'user_id'=>$manager['user_id'],'property_id'=>$cf['id'],'granted_by_user_id'=>$admin['user_id'],'granted_at'=>$at]);foreach($segments as $segment)if($community->action($cf['slug'],$segment,$manager['context'])->status!==200)throw new RuntimeException('Regrant did not restore action route.');$repository->revoke($manager['user_id'],$cf['id']);if($service->applyChanges($input,$admin['context']->user)!==0)throw new RuntimeException('Repeated revoke was not idempotent.');
  $bad=$input;$bad['access'][$maintenance['employee_public_id']][$hr['public_id']]=true;try{$service->applyChanges($bad,$admin['context']->user);throw new RuntimeException('Maintenance crafted grant accepted.');}catch(InvalidArgumentException){}foreach([(string)$hr['id'],str_repeat('X',26),$inactive['public_id']] as $forgedProperty){$bad=$input;$bad['access'][$manager['employee_public_id']]=[$forgedProperty=>true];try{$service->applyChanges($bad,$admin['context']->user);throw new RuntimeException('Forged property identity accepted.');}catch(InvalidArgumentException){}}
  $assignmentAfter=json_encode($db->query("SELECT public_id,employee_id,property_id,assignment_type,is_primary,starts_on,ends_on,notes,created_by,updated_by FROM employee_property_assignments ORDER BY id")->fetch_all(MYSQLI_ASSOC),JSON_THROW_ON_ERROR);if($assignmentBefore!==$assignmentAfter)throw new RuntimeException('Assignment history changed.');$audits=$db->query("SELECT event_type,after_data FROM audit_logs WHERE event_type IN ('property_access.granted','property_access.revoked') ORDER BY id")->fetch_all(MYSQLI_ASSOC);if(count($audits)!==3)throw new RuntimeException('Audit event count failed.');$auditJson=json_encode($audits,JSON_THROW_ON_ERROR);foreach([$manager['user_public_id'],$hr['public_id'],$cf['public_id'],$admin['user_public_id'],'grant','revoke'] as $required)if(!str_contains($auditJson,(string)$required))throw new RuntimeException('Required sanitized audit metadata missing.');foreach(['Roving Manager','Corporate Administrator','@example.test'] as $private)if(str_contains($auditJson,$private))throw new RuntimeException('Private audit data leaked.');if((int)$db->query("SELECT COUNT(*) FROM user_property_access WHERE user_id={$admin['user_id']}")->fetch_row()[0]!==0)throw new RuntimeException('Admin category implied Property Access.');$container->get(mysqli::class)->close();echo "fixtures=4_employees_3_properties\nassignment_alone=denied\nmatrix=CF,HR_all_employees_maintenance_disabled\none_property=HR\ntwo_properties=CF,HR\nworkspace_cards=10\nauthorized_action_routes=10x200\nunauthorized_action_routes=10x403\nunknown_action_routes=10x404\nrevoke_CF=immediate_403_all_routes\nregrant_CF=restored_all_routes\nHR_remains=200\nidempotence=passed\nforged_inputs=denied\naudits=sanitized\nassignments=unchanged\nworkflow_rows=none\nadmin_matrix=200\nmanager_matrix=403\n";
 }
 elseif($mode==='remove-access'){$count=(int)$db->query('SELECT COUNT(*) FROM user_property_access')->fetch_row()[0];$db->query('DELETE FROM user_property_access');echo "access_rows_removed={$count}\n";}
 elseif($mode==='reapply-clean'){$user=(int)$db->query("SELECT id FROM users WHERE username='paroving'")->fetch_row()[0];$property=(int)$db->query("SELECT id FROM properties WHERE slug='cert-highridge'")->fetch_row()[0];$actor=(int)$db->query("SELECT id FROM users WHERE username='paadmin'")->fetch_row()[0];$s=$db->prepare('INSERT INTO user_property_access(public_id,user_id,property_id,granted_by_user_id,granted_at) VALUES(?,?,?,?,NOW())');$public=$ids->generate();$s->bind_param('siii',$public,$user,$property,$actor);$s->execute();$s->close();if((int)$db->query('SELECT COUNT(*) FROM user_property_access')->fetch_row()[0]!==1)throw new RuntimeException('Reapplied migration grant failed.');$clean($db);echo "reapply_grant=passed\nfixtures_cleaned=yes\n";}
 elseif($mode==='residue'){$total=0;foreach(['user_property_access','employee_property_assignments','user_category_access','audit_logs','properties','users','employees'] as $table)$total+=(int)$db->query("SELECT COUNT(*) FROM {$table}")->fetch_row()[0];echo "disposable_residue={$total}\n";if($total!==0)exit(1);}
 else throw new InvalidArgumentException('Unknown certification mode.');
}catch(Throwable $e){fwrite(STDERR,str_replace(["\r","\n"],' ',$e->getMessage())."\n");exit(1);}finally{$db->close();}
