<?php
declare(strict_types=1);
use NpmGateway\Configuration\ProtectedPrincipalConfig;
use NpmGateway\Database\DatabaseProfiles;
use NpmGateway\Database\MySqlConnectionFactory;
use NpmGateway\Repositories\AuditRepository;
use NpmGateway\Services\AuditService;
use NpmGateway\Services\ProtectedPrincipalMaintenanceService;
use NpmGateway\Support\PublicIdGenerator;
use NpmGateway\Support\SystemClock;
use PHPUnit\Framework\TestCase;
final class ProtectedPrincipalIntegrationTest extends TestCase
{
    private mysqli $db;private string $userPublic;private string $employeePublic;private int $userId;private int $employeeId;
    protected function setUp():void{$root=dirname(__DIR__,2);$profile=DatabaseProfiles::load('migration',$root);if(($profile['database']??'')!=='npmgateway_test')self::markTestSkipped('Disposable protected-principal certification requires npmgateway_test.');$this->db=MySqlConnectionFactory::connect($profile);$ids=new PublicIdGenerator();$this->userPublic=$ids->generate();$this->employeePublic=$ids->generate();$number='NPM'.random_int(700000,799999);$s=$this->db->prepare("INSERT INTO employees(public_id,employee_number,employee_class,first_name,last_name,job_title,employment_status,start_date) VALUES(?,?,'corporate','Protected','Disposable','Certification','active','2026-08-05')");$s->bind_param('ss',$this->employeePublic,$number);$s->execute();$this->employeeId=(int)$this->db->insert_id;$s->close();$hash=password_hash('Disposable-only-123!',PASSWORD_DEFAULT);$username='protected'.random_int(10000,99999);$s=$this->db->prepare("INSERT INTO users(public_id,employee_id,username,password_hash,status) VALUES(?,?,?,?,'active')");$s->bind_param('siss',$this->userPublic,$this->employeeId,$username,$hash);$s->execute();$this->userId=(int)$this->db->insert_id;$s->close();$membership=$ids->generate();$s=$this->db->prepare("INSERT INTO user_category_access(public_id,user_id,category,granted_by_user_id,granted_at) VALUES(?,?,'admin',?,NOW())");$s->bind_param('sii',$membership,$this->userId,$this->userId);$s->execute();$s->close();}
    protected function tearDown():void{if(!isset($this->db))return;$this->db->query("DELETE FROM audit_logs WHERE entity_public_id='".$this->db->real_escape_string($this->userPublic)."'");$this->db->query('DELETE FROM user_category_access WHERE user_id='.(int)$this->userId);$this->db->query('DELETE FROM users WHERE id='.(int)$this->userId);$this->db->query('DELETE FROM employees WHERE id='.(int)$this->employeeId);$this->db->close();}
    public function testDisposableHealthRepairIsTransactionalMinimalAndIdempotent():void
    {
        $propertyBefore=(int)$this->db->query('SELECT COUNT(*) FROM user_property_access')->fetch_row()[0];$assignmentBefore=(int)$this->db->query('SELECT COUNT(*) FROM employee_property_assignments')->fetch_row()[0];$categories=['admin'=>'Admin','finance'=>'Finance'];$config=ProtectedPrincipalConfig::fromArray(['user_public_id'=>$this->userPublic,'employee_public_id'=>$this->employeePublic,'required_categories'=>'admin'],$categories);$ids=new PublicIdGenerator();$service=new ProtectedPrincipalMaintenanceService($this->db,$config,new AuditService(new AuditRepository($this->db),$ids),$ids,new SystemClock(new DateTimeZone('UTC')));self::assertSame([],$service->proposedRepairs()['repairs']);$this->db->query("UPDATE users SET status='disabled',disabled_at=NOW() WHERE id={$this->userId}");$this->db->query("UPDATE employees SET employment_status='inactive' WHERE id={$this->employeeId}");$this->db->query("DELETE FROM user_category_access WHERE user_id={$this->userId} AND category='admin'");$proposal=$service->proposedRepairs();self::assertEqualsCanonicalizing(['reactivate_user','reactivate_employee','grant_category:admin'],$proposal['repairs']);self::assertCount(3,$service->repair()['repairs']);self::assertSame([],$service->proposedRepairs()['repairs']);self::assertSame([],$service->repair()['repairs']);self::assertSame('active',$this->db->query("SELECT status FROM users WHERE id={$this->userId}")->fetch_row()[0]);self::assertSame('active',$this->db->query("SELECT employment_status FROM employees WHERE id={$this->employeeId}")->fetch_row()[0]);self::assertSame(1,(int)$this->db->query("SELECT COUNT(*) FROM user_category_access WHERE user_id={$this->userId} AND category='admin'")->fetch_row()[0]);self::assertSame($propertyBefore,(int)$this->db->query('SELECT COUNT(*) FROM user_property_access')->fetch_row()[0]);self::assertSame($assignmentBefore,(int)$this->db->query('SELECT COUNT(*) FROM employee_property_assignments')->fetch_row()[0]);$audit=$this->db->query("SELECT event_type,after_data FROM audit_logs WHERE entity_public_id='".$this->db->real_escape_string($this->userPublic)."'")->fetch_assoc();self::assertSame('security.protected_principal_repaired',$audit['event_type']);foreach(['password','session_token','personal_email'] as $secret)self::assertStringNotContainsString($secret,(string)$audit['after_data']);
    }
}
