<?php
declare(strict_types=1);
use NpmGateway\Database\DatabaseProfiles;
use NpmGateway\Database\Migration\MigrationException;
use NpmGateway\Database\MySqlConnectionFactory;
use PHPUnit\Framework\TestCase;
final class StorageSystemCleanupActorIntegrationTest extends TestCase
{
 private mysqli $db;private object $migration;
 protected function setUp():void{if(getenv('RUN_DB_INTEGRATION_TESTS')!=='true')self::markTestSkipped('Set RUN_DB_INTEGRATION_TESTS=true with both profiles on npmgateway_test.');$app=require dirname(__DIR__,2).'/bootstrap/app.php';foreach(['application','migration'] as $profile)self::assertSame('npmgateway_test',DatabaseProfiles::load($profile,$app['root'])['database']);$this->db=MySqlConnectionFactory::connect(DatabaseProfiles::load('migration',$app['root']));$this->migration=require dirname(__DIR__,2).'/database/migrations/202608020011_storage_system_cleanup_actor.php';$this->clean();}
 protected function tearDown():void{if(isset($this->db)){$this->clean();try{$this->migration->up($this->db);}catch(Throwable){}$this->db->close();}}
 public function testInteractiveAndSystemDeletionAndRollbackGuard():void{$user=$this->user();$interactive=$this->temporary($user,'I');$system=$this->temporary($user,'S');$this->db->query("UPDATE storage_objects SET lifecycle_state='deleted',temporary_review_owner_user_id=NULL,deleted_at=NOW(),deleted_by_user_id={$user} WHERE id={$interactive}");$this->db->query("UPDATE storage_objects SET lifecycle_state='deleted',temporary_review_owner_user_id=NULL,deleted_at=NOW(),deleted_by_user_id=NULL WHERE id={$system}");$rows=$this->db->query('SELECT deleted_by_user_id FROM storage_objects ORDER BY id')->fetch_all(MYSQLI_NUM);self::assertSame($user,(int)$rows[0][0]);self::assertNull($rows[1][0]);try{$this->migration->down($this->db);self::fail('Rollback accepted system-deleted history.');}catch(MigrationException){self::addToAssertionCount(1);}self::assertSame(2,(int)$this->db->query('SELECT COUNT(*) FROM storage_objects')->fetch_row()[0]);$this->db->query('DELETE FROM storage_objects');$this->migration->down($this->db);$this->migration->up($this->db);}
 private function user():int{$employee=str_repeat('C',26);$this->db->query("INSERT INTO employees(public_id,employee_number,employee_class,first_name,last_name,job_title,employment_status,start_date) VALUES ('{$employee}','NPM900011','corporate','Cleanup','Actor','Tester','active','2026-08-02')");$employeeId=$this->db->insert_id;$hash=password_hash('test',PASSWORD_DEFAULT);$public=str_repeat('A',26);$s=$this->db->prepare("INSERT INTO users(public_id,employee_id,username,password_hash,status) VALUES (?,?,'cleanupactor',?,'active')");$s->bind_param('sis',$public,$employeeId,$hash);$s->execute();$id=$this->db->insert_id;$s->close();return $id;}
 private function temporary(int $user,string $suffix):int{$public=str_repeat($suffix,26);$sha=str_repeat($suffix==='I'?'a':'b',64);$key='company_notices/test/fixture_'.$suffix;$s=$this->db->prepare("INSERT INTO storage_objects(public_id,provider,provider_container,object_key,original_filename,display_filename,mime_type,byte_size,sha256_hex,lifecycle_state,uploaded_by_user_id,temporary_review_owner_user_id) VALUES (?,'wasabi','npmgateway',?,'fixture.txt','fixture.txt','text/plain',1,?,'temporary',?,?)");$s->bind_param('sssii',$public,$key,$sha,$user,$user);$s->execute();$id=$this->db->insert_id;$s->close();return $id;}
 private function clean():void{foreach(['notification_storage_objects','storage_objects','notification_recipients','notifications','user_category_access','audit_logs','employee_property_assignments','user_sessions','login_attempts','properties','users','employees'] as $table)$this->db->query("DELETE FROM {$table}");}
}
