<?php
declare(strict_types=1);
$escape=static fn(string $value):string=>htmlspecialchars($value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
$old=static fn(string $key,string $default=''):string=>(string)($input[$key]??$default);
$invalid=static fn(string $key):string=>isset($errors[$key])?' is-invalid':'';
$field=static function(string $key,string $label,string $type='text',string $attrs='',bool $required=true)use($escape,$old,$invalid,$errors,$input):void{
    $attrs.=match($key){'first_name'=>' data-username-source','username'=>' data-username-target'.(array_key_exists('username',$input)?' data-username-preserved':''),default=>''};
    ?><div class="col-md-6"><label class="form-label" for="employee-<?= $key ?>"><?= $escape($label) ?><?= $required?'':' <span class="form-text">(Optional)</span>' ?></label><input class="form-control<?= $invalid($key) ?>" id="employee-<?= $key ?>" name="<?= $key ?>" type="<?= $type ?>" value="<?= $escape($old($key)) ?>"<?= $required?' required':'' ?> <?= $attrs ?>><?php if(isset($errors[$key])):?><div class="invalid-feedback"><?= $escape((string)$errors[$key]) ?></div><?php endif;?></div><?php
};
?>
<form method="post" action="/human-resources/employees" class="gateway-property-form" novalidate>
<input type="hidden" name="_token" value="<?= $escape($csrfToken) ?>">
<?php if($errors!==[]):?><div class="alert gateway-alert gateway-alert--danger" role="alert"><strong>We could not create the employee.</strong><p class="mb-0">Review the highlighted fields and try again.</p></div><?php endif;?>
<section class="gateway-form-section"><h2 class="gateway-form-section-title">Employee Information</h2><div class="row gateway-form-grid">
<div class="col-md-6"><span class="form-label d-block">Employee Number</span><p>Generated automatically</p></div>
<?php $field('first_name','First Name','','autocomplete="given-name"');$field('last_name','Last Name','','autocomplete="family-name"');$field('job_title','Job Title'); ?>
<div class="col-md-6"><label class="form-label" for="employee-type">Employee Type</label><select class="form-select<?= $invalid('employee_type') ?>" id="employee-type" name="employee_type" required><option value="">Select type</option><?php foreach(['corporate'=>'Corporate','manager'=>'Manager','assistant_manager'=>'Assistant Manager'] as $value=>$label):?><option value="<?= $value ?>"<?= $old('employee_type')===$value?' selected':'' ?>><?= $label ?></option><?php endforeach;?></select><?php if(isset($errors['employee_type'])):?><div class="invalid-feedback"><?= $escape((string)$errors['employee_type']) ?></div><?php endif;?></div>
<div class="col-md-6"><label class="form-label" for="employee-status">Employment Status</label><select class="form-select" id="employee-status" name="employment_status" required><?php foreach(['active'=>'Active','inactive'=>'Inactive'] as $value=>$label):?><option value="<?= $value ?>"<?= $old('employment_status','active')===$value?' selected':'' ?>><?= $label ?></option><?php endforeach;?></select></div>
<?php $field('start_date','Start Date','date');$field('date_of_birth','Date of Birth','date'); ?>
</div></section>
<section class="gateway-form-section"><h2 class="gateway-form-section-title">Contact Information</h2><div class="row gateway-form-grid"><?php $field('company_phone','Company Phone','tel','inputmode="tel" autocomplete="tel" data-phone-mask maxlength="14"');$field('business_email','Business Email','email','autocomplete="email"');$field('personal_phone','Personal Phone','tel','inputmode="tel" autocomplete="tel" data-phone-mask maxlength="14"',false);$field('personal_email','Personal Email','email','autocomplete="email"',false);?></div></section>
<section class="gateway-form-section"><h2 class="gateway-form-section-title">Operational Context</h2><p id="corporate-context">Corporate employees use the protected Corporate context. Managers and Assistant Managers require an active community.</p><div class="row gateway-form-grid"><div class="col-12"><label class="form-label" for="employee-property">Primary Property</label><select class="form-select<?= $invalid('property_id') ?>" id="employee-property" name="property_id"><option value="">Corporate / select community</option><?php foreach($properties as $property):?><option value="<?= (int)$property['id'] ?>"<?= $old('property_id')===(string)$property['id']?' selected':'' ?>><?= $escape($property['display_name'].' ('.$property['property_code'].')') ?></option><?php endforeach;?></select><?php if($properties===[]):?><div class="form-text">No active community properties are available; Manager and Assistant Manager creation is blocked.</div><?php endif;?><?php if(isset($errors['property_id'])):?><div class="invalid-feedback"><?= $escape((string)$errors['property_id']) ?></div><?php endif;?></div></div></section>
<section class="gateway-form-section"><h2 class="gateway-form-section-title">Gateway Account</h2><div class="row gateway-form-grid"><?php $field('username','Gateway Username','','autocomplete="off"');?></div><div class="form-text">Generated from the employee’s first name. Change only when an alternate permanent username is required.</div><p>No password entry is required. Gateway securely generates the initial password.</p></section>
<section class="gateway-form-section"><h2 class="gateway-form-section-title">Employee Notes</h2><label class="form-label" for="employee-comments">Employee Notes <span class="form-text">(Optional)</span></label><textarea class="form-control<?= $invalid('comments') ?>" id="employee-comments" name="comments" rows="5" maxlength="65535"><?= $escape($old('comments')) ?></textarea><div class="form-text">Optional internal employment or operational notes visible only within authorized HR workflows.</div><?php if(isset($errors['comments'])):?><div class="invalid-feedback"><?= $escape((string)$errors['comments']) ?></div><?php endif;?></section>
<div class="gateway-form-actions"><a class="btn gateway-button gateway-button--secondary" href="/human-resources/employees">Cancel</a><button class="btn gateway-button gateway-button--primary" type="submit">Create Employee</button></div>
</form>
