<?php
declare(strict_types=1);
use NpmGateway\Database\Migration\MigrationInterface;
return new class implements MigrationInterface{
 public function up(mysqli $db):void{
  foreach(['credit_card_purchases','credit_card_purchase_receipts','credit_card_purchase_history'] as $t)if((int)$db->query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='{$t}'")->fetch_row()[0])throw new RuntimeException("{$t} already exists.");
  $db->query("CREATE TABLE credit_card_purchases(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(26) NOT NULL,property_id BIGINT UNSIGNED NOT NULL,card_last_four CHAR(4) NOT NULL,purchase_date DATE NOT NULL,amount DECIMAL(12,2) NOT NULL,purchased_by_employee_id BIGINT UNSIGNED NOT NULL,submitted_by_user_id BIGINT UNSIGNED NOT NULL,vendor VARCHAR(150) NOT NULL,description TEXT NOT NULL,receipt_status VARCHAR(20) NOT NULL,missing_receipt_reason TEXT NULL,status VARCHAR(20) NOT NULL DEFAULT 'posted',submitted_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY uq_cc_purchases_public(public_id),KEY idx_cc_purchases_property_date(property_id,purchase_date),KEY idx_cc_purchases_property_submitted(property_id,submitted_at),KEY idx_cc_purchases_match(card_last_four,purchase_date,amount),KEY idx_cc_purchases_receipt(receipt_status),KEY idx_cc_purchases_purchaser(purchased_by_employee_id),KEY idx_cc_purchases_submitter(submitted_by_user_id),KEY idx_cc_purchases_status(status),CONSTRAINT chk_cc_purchases_last_four CHECK(card_last_four REGEXP '^[0-9]{4}$'),CONSTRAINT chk_cc_purchases_amount CHECK(amount>0 AND amount<=9999999999.99),CONSTRAINT chk_cc_purchases_receipt CHECK(receipt_status IN ('missing','attached')),CONSTRAINT chk_cc_purchases_receipt_reason CHECK((receipt_status='missing' AND missing_receipt_reason IS NOT NULL) OR receipt_status='attached'),CONSTRAINT chk_cc_purchases_status CHECK(status IN ('posted','corrected','voided')),CONSTRAINT fk_cc_purchases_property FOREIGN KEY(property_id) REFERENCES properties(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT fk_cc_purchases_purchaser FOREIGN KEY(purchased_by_employee_id) REFERENCES employees(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT fk_cc_purchases_submitter FOREIGN KEY(submitted_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Property-scoped company credit card transactions; records are never deleted.'");
  $db->query("CREATE TABLE credit_card_purchase_receipts(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(26) NOT NULL,purchase_id BIGINT UNSIGNED NOT NULL,storage_object_id BIGINT UNSIGNED NOT NULL,uploaded_by_user_id BIGINT UNSIGNED NOT NULL,uploaded_at DATETIME NOT NULL,superseded_at DATETIME NULL,PRIMARY KEY(id),UNIQUE KEY uq_cc_receipts_public(public_id),UNIQUE KEY uq_cc_receipts_storage(storage_object_id),KEY idx_cc_receipts_purchase(purchase_id,uploaded_at),CONSTRAINT fk_cc_receipts_purchase FOREIGN KEY(purchase_id) REFERENCES credit_card_purchases(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT fk_cc_receipts_storage FOREIGN KEY(storage_object_id) REFERENCES storage_objects(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT fk_cc_receipts_uploader FOREIGN KEY(uploaded_by_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Private receipt metadata linked to Gateway storage objects.'");
  $db->query("CREATE TABLE credit_card_purchase_history(id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(26) NOT NULL,purchase_id BIGINT UNSIGNED NOT NULL,event_type VARCHAR(30) NOT NULL,actor_user_id BIGINT UNSIGNED NOT NULL,metadata JSON NULL,comments TEXT NULL,created_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY uq_cc_history_public(public_id),KEY idx_cc_history_purchase_created(purchase_id,created_at,id),CONSTRAINT chk_cc_history_event CHECK(event_type IN ('posted','receipt_uploaded','corrected','voided')),CONSTRAINT fk_cc_history_purchase FOREIGN KEY(purchase_id) REFERENCES credit_card_purchases(id) ON DELETE RESTRICT ON UPDATE RESTRICT,CONSTRAINT fk_cc_history_actor FOREIGN KEY(actor_user_id) REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Append-only credit card purchase lifecycle history.'");
 }
 public function down(mysqli $db):void{foreach(['credit_card_purchase_history','credit_card_purchase_receipts','credit_card_purchases'] as $t)if((int)$db->query("SELECT COUNT(*) FROM {$t}")->fetch_row()[0]>0)throw new RuntimeException('Cannot roll back Credit Card Purchases while business records exist.');$db->query('DROP TABLE credit_card_purchase_history');$db->query('DROP TABLE credit_card_purchase_receipts');$db->query('DROP TABLE credit_card_purchases');}
};
