<?php
declare(strict_types=1);
use NpmGateway\Database\Migration\MigrationInterface;
return new class implements MigrationInterface
{
 public function up(mysqli $db):void
 {
  foreach(['users','properties'] as $table){$exists=(int)$db->query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='{$table}'")->fetch_row()[0];if($exists!==1)throw new RuntimeException("Required table {$table} is missing.");}
  foreach(['application_reviews','application_review_history'] as $table)if((int)$db->query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='{$table}'")->fetch_row()[0]!==0)throw new RuntimeException("{$table} already exists.");
  if((int)$db->query("SELECT COUNT(*) FROM information_schema.COLLATIONS WHERE COLLATION_NAME='utf8mb4_0900_ai_ci'")->fetch_row()[0]!==1)throw new RuntimeException('Required utf8mb4 collation is unavailable.');
  $db->query("CREATE TABLE application_reviews (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(26) NOT NULL,property_id BIGINT UNSIGNED NOT NULL,prospect_name VARCHAR(200) NOT NULL,manager_comments TEXT NULL,rm_documents_confirmed TINYINT(1) NOT NULL,status VARCHAR(30) NOT NULL DEFAULT 'pending_review',submitted_by_user_id BIGINT UNSIGNED NOT NULL,submitted_at DATETIME NOT NULL,reviewed_by_user_id BIGINT UNSIGNED NULL,reviewed_at DATETIME NULL,reviewer_comments TEXT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY uq_application_reviews_public_id(public_id),KEY idx_application_reviews_status_submitted(status,submitted_at),KEY idx_application_reviews_property_submitted(property_id,submitted_at),KEY idx_application_reviews_submitter_submitted(submitted_by_user_id,submitted_at),KEY idx_application_reviews_reviewer_reviewed(reviewed_by_user_id,reviewed_at),KEY idx_application_reviews_queue(property_id,status,submitted_at),CONSTRAINT chk_application_reviews_status CHECK(status IN ('pending_review','approved','denied')),CONSTRAINT chk_application_reviews_rm_confirmed CHECK(rm_documents_confirmed=1),CONSTRAINT chk_application_reviews_review_state CHECK((status='pending_review' AND reviewed_by_user_id IS NULL AND reviewed_at IS NULL AND reviewer_comments IS NULL) OR (status IN ('approved','denied') AND reviewed_by_user_id IS NOT NULL AND reviewed_at IS NOT NULL AND reviewer_comments IS NOT NULL)),CONSTRAINT fk_application_reviews_property FOREIGN KEY(property_id) REFERENCES properties(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT fk_application_reviews_submitter FOREIGN KEY(submitted_by_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT fk_application_reviews_reviewer FOREIGN KEY(reviewed_by_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Property-scoped prospect application reviews.'");
  $db->query("CREATE TABLE application_review_history (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(26) NOT NULL,application_review_id BIGINT UNSIGNED NOT NULL,event_type VARCHAR(40) NOT NULL,from_status VARCHAR(30) NULL,to_status VARCHAR(30) NOT NULL,acted_by_user_id BIGINT UNSIGNED NOT NULL,comments TEXT NULL,created_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY uq_application_review_history_public_id(public_id),KEY idx_application_review_history_review_created(application_review_id,created_at,id),KEY idx_application_review_history_actor_created(acted_by_user_id,created_at),CONSTRAINT chk_application_review_history_event CHECK(event_type IN ('submitted','approved','denied')),CONSTRAINT chk_application_review_history_from_status CHECK(from_status IS NULL OR from_status IN ('pending_review','approved','denied')),CONSTRAINT chk_application_review_history_to_status CHECK(to_status IN ('pending_review','approved','denied')),CONSTRAINT fk_application_review_history_review FOREIGN KEY(application_review_id) REFERENCES application_reviews(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT fk_application_review_history_actor FOREIGN KEY(acted_by_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Append-only Application Review lifecycle history; application code exposes insert and read operations only.'");
 }
 public function down(mysqli $db):void
 {
  foreach(['application_review_history','application_reviews'] as $table){$exists=(int)$db->query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='{$table}'")->fetch_row()[0];if($exists&&((int)$db->query("SELECT COUNT(*) FROM {$table}")->fetch_row()[0])>0)throw new RuntimeException('Cannot roll back Application Reviews while business or history records exist.');}
  $db->query('DROP TABLE application_review_history');$db->query('DROP TABLE application_reviews');
 }
};
