<?php declare(strict_types=1);use NpmGateway\Database\Migration\{MigrationException,MigrationInterface};
return new class implements MigrationInterface{
 public function up(mysqli$db):void{
  foreach(['marketing_flyers']as$table)if($this->count($db,"SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='{$table}'")!==1)throw new MigrationException("Required table {$table} is missing.");
  if($this->count($db,"SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME IN ('marketing_flyer_notification_outbox','gateway_worker_heartbeats')")!==0)throw new MigrationException('Marketing Flyer outbox infrastructure already exists.');
  $db->query("CREATE TABLE marketing_flyer_notification_outbox (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(26) NOT NULL,flyer_id BIGINT UNSIGNED NULL,event_public_id CHAR(26) NOT NULL,event_type VARCHAR(16) NOT NULL,recipient_email VARCHAR(254) NOT NULL,idempotency_key CHAR(64) NOT NULL,status VARCHAR(16) NOT NULL DEFAULT 'pending',attempt_count TINYINT UNSIGNED NOT NULL DEFAULT 0,available_at DATETIME NOT NULL,claimed_at DATETIME NULL,claim_token CHAR(26) NULL,last_attempt_at DATETIME NULL,delivered_at DATETIME NULL,failed_at DATETIME NULL,last_failure_code VARCHAR(64) NULL,attachment_object_key VARCHAR(1024) NOT NULL,attachment_filename VARCHAR(255) NOT NULL,attachment_mime_type VARCHAR(32) NOT NULL,property_name VARCHAR(200) NOT NULL,flyer_month DATE NOT NULL,flyer_type VARCHAR(10) NOT NULL,uploaded_by_name VARCHAR(151) NOT NULL,uploaded_at DATETIME NOT NULL,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY uq_mfno_public_id(public_id),UNIQUE KEY uq_mfno_idempotency(idempotency_key),KEY idx_mfno_claim(status,available_at,claimed_at),KEY idx_mfno_flyer(flyer_id,status),KEY idx_mfno_event(event_public_id),CONSTRAINT fk_mfno_flyer FOREIGN KEY(flyer_id) REFERENCES marketing_flyers(id) ON UPDATE RESTRICT ON DELETE SET NULL,CONSTRAINT chk_mfno_event CHECK(event_type IN ('uploaded','replaced')),CONSTRAINT chk_mfno_status CHECK(status IN ('pending','processing','retry','delivered','failed','cancelled')),CONSTRAINT chk_mfno_type CHECK(flyer_type IN ('standard','promo'))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Durable recipient-specific Marketing Flyer notification deliveries.'");
  $db->query("CREATE TABLE gateway_worker_heartbeats (worker_name VARCHAR(100) NOT NULL,last_started_at DATETIME NULL,last_completed_at DATETIME NULL,last_success_at DATETIME NULL,last_exit_code SMALLINT NULL,last_processed_count INT UNSIGNED NOT NULL DEFAULT 0,updated_at DATETIME NOT NULL,PRIMARY KEY(worker_name)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Non-secret scheduled worker health metadata.'");
 }
 public function down(mysqli$db):void{if($this->count($db,"SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='marketing_flyer_notification_outbox'")===1&&$this->count($db,'SELECT COUNT(*) FROM marketing_flyer_notification_outbox')>0)throw new MigrationException('Cannot roll back Marketing Flyer notification outbox while delivery records exist.');$db->query('DROP TABLE IF EXISTS marketing_flyer_notification_outbox');$db->query('DROP TABLE IF EXISTS gateway_worker_heartbeats');}
 private function count(mysqli$db,string$sql):int{return(int)$db->query($sql)->fetch_row()[0];}
};
