<?php
declare(strict_types=1);
use NpmGateway\Database\Migration\MigrationException;
use NpmGateway\Database\Migration\MigrationInterface;
use NpmGateway\Database\Migration\StorageSystemCleanupActorSchema as Schema;
return new class implements MigrationInterface {
 public function up(mysqli $db):void{$this->assertClause($db,Schema::BEFORE);if($this->count($db,"SELECT COUNT(*) FROM storage_objects WHERE NOT (((lifecycle_state='temporary') AND temporary_review_owner_user_id IS NOT NULL AND published_at IS NULL AND deleted_at IS NULL AND deleted_by_user_id IS NULL) OR ((lifecycle_state='published') AND temporary_review_owner_user_id IS NULL AND published_at IS NOT NULL AND deleted_at IS NULL AND deleted_by_user_id IS NULL) OR ((lifecycle_state='deleted') AND temporary_review_owner_user_id IS NULL AND deleted_at IS NOT NULL))")>0)throw new MigrationException('Existing storage rows violate the approved cleanup lifecycle constraint.');$db->query("ALTER TABLE storage_objects DROP CHECK chk_storage_objects_lifecycle_metadata, ADD CONSTRAINT chk_storage_objects_lifecycle_metadata CHECK (((lifecycle_state='temporary') AND temporary_review_owner_user_id IS NOT NULL AND published_at IS NULL AND deleted_at IS NULL AND deleted_by_user_id IS NULL) OR ((lifecycle_state='published') AND temporary_review_owner_user_id IS NULL AND published_at IS NOT NULL AND deleted_at IS NULL AND deleted_by_user_id IS NULL) OR ((lifecycle_state='deleted') AND temporary_review_owner_user_id IS NULL AND deleted_at IS NOT NULL))");}
 public function down(mysqli $db):void{$this->assertClause($db,Schema::AFTER);if($this->count($db,"SELECT COUNT(*) FROM storage_objects WHERE lifecycle_state='deleted' AND deleted_by_user_id IS NULL")>0)throw new MigrationException('Cannot roll back Storage System Cleanup Actor while system-deleted storage history exists.');$db->query("ALTER TABLE storage_objects DROP CHECK chk_storage_objects_lifecycle_metadata, ADD CONSTRAINT chk_storage_objects_lifecycle_metadata CHECK (((lifecycle_state='temporary') AND temporary_review_owner_user_id IS NOT NULL AND published_at IS NULL AND deleted_at IS NULL AND deleted_by_user_id IS NULL) OR ((lifecycle_state='published') AND temporary_review_owner_user_id IS NULL AND published_at IS NOT NULL AND deleted_at IS NULL AND deleted_by_user_id IS NULL) OR ((lifecycle_state='deleted') AND temporary_review_owner_user_id IS NULL AND deleted_at IS NOT NULL AND deleted_by_user_id IS NOT NULL))");}
 private function assertClause(mysqli $db,string $expected):void{$s=$db->prepare("SELECT cc.CHECK_CLAUSE FROM information_schema.TABLE_CONSTRAINTS tc JOIN information_schema.CHECK_CONSTRAINTS cc ON cc.CONSTRAINT_SCHEMA=tc.CONSTRAINT_SCHEMA AND cc.CONSTRAINT_NAME=tc.CONSTRAINT_NAME WHERE tc.CONSTRAINT_SCHEMA=DATABASE() AND tc.TABLE_NAME='storage_objects' AND tc.CONSTRAINT_NAME='chk_storage_objects_lifecycle_metadata' AND tc.CONSTRAINT_TYPE='CHECK'");$s->execute();$clause=$s->get_result()->fetch_row()[0]??null;$s->close();if(!is_string($clause)||Schema::normalize($clause)!==Schema::normalize($expected))throw new MigrationException('Gateway Storage lifecycle constraint differs from the expected schema.');}
 private function count(mysqli $db,string $sql):int{return (int)$db->query($sql)->fetch_row()[0];}
};
