<?php
declare(strict_types=1);
use NpmGateway\Database\Migration\MigrationException;
use NpmGateway\Database\Migration\MigrationInterface;
return new class implements MigrationInterface {
 public function up(mysqli $db):void{
  foreach(['users','properties','user_category_access'] as $t)if($this->count($db,"SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='{$t}'")!==1)throw new MigrationException("Required table {$t} is missing.");
  foreach(['rm_audits','rm_audit_history'] as $t)if($this->count($db,"SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='{$t}'")!==0)throw new MigrationException("{$t} already exists.");
  $db->query("ALTER TABLE user_category_access DROP CHECK chk_user_category_access_category, ADD CONSTRAINT chk_user_category_access_category CHECK (category IN ('operations','finance','human-resources','company-notices','application-reviews','rm-corrections','rm-audit','marketing','admin','credit-cards'))");
  $db->query("CREATE TABLE rm_audits (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(26) NOT NULL,property_id BIGINT UNSIGNED NOT NULL,tenant_name VARCHAR(200) NOT NULL,unit_identifier VARCHAR(100) NOT NULL,audit_findings_html MEDIUMTEXT NOT NULL,audit_findings_text TEXT NOT NULL,status VARCHAR(20) NOT NULL DEFAULT 'open',submitted_by_user_id BIGINT UNSIGNED NOT NULL,submitted_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,completed_by_user_id BIGINT UNSIGNED NULL,completed_at DATETIME NULL,PRIMARY KEY(id),UNIQUE KEY uq_rm_audits_public_id(public_id),KEY idx_rm_audits_property_status_updated(property_id,status,updated_at),KEY idx_rm_audits_status_updated(status,updated_at),CONSTRAINT chk_rm_audits_status CHECK(status IN ('open','completed','returned')),CONSTRAINT fk_rm_audits_property FOREIGN KEY(property_id) REFERENCES properties(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT fk_rm_audits_submitter FOREIGN KEY(submitted_by_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT fk_rm_audits_completer FOREIGN KEY(completed_by_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Property-scoped Rent Manager tenant-file audits.'");
  $db->query("CREATE TABLE rm_audit_history (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(26) NOT NULL,rm_audit_id BIGINT UNSIGNED NOT NULL,event_type VARCHAR(20) NOT NULL,actor_user_id BIGINT UNSIGNED NOT NULL,comments TEXT NULL,created_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY uq_rm_audit_history_public_id(public_id),KEY idx_rm_audit_history_audit_created(rm_audit_id,created_at,id),CONSTRAINT chk_rm_audit_history_event CHECK(event_type IN ('submitted','completed','returned')),CONSTRAINT fk_rm_audit_history_audit FOREIGN KEY(rm_audit_id) REFERENCES rm_audits(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT fk_rm_audit_history_actor FOREIGN KEY(actor_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Append-only RM Audit lifecycle history.'");
 }
 public function down(mysqli $db):void{foreach(['rm_audit_history','rm_audits'] as$t)if($this->count($db,"SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='{$t}'")===1&&$this->count($db,"SELECT COUNT(*) FROM {$t}")>0)throw new MigrationException('Cannot roll back RM Audits while business records exist.');if($this->count($db,"SELECT COUNT(*) FROM user_category_access WHERE category='rm-audit'")>0)throw new MigrationException('Cannot roll back RM Audit while category memberships exist.');$db->query('DROP TABLE IF EXISTS rm_audit_history');$db->query('DROP TABLE IF EXISTS rm_audits');$db->query("ALTER TABLE user_category_access DROP CHECK chk_user_category_access_category, ADD CONSTRAINT chk_user_category_access_category CHECK (category IN ('operations','finance','human-resources','company-notices','application-reviews','rm-corrections','marketing','admin','credit-cards'))");}
 private function count(mysqli$db,string$sql):int{return(int)$db->query($sql)->fetch_row()[0];}
};
