<?php
declare(strict_types=1);
use NpmGateway\Database\Migration\MigrationException;
use NpmGateway\Database\Migration\MigrationInterface;
return new class implements MigrationInterface {
 public function up(mysqli $db):void
 {
  foreach(['users','properties','user_category_access'] as $t)if($this->count($db,"SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='{$t}'")!==1)throw new MigrationException("Required table {$t} is missing.");
  foreach(['rm_correction_requests','rm_correction_history'] as $t)if($this->count($db,"SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='{$t}'")!==0)throw new MigrationException("{$t} already exists.");
  $db->query("ALTER TABLE user_category_access DROP CHECK chk_user_category_access_category, ADD CONSTRAINT chk_user_category_access_category CHECK (category IN ('operations','finance','human-resources','company-notices','application-reviews','rm-corrections','marketing','admin','credit-cards'))");
  $db->query("CREATE TABLE rm_correction_requests (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(26) NOT NULL,property_id BIGINT UNSIGNED NOT NULL,submitted_by_user_id BIGINT UNSIGNED NOT NULL,lot_address VARCHAR(200) NOT NULL,tenant_name VARCHAR(200) NOT NULL,correction_request TEXT NOT NULL,status VARCHAR(32) NOT NULL DEFAULT 'pending_review',submitted_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,reviewed_by_user_id BIGINT UNSIGNED NULL,reviewed_at DATETIME NULL,PRIMARY KEY(id),UNIQUE KEY uq_rm_correction_requests_public_id(public_id),KEY idx_rm_corrections_property_status_updated(property_id,status,updated_at),KEY idx_rm_corrections_status_updated(status,updated_at),KEY idx_rm_corrections_submitter(submitted_by_user_id,submitted_at),CONSTRAINT chk_rm_corrections_status CHECK(status IN ('pending_review','approved','denied','more_information_needed')),CONSTRAINT fk_rm_corrections_property FOREIGN KEY(property_id) REFERENCES properties(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT fk_rm_corrections_submitter FOREIGN KEY(submitted_by_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT fk_rm_corrections_reviewer FOREIGN KEY(reviewed_by_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Immutable property-scoped Rent Manager correction requests.'");
  $db->query("CREATE TABLE rm_correction_history (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(26) NOT NULL,rm_correction_request_id BIGINT UNSIGNED NOT NULL,event_type VARCHAR(40) NOT NULL,actor_user_id BIGINT UNSIGNED NOT NULL,comments TEXT NULL,created_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY uq_rm_correction_history_public_id(public_id),KEY idx_rm_correction_history_request_created(rm_correction_request_id,created_at,id),KEY idx_rm_correction_history_actor_created(actor_user_id,created_at),CONSTRAINT chk_rm_correction_history_event CHECK(event_type IN ('submitted','approved','denied','more_information_needed','manager_responded')),CONSTRAINT fk_rm_correction_history_request FOREIGN KEY(rm_correction_request_id) REFERENCES rm_correction_requests(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT fk_rm_correction_history_actor FOREIGN KEY(actor_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Append-only RM Correction lifecycle history.'");
 }
 public function down(mysqli $db):void
 {
  foreach(['rm_correction_history','rm_correction_requests'] as $t)if($this->count($db,"SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='{$t}'")===1&&$this->count($db,"SELECT COUNT(*) FROM {$t}")>0)throw new MigrationException('Cannot roll back RM Corrections while business records exist.');
  if($this->count($db,"SELECT COUNT(*) FROM user_category_access WHERE category='rm-corrections'")>0)throw new MigrationException('Cannot roll back RM Corrections while category memberships exist.');
  $db->query('DROP TABLE IF EXISTS rm_correction_history');$db->query('DROP TABLE IF EXISTS rm_correction_requests');
  $db->query("ALTER TABLE user_category_access DROP CHECK chk_user_category_access_category, ADD CONSTRAINT chk_user_category_access_category CHECK (category IN ('operations','finance','human-resources','company-notices','application-reviews','marketing','admin','credit-cards'))");
 }
 private function count(mysqli $db,string $sql):int{return (int)$db->query($sql)->fetch_row()[0];}
};
