<?php
declare(strict_types=1);
use NpmGateway\Database\Migration\{MigrationException,MigrationInterface,ZillowComSchema};
return new class implements MigrationInterface
{
 public function up(mysqli$db):void
 {
  foreach(ZillowComSchema::TABLES as$table)if($this->tables($db,$table)!==0)throw new MigrationException("{$table} already exists.");$properties=[];foreach(ZillowComSchema::MAPPINGS as$source=>$code){$s=$db->prepare("SELECT id FROM properties WHERE property_code=? AND status='active'");$s->bind_param('s',$code);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();if(count($rows)!==1)throw new MigrationException("Zillow.com mapping property {$code} is missing or inactive.");$properties[$source]=(int)$rows[0]['id'];}
  $db->query("CREATE TABLE zillow_imports (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(26) NOT NULL,original_filename VARCHAR(255) NOT NULL,file_sha256 CHAR(64) NOT NULL,uploaded_by_user_id BIGINT UNSIGNED NOT NULL,source_started_at DATETIME NOT NULL,source_ended_at DATETIME NOT NULL,total_lead_count INT UNSIGNED NOT NULL,phone_lead_count INT UNSIGNED NOT NULL,email_lead_count INT UNSIGNED NOT NULL,imported_at DATETIME NOT NULL,created_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY uq_zillow_imports_public_id(public_id),UNIQUE KEY uq_zillow_imports_file_sha256(file_sha256),KEY idx_zillow_imports_imported(imported_at),CONSTRAINT fk_zillow_imports_uploader FOREIGN KEY(uploaded_by_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT chk_zillow_imports_dates CHECK(source_ended_at>=source_started_at),CONSTRAINT chk_zillow_imports_counts CHECK(total_lead_count=phone_lead_count+email_lead_count)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
  $db->query("CREATE TABLE zillow_property_mappings (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(26) NOT NULL,source_listing_name VARCHAR(150) NOT NULL,property_id BIGINT UNSIGNED NOT NULL,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY uq_zillow_mappings_public_id(public_id),UNIQUE KEY uq_zillow_mappings_source_name(source_listing_name),KEY idx_zillow_mappings_property(property_id),CONSTRAINT fk_zillow_mappings_property FOREIGN KEY(property_id) REFERENCES properties(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT chk_zillow_mappings_active CHECK(active IN(0,1))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
  $db->query("CREATE TABLE zillow_leads (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(26) NOT NULL,import_id BIGINT UNSIGNED NOT NULL,property_id BIGINT UNSIGNED NOT NULL,source_listing_name VARCHAR(150) NOT NULL,occurred_at DATETIME NOT NULL,lead_type VARCHAR(10) NOT NULL,prospect_name VARCHAR(200) NULL,prospect_email VARCHAR(320) NULL,prospect_phone_raw VARCHAR(100) NULL,prospect_phone_normalized CHAR(10) NULL,created_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY uq_zillow_leads_public_id(public_id),KEY idx_zillow_leads_property_occurred(property_id,occurred_at),KEY idx_zillow_leads_occurred(occurred_at),KEY idx_zillow_leads_type_occurred(lead_type,occurred_at),KEY idx_zillow_leads_import(import_id),CONSTRAINT fk_zillow_leads_import FOREIGN KEY(import_id) REFERENCES zillow_imports(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT fk_zillow_leads_property FOREIGN KEY(property_id) REFERENCES properties(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT chk_zillow_leads_type CHECK(lead_type IN('phone','email')),CONSTRAINT chk_zillow_leads_phone CHECK(prospect_phone_normalized IS NULL OR prospect_phone_normalized REGEXP '^[0-9]{10}$')) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
  $now=(new DateTimeImmutable('now',new DateTimeZone('UTC')))->format('Y-m-d H:i:s');$s=$db->prepare('INSERT INTO zillow_property_mappings(public_id,source_listing_name,property_id,active,created_at,updated_at) VALUES(?,?,?,1,?,?)');$i=0;foreach($properties as$source=>$property){$public='01K3NPMZILMAPPING'.str_pad((string)++$i,9,'0',STR_PAD_LEFT);$s->bind_param('ssiss',$public,$source,$property,$now,$now);$s->execute();}$s->close();
 }
 public function down(mysqli$db):void{if($this->tables($db,'zillow_imports')===1&&(int)$db->query('SELECT COUNT(*) FROM zillow_imports')->fetch_row()[0]>0)throw new MigrationException('Cannot roll back Zillow.com while imported records exist.');$db->query('DROP TABLE IF EXISTS zillow_leads');$db->query('DROP TABLE IF EXISTS zillow_property_mappings');$db->query('DROP TABLE IF EXISTS zillow_imports');}
 private function tables(mysqli$db,string$table):int{$s=$db->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$s->bind_param('s',$table);$s->execute();$count=(int)$s->get_result()->fetch_row()[0];$s->close();return$count;}
};
