<?php
declare(strict_types=1);
use NpmGateway\Database\Migration\MigrationInterface;
return new class implements MigrationInterface
{
 public function up(mysqli $db):void
 {
  foreach(['users','properties'] as $table){$s=$db->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$s->bind_param('s',$table);$s->execute();$exists=(int)$s->get_result()->fetch_row()[0];$s->close();if($exists!==1)throw new RuntimeException("Required table {$table} is missing.");$s=$db->prepare("SELECT COUNT(*) FROM information_schema.STATISTICS WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=? AND INDEX_NAME='PRIMARY' AND COLUMN_NAME='id'");$s->bind_param('s',$table);$s->execute();$primary=(int)$s->get_result()->fetch_row()[0];$s->close();if($primary!==1)throw new RuntimeException("Required primary key {$table}.id is missing.");}
  $exists=(int)$db->query("SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME='user_property_access'")->fetch_row()[0];if($exists!==0)throw new RuntimeException('user_property_access already exists.');
  $collation=(int)$db->query("SELECT COUNT(*) FROM information_schema.COLLATIONS WHERE COLLATION_NAME='utf8mb4_0900_ai_ci'")->fetch_row()[0];if($collation!==1)throw new RuntimeException('Required utf8mb4 collation is unavailable.');
  $db->query("CREATE TABLE user_property_access (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(26) NOT NULL,user_id BIGINT UNSIGNED NOT NULL,property_id BIGINT UNSIGNED NOT NULL,granted_by_user_id BIGINT UNSIGNED NOT NULL,granted_at DATETIME NOT NULL,updated_by_user_id BIGINT UNSIGNED NULL,updated_at DATETIME NULL,PRIMARY KEY(id),UNIQUE KEY uq_user_property_access_public_id(public_id),UNIQUE KEY uq_user_property_access_user_property(user_id,property_id),KEY idx_user_property_access_property(property_id),KEY idx_user_property_access_granted_by(granted_by_user_id),KEY idx_user_property_access_updated_by(updated_by_user_id),CONSTRAINT fk_user_property_access_user FOREIGN KEY(user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT fk_user_property_access_property FOREIGN KEY(property_id) REFERENCES properties(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT fk_user_property_access_granted_by FOREIGN KEY(granted_by_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT fk_user_property_access_updated_by FOREIGN KEY(updated_by_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='Explicit current property authorization for Gateway users.'");
 }
 public function down(mysqli $db):void{$count=(int)$db->query('SELECT COUNT(*) FROM user_property_access')->fetch_row()[0];if($count>0)throw new RuntimeException('Cannot roll back Property Access while access rows exist; dropping the table would destroy active authorization records.');$db->query('DROP TABLE user_property_access');}
};
