<?php
declare(strict_types=1);
use NpmGateway\Database\Migration\{ApartmentsComSchema,MigrationException,MigrationInterface};
return new class implements MigrationInterface
{
 public function up(mysqli$db):void
 {
  foreach(ApartmentsComSchema::TABLES as$table)if($this->tables($db,$table)!==0)throw new MigrationException("{$table} already exists.");$properties=[];foreach(ApartmentsComSchema::MAPPINGS as$source=>$code){$s=$db->prepare("SELECT id FROM properties WHERE property_code=? AND status='active'");$s->bind_param('s',$code);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();if(count($rows)!==1)throw new MigrationException("Apartments.com mapping property {$code} is missing or inactive.");$properties[$source]=(int)$rows[0]['id'];}
  $db->query("CREATE TABLE apartments_imports (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(26) NOT NULL,original_filename VARCHAR(255) NOT NULL,file_sha256 CHAR(64) NOT NULL,uploaded_by_user_id BIGINT UNSIGNED NOT NULL,source_started_at DATETIME NOT NULL,source_ended_at DATETIME NOT NULL,phone_call_count INT UNSIGNED NOT NULL,email_lead_count INT UNSIGNED NOT NULL,imported_at DATETIME NOT NULL,created_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY uq_apartments_imports_public_id(public_id),UNIQUE KEY uq_apartments_imports_file_sha256(file_sha256),KEY idx_apartments_imports_imported(imported_at),CONSTRAINT fk_apartments_imports_uploader FOREIGN KEY(uploaded_by_user_id) REFERENCES users(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT chk_apartments_imports_dates CHECK(source_ended_at>=source_started_at)) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
  $db->query("CREATE TABLE apartments_property_mappings (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(26) NOT NULL,source_property_name VARCHAR(150) NOT NULL,property_id BIGINT UNSIGNED NOT NULL,active TINYINT(1) NOT NULL DEFAULT 1,created_at DATETIME NOT NULL,updated_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY uq_apartments_mappings_public_id(public_id),UNIQUE KEY uq_apartments_mappings_source_name(source_property_name),KEY idx_apartments_mappings_property(property_id),CONSTRAINT fk_apartments_mappings_property FOREIGN KEY(property_id) REFERENCES properties(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT chk_apartments_mappings_active CHECK(active IN(0,1))) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
  $db->query("CREATE TABLE apartments_calls (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(26) NOT NULL,import_id BIGINT UNSIGNED NOT NULL,property_id BIGINT UNSIGNED NOT NULL,occurred_at DATETIME NOT NULL,caller_phone_raw VARCHAR(100) NOT NULL,caller_phone_normalized VARCHAR(16) NULL,ring_to_number_raw VARCHAR(100) NOT NULL,ring_to_number_normalized VARCHAR(16) NULL,tracking_number_raw VARCHAR(100) NOT NULL,tracking_number_normalized VARCHAR(16) NULL,call_duration_seconds INT UNSIGNED NOT NULL,call_recording_value VARCHAR(100) NULL,status VARCHAR(50) NOT NULL,created_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY uq_apartments_calls_public_id(public_id),KEY idx_apartments_calls_property_occurred(property_id,occurred_at),KEY idx_apartments_calls_occurred(occurred_at),KEY idx_apartments_calls_import(import_id),CONSTRAINT fk_apartments_calls_import FOREIGN KEY(import_id) REFERENCES apartments_imports(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT fk_apartments_calls_property FOREIGN KEY(property_id) REFERENCES properties(id) ON UPDATE RESTRICT ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
  $db->query("CREATE TABLE apartments_email_leads (id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,public_id CHAR(26) NOT NULL,import_id BIGINT UNSIGNED NOT NULL,property_id BIGINT UNSIGNED NOT NULL,occurred_at DATETIME NOT NULL,renter_name VARCHAR(200) NOT NULL,renter_phone_raw VARCHAR(100) NULL,renter_phone_normalized VARCHAR(16) NULL,renter_email VARCHAR(320) NOT NULL,created_at DATETIME NOT NULL,PRIMARY KEY(id),UNIQUE KEY uq_apartments_email_leads_public_id(public_id),KEY idx_apartments_email_leads_property_occurred(property_id,occurred_at),KEY idx_apartments_email_leads_occurred(occurred_at),KEY idx_apartments_email_leads_import(import_id),CONSTRAINT fk_apartments_email_leads_import FOREIGN KEY(import_id) REFERENCES apartments_imports(id) ON UPDATE RESTRICT ON DELETE RESTRICT,CONSTRAINT fk_apartments_email_leads_property FOREIGN KEY(property_id) REFERENCES properties(id) ON UPDATE RESTRICT ON DELETE RESTRICT) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci");
  $now=(new DateTimeImmutable('now',new DateTimeZone('UTC')))->format('Y-m-d H:i:s');$s=$db->prepare('INSERT INTO apartments_property_mappings(public_id,source_property_name,property_id,active,created_at,updated_at) VALUES(?,?,?,1,?,?)');$i=0;foreach($properties as$source=>$property){$public='01K2NPMAPTMAPPING'.str_pad((string)++$i,9,'0',STR_PAD_LEFT);$s->bind_param('ssiss',$public,$source,$property,$now,$now);$s->execute();}$s->close();
 }
 public function down(mysqli$db):void{if($this->tables($db,'apartments_imports')===1&&(int)$db->query('SELECT COUNT(*) FROM apartments_imports')->fetch_row()[0]>0)throw new MigrationException('Cannot roll back Apartments.com while imported records exist.');$db->query('DROP TABLE IF EXISTS apartments_email_leads');$db->query('DROP TABLE IF EXISTS apartments_calls');$db->query('DROP TABLE IF EXISTS apartments_property_mappings');$db->query('DROP TABLE IF EXISTS apartments_imports');}
 private function tables(mysqli$db,string$table):int{$s=$db->prepare('SELECT COUNT(*) FROM information_schema.TABLES WHERE TABLE_SCHEMA=DATABASE() AND TABLE_NAME=?');$s->bind_param('s',$table);$s->execute();$count=(int)$s->get_result()->fetch_row()[0];$s->close();return$count;}
};
