<?php
declare(strict_types=1);
$components=dirname(__DIR__).'/components';$escape=static fn(string $v):string=>htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');$criteria=$directoryPage->criteria;
ob_start();$breadcrumbItems=[['label'=>'Dashboard','url'=>'/dashboard']];if($hr)$breadcrumbItems[]=['label'=>'Human Resources','url'=>'/human-resources'];$breadcrumbItems[]=['label'=>$hr?'HR Properties':'Properties','current'=>true];require $components.'/breadcrumb.php';
$heading=$hr?'HR Properties':'Properties';$description=$hr?'Manage company property records and operational contact information.':'View company property contact and operational information.';$eyebrow=$hr?'Human Resources':'Universal Tools';$actionsHtml=$hr?'<a class="btn gateway-button gateway-button--primary" href="/human-resources/properties/create">Add Property</a>':'';require $components.'/page-header.php';
if($success!==''): ?><div class="alert gateway-alert gateway-alert--success" role="status"><?= $escape($success) ?></div><?php endif; ?>
<form class="gateway-directory-toolbar" method="get" action="<?= $hr?'/human-resources/properties':'/properties' ?>"><div class="gateway-directory-search"><label class="form-label" for="property-search">Search properties</label><div class="gateway-directory-search__controls"><input class="form-control form-control-lg" id="property-search" name="search" value="<?= $escape($criteria->search) ?>" placeholder="PropID, name, address, phone, IVR, or manager"><button class="btn gateway-button gateway-button--primary" type="submit">Search</button></div></div><div class="gateway-directory-filters"><div><label class="form-label" for="property-sort">Sort by</label><select class="form-select" id="property-sort" name="sort"><?php foreach(['prop_id'=>'PropID','name'=>'Name','address'=>'Address','phone'=>'Phone','ivr'=>'IVR','manager'=>'Manager'] as $value=>$label): ?><option value="<?= $value ?>"<?= $criteria->sort===$value?' selected':'' ?>><?= $label ?></option><?php endforeach; ?></select></div></div><input type="hidden" name="direction" value="<?= $escape($criteria->direction) ?>"><div class="gateway-directory-toolbar__actions"><button class="btn gateway-button gateway-button--secondary">Apply</button><a class="btn gateway-button gateway-button--secondary" href="<?= $hr?'/human-resources/properties':'/properties' ?>">Clear</a></div></form>
<div class="gateway-directory-result-count"><h2><?= $directoryPage->totalResults ?> propert<?= $directoryPage->totalResults===1?'y':'ies' ?></h2><p>Sorted by PropID ascending by default.</p></div>
<?php require $components.'/property-table.php';
$contentHtml=(string)ob_get_clean();$pageTitle=($hr?'HR Properties':'Properties').' — NPM Gateway';$navbarItems=\NpmGateway\Support\Navigation::forRoute($hr?'/human-resources/properties':'/properties',dirname(__DIR__,3));$navbarUserLabel=$user->displayName;$navbarUserContext='@'.$user->username;require dirname(__DIR__).'/layouts/app.php';
