<?php
declare(strict_types=1);
$escape=static fn(mixed $v):string=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');$labels=['employee_name'=>'Employee Name','job_title'=>'Job Title','start_date'=>'Start Date','company_phone'=>'Company Phone','business_email'=>'Business Email','primary_property'=>'Primary Property'];$attachments=array_values(array_filter((array)($notice['assets']??[]),fn($asset)=>($asset['asset_role']??'')==='attachment'));$companyBody=(string)($displayPayload['rich_message_html']??'<p>'.$escape($displayPayload['message']??'').'</p>');foreach((array)($notice['assets']??[]) as $asset)if(($asset['asset_role']??'')==='embedded_image')$companyBody=str_replace('gateway-storage:'.$asset['public_id'],'/storage/'.$asset['public_id'].'/image',$companyBody);$companyBody=(new \NpmGateway\Services\RichTextSanitizer())->renderImageWidths($companyBody);ob_start();
?>
<p><a href="/notifications">← Notifications</a></p><header class="mb-4"><p class="gateway-eyebrow">NPM GATEWAY</p><h1 class="gateway-page-header__title"><?= $escape($notice['title']) ?></h1><p class="gateway-page-header__description"><?= $escape($notice['summary']) ?></p></header>
<section class="gateway-card gateway-notification-detail"><div class="gateway-card__body">
<?php if($notice['notification_type']==='company_notice'): ?>
 <div class="gateway-notice-rich-body"><?= $companyBody ?></div>
 <dl class="mt-4"><dt>Published by</dt><dd><?= $escape($displayPayload['published_by_name']??'') ?></dd><dt>Published</dt><dd><?= $escape(\NpmGateway\Support\CompanyNoticePresentation::publishedAt((string)$notice['published_at'])) ?></dd><dt>Priority</dt><dd><?= $escape(ucfirst((string)$notice['priority'])) ?></dd></dl>
 <?php if($attachments): ?><section aria-labelledby="recipient-attachments-heading"><h2 id="recipient-attachments-heading"><?php require dirname(__DIR__).'/components/icon-paperclip.php'; ?> <?= $escape(\NpmGateway\Support\CompanyNoticePresentation::attachmentHeading(count($attachments))) ?></h2><ul class="list-unstyled"><?php foreach($attachments as $asset): ?><li class="mb-3"><strong><?= $escape($asset['display_filename']) ?></strong><br><span class="text-secondary"><?= $escape(\NpmGateway\Support\CompanyNoticePresentation::typeLabel($asset)) ?> · <?= $escape(\NpmGateway\Support\CompanyNoticePresentation::fileSize((int)$asset['byte_size'])) ?></span><br><a href="/storage/<?= $escape($asset['public_id']) ?>" aria-label="Download <?= $escape($asset['display_filename']) ?>">Download</a></li><?php endforeach; ?></ul></section><?php endif; ?>
<?php else: ?><dl class="mb-0"><?php foreach($labels as $key=>$label): ?><div class="row py-3 border-bottom"><dt class="col-sm-4"><?= $label ?></dt><dd class="col-sm-8 mb-0"><?php if($key==='business_email'&&filter_var($displayPayload[$key]??'',FILTER_VALIDATE_EMAIL)!==false): ?><a href="mailto:<?= $escape($displayPayload[$key]) ?>"><?= $escape($displayPayload[$key]) ?></a><?php else: ?><?= $escape($displayPayload[$key]??'') ?><?php endif; ?></dd></div><?php endforeach; ?></dl><?php endif; ?>
</div></section>
<?php if($notice['notification_type']!=='company_notice'): ?><p class="mt-4 text-secondary">Published <?= $escape(\NpmGateway\Support\CompanyNoticePresentation::publishedAt((string)$notice['published_at'])) ?> · Priority: <?= $escape(ucfirst((string)$notice['priority'])) ?></p><?php endif; ?>
<?php if((int)$notice['requires_acknowledgment']===0): ?><p class="mt-3"><strong>No acknowledgment required</strong></p><?php elseif($notice['acknowledged_at']===null): ?><form class="mt-3" method="post" action="/notifications/<?= $escape($notice['public_id']) ?>/acknowledge"><input type="hidden" name="_token" value="<?= $escape($csrfToken) ?>"><button class="btn btn-primary" type="submit">I Have Read This Notice</button></form><?php else: ?><p class="mt-3"><strong>Acknowledged <?= $escape((new DateTimeImmutable($notice['acknowledged_at']))->format('F j, Y \a\t g:i A')) ?></strong></p><?php endif; ?>
<?php $contentHtml=(string)ob_get_clean();$pageTitle=$notice['title'].' — NPM Gateway';$navbarItems=\NpmGateway\Support\Navigation::forRoute('/notifications',dirname(__DIR__,3));$navbarUserLabel=$user->displayName;$navbarUserContext='@'.$user->username;$footerText='NPM Gateway — Internal use only';require dirname(__DIR__).'/layouts/app.php';
