<?php
declare(strict_types=1);
namespace NpmGateway\Http\Controllers;
use NpmGateway\Contracts\CorporateToolsProviderInterface;
use NpmGateway\Http\AuthenticatedRequestContext;
use NpmGateway\Http\Request;
use NpmGateway\Http\Response;
use NpmGateway\Security\CsrfService;
use NpmGateway\Services\CategoryAccessAdministrationService;
use NpmGateway\Services\CategoryAccessPayloadParser;
use NpmGateway\Services\CorporateAccessService;
use NpmGateway\Services\PropertyAccessService;
use NpmGateway\Services\PropertyAccessPayloadParser;
use NpmGateway\Services\CallLogAccessPolicy;
use NpmGateway\Support\FlashSession;
use NpmGateway\ValueObjects\ToolCard;
final class AdminController
{
    public function __construct(private readonly CorporateAccessService $access,private readonly CategoryAccessAdministrationService $administration,private readonly CategoryAccessPayloadParser $payloads,private readonly CorporateToolsProviderInterface $tools,private readonly CsrfService $csrf,private readonly FlashSession $flash,private readonly string $views,private readonly ?PropertyAccessService $propertyAccess=null,private readonly ?PropertyAccessPayloadParser $propertyPayloads=null,private readonly ?CallLogAccessPolicy $callLogs=null){}
    public function index(AuthenticatedRequestContext $context):Response{if(!$this->allowed($context))return new Response(403,'Forbidden');$user=$context->user;$logoutCsrfToken=$this->csrf->token();$navbarCorporateItems=$this->tools->tools($context);$cards=[new ToolCard('category-access','Category Access','Manage access to Corporate Gateway categories.','Administration','Manage access','/admin/category-access',true,10,null,null,'admin.category-access.index'),new ToolCard('property-access','Property Access','Control which communities each Gateway user may access.','Administration','Manage access','/corporate/admin/property-access',true,20,null,null,'admin.property-access.index')];if($this->callLogs?->allows($context->user)){$cards[]=new ToolCard('call-logs','Call Logs','Import and review Lumen IVR call activity.','Administration','Open Call Logs','/admin/call-logs',true,30,null,null,'admin.call-logs.index');$cards[]=new ToolCard('call-log-reports','Call Log Reports','Reporting and analysis of imported Lumen call activity.','Administration','Open Reports','/admin/call-log-reports',true,40,null,null,'admin.call-log-reports.index');}ob_start();require $this->views.'/admin/index.php';return new Response(200,(string)ob_get_clean());}
    public function categoryAccess(AuthenticatedRequestContext $context):Response{if(!$this->allowed($context))return new Response(403,'Forbidden');$user=$context->user;$logoutCsrfToken=$this->csrf->token();$csrfToken=$this->csrf->token();$navbarCorporateItems=$this->tools->tools($context);$matrix=$this->administration->matrix();$error=(string)$this->flash->pull('admin_access_error','');$success=(string)$this->flash->pull('admin_access_success','');ob_start();require $this->views.'/admin/category-access.php';return new Response(200,(string)ob_get_clean());}
    public function save(Request $request,AuthenticatedRequestContext $context):Response{if(!$this->allowed($context))return new Response(403,'Forbidden');if(!$this->csrf->valid($request->post['_token']??null))return new Response(419,'Invalid request.');try{$changes=$this->administration->applyChanges($this->payloads->parse($request->post),$context->user);$this->flash->put('admin_access_success',$changes===0?'No category access changes were needed.':'Category access changes saved.');}catch(\InvalidArgumentException $e){$this->flash->put('admin_access_error',$e->getMessage());}return Response::redirect('/admin/category-access');}
    public function propertyAccess(AuthenticatedRequestContext $context):Response{if(!$this->allowed($context))return new Response(403,'Forbidden');if($this->propertyAccess===null)return new Response(404,'Not Found');$user=$context->user;$logoutCsrfToken=$this->csrf->token();$csrfToken=$this->csrf->token();$navbarCorporateItems=$this->tools->tools($context);$matrix=$this->propertyAccess->accessMatrix();$error=(string)$this->flash->pull('property_access_error','');$success=(string)$this->flash->pull('property_access_success','');ob_start();require $this->views.'/admin/property-access.php';return new Response(200,(string)ob_get_clean(),['Cache-Control'=>'private, no-store']);}
    public function savePropertyAccess(Request $request,AuthenticatedRequestContext $context):Response{if(!$this->allowed($context))return new Response(403,'Forbidden');if(!$this->csrf->valid($request->post['_token']??null))return new Response(419,'Invalid request.');if($this->propertyAccess===null||$this->propertyPayloads===null)return new Response(404,'Not Found');try{$changes=$this->propertyAccess->applyChanges($this->propertyPayloads->parse($request->post),$context->user);$this->flash->put('property_access_success',$changes===0?'No Property Access changes were needed.':'Property Access changes saved.');}catch(\InvalidArgumentException $e){$this->flash->put('property_access_error',$e->getMessage());}return Response::redirect('/corporate/admin/property-access');}
    private function allowed(AuthenticatedRequestContext $context):bool{return $this->access->canAccessCategory($context,'admin');}
}
