<?php
declare(strict_types=1);
namespace NpmGateway\Http\Controllers;
use NpmGateway\Contracts\CorporateToolsProviderInterface;
use NpmGateway\Http\AuthenticatedRequestContext;
use NpmGateway\Http\Request;
use NpmGateway\Http\Response;
use NpmGateway\Services\CompanyNoticeQueryService;
use NpmGateway\Security\CsrfService;
use NpmGateway\Services\CompanyNoticePublicationService;
use NpmGateway\Services\CompanyNoticeReviewStore;
use NpmGateway\Services\CompanyNoticeValidator;
use NpmGateway\Services\CorporateAccessService;
use NpmGateway\Support\FlashSession;
use NpmGateway\Services\CompanyNoticeComposeStore;
use NpmGateway\Services\CompanyNoticeAssetService;
use NpmGateway\Services\GatewayStorageService;
use NpmGateway\Contracts\ClockInterface;
use NpmGateway\Exceptions\Domain\StorageProviderException;
use NpmGateway\Services\CompanyNoticeDraftDiscardService;
final class CompanyNoticeController
{
 public function __construct(private readonly CorporateAccessService $access,private readonly CompanyNoticeQueryService $notices,private readonly CompanyNoticeValidator $validator,private readonly CompanyNoticeReviewStore $reviews,private readonly CompanyNoticePublicationService $publication,private readonly CorporateToolsProviderInterface $tools,private readonly CsrfService $csrf,private readonly FlashSession $flash,private readonly string $views,private readonly ?CompanyNoticeComposeStore $composes=null,private readonly ?CompanyNoticeAssetService $assets=null,private readonly ?GatewayStorageService $storage=null,private readonly ?ClockInterface $clock=null,private readonly ?CompanyNoticeDraftDiscardService $drafts=null){}
 private function allowed(AuthenticatedRequestContext $c):bool{return $this->access->canAccessCategory($c,'company-notices');}
 private function shell(AuthenticatedRequestContext $c):array{return [$c->user,$this->csrf->token(),$this->tools->tools($c)];}
 public function index(AuthenticatedRequestContext $c):Response{if(!$this->allowed($c))return new Response(403,'Forbidden');[$user,$csrfToken,$navbarCorporateItems]=$this->shell($c);$logoutCsrfToken=$csrfToken;$published=$this->notices->companyNoticeSummaries();$success=(string)$this->flash->pull('company_notice_success','');ob_start();require $this->views.'/company-notices/index.php';return new Response(200,(string)ob_get_clean());}
 public function create(Request $r,AuthenticatedRequestContext $c):Response{if(!$this->allowed($c))return new Response(403,'Forbidden');[$user,$csrfToken,$navbarCorporateItems]=$this->shell($c);$logoutCsrfToken=$csrfToken;$compose=$this->composes?->active($c->user->id);$composeContext=(string)($compose['id']??'');$selectedAssets=$composeContext!==''&&$this->assets!==null?$this->assets->authorized($composeContext,$c->user):[];$flashed=$this->flash->pull('company_notice_input',null);$input=is_array($flashed)?$flashed:['priority'=>'normal','requires_acknowledgment'=>'yes'];if(!is_array($flashed)){$active=$this->reviews->active($c->user->id);if(is_array($active)&&is_array($active['review']['data']??null)){$input=$active['review']['data'];$input['requires_acknowledgment']=$input['requires_acknowledgment']?'yes':'no';}}$errors=(array)$this->flash->pull('company_notice_errors',[]);$draftNotice=(string)$this->flash->pull('company_notice_draft_notice','');$draftError=(string)$this->flash->pull('company_notice_draft_error','');ob_start();require $this->views.'/company-notices/create.php';return new Response(200,(string)ob_get_clean(),['Cache-Control'=>'private, no-store']);}
 public function discard(Request $r,AuthenticatedRequestContext $c):Response
 {
  if(!$this->allowed($c))return new Response(403,'Forbidden');if(!$this->csrf->valid($r->post['_token']??null))return new Response(419,'Invalid request.');if($this->drafts===null)return new Response(404,'Not Found');
  $result=$this->drafts->discard((string)($r->post['compose_context']??''),$c->user);if($result['status']==='failed'){$this->flash->put('company_notice_draft_error','Draft could not be discarded safely.');return Response::redirect('/company-notices/create');}
  if($result['status']==='unavailable'){$this->flash->put('company_notice_draft_notice','This draft is no longer available.');return Response::redirect('/company-notices/create');}
  $this->flash->forget('company_notice_input');$this->flash->forget('company_notice_errors');$this->flash->put('company_notice_draft_notice','Draft discarded.');return Response::redirect('/company-notices/create');
 }
 public function upload(Request $r,string $role,AuthenticatedRequestContext $c):Response{if(!$this->allowed($c)||$this->assets===null)return $this->uploadError('not_found','The upload endpoint is unavailable.',404);if(!$this->csrf->valid($r->post['_token']??null))return $this->uploadError('csrf_failed','The upload request expired. Refresh the page and try again.',419);$compose=(string)($r->post['compose_context']??'');if(count($r->files)!==1||!isset($r->files['file'])||!is_array($r->files['file']))return $this->uploadError('invalid_upload_request','Choose exactly one file to upload.',422);try{return Response::json(['ok'=>true,'asset'=>$this->assets->upload($compose,$r->files['file'],$role,$c->user)],201);}catch(\InvalidArgumentException $e){$code=$e->getMessage()==='The compose context is unavailable.'?'invalid_compose_context':'upload_validation_failed';$message=$code==='invalid_compose_context'?'This upload session expired. Refresh the page and try again.':'The file could not be uploaded.';return $this->uploadError($code,$message,422);}catch(StorageProviderException){return $this->uploadError('storage_unavailable','The file could not be uploaded right now.',503);}catch(\Throwable $e){$code=$this->causedBy($e,\mysqli_sql_exception::class)?'metadata_persistence_failed':'upload_failed';return $this->uploadError($code,'The file could not be uploaded right now.',500);}}
 private function uploadError(string $code,string $message,int $status):Response{return Response::json(['ok'=>false,'error_code'=>$code,'message'=>$message],$status);}
 private function causedBy(\Throwable $error,string $class):bool{do{if($error instanceof $class)return true;$error=$error->getPrevious();}while($error instanceof \Throwable);return false;}
 public function removeUpload(Request $r,string $publicId,AuthenticatedRequestContext $c):Response{if(!$this->allowed($c)||$this->assets===null)return Response::json(['error'=>'Not found.'],404);if(!$this->csrf->valid($r->post['_token']??null))return Response::json(['error'=>'Invalid request.'],419);$at=$this->clock?->now()->format('Y-m-d H:i:s')??date('Y-m-d H:i:s');return $this->assets->remove((string)($r->post['compose_context']??''),$publicId,$c->user,$at)?Response::json(['removed'=>true]):Response::json(['error'=>'Not found.'],404);}
 public function temporary(string $publicId,bool $inline,Request $r,AuthenticatedRequestContext $c):Response{if(!$this->allowed($c)||$this->assets===null||$this->storage===null)return new Response(404,'Not Found');$object=$this->assets->findTemporary((string)($r->query['compose_context']??''),$publicId,$c->user,$inline?'embedded_image':'attachment');if($object===null)return new Response(404,'Not Found');try{$stream=$this->storage->open($object);}catch(\Throwable){return new Response(404,'Not Found');}$name=preg_replace('/[^A-Za-z0-9._ -]/','_',basename((string)$object['display_filename']))?:'download';return new Response(200,'',['Content-Type'=>(string)$object['mime_type'],'Content-Disposition'=>($inline?'inline':'attachment').'; filename="'.addcslashes($name,'"\\').'"','X-Content-Type-Options'=>'nosniff','Cache-Control'=>'private, no-store'],[],$stream);}
 public function preview(Request $r,AuthenticatedRequestContext $c):Response{if(!$this->allowed($c))return new Response(403,'Forbidden');if(!$this->csrf->valid($r->post['_token']??null))return new Response(419,'Invalid request.');try{$data=$this->validator->validate($r->post);$reviewAssets=$this->assets?->authorized((string)$data['compose_context'],$c->user)??[];$imageReferences=(new \NpmGateway\Services\RichTextSanitizer())->imageReferences((string)$data['rich_message_html']);foreach($imageReferences as $publicId=>$alt){$found=false;foreach($reviewAssets as $asset)if($asset['public_id']===$publicId&&$asset['asset_role']==='embedded_image')$found=true;if(!$found)throw new \InvalidArgumentException(json_encode(['message'=>'An embedded image is unavailable.'],JSON_THROW_ON_ERROR));}}catch(\InvalidArgumentException $e){$this->flash->put('company_notice_input',$r->post);$decoded=json_decode($e->getMessage(),true);$this->flash->put('company_notice_errors',is_array($decoded)?$decoded:['message'=>$e->getMessage()]);return Response::redirect('/company-notices/create');}$token=$this->reviews->create($c->user->id,$data);[$user,$csrfToken,$navbarCorporateItems]=$this->shell($c);$logoutCsrfToken=$csrfToken;$recipientCount=$this->publication->audienceCount();ob_start();require $this->views.'/company-notices/review.php';return new Response(200,(string)ob_get_clean(),['Cache-Control'=>'private, no-store']);}
 public function publish(Request $r,AuthenticatedRequestContext $c):Response
 {
  if(!$this->allowed($c))return new Response(403,'Forbidden');if(!$this->csrf->valid($r->post['_token']??null))return new Response(419,'Invalid request.');$token=(string)($r->post['review_token']??'');$resolved=$this->reviews->resolve($token,$c->user->id);if($resolved['status']==='unavailable')return new Response(404,'Review unavailable.');if(in_array($resolved['status'],['expired','superseded'],true))return new Response(409,'This review is no longer active. Please review the notice again before publishing.');$review=$resolved['review'];if($resolved['status']==='published'&&is_string($review['published']))return Response::redirect('/company-notices/'.$review['published']);try{$publication=$this->publication->publish($review,$c->user);}catch(\Throwable){return new Response(500,'The company notice could not be published safely.');}$this->reviews->complete($token,$publication['public_id']);$dispatch=$this->publication->dispatch($publication,$c->user);if($dispatch['reporting_failed'])$message='Company notice was published, but delivery reporting could not be completed.';elseif($dispatch['failed'])$message='Company notice published, but one or more announcement emails could not be delivered.';else $message=$publication['already_published']?'Company notice was already published.':'Company notice published successfully and announcement emails sent.';$this->flash->put('company_notice_success',$message);return Response::redirect('/company-notices/'.$publication['public_id']);
 }
 public function show(string $publicId,AuthenticatedRequestContext $c):Response{if(!$this->allowed($c))return new Response(403,'Forbidden');$notice=$this->notices->companyNoticeDetail($publicId);if($notice===null)return new Response(404,'Not Found');[$user,$csrfToken,$navbarCorporateItems]=$this->shell($c);$logoutCsrfToken=$csrfToken;$success=(string)$this->flash->pull('company_notice_success','');ob_start();require $this->views.'/company-notices/show.php';return new Response(200,(string)ob_get_clean());}
}
