<?php
declare(strict_types=1);
namespace NpmGateway\Http\Controllers;
use NpmGateway\Contracts\CorporateToolsProviderInterface;use NpmGateway\Exceptions\Domain\InvalidRmCorrectionException;use NpmGateway\Exceptions\Domain\RmCorrectionStateConflictException;use NpmGateway\Http\AuthenticatedRequestContext;use NpmGateway\Http\Request;use NpmGateway\Http\Response;use NpmGateway\Security\CsrfService;use NpmGateway\Services\CorporateAccessService;use NpmGateway\Services\RmCorrectionQueryService;use NpmGateway\Services\RmCorrectionService;use NpmGateway\Support\FlashSession;
final class CorporateRmCorrectionController
{
 public function __construct(private readonly CorporateAccessService $access,private readonly RmCorrectionQueryService $query,private readonly RmCorrectionService $service,private readonly CorporateToolsProviderInterface $tools,private readonly CsrfService $csrf,private readonly FlashSession $flash,private readonly string $views){}
 public function index(Request $r,AuthenticatedRequestContext $c):Response{if(!$this->allowed($c))return$this->denied();$status=(string)($r->query['status']??'');$propertyPublicId=(string)($r->query['property']??'');$search=trim((string)($r->query['search']??''));$requests=$this->query->corporateList($status,$propertyPublicId,$search);$counts=$this->query->counts();$properties=$this->query->properties();return$this->render('index',$c,compact('requests','counts','properties','status','propertyPublicId','search'));}
 public function show(string $public,AuthenticatedRequestContext $c):Response{if(!$this->allowed($c))return$this->denied();$request=$this->query->corporateDetail($public);if($request===null)return new Response(404,'Not Found');$input=(array)$this->flash->pull('rm_decision_input',[]);$errors=(array)$this->flash->pull('rm_decision_errors',[]);$success=(string)$this->flash->pull('rm_decision_success','');$error=(string)$this->flash->pull('rm_decision_error','');return$this->render('show',$c,compact('request','input','errors','success','error'));}
 public function decide(Request $r,string $public,AuthenticatedRequestContext $c):Response{if(!$this->allowed($c))return$this->denied();if(!$this->csrf->valid($r->post['_token']??null))return new Response(419,'Invalid request.');try{$result=$this->service->decide($public,$r->post,$c->user);$this->flash->put('rm_decision_success',$result['email_sent']?'Decision saved successfully.':'Decision saved, but the manager email could not be delivered.');}catch(InvalidRmCorrectionException $e){$this->flash->put('rm_decision_input',$e->input);$this->flash->put('rm_decision_errors',$e->errors);}catch(RmCorrectionStateConflictException){$this->flash->put('rm_decision_error','This RM correction is no longer pending review.');}catch(\OutOfBoundsException){return new Response(404,'Not Found');}return Response::redirect('/corporate/rm-corrections/'.$public);}
 private function allowed(AuthenticatedRequestContext $c):bool{return$this->access->canAccessCategory($c,'rm-corrections');}private function denied():Response{return new Response(403,'Forbidden',['Cache-Control'=>'private, no-store']);}
 private function render(string $view,AuthenticatedRequestContext $c,array $vars):Response{$user=$c->user;$csrfToken=$this->csrf->token();$logoutCsrfToken=$csrfToken;$navbarCorporateItems=$this->tools->tools($c);extract($vars);ob_start();require$this->views.'/corporate/rm-corrections/'.$view.'.php';return new Response(200,(string)ob_get_clean(),['Cache-Control'=>'private, no-store']);}
}
