<?php declare(strict_types=1);namespace NpmGateway\Http\Controllers;
use NpmGateway\Http\{AuthenticatedRequestContext,Request,Response};use NpmGateway\Security\CsrfService;use NpmGateway\Services\{CorporateAccessService,MarketingFlyerService};use NpmGateway\Support\FlashSession;
final class MarketingFlyerController{
 public function __construct(private readonly CorporateAccessService$access,private readonly MarketingFlyerService$service,private readonly CsrfService$csrf,private readonly FlashSession$flash,private readonly string$views){}
 private function allowed(AuthenticatedRequestContext$c):bool{return$this->access->canAccessCategory($c,'marketing');}
 private function enhanced(Request$r):bool{return strcasecmp((string)($r->server['HTTP_X_REQUESTED_WITH']??''),'XMLHttpRequest')===0&&str_contains(strtolower((string)($r->server['HTTP_ACCEPT']??'')),'application/json');}
 private function failure(Request$r,string$message,int$status=422):Response{if($this->enhanced($r))return Response::json(['ok'=>false,'message'=>$message],$status);$this->flash->put('flyer_error',$message);$this->flash->put('flyer_input',['property'=>(string)($r->post['property']??''),'month'=>(string)($r->post['month']??''),'type'=>(string)($r->post['type']??'standard')]);return Response::redirect('/corporate/marketing/flyers/new');}
 private function libraryRedirect(array$flyer):string{return'/corporate/marketing/flyers?month='.rawurlencode(substr((string)$flyer['flyer_month'],0,7));}
 public function index(Request$r,AuthenticatedRequestContext$c):Response{if(!$this->allowed($c))return new Response(403,'Forbidden');$month=(string)($r->query['month']??$this->service->currentMonth());$property=(string)($r->query['property']??'');try{$flyers=$this->service->list($month,$property);$error='';}catch(\InvalidArgumentException$e){$flyers=[];$error=$e->getMessage();}$properties=$this->service->properties();$months=$this->service->months();$user=$c->user;$csrfToken=$this->csrf->token();$success=$this->flash->pull('flyer_success','');$warning=$this->flash->pull('flyer_warning','');ob_start();require$this->views.'/corporate/marketing/flyers/index.php';return new Response(200,(string)ob_get_clean(),['Cache-Control'=>'private, no-store']);}
 public function create(AuthenticatedRequestContext$c):Response{if(!$this->allowed($c))return new Response(403,'Forbidden');$properties=$this->service->properties();$months=$this->service->months();$input=$this->flash->pull('flyer_input',[]);$input=is_array($input)?$input:[];$candidateMonth=(string)($input['month']??'');$month=array_key_exists($candidateMonth,$months)?$candidateMonth:$this->service->currentMonth();$property=(string)($input['property']??'');$type=in_array(($input['type']??''),['standard','promo'],true)?(string)$input['type']:'standard';$user=$c->user;$csrfToken=$this->csrf->token();$error=(string)$this->flash->pull('flyer_error','');ob_start();require$this->views.'/corporate/marketing/flyers/form.php';return new Response(200,(string)ob_get_clean(),['Cache-Control'=>'private, no-store']);}
 public function store(Request$r,AuthenticatedRequestContext$c):Response{if(!$this->allowed($c))return new Response(403,'Forbidden');if(!$this->csrf->valid($r->post['_token']??null))return$this->failure($r,'Invalid request.',419);try{$result=$this->service->save($c->user,(string)($r->post['property']??''),(string)($r->post['month']??''),(string)($r->post['type']??''),(array)($r->files['flyer']??[]));$redirect=$this->libraryRedirect($result['flyer']);$this->flash->put('flyer_success','Flyer uploaded successfully. Manager notification queued for delivery.');if(($result['notification']['warning']??'')!=='')$this->flash->put('flyer_warning',$result['notification']['warning']);return$this->enhanced($r)?Response::json(['ok'=>true,'redirect'=>$redirect]):Response::redirect($redirect);}catch(\Throwable$e){$message=$e instanceof \InvalidArgumentException?$e->getMessage():'The flyer could not be saved safely.';return$this->failure($r,$message);}}
 public function show(string$id,AuthenticatedRequestContext$c):Response{if(!$this->allowed($c))return new Response(403,'Forbidden');$flyer=$this->service->find($id);if(!$flyer)return new Response(404,'Not found');$user=$c->user;$csrfToken=$this->csrf->token();$success=$this->flash->pull('flyer_success','');$warning=$this->flash->pull('flyer_warning','');ob_start();require$this->views.'/corporate/marketing/flyers/show.php';return new Response(200,(string)ob_get_clean(),['Cache-Control'=>'private, no-store']);}
 public function asset(string$id,string$kind,AuthenticatedRequestContext$c):Response{if(!$this->allowed($c))return new Response(403,'Forbidden');$flyer=$this->service->find($id);if(!$flyer)return new Response(404,'Not found');return$this->assetResponse($flyer,$kind==='download');}
 public function managerDownload(string$slug,string$id,AuthenticatedRequestContext$c):Response{$flyer=$this->service->managerAccessible($id,$slug,$c->user->employeeId);if(!$flyer)return new Response(404,'Not found');return$this->assetResponse($flyer,true);}
 private function assetResponse(array$flyer,bool$download):Response{return new Response(200,'',['Content-Type'=>$flyer['mime_type'],'Content-Disposition'=>($download?'attachment':'inline').'; filename="'.basename($flyer['object_key']).'"','Cache-Control'=>'private, no-store','Pragma'=>'no-cache','X-Content-Type-Options'=>'nosniff'],[],$this->service->open($flyer));}
 public function replaceForm(string$id,AuthenticatedRequestContext$c):Response{$flyer=$this->service->find($id);if(!$this->allowed($c))return new Response(403,'Forbidden');if(!$flyer)return new Response(404,'Not found');$user=$c->user;$csrfToken=$this->csrf->token();$error=$this->flash->pull('flyer_error','');ob_start();require$this->views.'/corporate/marketing/flyers/replace.php';return new Response(200,(string)ob_get_clean());}
 public function replace(Request$r,string$id,AuthenticatedRequestContext$c):Response{if(!$this->allowed($c))return new Response(403,'Forbidden');if(!$this->csrf->valid($r->post['_token']??null))return new Response(419,'Invalid request.');$flyer=$this->service->find($id);if(!$flyer)return new Response(404,'Not found');try{$result=$this->service->save($c->user,$flyer['property_public_id'],substr($flyer['flyer_month'],0,7),$flyer['flyer_type'],(array)($r->files['flyer']??[]),$id);$this->flash->put('flyer_success','Flyer replaced successfully. Manager notification queued for delivery.');if(($result['notification']['warning']??'')!=='')$this->flash->put('flyer_warning',$result['notification']['warning']);return Response::redirect($this->libraryRedirect($result['flyer']));}catch(\Throwable$e){$this->flash->put('flyer_error',$e instanceof \InvalidArgumentException?$e->getMessage():'The flyer could not be replaced safely.');return Response::redirect('/corporate/marketing/flyers/'.$id.'/replace');}}
 public function delete(Request$r,string$id,AuthenticatedRequestContext$c):Response{if(!$this->allowed($c))return new Response(403,'Forbidden');if(!$this->csrf->valid($r->post['_token']??null))return new Response(419,'Invalid request.');try{$this->service->delete($c->user,$id);$this->flash->put('flyer_success','Flyer permanently deleted.');return Response::redirect('/corporate/marketing/flyers');}catch(\Throwable$e){$this->flash->put('flyer_warning',$e->getMessage());return Response::redirect('/corporate/marketing/flyers/'.$id);}}
}
