<?php
declare(strict_types=1);
namespace NpmGateway\Http\Controllers;
use NpmGateway\Contracts\ClockInterface;use NpmGateway\Contracts\CorporateToolsProviderInterface;use NpmGateway\Http\AuthenticatedRequestContext;use NpmGateway\Http\Request;use NpmGateway\Http\Response;use NpmGateway\Security\CsrfService;use NpmGateway\Services\CorporateAccessService;use NpmGateway\Services\OperationsRmCorrectionOverviewService;use NpmGateway\ValueObjects\RmCorrectionOverviewCriteria;use NpmGateway\ValueObjects\ToolCard;
final class OperationsOverviewController
{
 public function __construct(private readonly CorporateAccessService $access,private readonly OperationsRmCorrectionOverviewService $query,private readonly ClockInterface $clock,private readonly CorporateToolsProviderInterface $tools,private readonly CsrfService $csrf,private readonly string $views){}
 public function index(AuthenticatedRequestContext $c):Response{if(!$this->allowed($c))return$this->denied();$cards=[new ToolCard('rm-corrections','RM Corrections','Review Rent Manager correction activity across all communities.','Operations Overview','View RM Corrections','/corporate/operations/overview/rm-corrections',true,10,null,null,'corporate.operations.overview.rm-corrections')];return$this->render('index',$c,compact('cards'));}
 public function rmCorrections(Request $request,AuthenticatedRequestContext $c):Response{if(!$this->allowed($c))return$this->denied();$properties=$this->query->properties();$criteria=RmCorrectionOverviewCriteria::fromQuery($request->query,$this->clock->now(),$properties);$report=$this->query->report($criteria);return$this->render('rm-corrections/index',$c,compact('properties','criteria','report'));}
 public function rmCorrection(string $public,Request $http,AuthenticatedRequestContext $c):Response{if(!$this->allowed($c))return$this->denied();$request=$this->query->detail($public);if($request===null)return new Response(404,'Not Found',['Cache-Control'=>'private, no-store']);$properties=$this->query->properties();$criteria=RmCorrectionOverviewCriteria::fromQuery($http->query,$this->clock->now(),$properties);if($criteria->errors!==[])$criteria=RmCorrectionOverviewCriteria::fromQuery([],$this->clock->now(),$properties);return$this->render('rm-corrections/show',$c,compact('request','criteria'));}
 private function allowed(AuthenticatedRequestContext $c):bool{return$this->access->canAccessCategory($c,'operations');}private function denied():Response{return new Response(403,'Forbidden',['Cache-Control'=>'private, no-store']);}
 private function render(string $view,AuthenticatedRequestContext $c,array $vars):Response{$user=$c->user;$logoutCsrfToken=$this->csrf->token();$navbarCorporateItems=$this->tools->tools($c);extract($vars);ob_start();require$this->views.'/corporate/operations/overview/'.$view.'.php';return new Response(200,(string)ob_get_clean(),['Cache-Control'=>'private, no-store']);}
}
