<?php
declare(strict_types=1);
namespace NpmGateway\Http\Controllers;
use NpmGateway\Contracts\CorporateToolsProviderInterface;use NpmGateway\Exceptions\Domain\CommunityActionPropertyForbiddenException;use NpmGateway\Exceptions\Domain\CommunityActionPropertyNotFoundException;use NpmGateway\Exceptions\Domain\InvalidRmCorrectionException;use NpmGateway\Exceptions\Domain\RmCorrectionStateConflictException;use NpmGateway\Http\AuthenticatedRequestContext;use NpmGateway\Http\Request;use NpmGateway\Http\Response;use NpmGateway\Security\CsrfService;use NpmGateway\Services\CommunityActionContextResolver;use NpmGateway\Services\RmCorrectionQueryService;use NpmGateway\Services\RmCorrectionService;use NpmGateway\Support\FlashSession;
final class RmCorrectionController
{
 public function __construct(private readonly CommunityActionContextResolver $resolver,private readonly RmCorrectionQueryService $query,private readonly RmCorrectionService $service,private readonly CorporateToolsProviderInterface $tools,private readonly CsrfService $csrf,private readonly FlashSession $flash,private readonly string $views){}
 public function index(Request $r,string $slug,AuthenticatedRequestContext $c):Response{if(($x=$this->context($c,$slug))instanceof Response)return$x;$status=(string)($r->query['status']??'');$search=trim((string)($r->query['search']??''));$requests=$this->query->managerList($x->propertyId,$status,$search);$counts=$this->query->counts($x->propertyId);$context=$x;return $this->render('index',$c,compact('context','requests','counts','status','search'));}
 public function create(string $slug,AuthenticatedRequestContext $c):Response{if(($x=$this->context($c,$slug))instanceof Response)return$x;$context=$x;$input=(array)$this->flash->pull('rm_input',[]);$errors=(array)$this->flash->pull('rm_errors',[]);return$this->render('create',$c,compact('context','input','errors'));}
 public function store(Request $r,string $slug,AuthenticatedRequestContext $c):Response{if(($x=$this->context($c,$slug))instanceof Response)return$x;if(!$this->csrf->valid($r->post['_token']??null))return new Response(419,'Invalid request.',['Cache-Control'=>'private, no-store']);try{$result=$this->service->submit($x,$r->post);$this->flash->put('rm_success','RM correction submitted successfully.');if(!$result['email_sent'])$this->flash->put('rm_warning','The request was saved, but the reviewer notification could not be delivered.');return Response::redirect('/community-actions/'.$x->propertySlug.'/rm-corrections/'.$result['public_id']);}catch(InvalidRmCorrectionException $e){$this->flash->put('rm_input',$e->input);$this->flash->put('rm_errors',$e->errors);return Response::redirect('/community-actions/'.$x->propertySlug.'/rm-corrections/create');}catch(CommunityActionPropertyForbiddenException){return new Response(403,'Forbidden');}catch(\Throwable){return new Response(500,'The RM correction could not be submitted safely.');}}
 public function show(string $slug,string $public,AuthenticatedRequestContext $c):Response{if(($x=$this->context($c,$slug))instanceof Response)return$x;$request=$this->query->managerDetail($public,$x->propertyId);if($request===null)return new Response(404,'Not Found');$context=$x;$success=(string)$this->flash->pull('rm_success','');$warning=(string)$this->flash->pull('rm_warning','');$error=(string)$this->flash->pull('rm_state_error','');return$this->render('show',$c,compact('context','request','success','warning','error'));}
 public function respondForm(string $slug,string $public,AuthenticatedRequestContext $c):Response{if(($x=$this->context($c,$slug))instanceof Response)return$x;$request=$this->query->managerDetail($public,$x->propertyId);if($request===null)return new Response(404,'Not Found');if($request['status']!=='more_information_needed')return Response::redirect('/community-actions/'.$x->propertySlug.'/rm-corrections/'.$public);$informationRequested=$this->latestInformationRequested($request['history']);if($informationRequested===null){$this->flash->put('rm_state_error','The requested information could not be resolved safely.');return Response::redirect('/community-actions/'.$x->propertySlug.'/rm-corrections/'.$public);}$context=$x;$input=(array)$this->flash->pull('rm_response_input',[]);$errors=(array)$this->flash->pull('rm_response_errors',[]);return$this->render('respond',$c,compact('context','request','informationRequested','input','errors'));}
 public function respond(Request $r,string $slug,string $public,AuthenticatedRequestContext $c):Response{if(($x=$this->context($c,$slug))instanceof Response)return$x;if(!$this->csrf->valid($r->post['_token']??null))return new Response(419,'Invalid request.');try{$result=$this->service->respond($x,$public,$r->post);$this->flash->put('rm_success',$result['email_sent']?'Additional information submitted successfully.':'Additional information submitted, but the reviewer email could not be delivered.');}catch(InvalidRmCorrectionException $e){$this->flash->put('rm_response_input',$e->input);$this->flash->put('rm_response_errors',$e->errors);return Response::redirect('/community-actions/'.$x->propertySlug.'/rm-corrections/'.$public.'/respond');}catch(RmCorrectionStateConflictException){$this->flash->put('rm_state_error','This request is no longer awaiting additional information.');}catch(\OutOfBoundsException){return new Response(404,'Not Found');}return Response::redirect('/community-actions/'.$x->propertySlug.'/rm-corrections/'.$public);}
 private function context(AuthenticatedRequestContext $c,string $slug):mixed{try{return$this->resolver->resolve($c,$slug);}catch(CommunityActionPropertyNotFoundException){return new Response(404,'Not Found');}catch(CommunityActionPropertyForbiddenException){return new Response(403,'Forbidden');}}
 private function latestInformationRequested(array $history):?string{foreach(array_reverse($history)as$event)if(($event['event_type']??null)==='more_information_needed'&&trim((string)($event['comments']??''))!=='')return(string)$event['comments'];return null;}
 private function render(string $view,AuthenticatedRequestContext $c,array $vars):Response{$user=$c->user;$csrfToken=$this->csrf->token();$logoutCsrfToken=$csrfToken;$navbarCorporateItems=$this->tools->tools($c);extract($vars);ob_start();require$this->views.'/community-actions/rm-corrections/'.$view.'.php';return new Response(200,(string)ob_get_clean(),['Cache-Control'=>'private, no-store']);}
}
