<?php
declare(strict_types=1);
namespace NpmGateway\Http\Controllers;
use NpmGateway\Contracts\CorporateToolsProviderInterface;use NpmGateway\Exceptions\Domain\InvalidZillowWorkbookException;use NpmGateway\Http\{AuthenticatedRequestContext,Request,Response};use NpmGateway\Security\CsrfService;use NpmGateway\Services\{CallLogAccessPolicy,ZillowService};use NpmGateway\Support\FlashSession;
final readonly class ZillowController
{
 public function __construct(private CallLogAccessPolicy$access,private ZillowService$service,private CorporateToolsProviderInterface$tools,private CsrfService$csrf,private FlashSession$flash,private string$views){}
 public function index(Request$request,AuthenticatedRequestContext$c):Response{if(!$this->access->allows($c->user))return new Response(403,'Forbidden');$user=$c->user;$logoutCsrfToken=$this->csrf->token();$navbarCorporateItems=$this->tools->tools($c);$report=$this->service->report($request->query);$success=(string)$this->flash->pull('zillow_success','');$error=(string)$this->flash->pull('zillow_error','');ob_start();require$this->views.'/admin/zillow/index.php';return new Response(200,(string)ob_get_clean(),['Cache-Control'=>'private, no-store']);}
 public function history(AuthenticatedRequestContext$c):Response{if(!$this->access->allows($c->user))return new Response(403,'Forbidden');$user=$c->user;$logoutCsrfToken=$this->csrf->token();$navbarCorporateItems=$this->tools->tools($c);$history=$this->service->history();ob_start();require$this->views.'/admin/zillow/history.php';return new Response(200,(string)ob_get_clean(),['Cache-Control'=>'private, no-store']);}
 public function upload(AuthenticatedRequestContext$c):Response{if(!$this->access->allows($c->user))return new Response(403,'Forbidden');$user=$c->user;$logoutCsrfToken=$this->csrf->token();$csrfToken=$this->csrf->token();$navbarCorporateItems=$this->tools->tools($c);$error=(string)$this->flash->pull('zillow_error','');ob_start();require$this->views.'/admin/zillow/upload.php';return new Response(200,(string)ob_get_clean(),['Cache-Control'=>'private, no-store']);}
 public function store(Request$r,AuthenticatedRequestContext$c):Response{if(!$this->access->allows($c->user))return new Response(403,'Forbidden');if(!$this->csrf->valid($r->post['_token']??null))return new Response(419,'Invalid request.');try{$x=$this->service->import((array)($r->files['zillow_workbook']??[]),$c->user);$this->flash->put('zillow_success','Zillow.com data imported successfully: '.number_format($x['total']).' total leads, '.number_format($x['phone']).' phone, and '.number_format($x['email']).' email.');$redirect='/admin/zillow';}catch(InvalidZillowWorkbookException$e){$this->flash->put('zillow_error',$e->getMessage());$redirect='/admin/zillow/upload';}catch(\Throwable){$this->flash->put('zillow_error','The Zillow.com workbook could not be imported safely. No records were imported.');$redirect='/admin/zillow/upload';}if(strtolower((string)($r->server['HTTP_X_REQUESTED_WITH']??''))==='xmlhttprequest')return Response::json(['ok'=>$redirect==='/admin/zillow','redirect'=>$redirect,'message'=>(string)$this->flash->pull('zillow_error','')],$redirect==='/admin/zillow'?200:422);return Response::redirect($redirect);}
}
