<?php
declare(strict_types=1);
$components=dirname(__DIR__).'/components';$escape=static fn(string $v):string=>htmlspecialchars($v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
ob_start();$breadcrumbItems=[['label'=>'Dashboard','url'=>'/dashboard'],['label'=>'Employee Workspace','url'=>'/employees'],['label'=>$profile->fullName,'current'=>true]];require $components.'/breadcrumb.php';
?>
<header class="gateway-profile-header"><div><p class="gateway-eyebrow">Employee Profile</p><h1><?= $escape($profile->fullName) ?></h1><p><?= $escape($profile->jobTitle) ?></p></div><div class="gateway-profile-header__badges"><span class="gateway-status gateway-status--neutral"><?= $escape(ucfirst($profile->employeeClass)) ?></span><span class="gateway-status gateway-status--<?= $profile->employmentStatus==='active'?'success':'neutral' ?>"><?= $escape(ucfirst($profile->employmentStatus)) ?></span><span class="gateway-status gateway-status--<?= $profile->gatewayAccessStatus==='Active'?'success':'neutral' ?>">Gateway Access: <?= $escape($profile->gatewayAccessStatus) ?></span></div></header>
<div class="gateway-profile-grid">
 <section class="gateway-profile-section" aria-labelledby="employment-title"><h2 id="employment-title">Employment</h2><dl><div><dt>Employee number</dt><dd><?= $escape($profile->employeeNumber) ?></dd></div><div><dt>Employee class</dt><dd><?= $escape(ucfirst($profile->employeeClass)) ?></dd></div><div><dt>Status</dt><dd><?= $escape(ucfirst($profile->employmentStatus)) ?></dd></div></dl></section>
 <section class="gateway-profile-section" aria-labelledby="contact-title"><h2 id="contact-title">Company Contact</h2><dl><div><dt>Business email</dt><dd><?= $profile->businessEmail===null?'Not provided':$escape($profile->businessEmail) ?></dd></div><div><dt>Company phone</dt><dd><?= $profile->companyPhone===null?'Not provided':$escape($profile->companyPhone) ?></dd></div></dl></section>
 <section class="gateway-profile-section gateway-profile-section--wide" aria-labelledby="assignments-title"><h2 id="assignments-title">Current Assignments</h2><?php if($profile->assignments===[]): ?><p class="mb-0 text-secondary">Not assigned to a property</p><?php else: ?><ul class="gateway-assignment-list"><?php foreach($profile->assignments as $assignment): ?><li><strong><?= $escape($assignment->propertyName) ?></strong><span><?= $escape(ucwords(str_replace('_',' ',$assignment->assignmentRole))) ?> · <?= $assignment->primary?'Primary':'Secondary' ?> · Since <?= $escape($assignment->startsOn) ?></span></li><?php endforeach; ?></ul><?php endif; ?></section>
</div>
<p class="mt-4"><a href="/employees">Back to Employee Workspace</a></p>
<?php
$contentHtml=(string)ob_get_clean();$pageTitle=$profile->fullName.' — NPM Gateway';$navbarItems=\NpmGateway\Support\Navigation::forRoute('/employees',dirname(__DIR__,3));$navbarUserLabel=$user->displayName;$navbarUserContext='@'.$user->username.($user->jobTitle!==''?' · '.$user->jobTitle:'');$footerText='NPM Gateway — Internal use only';require dirname(__DIR__).'/layouts/app.php';
