import assert from 'node:assert/strict';import fs from 'node:fs';import vm from 'node:vm';
const source=fs.readFileSync(new URL('../../public/assets/js/marketing-flyer-upload.js',import.meta.url),'utf8');
const scenario=response=>{let submit;let assigned='';let sends=0;let xhr;const button={disabled:false};const attributes=new Map([['aria-valuenow','0']]);const track={setAttribute(name,value){attributes.set(name,value);},getAttribute(name){return attributes.get(name);}};const bar={style:{width:'0%'}};const label={textContent:''};const makeClasses=()=>({values:new Set(),add(v){this.values.add(v);},remove(v){this.values.delete(v);}});const classList=makeClasses();const box={hidden:true,classList,querySelector(selector){if(selector==='[role=progressbar]')return track;if(selector==='.gateway-flyer-progress__bar')return bar;return label;}};const form={action:'/corporate/marketing/flyers',querySelector(){return button;},addEventListener(name,callback){if(name==='submit')submit=callback;}};class Xhr{constructor(){this.upload={};this.status=response.status;this.response=response.body;xhr=this;}open(){}setRequestHeader(){}send(){sends++;}}const context={document:{getElementById(id){return id==='flyer-upload'?form:box;}},XMLHttpRequest:Xhr,FormData:class{},location:{assign(url){assigned=url;}}};vm.runInNewContext(source,context);return{submit:()=>submit({preventDefault(){}}),progress:event=>xhr.upload.onprogress(event),uploaded:()=>xhr.upload.onload(),complete:()=>xhr.onload(),button,track,bar,label,box,classList,get assigned(){return assigned;},get sends(){return sends;}};};
{
 const run=scenario({status:200,body:{ok:true,redirect:'/corporate/marketing/flyers?month=2026-08'}});assert.equal(run.box.hidden,true);run.submit();assert.equal(run.box.hidden,false);assert.equal(run.bar.style.width,'0%');for(const percentage of[25,50,100]){run.progress({lengthComputable:true,loaded:percentage,total:100});assert.equal(run.bar.style.width,`${percentage}%`);assert.equal(run.track.getAttribute('aria-valuenow'),String(percentage));assert.equal(run.label.textContent,`Uploading flyer... ${percentage}%`);}run.uploaded();assert.equal(run.bar.style.width,'100%');assert.equal(run.track.getAttribute('aria-valuenow'),'100');assert.equal(run.label.textContent,'Saving flyer...');run.complete();assert.equal(run.assigned,'/corporate/marketing/flyers?month=2026-08');assert.equal(run.button.disabled,true);run.submit();assert.equal(run.sends,1);
}
{
 const run=scenario({status:422,body:{ok:false,message:'Choose a portrait PNG or JPG.'}});run.submit();run.progress({lengthComputable:true,loaded:50,total:100});run.complete();assert.equal(run.assigned,'');assert.equal(run.button.disabled,false);assert.equal(run.label.textContent,'Choose a portrait PNG or JPG.');assert.equal(run.classList.values.has('gateway-flyer-progress--error'),true);assert.equal(run.bar.style.width,'50%');
}
for(const forbidden of['setTimeout','setInterval','animation','Sending notification','Complete'])assert.equal(source.includes(forbidden),false);console.log('Marketing Flyer upload JavaScript: 2 scenarios passed');
