<?php
declare(strict_types=1);
use NpmGateway\Exceptions\Domain\InvalidApplicationReviewException;
use NpmGateway\Notifications\ApplicationReviewEmailSender;
use NpmGateway\Services\ApplicationReviewValidator;
use PHPUnit\Framework\TestCase;
final class ApplicationReviewsWorkflowTest extends TestCase
{
 public function testMigrationDeclaresExactRestrictiveAppendOnlySchema():void{$sql=(string)file_get_contents(dirname(__DIR__,2).'/database/migrations/202608040015_application_reviews.php');foreach(['application_reviews','application_review_history','pending_review','approved','denied','ON UPDATE RESTRICT ON DELETE RESTRICT','uq_application_reviews_public_id','idx_application_reviews_queue','Cannot roll back Application Reviews'] as $required)self::assertStringContainsString($required,$sql);self::assertStringNotContainsString('ON DELETE CASCADE',$sql);$repo=(string)file_get_contents(dirname(__DIR__,2).'/app/Repositories/ApplicationReviewRepository.php');self::assertStringNotContainsString('deleteHistory',$repo);self::assertStringNotContainsString('updateHistory',$repo);}
 public function testSubmissionValidationAllowsMultipleApplicantsButRequiresTrustedConfirmation():void{$v=new ApplicationReviewValidator();$data=$v->submission(['prospect_name'=>'  Alex   and  Sam Rivera ','manager_comments'=>"Plain\r\nnotes",'rm_documents_confirmed'=>'confirmed','property_id'=>'999','user_id'=>'888']);self::assertSame('Alex and Sam Rivera',$data['prospect_name']);self::assertSame("Plain\nnotes",$data['manager_comments']);foreach([['prospect_name'=>'','rm_documents_confirmed'=>'confirmed'],['prospect_name'=>'Alex'],['prospect_name'=>'Alex','rm_documents_confirmed'=>'tampered'],['prospect_name'=>'Alex','rm_documents_confirmed'=>'confirmed','manager_comments'=>'<script>alert(1)</script>']] as $bad){try{$v->submission($bad);self::fail('Invalid submission accepted.');}catch(InvalidApplicationReviewException){self::addToAssertionCount(1);}}}
 public function testDecisionRequiresAllowlistedButtonAndComments():void{$v=new ApplicationReviewValidator();self::assertSame('approved',$v->decision(['decision'=>'approved','reviewer_comments'=>'Complete basis.'])['decision']);self::assertSame('denied',$v->decision(['decision'=>'denied','reviewer_comments'=>'Complete basis.'])['decision']);foreach([['decision'=>'approved'],['decision'=>'pending_review','reviewer_comments'=>'No'],['decision'=>'approved','reviewer_comments'=>'<b>unsafe</b>']] as $bad){$this->expectValidation($v,$bad);}}
 public function testReviewNotesRequestContractNormalizesOnceWithoutLosingValidText():void
 {
  $validator=new ApplicationReviewValidator();
  self::assertSame('0',$validator->decision(['decision'=>'approved','reviewer_comments'=>' 0 '])['reviewer_comments']);
  self::assertSame("First line\nSecond line",$validator->decision(['decision'=>'denied','reviewer_comments'=>" First line\r\nSecond line "])['reviewer_comments']);
  self::assertSame(str_repeat('a',5000),$validator->decision(['decision'=>'approved','reviewer_comments'=>str_repeat('a',5000)])['reviewer_comments']);
  foreach([''," \r\n\t",str_repeat('a',5001)] as $notes)$this->expectValidation($validator,['decision'=>'approved','reviewer_comments'=>$notes]);
 }
 public function testEmailTestModeUsesOnlyConfiguredRecipientAndBothFormats():void{$sent=[];$sender=new ApplicationReviewEmailSender(['test_mode'=>true,'test_email'=>'chuck@example.test','app_url'=>'https://gateway.example.test'],function(...$args)use(&$sent){$sent[]=$args;return true;});$review=['public_id'=>str_repeat('R',26),'property_name'=>'Alpha','property_slug'=>'alpha','prospect_name'=>'Test Prospect','submitted_by_name'=>'Manager User','submitted_at'=>'2026-08-05 09:00:00','manager_comments'=>'Notes','status'=>'approved','reviewed_by_name'=>'Reviewer User','reviewed_at'=>'2026-08-05 10:00:00','reviewer_comments'=>'Approved basis'];self::assertTrue($sender->sendSubmission($review));self::assertTrue($sender->sendDecision($review));self::assertCount(2,$sent);self::assertSame(['chuck@example.test','chuck@example.test'],array_column($sent,0));self::assertStringContainsString('https://gateway.example.test/corporate/application-reviews/',$sent[0][2]);self::assertStringContainsString('https://gateway.example.test/community-actions/alpha/application-reviews/',$sent[1][3]);self::assertNotSame('',$sent[0][2]);self::assertNotSame('',$sent[0][3]);}
 public function testMissingTestRecipientFailsClosed():void{$sender=new ApplicationReviewEmailSender(['test_mode'=>true,'test_email'=>'','app_url'=>'https://gateway.example.test'],fn()=>true);$review=['public_id'=>str_repeat('R',26),'property_name'=>'Alpha','property_slug'=>'alpha','prospect_name'=>'Prospect','submitted_by_name'=>'Manager','submitted_at'=>'2026-08-05 09:00:00','manager_comments'=>''];self::assertFalse($sender->sendSubmission($review));}
 public function testRoutesFormsPrivacyAndOperationsPlacement():void{$root=dirname(__DIR__,2);$routes=require $root.'/routes/web.php';foreach(['/community-actions/{propertySlug}/application-reviews','/community-actions/{propertySlug}/application-reviews/create','/community-actions/{propertySlug}/application-reviews/{reviewPublicId}','/corporate/application-reviews','/corporate/application-reviews/{reviewPublicId}','/corporate/application-reviews/{reviewPublicId}/decision'] as $route)self::assertArrayHasKey($route,$routes);$form=(string)file_get_contents($root.'/resources/views/community-actions/application-reviews/create.php');foreach(['Prospect Full Name','Comments for Reviewer (Optional)','uploaded to Rent Manager','Submit Prospect','data-processing-form'] as $text)self::assertStringContainsString($text,$form);foreach(['property_id','property_public_id','property_slug','employee_id','user_id','submitted_by','recipient','<script','style='] as $forbidden)self::assertStringNotContainsString('name="'.$forbidden,$form);$manager=(string)file_get_contents($root.'/app/Http/Controllers/ApplicationReviewController.php');$corporate=(string)file_get_contents($root.'/app/Http/Controllers/CorporateApplicationReviewController.php');self::assertStringContainsString('CommunityActionContextResolver',$manager);self::assertStringContainsString("canAccessCategory(\$c,'application-reviews')",$corporate);self::assertStringContainsString("['Cache-Control'=>'private, no-store']",$manager.$corporate);}
 public function testSubmitFormUsesApprovedSectionsInformationAndActionOrder():void{$root=dirname(__DIR__,2);$form=(string)file_get_contents($root.'/resources/views/community-actions/application-reviews/create.php');foreach(['Prospect Information','Comments for Reviewer (Optional)','Required Company Policy','Rent Manager Confirmation','Required Confirmation','Applications and supporting documents must be uploaded to Rent Manager before they can be submitted for Corporate review.','I confirm that the application and all supporting documents have been uploaded to Rent Manager.','gateway-alert--info','gateway-company-policy__notice','gateway-form-check--top-aligned','data-character-counter','data-character-counter-target="manager-comments-counter"','data-character-counter-max="5000"','aria-describedby="manager-comments-counter','maxlength="5000"','name="manager_comments"','name="rm_documents_confirmed"','for="rm_documents_confirmed"',' required'] as $required)self::assertStringContainsString($required,$form);foreach(['Manager Comments (Optional)','Comments for Corporate (Optional)','gateway-alert--warning','gateway-alert--danger'] as $forbidden)self::assertStringNotContainsString($forbidden,$form);$positions=array_map(static fn(string $text):int=>strpos($form,$text),['Prospect Information','Prospect Full Name','Comments for Reviewer (Optional)','Required Company Policy','Rent Manager Confirmation','Required Confirmation','I confirm that the application','>Submit Prospect</button>','>Cancel</a>']);self::assertSame($positions,array_values($positions));for($i=1;$i<count($positions);$i++)self::assertGreaterThan($positions[$i-1],$positions[$i]);self::assertStringContainsString('/community-actions/<?=$e($context->propertySlug)?>/application-reviews">Cancel',$form);self::assertStringContainsString('mb_strlen',(string)$form);self::assertStringContainsString('mb_strlen($comments)>5000',(string)file_get_contents($root.'/app/Services/ApplicationReviewValidator.php'));self::assertStringContainsString('/assets/js/character-counter.js',(string)file_get_contents($root.'/resources/views/components/footer.php'));foreach(['<style','style=','<script'] as $inline)self::assertStringNotContainsString($inline,$form);}
 public function testFinalFormRefinementCssIsScopedAndResponsive():void{$css=(string)file_get_contents(dirname(__DIR__,2).'/public/assets/css/gateway.css');foreach(['.gateway-company-policy__notice { width:75%;max-width:100%; }','.gateway-company-policy__notice { width:100%; }','.gateway-prospect-information .gateway-prospect-field + .gateway-prospect-field { margin-top:-.5rem; }','.gateway-form-check--top-aligned { display:grid;grid-template-columns:auto minmax(0,1fr);column-gap:.75rem;align-items:start;padding-left:0; }','.gateway-form-check--top-aligned .form-check-input { float:none;margin:.2rem 0 0; }','.gateway-form-check--top-aligned .form-check-label,.gateway-form-check--top-aligned .invalid-feedback { grid-column:2; }'] as $rule)self::assertStringContainsString($rule,$css);self::assertStringNotContainsString('.gateway-alert--info { width:75%',$css);}
 private function expectValidation(ApplicationReviewValidator $v,array $bad):void{try{$v->decision($bad);self::fail('Invalid decision accepted.');}catch(InvalidApplicationReviewException){self::addToAssertionCount(1);}}
}
