<?php
declare(strict_types=1);
use NpmGateway\Database\Migration\CallLogDestinationsSchema;use PHPUnit\Framework\TestCase;
final class CallLogDestinationCompletionTest extends TestCase
{
 public function testApprovedMappingContractAndHistoricalIntegrity():void{$expected=['+12293544477'=>'Boulder Trails','+12295205722'=>'Crumley Farms','+16206807080'=>'Flamingo Flats','+13342038030'=>'Highridge','+17858027085'=>'Maplewind','+12292317979'=>'Pearce Pointe','+12292317090'=>'Pine Hill','+12292317927'=>'Wunderpark','+12297928075'=>'Suburban'];self::assertSame($expected,CallLogDestinationsSchema::MAPPINGS);$root=dirname(__DIR__,2);$migration=(string)file_get_contents($root.'/database/migrations/202608140025_complete_call_log_destinations.php');foreach(['property_code=?','incorrect existing Call Log destination','INSERT INTO call_log_destinations','SELECT COUNT(*) FROM call_logs','Suburban']as$text)self::assertStringContainsString($text,$migration);self::assertStringNotContainsString('INSERT IGNORE',$migration);self::assertStringNotContainsString('UPDATE properties',$migration);self::assertStringNotContainsString("['PM'",$migration);self::assertStringNotContainsString("['SM'",$migration);}
 public function testUnknownProtectionAndFailurePresentationRemainExplicit():void{$root=dirname(__DIR__,2);$service=(string)file_get_contents($root.'/app/Services/CallLogService.php');self::assertStringContainsString('not configured in Gateway',$service);self::assertStringContainsString('array_diff($tns,array_keys($destinations))',$service);self::assertLessThan(strpos($service,'$this->tx->begin()'),strpos($service,'$unknown='));$view=(string)file_get_contents($root.'/resources/views/admin/call-logs/upload.php');self::assertStringContainsString('gateway-alert--danger',$view);self::assertStringContainsString('data-error',$view);$js=(string)file_get_contents($root.'/public/assets/js/call-log-upload.js');foreach(['progress(0)','bg-danger','button.disabled=false','error.hidden=false']as$text)self::assertStringContainsString($text,$js);}
 public function testCallLogControlsAndSummaryUseResponsiveBootstrapLayout():void{$root=dirname(__DIR__,2);$view=(string)file_get_contents($root.'/resources/views/admin/call-logs/index.php');foreach(['method="get" action="/admin/call-logs"','d-flex flex-wrap align-items-end gap-2 mb-0','form-label mb-0','form-select mt-1','name="per_page"','type="submit">Apply','mt-3 mb-3','foreach([100,250,500]',' selected','http_build_query(','pageUrlPattern']as$text)self::assertStringContainsString($text,$view);self::assertLessThan(strpos($view,'mt-3 mb-3'),strpos($view,'name="per_page"'));$factory=(string)file_get_contents($root.'/app/Services/CallLogFilterCriteriaFactory.php');self::assertStringContainsString('if(!in_array($per,[100,250,500],true))$per=500',$factory);$controller=(string)file_get_contents($root.'/app/Http/Controllers/CallLogController.php');self::assertStringContainsString('call records imported successfully.',$controller);}
}
