<?php
declare(strict_types=1);
use NpmGateway\Services\CallLogFilterCriteriaFactory;use PHPUnit\Framework\TestCase;
final class CallLogFilteringTest extends TestCase
{
 private array$destinations=[['public_id'=>'AAAAAAAAAAAAAAAAAAAAAAAAAA','display_name'=>'Boulder Trails'],['public_id'=>'BBBBBBBBBBBBBBBBBBBBBBBBBB','display_name'=>'Suburban']];
 public function testDefaultsAndAllowedPagination():void{$factory=new CallLogFilterCriteriaFactory();$default=$factory->fromQuery([],$this->destinations);self::assertSame('',$default->fromDate);self::assertSame('',$default->toDate);self::assertSame('',$default->destinationPublicId);self::assertSame(1,$default->page);self::assertSame(500,$default->perPage);self::assertSame([],$default->errors);foreach([100,250,500]as$size)self::assertSame($size,$factory->fromQuery(['per_page'=>(string)$size],$this->destinations)->perPage);self::assertSame(500,$factory->fromQuery(['per_page'=>'999'],[])->perPage);}
 public function testInclusiveDateCriteriaUseExclusiveFollowingDay():void{$criteria=(new CallLogFilterCriteriaFactory())->fromQuery(['from'=>'2026-01-01','to'=>'2026-01-31'],$this->destinations);self::assertSame('2026-01-01',$criteria->fromDate);self::assertSame('2026-01-31',$criteria->toDate);self::assertSame('2026-02-01',$criteria->toExclusive);self::assertSame([],$criteria->errors);self::assertSame('2026-01-01',(new CallLogFilterCriteriaFactory())->fromQuery(['from'=>'2026-01-01'],[])->fromDate);self::assertSame('2026-02-01',(new CallLogFilterCriteriaFactory())->fromQuery(['to'=>'2026-01-31'],[])->toExclusive);}
 public function testInvalidDatesRangesDestinationAndPageAreSafe():void{$factory=new CallLogFilterCriteriaFactory();self::assertArrayHasKey('from',$factory->fromQuery(['from'=>'2026-02-30'],[])->errors);self::assertArrayHasKey('to',$factory->fromQuery(['to'=>'January 1'],[])->errors);self::assertArrayHasKey('date_range',$factory->fromQuery(['from'=>'2026-02-01','to'=>'2026-01-31'],[])->errors);self::assertArrayHasKey('property',$factory->fromQuery(['property'=>str_repeat('Z',26)],$this->destinations)->errors);self::assertSame(1,$factory->fromQuery(['page'=>'-2'],$this->destinations)->page);}
 public function testValidDestinationUsesOpaquePublicId():void{$criteria=(new CallLogFilterCriteriaFactory())->fromQuery(['property'=>$this->destinations[0]['public_id'],'page'=>'2','per_page'=>'250'],$this->destinations);self::assertSame($this->destinations[0]['public_id'],$criteria->destinationPublicId);self::assertSame(2,$criteria->page);self::assertSame(250,$criteria->perPage);self::assertTrue($criteria->active());self::assertSame([],$criteria->errors);}
 public function testRepositoryAndViewPreserveFilteringContract():void{$root=dirname(__DIR__,2);$repo=(string)file_get_contents($root.'/app/Repositories/CallLogRepository.php');foreach(['l.started_at>=?','l.started_at<?','d.public_id=?','SELECT COUNT(*)','ORDER BY l.started_at DESC,l.id DESC','LIMIT ? OFFSET ?']as$text)self::assertStringContainsString($text,$repo);$view=(string)file_get_contents($root.'/resources/views/admin/call-logs/index.php');foreach(['name="from"','name="to"','name="property"','All Properties','View Results','Clear Filters','name="per_page"','No calls found for the selected criteria.','call records have been imported',"'call':'calls'","?' found':''","'from'=>","'to'=>","'property'=>"]as$text)self::assertStringContainsString($text,$view);self::assertLessThan(strpos($view,'Calls per page'),strpos($view,'View Results'));}
}
