<?php
declare(strict_types=1);
use PHPUnit\Framework\TestCase;
final class CommunityActionsPresentationTest extends TestCase
{
 public function testDashboardCatalogAndCountMatchApprovedTwoRows():void{$root=dirname(__DIR__,2);$provider=new \NpmGateway\Services\UniversalToolProvider();$cards=$provider->tools();self::assertSame(['Company Directory','Properties','Community Actions','Notifications','Credit Card Purchases','Large File Transfers','Company Documents','Order Supplies'],array_map(static fn($card)=>$card->title,$cards));foreach(['Time Off Requests','Policies & Procedures','Training Library','Support Requests','Help Desk'] as $removed)self::assertNotContains($removed,array_map(static fn($card)=>$card->title,$cards));$dashboard=(string)file_get_contents($root.'/resources/views/dashboard.php');self::assertStringContainsString("count(\$toolSectionCards).' tools'",$dashboard);self::assertStringNotContainsString('12 tools',$dashboard);}
 public function testCommunityActionsRouteAndPlaceholderUseStandardComponents():void{$root=dirname(__DIR__,2);$routes=require $root.'/routes/web.php';self::assertSame(['GET'],$routes['/community-actions']['methods']);self::assertSame('community-actions.index',$routes['/community-actions']['name']);self::assertSame(['authentication'],$routes['/community-actions']['middleware']);$view=(string)file_get_contents($root.'/resources/views/community-actions/index.php');foreach(['Community Actions','Select a community to access property management tasks and operational activities.','No communities are available.','You do not currently have access to any Community Actions workspaces.','breadcrumb.php','page-header.php','empty-state.php'] as $required)self::assertStringContainsString($required,$view);foreach(['<style','style=','<script','Corporate Tools'] as $forbidden)self::assertStringNotContainsString($forbidden,$view);$kernel=(string)file_get_contents($root.'/app/Http/WebKernel.php');self::assertStringContainsString("path==='/community-actions'",$kernel);}
 public function testRemovedDashboardCardsDoNotDeleteLegacyRoutes():void{$routes=(string)file_get_contents(dirname(__DIR__,2).'/routes/web.php');self::assertIsString($routes);self::assertStringNotContainsString("'/community-actions'.*corporate",$routes);}
}
