<?php
declare(strict_types=1);
use NpmGateway\Services\CompanyNoticeReviewStore;
use NpmGateway\Services\CompanyNoticeValidator;
use NpmGateway\Support\PublicIdGenerator;
use PHPUnit\Framework\TestCase;
final class CompanyNoticesTest extends TestCase
{
 public function testMigration009ChangesOnlyApprovedChecksAndGuardsRollback():void{$s=(string)file_get_contents(dirname(__DIR__,2).'/database/migrations/202608020009_company_notices_category.php');foreach(['chk_user_category_access_category','company-notices','chk_notifications_type','company_notice','assertConstraint','Unsupported category rows','historical notices exist'] as $v)self::assertStringContainsString($v,$s);foreach(['CREATE TABLE','ADD COLUMN','ADD INDEX','FOREIGN KEY'] as $v)self::assertStringNotContainsString($v,$s);}
 public function testRoutesAndCorporateOrderAreApproved():void{$routes=require dirname(__DIR__,2).'/routes/web.php';foreach(['/company-notices','/company-notices/create','/company-notices/preview','/company-notices/publish','/company-notices/{notificationPublicId}'] as $path){self::assertArrayHasKey($path,$routes);self::assertContains('company-notices-access',$routes[$path]['middleware']);}$provider=(string)file_get_contents(dirname(__DIR__,2).'/app/Services/CorporateToolsProvider.php');self::assertLessThan(strpos($provider,"['marketing'"),strpos($provider,"['company-notices'"));}
 public function testValidatorPreservesPlainTextAndSanitizesRichHtml():void{$v=new CompanyNoticeValidator();$data=$v->validate(['title'=>' Notice Title ','message'=>"First paragraph.\n\nSecond paragraph.",'priority'=>'important','requires_acknowledgment'=>'no']);self::assertSame('Notice Title',$data['title']);self::assertFalse($data['requires_acknowledgment']);self::assertSame('First paragraph.',$v->summary($data['message']));$rich=$v->validate(['title'=>'Good','message'=>'fallback','rich_message_html'=>'<p class="bad" onclick="x()">Safe <strong>content</strong><script>bad()</script></p>','priority'=>'normal','requires_acknowledgment'=>'yes']);self::assertSame('<p>Safe <strong>content</strong></p>',$rich['rich_message_html']);try{$v->validate(['title'=>'<b>Bad</b>','message'=>'ok','priority'=>'normal','requires_acknowledgment'=>'yes']);self::fail('HTML title accepted.');}catch(InvalidArgumentException){self::addToAssertionCount(1);}}
 public function testReviewTokenIsOpaqueOwnerBoundAndOneTimeState():void{$session=[];$store=new CompanyNoticeReviewStore($session,new PublicIdGenerator());$token=$store->create(7,['title'=>'Confidential title','message'=>'Full message']);self::assertStringNotContainsString('Full message',$token);self::assertNull($store->get($token,8));self::assertSame('Full message',$store->get($token,7)['data']['message']);$store->complete($token,str_repeat('N',26));self::assertNull($store->get($token,7)['data']);self::assertSame(str_repeat('N',26),$store->get($token,7)['published']);}
 public function testSecondReviewSupersedesFirstAndRenderingDoesNotConsumeIt():void{$now=1000;$session=[];$store=new CompanyNoticeReviewStore($session,new PublicIdGenerator(),function()use(&$now){return $now;});$first=$store->create(7,['title'=>'First','message'=>'Original','priority'=>'normal','requires_acknowledgment'=>true]);self::assertSame('created',$store->resolve($first,7)['status']);self::assertSame('created',$store->resolve($first,7)['status']);$second=$store->create(7,['title'=>'Second','message'=>'Edited','priority'=>'urgent','requires_acknowledgment'=>false]);self::assertSame('superseded',$store->resolve($first,7)['status']);self::assertSame('created',$store->resolve($second,7)['status']);self::assertSame('Edited',$store->get($second,7)['data']['message']);self::assertSame($second,$store->active(7)['token']);self::assertNull($store->active(8));self::assertSame('unavailable',$store->resolve($second,8)['status']);}
 public function testExpiredReviewHasExplicitStateAndCannotBeCompleted():void{$now=1000;$session=[];$store=new CompanyNoticeReviewStore($session,new PublicIdGenerator(),function()use(&$now){return $now;});$token=$store->create(7,['title'=>'Expiring']);$now=1901;self::assertSame('expired',$store->resolve($token,7)['status']);$store->complete($token,str_repeat('N',26));self::assertSame('expired',$store->resolve($token,7)['status']);self::assertNull($store->get($token,7));}
 public function testComposeAndReviewViewsContainRequiredControlsAndNoDraftRoute():void{$root=dirname(__DIR__,2);$create=(string)file_get_contents($root.'/resources/views/company-notices/create.php');foreach(['Create Company Notice','All Active Gateway Users','Notice Message','requires_acknowledgment','Review Notice','_token'] as $v)self::assertStringContainsString($v,$create);self::assertStringNotContainsString('contenteditable',$create);$review=(string)file_get_contents($root.'/resources/views/company-notices/review.php');self::assertStringContainsString('Publishing will immediately create Gateway notifications',$review);self::assertStringContainsString('review_token',$review);self::assertStringNotContainsString('name="message"',$review);$routes=(string)file_get_contents($root.'/routes/web.php');self::assertStringNotContainsString('company-notices/drafts',$routes);}
 public function testComposePageUsesApprovedResponsiveWorkflowAndMarkup():void
 {
  $view=(string)file_get_contents(dirname(__DIR__,2).'/resources/views/company-notices/create.php');
  $headings=['Notice Information','Audience','Message','Publishing Options'];$last=-1;foreach($headings as $heading){$position=strpos($view,'>'.$heading.'</h2>');self::assertNotFalse($position);self::assertGreaterThan($last,$position);$last=$position;}
  self::assertStringContainsString('class="form-control w-100<?= $invalid(\'title\') ?>"',$view);
  self::assertStringContainsString('class="form-control w-100 gateway-notice-message<?= $invalid(\'message\') ?>"',$view);
  self::assertStringContainsString('rows="9"',$view);self::assertStringContainsString('maxlength="10000"',$view);
  self::assertGreaterThan(strpos($view,'>Publishing Options</h2>'),strpos($view,'>Priority</label>'));
  self::assertGreaterThan(strpos($view,'>Priority</label>'),strpos($view,'>Requires Acknowledgment</legend>'));
  self::assertStringContainsString('$old(\'priority\',\'normal\')',$view);self::assertStringContainsString('$old(\'requires_acknowledgment\',\'yes\')',$view);
  self::assertStringContainsString('$e($old(\'message\'))',$view);self::assertStringContainsString('aria-describedby="company-notice-message-help',$view);
  self::assertStringContainsString('Category: <strong>General Company Notice</strong>',$view);self::assertStringContainsString('All Active Gateway Users',$view);
  foreach(['name="recipients"','contenteditable','<script','style=','modal','rich-text','markdown'] as $forbidden)self::assertStringNotContainsString($forbidden,$view);
  foreach(['gateway-property-form-card','gateway-form-section','row gateway-form-grid','col-12','col-md-6','d-flex flex-wrap'] as $responsive)self::assertStringContainsString($responsive,$view);
 }
}
