<?php
declare(strict_types=1);
use NpmGateway\Exceptions\Domain\InvalidCreditCardPurchaseException;
use NpmGateway\Services\CreditCardPurchaseValidator;
use PHPUnit\Framework\TestCase;

final class CreditCardPurchaseCorrectionsTest extends TestCase
{
 private function valid():array{return ['card_last_four'=>'0425','purchase_date'=>'2026-08-05','amount'=>'639.05','purchased_by_employee_public_id'=>str_repeat('A',26),'vendor'=>'Lowe’s','description'=>'Maintenance materials.','missing_receipt_reason'=>'The vendor did not provide a receipt.','record_version'=>str_repeat('V',26),'correction_reason'=>'Correcting a one-cent transcription error.'];}
 public function testCorrectionReusesValidationAndKeepsExactDecimalStrings():void{$data=(new CreditCardPurchaseValidator())->validateCorrection($this->valid(),'missing',new DateTimeImmutable('2026-08-05'));self::assertSame('639.05',$data['amount']);self::assertSame('0425',$data['card_last_four']);foreach(['1e3','639.005','0','-1','1,000.00'] as $amount){try{(new CreditCardPurchaseValidator())->validateCorrection(array_replace($this->valid(),['amount'=>$amount]),'missing',new DateTimeImmutable('2026-08-05'));self::fail('Malformed correction amount accepted.');}catch(InvalidCreditCardPurchaseException){self::addToAssertionCount(1);}}}
 public function testCorrectionReasonIsRequiredTrimmedAndPlainText():void{foreach(['','         ','short','<b>Incorrect amount</b>',str_repeat('x',501)] as $reason){try{(new CreditCardPurchaseValidator())->validateCorrection(array_replace($this->valid(),['correction_reason'=>$reason]),'missing',new DateTimeImmutable('2026-08-05'));self::fail('Unsafe correction reason accepted.');}catch(InvalidCreditCardPurchaseException $e){self::assertArrayHasKey('correction_reason',$e->errors);}}}
 public function testControlledEditRoutesAndFormContract():void{$root=dirname(__DIR__,2);$routes=require $root.'/routes/web.php';self::assertSame(['GET'],$routes['/community-actions/{propertySlug}/credit-card-purchases/{purchasePublicId}/edit']['methods']);self::assertContains('POST',$routes['/community-actions/{propertySlug}/credit-card-purchases/{purchasePublicId}']['methods']);$edit=(string)file_get_contents($root.'/resources/views/community-actions/credit-card-purchases/edit.php');foreach(['Reason for Correction','Briefly explain why this purchase record is being changed.','Saving correction…','record_version','Purchase Information'] as $required)self::assertStringContainsString($required,$edit);foreach(['name="property','name="public_id','name="submitted_by','name="submitted_at','name="receipt"','storage_object','Delete','<script','style='] as $forbidden)self::assertStringNotContainsString($forbidden,$edit);}
 public function testHistoryConcurrencyAndSanitizedAuditContract():void{$root=dirname(__DIR__,2);$show=(string)file_get_contents($root.'/resources/views/community-actions/credit-card-purchases/show.php');foreach(['Edit Purchase','Reason for Correction','Amount changed from','Purchased At changed from','Purchased By changed from'] as $required)self::assertStringContainsString($required,$show);$service=(string)file_get_contents($root.'/app/Services/CreditCardPurchaseService.php');$repo=(string)file_get_contents($root.'/app/Repositories/CreditCardPurchaseRepository.php');foreach(['credit_card_purchase.corrected','controlled_correction','changed_fields','prior_amount','new_amount','hash_equals($this->version($locked)','No purchase information was changed.',' FOR UPDATE'] as $required)self::assertStringContainsString($required,$service.$repo);self::assertStringNotContainsString('(float)',$service.$repo.(string)file_get_contents($root.'/app/Services/CreditCardPurchaseValidator.php'));$audit=substr($service,(int)strpos($service,"\$this->audits->record('credit_card_purchase.corrected"));$audit=substr($audit,0,(int)strpos($audit,'$this->tx->commit'));foreach(['correction_reason','missing_receipt_reason','description','object_key','filename','email','raw_post'] as $private)self::assertStringNotContainsString("'{$private}'",$audit);}
 public function testDocumentationDefinesControlledCorrectionPolicy():void{$root=dirname(__DIR__,2);$docs=(string)file_get_contents($root.'/docs/credit-card-purchases.md').(string)file_get_contents($root.'/docs/architecture/GATEWAY_CONSTITUTION.md');foreach(['controlled corrections','original submitter','append-only','stale','decimal strings','silently deleted or overwritten'] as $required)self::assertStringContainsStringIgnoringCase($required,$docs);}
}
