<?php
declare(strict_types=1);
use PHPUnit\Framework\TestCase;
final class DocumentViewerTest extends TestCase
{
 private string $root;
 protected function setUp():void{$this->root=dirname(__DIR__,2);}
 public function testSharedComponentHasOneAccessibleViewerAndAllStates():void{$source=(string)file_get_contents($this->root.'/resources/views/components/document-viewer.php');self::assertSame(1,substr_count($source,'data-document-viewer hidden'));foreach(['role="dialog"','aria-modal="true"','aria-labelledby="gateway-document-viewer-title"','data-document-viewer-close','Open in New Tab','Download','data-document-viewer-pdf','data-document-viewer-image','Loading document…','The document could not be displayed.'] as $required)self::assertStringContainsString($required,$source);foreach(['Wasabi','object_key','bucket','credit_card_purchase','<script','style='] as $forbidden)self::assertStringNotContainsString($forbidden,$source);}
 public function testGenericControllerValidatesRoutesMimeFocusAndSources():void{$source=(string)file_get_contents($this->root.'/public/assets/js/document-viewer.js');foreach(['data-document-viewer-trigger','application/pdf','image/jpeg','image/png','safeRoute','window.location.origin','frame.src = viewRoute','image.src = viewRoute','removeAttribute(\'src\')','event.key === \'Escape\'','dialog.focus()','opener?.focus()','node.inert = true','WeakSet','This file type cannot be displayed in Gateway.'] as $required)self::assertStringContainsString($required,$source);foreach(['wasabi','http://','https://','jquery','<script'] as $forbidden)self::assertStringNotContainsString($forbidden,strtolower($source));}
 public function testReceiptTriggerUsesOnlyPublicAuthorizedRoutesAndSafeMetadata():void{$source=(string)file_get_contents($this->root.'/resources/views/community-actions/credit-card-purchases/show.php');foreach(['data-document-viewer-trigger','data-document-view-url','data-document-download-url','data-document-title="Credit Card Receipt"','data-document-mime','receipt_public_id','/receipts/','/view','/download','View Receipt','document-viewer.php'] as $required)self::assertStringContainsString($required,$source);foreach(['storage_public_id','object_key','provider_container','target="_blank"'] as $forbidden)self::assertStringNotContainsString($forbidden,$source);self::assertSame(1,substr_count($source,"document-viewer.php"));}
 public function testDocumentResponsesAreRestrictedAndHardened():void{$controller=(string)file_get_contents($this->root.'/app/Http/Controllers/CreditCardPurchaseController.php');$repo=(string)file_get_contents($this->root.'/app/Repositories/CreditCardPurchaseRepository.php');foreach(['application/pdf','image/jpeg','image/png',"'inline'","'attachment'",'Content-Length','private, no-store','Pragma','nosniff','same-origin',"frame-ancestors 'self'",'available($object)'] as $required)self::assertStringContainsString($required,$controller);foreach(['p.public_id=?','pr.public_id=?','p.property_id=?','pr.superseded_at IS NULL',"s.lifecycle_state='published'"] as $required)self::assertStringContainsString($required,$repo);self::assertStringNotContainsString('object_key',$controller);}
 public function testRoutesAndDocumentationDefineReusableContract():void{$routes=(string)file_get_contents($this->root.'/routes/web.php');foreach(['/{receiptPublicId}/view','/{receiptPublicId}/download'] as $route)self::assertStringContainsString($route,$routes);$docs=(string)file_get_contents($this->root.'/docs/document-viewer.md');foreach(['PDFs','JPEGs','PNGs','frame-ancestors','HTTP byte ranges','fake storage','Future renovation'] as $required)self::assertStringContainsString($required,$docs);}
 public function testPolishedHeaderKeepsCallerTitleAndAccessibleFilenameHierarchy():void{$component=(string)file_get_contents($this->root.'/resources/views/components/document-viewer.php');$script=(string)file_get_contents($this->root.'/public/assets/js/document-viewer.js');$css=(string)file_get_contents($this->root.'/public/assets/css/gateway.css');self::assertStringContainsString('gateway-document-viewer__identity',$component);self::assertStringContainsString('class="gateway-document-viewer__filename"',$component);self::assertStringNotContainsString('Credit Card Receipt',$component.$script);foreach(['title.textContent = trigger.dataset.documentTitle','filename.textContent = trigger.dataset.documentFilename','filename.title = trigger.dataset.documentFilename'] as $required)self::assertStringContainsString($required,$script);foreach(['padding:.875rem 1.25rem','font-size:.78rem','overflow-wrap:anywhere','word-break:break-word','min-height:2.75rem','flex-wrap:wrap'] as $required)self::assertStringContainsString($required,$css);self::assertLessThan(strpos($component,'>Download</a>'),strpos($component,'Open in New Tab'));self::assertLessThan(strpos($component,'>Close</button>'),strpos($component,'>Download</a>'));foreach(['<script','style='] as $forbidden)self::assertStringNotContainsString($forbidden,$component);}
}
