<?php
declare(strict_types=1);
use NpmGateway\ValueObjects\AuthenticatedUser;
use PHPUnit\Framework\TestCase;
final class HrEmergencyContactActionPresentationTest extends TestCase
{
 public function testActionsMatchMissingAvailableMissingUnavailableAndCompletedStates():void
 {
  $html=$this->render();$document=new DOMDocument();$previous=libxml_use_internal_errors(true);$document->loadHTML($html);libxml_clear_errors();libxml_use_internal_errors($previous);$xpath=new DOMXPath($document);
  $available=$this->row($xpath,'Available Employee');self::assertStringContainsString('Send Reminder',$available->textContent);self::assertSame(1,$xpath->query('./td[last()]/button[contains(concat(" ",normalize-space(@class)," ")," btn-outline-primary ") and contains(concat(" ",normalize-space(@class)," ")," btn-sm ") and @data-bs-toggle="modal"]',$available)->length);self::assertSame(1,$xpath->query('.//svg',$available)->length);
  $unavailable=$this->row($xpath,'Unavailable Employee');self::assertStringContainsString('No current primary property is configured.',$unavailable->textContent);self::assertStringNotContainsString('Send Reminder',$unavailable->textContent);self::assertSame(0,$xpath->query('.//button',$unavailable)->length);
  $completed=$this->row($xpath,'Completed Employee');self::assertSame('View',trim($xpath->query('./td[last()]',$completed)->item(0)->textContent));self::assertStringNotContainsString('Emergency Contact Information is already complete.',$completed->textContent);self::assertStringNotContainsString('Send Reminder',$completed->textContent);self::assertSame(0,$xpath->query('.//button',$completed)->length);
 }
 public function testSummaryUsesAccessibleSuccessAndNeutralTreatments():void{$html=$this->render();self::assertStringContainsString('class="gateway-eci-summary d-flex flex-wrap gap-2"',$html);self::assertStringContainsString('aria-label="Emergency Contact Information completion summary"',$html);self::assertStringContainsString('gateway-status--success">1 Completed',$html);self::assertStringContainsString('gateway-status--neutral">2 Missing',$html);self::assertStringNotContainsString('gateway-status--danger',$html);$css=(string)file_get_contents(dirname(__DIR__,2).'/public/assets/css/gateway.css');self::assertStringContainsString('.gateway-eci-summary { margin-bottom:2.5rem; }',$css);self::assertStringContainsString('.gateway-eci-summary .gateway-status { padding:.45rem .85rem; }',$css);self::assertStringContainsString('.gateway-eci-summary .gateway-status--neutral { font-weight:750; }',$css);}
 public function testModalPostAccessibilityAndLocalMarkupRemainIntact():void{$html=$this->render();self::assertStringContainsString('data-bs-target="#remind-', $html);self::assertStringContainsString('data-bs-toggle="modal"',$html);self::assertStringContainsString('action="/corporate/human-resources/emergency-contacts/', $html);self::assertStringContainsString('/remind" data-processing-form',$html);self::assertStringContainsString('name="_token"',$html);self::assertStringContainsString('aria-label="Send ECI reminder',$html);self::assertStringContainsString('<svg class="align-text-bottom"',$html);foreach(['font-awesome','cdnjs'] as $forbidden)self::assertStringNotContainsString($forbidden,$html);$view=(string)file_get_contents(dirname(__DIR__,2).'/resources/views/human-resources/emergency-contacts/index.php');foreach(['<script','style='] as $forbidden)self::assertStringNotContainsString($forbidden,$view);}
 private function row(DOMXPath $xpath,string $employee):DOMElement{$nodes=$xpath->query('//tr[td[1][normalize-space(.)="'.$employee.'"]]');self::assertSame(1,$nodes->length);$row=$nodes->item(0);self::assertInstanceOf(DOMElement::class,$row);return $row;}
 private function render():string{$root=dirname(__DIR__,2);$id1=str_repeat('A',26);$id2=str_repeat('B',26);$id3=str_repeat('C',26);$rows=[['employee_public_id'=>$id1,'display_name'=>'Available Employee','employee_class'=>'corporate','primary_property'=>'Corporate','eci_status'=>'missing','updated_at'=>null,'reminder'=>['status'=>'available']],['employee_public_id'=>$id2,'display_name'=>'Unavailable Employee','employee_class'=>'maintenance','primary_property'=>'—','eci_status'=>'missing','updated_at'=>null,'reminder'=>['status'=>'missing_property']],['employee_public_id'=>$id3,'display_name'=>'Completed Employee','employee_class'=>'manager','primary_property'=>'Crumley Farms','eci_status'=>'completed','updated_at'=>'2026-08-04 12:00:00']];$summary=['completed'=>1,'missing'=>2];$status='all';$employeeClass='all';$search='';$success='';$csrfToken='csrf';$logoutCsrfToken='csrf';$navbarCorporateItems=[];$user=new AuthenticatedUser(1,1,str_repeat('U',26),str_repeat('E',26),'tester','Test User');ob_start();require $root.'/resources/views/human-resources/emergency-contacts/index.php';return (string)ob_get_clean();}
}
