<?php
declare(strict_types=1);
use PHPUnit\Framework\TestCase;
final class HrEmergencyContactAdministrationTest extends TestCase
{
 public function testHrRoutesAreReadOnlyExceptReminder():void{$routes=require dirname(__DIR__,2).'/routes/web.php';self::assertArrayHasKey('/corporate/human-resources/emergency-contacts',$routes);self::assertArrayHasKey('/corporate/human-resources/emergency-contacts/{employeePublicId}',$routes);self::assertArrayHasKey('/corporate/human-resources/emergency-contacts/{employeePublicId}/remind',$routes);self::assertArrayNotHasKey('/corporate/human-resources/emergency-contacts/{employeePublicId}/edit',$routes);self::assertSame(['POST'],$routes['/corporate/human-resources/emergency-contacts/{employeePublicId}/remind']['methods']);}
 public function testHrPresentationHasNoMutationAndUsesAccessibleLocalEmailAction():void{$root=dirname(__DIR__,2);$index=(string)file_get_contents($root.'/resources/views/human-resources/emergency-contacts/index.php');$show=(string)file_get_contents($root.'/resources/views/human-resources/emergency-contacts/show.php');foreach(['Send Reminder','icon-email.php','aria-label','data-bs-toggle="modal"','data-processing-form'] as $required)self::assertStringContainsString($required,$index);foreach(['/edit','>Edit<','View unavailable','visually-hidden">Email reminder'] as $forbidden){self::assertStringNotContainsString($forbidden,$index);self::assertStringNotContainsString($forbidden,$show);}self::assertFileDoesNotExist($root.'/resources/views/human-resources/emergency-contacts/edit.php');}
 public function testManagerMaintenanceWorkflowUsesSharedSaveAndServerResolvedScope():void{$root=dirname(__DIR__,2);$routes=require $root.'/routes/web.php';$path='/manager/maintenance/{employeePublicId}/emergency-contact';self::assertSame(['GET','POST'],$routes[$path]['methods']);self::assertSame(['authentication'],$routes[$path]['middleware']);$controller=(string)file_get_contents($root.'/app/Http/Controllers/ManagerMaintenanceEmergencyContactController.php');foreach(['authorizedTarget','saveForMaintenanceByManager',"['Cache-Control'=>'private, no-store']"] as $required)self::assertStringContainsString($required,$controller);foreach(["post['employee_id']","post['employee_public_id']","post['property_id']"] as $override)self::assertStringNotContainsString($override,$controller);$access=(string)file_get_contents($root.'/app/Services/ManagerMaintenanceEciAccessService.php');foreach(['employeeClass!==\'manager\'','findAuthorizedMaintenanceForManager'] as $required)self::assertStringContainsString($required,$access);$repository=(string)file_get_contents($root.'/app/Repositories/EmployeeEmergencyContactRepository.php');foreach(["target.employee_class='maintenance'","target.employment_status='active'","manager.employee_class='manager'","manager.employment_status='active'",'manager_assignment.property_id=p.id','starts_on<=CURRENT_DATE','ends_on IS NULL'] as $required)self::assertStringContainsString($required,$repository);}
 public function testManagerFormReusesMaskValidationProcessingAndSafeAudits():void{$root=dirname(__DIR__,2);$view=(string)file_get_contents($root.'/resources/views/manager/maintenance-emergency-contact.php');foreach(['First Name','Last Name','Relationship','Primary Phone','Alternate Phone (Optional)','Cancel','Save Emergency Contact','data-phone-mask','data-processing-form'] as $required)self::assertStringContainsString($required,$view);foreach(['<script','style='] as $forbidden)self::assertStringNotContainsString($forbidden,$view);$service=(string)file_get_contents($root.'/app/Services/EmployeeEmergencyContactService.php');foreach(['employee.emergency_contact_created_by_manager','employee.emergency_contact_updated_by_manager','acting_manager_public_id','property_public_id','alternate_phone_present','$data=$this->validate($submitted)'] as $required)self::assertStringContainsString($required,$service);foreach(['created_by_hr','updated_by_hr'] as $forbidden)self::assertStringNotContainsString($forbidden,$service);}
 public function testReminderRoutingCooldownAndContentFollowOwnershipRules():void{$root=dirname(__DIR__,2);$service=(string)file_get_contents($root.'/app/Services/EciReminderService.php');foreach(['employee_business_email','property_manager_mailbox','existsEventForEntitySince','employee.emergency_contact_reminder_sent'] as $required)self::assertStringContainsString($required,$service);$mail=(string)file_get_contents($root.'/app/Notifications/EciReminderEmailSender.php');self::assertStringContainsString("'/manager/maintenance/'.\$employee['public_id'].'/emergency-contact'",$mail);self::assertStringContainsString("'/my/emergency-contact'",$mail);self::assertStringNotContainsString('/corporate/human-resources/emergency-contacts/',$mail);foreach(['relationship','primaryPhone','alternatePhone'] as $private)self::assertStringNotContainsString($private,$mail);}
}
