<?php declare(strict_types=1);namespace NpmGateway\Tests\Unit;use NpmGateway\Services\{MarketingFlyerImageProcessor,MarketingFlyerMonthOptions};use PHPUnit\Framework\TestCase;
final class MarketingFlyersFoundationTest extends TestCase{
 public function testMonthsKeepFloorAndExtendTwelveMonths():void{$m=new MarketingFlyerMonthOptions();$options=$m->options(new \DateTimeImmutable('2027-01-15'));self::assertSame('August 2026',$options['2026-08']);self::assertSame('January 2028',$options['2028-01']);self::assertSame('2027-01-01',$m->normalize('2027-01',new \DateTimeImmutable('2027-01-15')));}
 public function testValidationKeepsOriginalAndDoesNotExposeThumbnailGeneration():void{$path=tempnam(sys_get_temp_dir(),'flyer-test-');$im=imagecreatetruecolor(850,1100);imagepng($im,$path);imagedestroy($im);$before=hash_file('sha256',$path);try{$processor=new MarketingFlyerImageProcessor();$valid=$processor->validate(['name'=>'flyer.png','tmp_name'=>$path,'size'=>filesize($path),'error'=>UPLOAD_ERR_OK]);self::assertSame('image/png',$valid['mime_type']);self::assertSame($before,hash_file('sha256',$path));self::assertFalse(method_exists($processor,'thumbnail'));}finally{@unlink($path);}}
 public function testLandscapeIsRejected():void{$path=tempnam(sys_get_temp_dir(),'flyer-test-');$im=imagecreatetruecolor(200,100);imagejpeg($im,$path);imagedestroy($im);try{$this->expectException(\InvalidArgumentException::class);(new MarketingFlyerImageProcessor())->validate(['name'=>'x.jpg','tmp_name'=>$path,'size'=>filesize($path),'error'=>UPLOAD_ERR_OK]);}finally{@unlink($path);}}
 public function testRoutesSeparateMarketingAndManagerBoundaries():void{$routes=require dirname(__DIR__,2).'/routes/web.php';foreach(['/corporate/marketing/flyers/{flyerPublicId}/thumbnail','/community-actions/{propertySlug}/flyers/{flyerPublicId}','/community-actions/{propertySlug}/flyers/{flyerPublicId}/view']as$route)self::assertArrayNotHasKey($route,$routes);foreach(['/corporate/marketing/flyers/{flyerPublicId}/view','/corporate/marketing/flyers/{flyerPublicId}/download','/corporate/marketing/flyers/{flyerPublicId}/replace','/corporate/marketing/flyers/{flyerPublicId}/delete']as$route)self::assertContains('marketing-access',$routes[$route]['middleware']);self::assertSame(['authentication'],$routes['/community-actions/{propertySlug}/flyers/{flyerPublicId}/download']['middleware']);$controller=(string)file_get_contents(dirname(__DIR__,2).'/app/Http/Controllers/MarketingFlyerController.php');self::assertStringNotContainsString('managerShow',$controller);self::assertStringNotContainsString('managerAsset',$controller);self::assertStringContainsString('managerDownload',$controller);}
 public function testLibraryOrdersNewestUploadsFirstDeterministically():void{$repository=(string)file_get_contents(dirname(__DIR__,2).'/app/Repositories/MarketingFlyerRepository.php');self::assertStringContainsString('ORDER BY f.uploaded_at DESC,f.id DESC',$repository);}
 public function testManagerDownloadUsesPrivateCanonicalStreamingHeaders():void{$controller=(string)file_get_contents(dirname(__DIR__,2).'/app/Http/Controllers/MarketingFlyerController.php');foreach(["'Content-Disposition'=>",'attachment',"'Cache-Control'=>'private, no-store'","'Pragma'=>'no-cache'","'X-Content-Type-Options'=>'nosniff'",'$this->service->open($flyer)']as$value)self::assertStringContainsString($value,$controller);foreach(['Location','wasabisys','object_key=']as$value)self::assertStringNotContainsString($value,substr($controller,(int)strpos($controller,'public function managerDownload')));}
}
