<?php declare(strict_types=1);namespace NpmGateway\Tests\Unit;
use NpmGateway\Notifications\MarketingFlyerEmailSender;use PHPMailer\PHPMailer\PHPMailer;use PHPUnit\Framework\TestCase;
final class MarketingFlyerCompletionBoundaryTest extends TestCase{
 private function config():array{return['test_mode'=>true,'test_email'=>'flyer-test@example.test','app_url'=>'https://gateway.example.test','smtp'=>['host'=>'smtp.example.test','port'=>587,'username'=>'fake-user','password'=>'fake-password','secure'=>'tls','from_address'=>'no-reply@npmpropertiesinc.com','from_name'=>'NPM Gateway','recipients'=>'unused@example.test','environment'=>'testing']];}
 private function flyer():array{return['flyer_month'=>'2026-08-01','flyer_type'=>'standard','property_name'=>'Timing Property','uploaded_by_name'=>'Timing User','updated_at'=>'2026-08-12 22:08:29','public_id'=>str_repeat('T',26),'object_key'=>'flyers/2026/08/TP-2026-08.png','mime_type'=>'image/png'];}
 private function elapsed(int$delayMicroseconds):array{$attempts=0;$path=tempnam(sys_get_temp_dir(),'flyer-timing-');file_put_contents($path,'fake attachment bytes');try{$sender=new MarketingFlyerEmailSender($this->config(),static function()use(&$attempts,$delayMicroseconds):PHPMailer{$attempts++;return new MarketingFlyerTimedMailer($delayMicroseconds);});$started=hrtime(true);$result=$sender->send($this->flyer(),['manager-one@example.test','manager-two@example.test'],$path);return['milliseconds'=>(hrtime(true)-$started)/1_000_000,'attempts'=>$attempts,'result'=>$result];}finally{@unlink($path);}}
 public function testFastFakeNotifierReturnsPromptlyAndTestModeAttemptsOnce():void{$timing=$this->elapsed(0);self::assertLessThan(100,$timing['milliseconds']);self::assertSame(1,$timing['attempts']);self::assertSame(1,$timing['result']['sent']);}
 public function testSlowMailerBlocksNotifierReturnForItsFullDuration():void{$timing=$this->elapsed(250_000);self::assertGreaterThanOrEqual(225,$timing['milliseconds']);self::assertLessThan(1000,$timing['milliseconds']);self::assertSame(1,$timing['attempts']);self::assertSame(1,$timing['result']['sent']);}
 public function testServiceQueuesBeforeCommitAndNeverSendsEmail():void{$root=dirname(__DIR__,2);$service=(string)file_get_contents($root.'/app/Services/MarketingFlyerService.php');$controller=(string)file_get_contents($root.'/app/Http/Controllers/MarketingFlyerController.php');$enqueue=(int)strpos($service,'$this->outbox->enqueue');$commit=(int)strpos($service,'$db->commit()');self::assertGreaterThan($enqueue,$commit);self::assertStringNotContainsString('notifier->send',$service);self::assertStringNotContainsString('MarketingFlyerEmailSender',$service);$save=(int)strpos($controller,'$result=$this->service->save');$json=(int)strpos($controller,"Response::json(['ok'=>true");self::assertGreaterThan($save,$json);}
 public function testUploadJavascriptDoesNotTrapNavigation():void{$js=(string)file_get_contents(dirname(__DIR__,2).'/public/assets/js/marketing-flyer-upload.js');foreach(['beforeunload','unload','window.on','document.querySelectorAll','pointerEvents','inert','focus(']as$blocking)self::assertStringNotContainsString($blocking,$js);self::assertSame(1,substr_count($js,'button.disabled=true'));}
 public function testRepositoryNowHasDurableDeferredDeliveryWithoutPostResponseHack():void{$root=dirname(__DIR__,2);$repository=(string)file_get_contents($root.'/app/Repositories/MarketingFlyerNotificationOutboxRepository.php');self::assertStringContainsString('marketing_flyer_notification_outbox',$repository);self::assertStringContainsString("status='processing'",$repository);$source=(string)file_get_contents($root.'/app/Services/MarketingFlyerService.php');self::assertStringNotContainsString('fastcgi_finish_request',$source);}
}
final class MarketingFlyerTimedMailer extends PHPMailer{public function __construct(private readonly int$delayMicroseconds){parent::__construct();}public function send():bool{if($this->delayMicroseconds>0)usleep($this->delayMicroseconds);return true;}}
