<?php
declare(strict_types=1);
use NpmGateway\Services\EmployeeAnnouncementFactory;
use NpmGateway\ValueObjects\NotificationCount;
use NpmGateway\Notifications\CompanyAnnouncementEmailSender;
use NpmGateway\Services\HrEmployeeNotificationConfig;
use NpmGateway\Support\PhoneFormatter;
use NpmGateway\Support\CompanyDateFormatter;
use NpmGateway\Services\EmployeeAnnouncementEmailBuilder;
use NpmGateway\Notifications\CompanyAnnouncementEmailRenderer;
use NpmGateway\ValueObjects\CompanyAnnouncementEmail;
use PHPMailer\PHPMailer\PHPMailer;
use PHPUnit\Framework\TestCase;
final class NotificationsFoundationTest extends TestCase
{
 public function testEmployeeSnapshotContainsExactlyApprovedFields():void{$a=(new EmployeeAnnouncementFactory())->create(str_repeat('E',26),['first_name'=>'Kathrina','last_name'=>'Petty','job_title'=>'Manager','start_date'=>'2026-08-02','company_phone'=>'+15551234567','business_email'=>'k@example.com','context_name'=>'Highridge','password'=>'secret','date_of_birth'=>'2000-01-01']);self::assertSame(['employee_name','job_title','start_date','company_phone','business_email','primary_property'],array_keys($a->payload));self::assertSame('Kathrina Petty',$a->payload['employee_name']);self::assertStringNotContainsString('secret',json_encode($a->payload,JSON_THROW_ON_ERROR));}
 public function testCountLabelsAreTruthful():void{self::assertSame('No outstanding notices',(new NotificationCount(0))->label());self::assertSame('3 require acknowledgment',(new NotificationCount(3))->label());}
 public function testRoutesAreAuthenticatedAndUsePublicIds():void{$routes=require dirname(__DIR__,2).'/routes/web.php';foreach(['/notifications','/notifications/{notificationPublicId}','/notifications/{notificationPublicId}/acknowledge'] as $route)self::assertContains('authentication',$routes[$route]['middleware']);self::assertSame(['POST'],$routes['/notifications/{notificationPublicId}/acknowledge']['methods']);}
 public function testMigrationContainsHistoricalConstraintsAndGuard():void{$source=file_get_contents(dirname(__DIR__,2).'/database/migrations/202608020008_notifications.php');foreach(['uq_notifications_source','uq_notification_recipients_notice_user','ON DELETE RESTRICT','payload JSON NOT NULL','skipped_no_email','Cannot roll back Notifications'] as $required)self::assertStringContainsString($required,$source);self::assertStringNotContainsString('ON DELETE CASCADE',$source);}
 public function testPrivacyAndAcknowledgmentWording():void{$root=dirname(__DIR__,2);$show=file_get_contents($root.'/resources/views/notifications/show.php');self::assertStringContainsString('I Have Read This Notice',$show);foreach(['password','date_of_birth','personal_phone','personal_email','comments'] as $private)self::assertStringNotContainsString($private,$show);}
 public function testCompanyEmailIsBrandedMultipartFormattedAndEscaped():void{$mail=new NotificationCapturingMailer();$config=HrEmployeeNotificationConfig::fromArray(['host'=>'smtp.example.test','port'=>587,'username'=>'user','password'=>'secret','secure'=>'tls','from_address'=>'no-reply@npmpropertiesinc.com','from_name'=>'NPM Gateway','recipients'=>'hr@example.test','environment'=>'testing']);$announcement=(new EmployeeAnnouncementFactory())->create(str_repeat('E',26),['first_name'=>'A <script>','last_name'=>'Person','job_title'=>'Manager & Lead','start_date'=>'2026-08-02','company_phone'=>'+15551234567','business_email'=>'a@example.test','context_name'=>'Highridge']);$renderer=new CompanyAnnouncementEmailRenderer();$builder=new EmployeeAnnouncementEmailBuilder(new CompanyDateFormatter(),new PhoneFormatter());$sender=new CompanyAnnouncementEmailSender($config,$builder,$renderer,static fn():PHPMailer=>$mail);self::assertTrue($sender->send('recipient@example.test',$announcement));self::assertSame('New Employee — A <script> Person',$mail->Subject);self::assertStringNotContainsString('SECURE',$mail->Subject);self::assertSame('no-reply@npmpropertiesinc.com',$mail->From);foreach(['NPM GATEWAY','COMPANY ANNOUNCEMENT','New Employee','Employee Name','Job Title','Start Date','Company Phone','Business Email','Primary Property','Please welcome A &lt;script&gt; Person to the NPM team.','NPM Gateway — Internal company communication'] as $text)self::assertStringContainsString($text,$mail->Body);self::assertStringContainsString('role="presentation"',$mail->Body);self::assertStringContainsString('table-layout:fixed',$mail->Body);self::assertStringContainsString('word-break:break-word',$mail->Body);self::assertStringContainsString('mailto:a@example.test',$mail->Body);self::assertStringContainsString('August 2, 2026',$mail->Body);self::assertStringContainsString('(555) 123-4567',$mail->Body);self::assertStringNotContainsString('2026-08-02',$mail->Body);self::assertStringNotContainsString('+15551234567',$mail->Body);self::assertStringContainsString('A &lt;script&gt; Person',$mail->Body);self::assertStringNotContainsString('<script>',$mail->Body);foreach(['NPM GATEWAY','COMPANY ANNOUNCEMENT','NEW EMPLOYEE','Employee Name: A <script> Person','Start Date: August 2, 2026','Company Phone: (555) 123-4567','NPM Gateway — Internal company communication'] as $text)self::assertStringContainsString($text,$mail->AltBody);foreach(['password','date_of_birth','personal_phone','personal_email','comments'] as $private){self::assertStringNotContainsString($private,$mail->Body);self::assertStringNotContainsString($private,$mail->AltBody);}}
 public function testGenericRendererSupportsFutureAnnouncementWithoutEmployeeLayoutCode():void{$message=new CompanyAnnouncementEmail('NPM GATEWAY','COMPANY ANNOUNCEMENT','New Property','A property has joined NPM.',['0'=>['label'=>'Property Name','value'=>'River & Oaks']],'Please welcome River & Oaks.','NPM Gateway — Internal company communication');$rendered=(new CompanyAnnouncementEmailRenderer())->render($message);self::assertStringContainsString('New Property',$rendered['html']);self::assertStringContainsString('River &amp; Oaks',$rendered['html']);self::assertStringContainsString('PROPERTY NAME: RIVER & OAKS',strtoupper($rendered['text']));$sender=(string)file_get_contents(dirname(__DIR__,2).'/app/Notifications/CompanyAnnouncementEmailSender.php');self::assertStringNotContainsString('<!doctype html>',$sender);}
}
final class NotificationCapturingMailer extends PHPMailer { public function send():bool{return true;} }
