<?php
declare(strict_types=1);
namespace Tests\Unit;
use NpmGateway\ValueObjects\RmCorrectionOverviewCriteria;use PHPUnit\Framework\TestCase;
final class OperationsOverviewTest extends TestCase
{
 private string $root;
 protected function setUp():void{$this->root=dirname(__DIR__,2);}
 public function testRoutesAreOperationsOnlyGetRoutesUsingPublicIds():void{$routes=require$this->root.'/routes/web.php';foreach(['/corporate/operations/overview','/corporate/operations/overview/rm-corrections','/corporate/operations/overview/rm-corrections/{requestPublicId}']as$path){self::assertSame(['GET'],$routes[$path]['methods']);self::assertSame(['authentication','operations-access'],$routes[$path]['middleware']);}self::assertStringNotContainsString('{requestId}',(string)file_get_contents($this->root.'/routes/web.php'));}
 public function testLandingAndOperationsNavigationExposePresentationOnlyOverview():void{$controller=(string)file_get_contents($this->root.'/app/Http/Controllers/CorporateWorkspaceController.php');$overview=(string)file_get_contents($this->root.'/app/Http/Controllers/OperationsOverviewController.php');$landing=(string)file_get_contents($this->root.'/resources/views/corporate/operations/overview/index.php');foreach(['Overview','Read-only operational reporting','/corporate/operations/overview']as$v)self::assertStringContainsString($v,$controller);foreach(['RM Corrections','Review Rent Manager correction activity across all communities.','View RM Corrections']as$v)self::assertStringContainsString($v,$overview);self::assertStringContainsString('gateway-tool-grid',$landing);foreach(['<form','Approve','Deny','Need More Info']as$v)self::assertStringNotContainsString($v,$landing);}
 public function testCriteriaDefaultsToCurrentLocalMonthAndUsesHalfOpenRange():void{$now=new \DateTimeImmutable('2026-08-07 12:00:00',new \DateTimeZone('America/New_York'));$c=RmCorrectionOverviewCriteria::fromQuery([],$now,[]);self::assertSame('2026-08-01',$c->from);self::assertSame('2026-08-07',$c->to);self::assertSame('2026-08-01 00:00:00',$c->startBoundary);self::assertSame('2026-08-08 00:00:00',$c->endBoundary);self::assertSame([],$c->errors);}
 public function testCriteriaRejectsInvalidReversedExcessiveAndUnknownPropertyWhilePreservingInput():void{$now=new \DateTimeImmutable('2026-08-07');$props=[['public_id'=>str_repeat('A',26)]];foreach([[['from'=>'bad','to'=>'2026-08-07'],'from'],[['from'=>'2026-08-08','to'=>'2026-08-07'],'range'],[['from'=>'2000-01-01','to'=>'2026-08-07'],'range'],[['from'=>'2026-08-01','to'=>'2026-08-07','property'=>str_repeat('B',26)],'property']]as[$query,$key]){$c=RmCorrectionOverviewCriteria::fromQuery($query,$now,$props);self::assertArrayHasKey($key,$c->errors);self::assertSame((string)$query['from'],$c->from);}}
 public function testReportViewGroupsWithoutRepeatingPropertyColumnAndPreservesFilters():void{$view=(string)file_get_contents($this->root.'/resources/views/corporate/operations/overview/rm-corrections/index.php');foreach(['From Date','To Date','All Properties','View Results','Date range applies to the RM Correction submission date.','pending_review','approved','denied','more_information_needed','GatewayDateTimeFormatter','propertyName','criteria->query()']as$v)self::assertStringContainsString($v,$view);self::assertStringNotContainsString('<th>Property</th>',$view);self::assertStringNotContainsString('property_id',$view);}
 public function testDetailReusesSharedRecordAndHasNavigationOnly():void{$view=(string)file_get_contents($this->root.'/resources/views/corporate/operations/overview/rm-corrections/show.php');foreach(['Operations Overview',"['label'=>'Detail','current'=>true]",'$heading=\'RM Correction\'','Read-only operational detail','rm-correction-detail.php','Back to RM Corrections','criteria->query()','$actionsHtml=\'\'']as$v)self::assertStringContainsString($v,$view);foreach(['<form','type="submit"','Approve','Deny','Need More Info','Respond to Request','Edit','Delete','$actionsHtml=\'<span']as$v)self::assertStringNotContainsString($v,$view);}
 public function testArchitectureIsReadOnlyAndIndependentOfWorkflowAuthority():void{$controller=(string)file_get_contents($this->root.'/app/Http/Controllers/OperationsOverviewController.php');$repo=(string)file_get_contents($this->root.'/app/Repositories/RmCorrectionRepository.php');foreach(["canAccessCategory(\$c,'operations')",'private, no-store','OperationsRmCorrectionOverviewService']as$v)self::assertStringContainsString($v,$controller);foreach(['RmCorrectionService','RmCorrectionEmailSender','PropertyAccessService','decide(','respond(','POST']as$v)self::assertStringNotContainsString($v,$controller);foreach(['r.submitted_at>=?','r.submitted_at<?','p.public_id=?','ORDER BY p.display_name,p.id,r.submitted_at DESC']as$v)self::assertStringContainsString($v,$repo);}
 public function testSummaryAndRowsUseAuthoritativeStatusBadgeComponent():void{$view=(string)file_get_contents($this->root.'/resources/views/corporate/operations/overview/rm-corrections/index.php');$status=(string)file_get_contents($this->root.'/app/Services/RmCorrectionStatus.php');$component=(string)file_get_contents($this->root.'/resources/views/components/status-badge.php');self::assertStringContainsString('gateway-status gateway-status--neutral',$view);self::assertSame(2,substr_count($view,"require\$components.'/status-badge.php'"));foreach(['pending_review','approved','denied','more_information_needed']as$key)self::assertStringContainsString("'{$key}'",$status);foreach(['neutral','success','danger','warning']as$type){self::assertStringContainsString("'{$type}'",$status);self::assertStringContainsString('gateway-status--',$component);}foreach(['statusLabel','statusType','labels[$status]','badges[$status]','labels[$row[\'status\']]','badges[$row[\'status\']]']as$v)self::assertStringContainsString($v,$view);foreach(['class="badge ','style=','<style']as$v)self::assertStringNotContainsString($v,$view);}
 public function testDetailProminentBadgeUsesCentralizedMappingWithoutRestoringDetailAction():void{$view=(string)file_get_contents($this->root.'/resources/views/corporate/operations/overview/rm-corrections/show.php');$status=(string)file_get_contents($this->root.'/app/Services/RmCorrectionStatus.php');foreach(['RmCorrectionStatus::LABELS','RmCorrectionStatus::BADGES',"require\$components.'/status-badge.php'",'$statusHtml=','$actionsHtml=\'\'',"['label'=>'Detail','current'=>true]",'Current Status','Back to RM Corrections']as$v)self::assertStringContainsString($v,$view.(string)file_get_contents($this->root.'/resources/views/components/rm-correction-detail.php'));foreach(["'pending_review'=>'Pending Review'","'approved'=>'Approved'","'denied'=>'Denied'","'more_information_needed'=>'More Information Needed'","'pending_review'=>'neutral'","'approved'=>'success'","'denied'=>'danger'","'more_information_needed'=>'warning'"]as$v)self::assertStringContainsString($v,$status);foreach(['$actionsHtml=\'<span','Approve','Deny','Need More Info','Respond to Request','Edit','Delete','<form']as$v)self::assertStringNotContainsString($v,$view);}
}
