<?php
declare(strict_types=1);
namespace Tests\Unit;
use NpmGateway\Database\Migration\OperationsCategorySchema;use PHPUnit\Framework\TestCase;
final class OperationsCorporateExpansionTest extends TestCase
{
 public function testCategoryOrderAndMigrationContract():void{$root=dirname(__DIR__,2);$config=require$root.'/config/corporate-access.php';self::assertSame(['operations','human-resources','company-notices','application-reviews','rm-corrections','finance','marketing','admin','credit-cards'],array_keys($config['categories']));self::assertSame('202608030012_operations_category',OperationsCategorySchema::MIGRATION);$migration=(string)file_get_contents($root.'/database/migrations/202608030012_operations_category.php');foreach(['user_category_access','chk_user_category_access_category',"category='operations'",'Cannot roll back Operations']as$v)self::assertStringContainsString($v,$migration);foreach(['ADD COLUMN','CREATE TABLE','ADD INDEX','FOREIGN KEY']as$v)self::assertStringNotContainsString($v,$migration);}
 public function testCorporateCardsAndRoutesUseApprovedOrder():void{$root=dirname(__DIR__,2);$provider=(string)file_get_contents($root.'/app/Services/CorporateToolsProvider.php');$positions=[];foreach(['operations','human-resources','company-notices','application-reviews','finance','marketing','admin','credit-cards']as$key)$positions[]=strpos($provider,"['{$key}'");self::assertSame($positions,array_values($positions));for($i=1;$i<count($positions);$i++)self::assertGreaterThan($positions[$i-1],$positions[$i]);$routes=require$root.'/routes/web.php';foreach(['/corporate/operations','/corporate/operations/overview','/corporate/operations/inventory-cf','/corporate/operations/inventory-hr','/corporate/operations/development','/corporate/marketing','/corporate/marketing/flyers']as$route)self::assertArrayHasKey($route,$routes);self::assertContains('operations-access',$routes['/corporate/operations']['middleware']);self::assertContains('marketing-access',$routes['/corporate/marketing/flyers']['middleware']);}
 public function testWorkspacePresentationIsCompleteAndSafe():void{$root=dirname(__DIR__,2);$controller=(string)file_get_contents($root.'/app/Http/Controllers/CorporateWorkspaceController.php');foreach(['Inventory – CF','Inventory – HR','Development','Flyers','Overview','operations','marketing']as$v)self::assertStringContainsString($v,$controller);self::assertSame(4,substr_count($controller,'new ToolCard(',0,(int)strpos($controller,'public function inventoryCf')));foreach(['resources/views/corporate/operations/index.php','resources/views/corporate/marketing/index.php','resources/views/corporate/planned.php']as$file){$html=(string)file_get_contents($root.'/'.$file);self::assertStringNotContainsString('<style',$html);self::assertStringNotContainsString('<script',$html);self::assertStringNotContainsString('sidebar',$html);self::assertStringContainsString('breadcrumb.php',$html);}self::assertStringContainsString("\$emptyTitle='Module planned'",(string)file_get_contents($root.'/resources/views/corporate/planned.php'));}
 public function testBackfillIsExplicitAndLimited():void{$root=dirname(__DIR__,2);$service=(string)file_get_contents($root.'/app/Services/OperationsAccessBackfillService.php');foreach(["['chuck','tim']","'category'=>'operations'",'begin()','commit()','rollback()']as$v)self::assertStringContainsString($v,$service);self::assertStringNotContainsString('hayleigh',$service);$cli=(string)file_get_contents($root.'/bin/gateway');self::assertStringContainsString('operations-access:backfill',$cli);}
}
