<?php declare(strict_types=1);namespace Tests\Unit;
use NpmGateway\Services\OperationsRmAuditStatus;use NpmGateway\ValueObjects\RmAuditOverviewCriteria;use PHPUnit\Framework\TestCase;
final class OperationsRmAuditOverviewTest extends TestCase
{
 private string $root;
 protected function setUp():void{$this->root=dirname(__DIR__,2);}
 public function testRoutesAreOperationsOnlyReadOnlyPublicIdRoutes():void{$routes=require$this->root.'/routes/web.php';foreach(['/corporate/operations/overview/rm-audits','/corporate/operations/overview/rm-audits/{auditPublicId}']as$path){self::assertSame(['GET'],$routes[$path]['methods']);self::assertSame(['authentication','operations-access'],$routes[$path]['middleware']);}}
 public function testCriteriaDefaultsAndHalfOpenInclusiveToBoundary():void{$now=new \DateTimeImmutable('2026-08-08 18:00:00',new \DateTimeZone('America/New_York'));$criteria=RmAuditOverviewCriteria::fromQuery([],$now,[]);self::assertSame('2026-08-01',$criteria->from);self::assertSame('2026-08-08',$criteria->to);self::assertSame('2026-08-01 00:00:00',$criteria->startBoundary);self::assertSame('2026-08-09 00:00:00',$criteria->endBoundary);self::assertSame('',$criteria->propertyPublicId);self::assertSame('all',$criteria->status);self::assertSame([],$criteria->errors);}
 public function testCriteriaRejectsBadDatesRangeAndUntrustedProperty():void{$now=new \DateTimeImmutable('2026-08-08');$properties=[['public_id'=>str_repeat('A',26)]];foreach([[['from'=>'','to'=>'2026-08-08'],'from'],[['from'=>'2026-02-30','to'=>'2026-08-08'],'from'],[['from'=>'2026-08-01','to'=>'nope'],'to'],[['from'=>'2026-08-09','to'=>'2026-08-08'],'range'],[['from'=>'2026-08-01','to'=>'2026-08-08','property'=>str_repeat('B',26)],'property']]as[$query,$error])self::assertArrayHasKey($error,RmAuditOverviewCriteria::fromQuery($query,$now,$properties)->errors);self::assertSame(str_repeat('A',26),RmAuditOverviewCriteria::fromQuery(['from'=>'2026-08-01','to'=>'2026-08-08','property'=>str_repeat('A',26)],$now,$properties)->propertyPublicId);}
 public function testCriteriaAllowsOnlyAllOrOpenStatusAndPreservesIt():void{$now=new \DateTimeImmutable('2026-08-08');foreach(['', 'all']as$status){$criteria=RmAuditOverviewCriteria::fromQuery(['from'=>'2026-08-01','to'=>'2026-08-08','status'=>$status],$now,[]);self::assertSame('all',$criteria->status);self::assertSame([],$criteria->errors);} $open=RmAuditOverviewCriteria::fromQuery(['from'=>'2026-08-01','to'=>'2026-08-08','status'=>'open'],$now,[]);self::assertSame('open',$open->status);self::assertStringContainsString('status=open',$open->query());foreach(['completed','returned',"open' OR 1=1 --"]as$status)self::assertArrayHasKey('status',RmAuditOverviewCriteria::fromQuery(['from'=>'2026-08-01','to'=>'2026-08-08','status'=>$status],$now,[])->errors);}
 public function testOperationsProjectionIsCentralizedAndDoesNotAlterAuthoritativeStatus():void{self::assertSame('open',OperationsRmAuditStatus::project('open'));self::assertSame('open',OperationsRmAuditStatus::project('returned'));self::assertSame('completed',OperationsRmAuditStatus::project('completed'));self::assertSame(['open'=>'Open','completed'=>'Completed'],OperationsRmAuditStatus::LABELS);self::assertSame(['open'=>'warning','completed'=>'success'],OperationsRmAuditStatus::BADGES);$authoritative=(string)file_get_contents($this->root.'/app/Services/RmAuditStatus.php');self::assertStringContainsString("'returned'=>'Returned'",$authoritative);}
 public function testRepositoryQueryUsesAuthoritativeRowsAndRequiredOrdering():void{$repository=(string)file_get_contents($this->root.'/app/Repositories/RmAuditRepository.php');foreach(['a.audit_findings_html','a.submitted_at>=?','a.submitted_at<?','p.public_id=?',"p.status='active'","p.slug<>'corporate'","a.status IN ('open','returned')",'ORDER BY p.display_name,p.id,a.submitted_at DESC,a.id DESC']as$value)self::assertStringContainsString($value,$repository);foreach(['reporting','summary','INSERT INTO rm_audit_overview']as$value)self::assertStringNotContainsString($value,$repository);}
 public function testReportRendersCanonicalFindingsGroupedAndPreservesFilters():void{$view=(string)file_get_contents($this->root.'/resources/views/corporate/operations/overview/rm-audits/index.php');foreach(['From Date','To Date','All Properties','Status','All Audits','Open Only','name="status"','View Results','audit_findings_html','gateway-rich-content','operations_status','criteria->query()','propertyName','Submitted <time']as$value)self::assertStringContainsString($value,$view);foreach(['htmlspecialchars((string)$row[\'audit_findings_html\']','Search','DataTable','Returned','<th>Property</th>']as$value)self::assertStringNotContainsString($value,$view);}
 public function testDetailReusesCertifiedTimelineAndHasNoWorkflowControls():void{$view=(string)file_get_contents($this->root.'/resources/views/corporate/operations/overview/rm-audits/show.php');foreach(['Read-only operational detail','Operations Status','rm-audit-detail.php','Back to RM Audits','criteria->query()','OperationsRmAuditStatus']as$value)self::assertStringContainsString($value,$view);foreach(['<form','Mark Completed','Return Audit','type="submit"','Create','Edit','Delete']as$value)self::assertStringNotContainsString($value,$view);$component=(string)file_get_contents($this->root.'/resources/views/components/rm-audit-detail.php');foreach(['Submitted','Completed','Returned','comments','audit_findings_html']as$value)self::assertStringContainsString($value,$component);}
 public function testControllerHasOnlyOperationsAuthorityAndReadDependencies():void{$controller=(string)file_get_contents($this->root.'/app/Http/Controllers/OperationsOverviewController.php');foreach(["canAccessCategory(\$c,'operations')",'OperationsRmAuditOverviewService','private, no-store']as$value)self::assertStringContainsString($value,$controller);foreach(['RmAuditService','RmAuditEmailSender','PropertyAccessService','returnAudit(','complete(','POST']as$value)self::assertStringNotContainsString($value,$controller);}
}
