<?php declare(strict_types=1);namespace Tests\Unit;use PHPUnit\Framework\TestCase;
final class OperationsRmAuditPrintPresentationTest extends TestCase
{
 private string $root;
 protected function setUp():void{$this->root=dirname(__DIR__,2);}
 public function testViewActionIsBesideStatusAndOccursOncePerRecordTemplate():void{$view=(string)file_get_contents($this->root.'/resources/views/corporate/operations/overview/rm-audits/index.php');self::assertSame(1,substr_count($view,'gateway-rm-audit-view'));self::assertStringContainsString('gateway-rm-audit-record__actions',$view);self::assertStringContainsString("require\$components.'/status-badge.php';?><a class=\"btn btn-sm btn-outline-primary gateway-rm-audit-view\"",$view);self::assertStringContainsString('criteria->query()',$view);self::assertStringContainsString('overflow-wrap:anywhere',(string)file_get_contents($this->root.'/public/assets/css/gateway.css'));}
 public function testPrintActionAndPrintableIdentityUseCurrentSharedReport():void{$view=(string)file_get_contents($this->root.'/resources/views/corporate/operations/overview/rm-audits/index.php');foreach(['type="button" data-print-report','Download PDF','/corporate/operations/overview/rm-audits/pdf?','criteria->query()','gateway-print-only','NPM Properties Inc.','NPM Gateway','From Date','To Date','selectedProperty',"report['total']","report['counts']",'propertyName','audit_findings_html','operations_status','No RM Audits found for the selected criteria.']as$value)self::assertStringContainsString($value,$view);foreach(['method="post"','audit_ids']as$value)self::assertStringNotContainsString($value,$view);}
 public function testScopedPrintCssHidesInteractiveChromeAndKeepsReadableStatus():void{$css=(string)file_get_contents($this->root.'/public/assets/css/gateway.css');foreach(['@media print','.gateway-app-header','.gateway-footer','.gateway-rm-audit-filters','.gateway-rm-audit-report-actions','.gateway-rm-audit-view','display:none!important','gateway-rm-audit-print-header','.gateway-status','color:#111!important','background:#fff!important','orphans:3','widows:3','a::after']as$value)self::assertStringContainsString($value,$css);self::assertSame(1,substr_count($css,'@media print'));
 }
 public function testApprovedPdfEndpointIsGetOnlyAndOperationsAuthorized():void{$composer=(array)json_decode((string)file_get_contents($this->root.'/composer.json'),true,512,JSON_THROW_ON_ERROR);self::assertArrayHasKey('dompdf/dompdf',$composer['require']);foreach(['mpdf/mpdf','tecnickcom/tcpdf','setasign/fpdf']as$library)self::assertArrayNotHasKey($library,$composer['require']);$routes=require$this->root.'/routes/web.php';$route=$routes['/corporate/operations/overview/rm-audits/pdf'];self::assertSame(['GET'],$route['methods']);self::assertSame(['authentication','operations-access'],$route['middleware']);}
}
