<?php declare(strict_types=1);namespace Tests\Unit;use PHPUnit\Framework\TestCase;
final class OperationsRmAuditPdfTest extends TestCase
{
 private string $root;
 protected function setUp():void{$this->root=dirname(__DIR__,2);}
 public function testPdfControllerIsReadOnlyOperationsAuthorizedAndSafe():void{$source=(string)file_get_contents($this->root.'/app/Http/Controllers/OperationsRmAuditPdfController.php');foreach(["canAccessCategory(\$context,'operations')",'RmAuditOverviewCriteria::fromQuery','audits->report($criteria)','GatewayPdfDocument','Content-Type','application/pdf','Content-Disposition','private, no-store','X-Content-Type-Options','operations_rm_audits','exception_class']as$value)self::assertStringContainsString($value,$source);foreach(['RmAuditService','RmAuditEmailSender','PropertyAccessService','INSERT','UPDATE','DELETE','audit_findings_html']as$value)self::assertStringNotContainsString($value,$source);}
 public function testFilenameUsesOnlyApprovedPropertyAndDates():void{$source=(string)file_get_contents($this->root.'/app/Http/Controllers/OperationsRmAuditPdfController.php');foreach(["'RM-Audits'","criteria->from","'_to_'","criteria->to","preg_replace('/[^A-Za-z0-9]+/'"]as$value)self::assertStringContainsString($value,$source);foreach(['tenant_name','unit_identifier','property_id']as$value)self::assertStringNotContainsString($value,$source);}
 public function testDedicatedTemplateUsesSharedProjectedModelAndCanonicalFindings():void{$view=(string)file_get_contents($this->root.'/resources/views/pdf/operations-rm-audits.php');foreach(['NPM Properties Inc.','NPM Gateway','RM Audits','From Date','To Date','Status','All Audits','Open Only','criteria->status','propertyName',"report['total']","report['counts']['open']","report['counts']['completed']",'report[\'groups\']','tenant_name','unit_identifier','GatewayDateTimeFormatter','OperationsRmAuditStatus::LABELS','operations_status','audit_findings_html','No RM Audits found for the selected criteria.','DejaVu Sans']as$value)self::assertStringContainsString($value,$view);self::assertStringNotContainsString('returned',$view);self::assertStringNotContainsString('gateway.css',$view);}
 public function testPdfButtonCarriesOnlyValidatedCriteriaAndPrintHidesIt():void{$view=(string)file_get_contents($this->root.'/resources/views/corporate/operations/overview/rm-audits/index.php');self::assertStringContainsString('/rm-audits/pdf?<?=$e($criteria->query())?>',$view);self::assertStringNotContainsString('audit_ids',$view);$css=(string)file_get_contents($this->root.'/public/assets/css/gateway.css');self::assertStringContainsString('.gateway-rm-audit-report-actions',$css);}
}
