<?php
declare(strict_types=1);
use PHPUnit\Framework\TestCase;
final class PropertyRoutesAndViewsTest extends TestCase
{
    public function testNamedRoutesAndAuthorizationBoundariesAreDeclared():void
    {
        $routes=require dirname(__DIR__,2).'/routes/web.php';self::assertSame('properties.index',$routes['/properties']['name']);self::assertSame(['authentication'],$routes['/properties']['middleware']);self::assertSame('hr.index',$routes['/human-resources']['name']);self::assertSame('hr.properties.create',$routes['/human-resources/properties/create']['name']);self::assertSame(['GET'],$routes['/human-resources/properties/create']['methods']);self::assertContains('corporate-access',$routes['/human-resources/properties/create']['middleware']);self::assertSame('hr.properties.store',$routes['/human-resources/properties']['names']['POST']);self::assertNotContains('PUT',$routes['/human-resources/properties']['methods']);self::assertNotContains('DELETE',$routes['/human-resources/properties']['methods']);
    }
    public function testIndexUsesNormalCreateLinkWithoutPropertyModalBehavior():void
    {
        $view=(string)file_get_contents(dirname(__DIR__,2).'/resources/views/properties/index.php');self::assertStringContainsString('<a class="btn gateway-button gateway-button--primary" href="/human-resources/properties/create">Add Property</a>',$view);self::assertStringNotContainsString('data-bs-toggle',$view);self::assertStringNotContainsString('data-bs-target',$view);self::assertStringNotContainsString('modal',$view);self::assertFileDoesNotExist(dirname(__DIR__,2).'/resources/views/properties/modal.php');
    }
    public function testCreatePageAndReusableFormContainApprovedWorkflow():void
    {
        $root=dirname(__DIR__,2);$page=(string)file_get_contents($root.'/resources/views/human-resources/properties/create.php');$form=(string)file_get_contents($root.'/resources/views/human-resources/properties/_form.php');foreach(['Dashboard','Human Resources','Properties','Add Property','Create a new company property and operational context.'] as $text)self::assertStringContainsString($text,$page);foreach(['prop_id','property_code','display_name','slug','status','address_line_1','city','state','postal_code','timezone','office_phone','manager_email','website_url','ivr_number','ivr_routing_email'] as $field)self::assertStringContainsString("'{$field}'",$form);self::assertStringContainsString('name="_token"',$form);self::assertStringContainsString('method="post" action="/human-resources/properties"',$form);self::assertStringContainsString('href="/human-resources/properties">Cancel</a>',$form);self::assertStringContainsString('Create Property</button>',$form);self::assertStringContainsString('America/New_York',$form);self::assertStringContainsString('America/Chicago',$form);self::assertStringContainsString('property-validation-summary',$form);self::assertStringNotContainsString('manager_name',$form);self::assertStringNotContainsString('IVR exemption',$form);self::assertStringNotContainsString('modal',$page.$form);self::assertStringNotContainsString('Corporate option',$form);
    }
    public function testSharedFormUsesConsistentReusableSpacingStructure():void
    {
        $root=dirname(__DIR__,2);$form=(string)file_get_contents($root.'/resources/views/human-resources/properties/_form.php');$css=(string)file_get_contents($root.'/public/assets/css/gateway.css');self::assertSame(4,substr_count($form,'<section class="gateway-form-section"'));self::assertSame(4,substr_count($form,'class="gateway-form-section-title"'));self::assertSame(4,substr_count($form,'class="row gateway-form-grid"'));self::assertSame(1,substr_count($form,'class="gateway-form-actions"'));self::assertStringContainsString('Cancel</a>',$form);self::assertStringContainsString('Create Property</button>',$form);self::assertStringNotContainsString('style=',$form);self::assertStringNotContainsString('modal',$form);foreach(['.gateway-form-section {','.gateway-form-section:first-child {','.gateway-form-section-title {','.gateway-form-grid {','.gateway-form-actions {'] as $selector)self::assertStringContainsString($selector,$css);self::assertStringNotContainsString('nth-child',$css);
    }
    public function testPhoneMaskMarkupAndSharedAssetAreProgressiveAndScoped():void
    {
        $root=dirname(__DIR__,2);$form=(string)file_get_contents($root.'/resources/views/human-resources/properties/_form.php');$footer=(string)file_get_contents($root.'/resources/views/components/footer.php');$page=(string)file_get_contents($root.'/resources/views/human-resources/properties/create.php');self::assertSame(1,substr_count($form,'data-phone-mask'));self::assertStringContainsString("'office_phone','Phone','tel','Format: (000) 000-0000'",$form);self::assertStringContainsString("'ivr_number','IVR Phone','tel','Format: (000) 000-0000'",$form);self::assertSame(1,substr_count($form,'inputmode="tel"'));self::assertStringContainsString("true,'tel'",$form);self::assertStringContainsString("true,'off'",$form);foreach(['prop_id','postal_code','manager_email','ivr_routing_email'] as $field)self::assertDoesNotMatchRegularExpression('/'.$field.'.{0,100}true,/s',$form);self::assertStringContainsString('<script type="module" src="/assets/js/phone-mask.js"></script>',$footer);self::assertStringNotContainsString('<script>',$form.$page);self::assertStringContainsString('$pageHeaderSpacious=true',$page);
    }
    public function testSharedTableRetainsExactColumnsAndNoninteractiveAction():void
    {
        $view=(string)file_get_contents(dirname(__DIR__,2).'/resources/views/components/property-table.php');$positions=[];foreach(['PropID','Name','Address','Phone','IVR','Manager'] as $label){$positions[]=strpos($view,'>'.$label.'<');self::assertNotFalse(end($positions));}$sorted=$positions;sort($sorted);self::assertSame($sorted,$positions);self::assertStringContainsString('Editing not yet enabled',$view);self::assertStringNotContainsString('<a',$view);self::assertStringNotContainsString('<button',$view);
    }
}
