<?php
declare(strict_types=1);
use NpmGateway\Contracts\AuditStoreInterface;
use NpmGateway\Contracts\ClockInterface;
use NpmGateway\Contracts\InitializationTransactionInterface;
use NpmGateway\Contracts\PropertyAccessStoreInterface;
use NpmGateway\Http\AuthenticatedRequestContext;
use NpmGateway\Services\AuditService;
use NpmGateway\Services\PropertyAccessPayloadParser;
use NpmGateway\Services\PropertyAccessService;
use NpmGateway\Support\PublicIdGenerator;
use NpmGateway\ValueObjects\AuthenticatedUser;
use PHPUnit\Framework\TestCase;
final class PropertyAccessFoundationTest extends TestCase
{
 public function testMigrationDeclaresNarrowRestrictiveCurrentStateSchema():void{$root=dirname(__DIR__,2);$migration=(string)file_get_contents($root.'/database/migrations/202608040014_user_property_access.php');foreach(['user_property_access','UNIQUE KEY uq_user_property_access_user_property','fk_user_property_access_user','fk_user_property_access_property','ON DELETE RESTRICT','Cannot roll back Property Access','utf8mb4_0900_ai_ci'] as $required)self::assertStringContainsString($required,$migration);foreach(['property_code','display_name','employee_class','email','assignment_type','CASCADE'] as $forbidden)self::assertStringNotContainsString($forbidden,$migration);}
 public function testMatrixShowsAllEmployeesAndDisablesIneligibleRows():void{$store=$this->store();$matrix=$this->service($store)->accessMatrix();self::assertSame(['Alpha Property','Beta Property','Corporate'],array_column($matrix['properties'],'display_name'));self::assertCount(4,$matrix['employees']);self::assertTrue($matrix['employees'][0]['assignable']);self::assertTrue($matrix['employees'][1]['assignable']);self::assertFalse($matrix['employees'][2]['assignable']);self::assertSame('No Gateway access',$matrix['employees'][2]['reason']);self::assertFalse($matrix['employees'][3]['assignable']);self::assertSame('Inactive',$matrix['employees'][3]['reason']);}
 public function testExplicitGrantsAloneDriveAccessibleActiveCommunities():void{$store=$this->store();$context=$this->context(10,'manager');$service=$this->service($store);self::assertSame(['Alpha Property'],$service->accessibleActiveCommunities($context)===[]?[]:array_column($service->accessibleActiveCommunities($context),'display_name'));self::assertTrue($service->canAccessProperty($context,101));self::assertFalse($service->canAccessProperty($context,102));self::assertSame('authorized',$service->resolveAccessibleCommunity($context,'alpha')['status']);self::assertSame('forbidden',$service->resolveAccessibleCommunity($context,'beta')['status']);self::assertSame('not_found',$service->resolveAccessibleCommunity($context,'unknown')['status']);}
 public function testCorporateGrantIsNotACommunityActionContext():void{$store=$this->store();$store->members[10][103]=true;$store->members[20]=[103=>true];$service=$this->service($store);self::assertSame(['Alpha Property'],array_column($service->accessibleActiveCommunities($this->context(10,'corporate')),'display_name'));self::assertSame([],$service->accessibleActiveCommunities($this->context(20,'corporate')));self::assertSame('not_found',$service->resolveAccessibleCommunity($this->context(10,'corporate'),'corporate')['status']);self::assertTrue($service->canAccessProperty($this->context(10,'corporate'),103));self::assertContains('Corporate',array_column($service->accessMatrix()['properties'],'display_name'));}
 public function testCorporateOnlyAccessRendersEmptyStateAndDirectRoutesReturnNotFound():void{$store=$this->store();$store->members=[20=>[103=>true]];$service=$this->service($store);$session=[];$tools=new class implements \NpmGateway\Contracts\CorporateToolsProviderInterface{public function tools(AuthenticatedRequestContext $context):array{return [];}};$controller=new \NpmGateway\Http\Controllers\CommunityActionsController($service,new \NpmGateway\Services\CommunityActionContextResolver($service),new \NpmGateway\Services\CommunityActionProvider(),$tools,new \NpmGateway\Security\CsrfService($session),dirname(__DIR__,2).'/resources/views');$context=$this->context(20,'corporate');$index=$controller->index($context);self::assertSame(200,$index->status);self::assertStringContainsString('No communities are available.',$index->body);self::assertStringContainsString('You do not currently have access to any Community Actions workspaces.',$index->body);self::assertStringNotContainsString('/community-actions/corporate',$index->body);foreach([$controller->show('corporate',$context),$controller->action('corporate','rm-audit',$context)] as $response){self::assertSame(404,$response->status);self::assertSame('private, no-store',$response->headers['Cache-Control']);}}
 public function testPayloadRejectsForgedIdentifiers():void{$parser=new PropertyAccessPayloadParser();$employee=str_repeat('E',26);$property=str_repeat('P',26);self::assertSame([$employee],$parser->parse(['employees'=>[$employee],'access'=>[$employee=>[$property=>'1']]])['employees']);foreach([[ 'employees'=>[$employee],'access'=>[$employee=>['12'=>'1']]],[ 'employees'=>[$employee],'access'=>['FORGED'=>[$property=>'1']]]] as $bad){try{$parser->parse($bad);self::fail('Forged Property Access payload accepted.');}catch(InvalidArgumentException){self::addToAssertionCount(1);}}}
 public function testPresentationAndRoutesUsePublicIdentityAndNoStaticAuthority():void{$root=dirname(__DIR__,2);$admin=(string)file_get_contents($root.'/resources/views/admin/property-access.php');foreach(['Property Access','property_code','display_name','title=','reason',' disabled','_token'] as $required)self::assertStringContainsString($required,$admin);$community=(string)file_get_contents($root.'/resources/views/community-actions/index.php').(string)file_get_contents($root.'/resources/views/community-actions/show.php');foreach(['<style','style=','<script','sidebar','config/community-access.php','employee_property_assignments'] as $forbidden)self::assertStringNotContainsString($forbidden,$community);self::assertStringContainsString("property['slug']",$community);$routes=require $root.'/routes/web.php';self::assertArrayHasKey('/community-actions/{propertySlug}',$routes);self::assertArrayHasKey('/corporate/admin/property-access',$routes);self::assertContains('admin-access',$routes['/corporate/admin/property-access']['middleware']);}
 public function testMatrixUsesGlobalCheckboxContrastWithoutChangingNativeSemantics():void{$root=dirname(__DIR__,2);$view=(string)file_get_contents($root.'/resources/views/admin/property-access.php');$css=(string)file_get_contents($root.'/public/assets/css/gateway.css');self::assertStringContainsString('gateway-property-access-matrix',$view);self::assertStringContainsString('class="form-check-input" type="checkbox"',$view);self::assertStringContainsString('.form-check-input[type="checkbox"]:not(:checked):not(:disabled):not(.is-invalid)',$css);self::assertStringContainsString('border-color:var(--gateway-control-border-strong)',$css);self::assertStringContainsString('.form-check-input[type="checkbox"]:disabled',$css);self::assertStringNotContainsString('.gateway-property-access-matrix .form-check-input:not(:checked)',$css);}
 public function testEmployeeColumnStickyPresentationIsScopedAndSemantic():void{$root=dirname(__DIR__,2);$view=(string)file_get_contents($root.'/resources/views/admin/property-access.php');$css=(string)file_get_contents($root.'/public/assets/css/gateway.css');self::assertStringContainsString('<th class="gateway-property-access-matrix__employee" scope="col">Employee</th>',$view);self::assertStringContainsString('<th class="gateway-property-access-matrix__employee" scope="row">',$view);self::assertSame(2,substr_count($view,'gateway-property-access-matrix__employee'));self::assertStringContainsString('<div class="table-responsive">',$view);self::assertStringContainsString('.gateway-property-access-matrix .gateway-property-access-matrix__employee { position:sticky;left:0;z-index:2',$css);self::assertStringContainsString('min-width:14rem;max-width:18rem;white-space:normal;background:var(--gateway-surface)',$css);self::assertStringContainsString('box-shadow:2px 0 4px rgba(7,27,52,.08)',$css);self::assertStringContainsString('.gateway-property-access-matrix thead .gateway-property-access-matrix__employee { z-index:3;background:#f7f9fb; }',$css);self::assertStringContainsString('@media (max-width:767.98px) { .gateway-property-access-matrix .gateway-property-access-matrix__employee { position:static',$css);self::assertStringNotContainsString('.gateway-property-access-matrix .gateway-property-access-matrix__employee { position:absolute',$css);self::assertStringNotContainsString('<script',$view);self::assertStringNotContainsString('style=',$view);}
 private function service(PropertyAccessFakeStore $store):PropertyAccessService{$tx=new class implements InitializationTransactionInterface{public function acquire(string $lockName,int $timeoutSeconds):bool{return true;}public function begin():void{}public function commit():void{}public function rollback():void{}public function release(string $lockName):void{}};$audits=new class implements AuditStoreInterface{public array $events=[];public function insert(array $event):void{$this->events[]=$event;}};$clock=new class implements ClockInterface{public function now():DateTimeImmutable{return new DateTimeImmutable('2026-08-04 12:00:00');}};return new PropertyAccessService($store,$tx,new AuditService($audits,new PublicIdGenerator()),new PublicIdGenerator(),$clock);}
 private function store():PropertyAccessFakeStore{return new PropertyAccessFakeStore();}
 private function context(int $userId,string $class):AuthenticatedRequestContext{return new AuthenticatedRequestContext(new AuthenticatedUser($userId,$userId,str_repeat('U',26),str_repeat('E',26),'user','Test User','Manager',$class),'token');}
}
final class PropertyAccessFakeStore implements PropertyAccessStoreInterface
{
 public array $members=[10=>[101=>true]];
 public function hasEffectiveAccess(int $userId,int $propertyId):bool{return isset($this->members[$userId][$propertyId]);}
 public function accessibleActiveCommunities(int $userId):array{return isset($this->members[$userId][101])?[['id'=>101,'public_id'=>str_repeat('A',26),'slug'=>'alpha','property_code'=>'AP','display_name'=>'Alpha Property']]:[];}
 public function activeCommunityBySlug(string $slug):?array{return match($slug){'alpha'=>['id'=>101,'public_id'=>str_repeat('A',26),'slug'=>'alpha','property_code'=>'AP','display_name'=>'Alpha Property'],'beta'=>['id'=>102,'public_id'=>str_repeat('B',26),'slug'=>'beta','property_code'=>'BP','display_name'=>'Beta Property'],default=>null};}
 public function employeesForMatrix():array{return [['employee_id'=>1,'employee_public_id'=>str_repeat('C',26),'display_name'=>'Corporate User','employee_class'=>'corporate','employment_status'=>'active','user_id'=>11,'user_public_id'=>str_repeat('U',26),'user_status'=>'active'],['employee_id'=>2,'employee_public_id'=>str_repeat('M',26),'display_name'=>'Manager User','employee_class'=>'manager','employment_status'=>'active','user_id'=>10,'user_public_id'=>str_repeat('V',26),'user_status'=>'active'],['employee_id'=>3,'employee_public_id'=>str_repeat('T',26),'display_name'=>'Maintenance User','employee_class'=>'maintenance','employment_status'=>'active','user_id'=>null,'user_public_id'=>null,'user_status'=>null],['employee_id'=>4,'employee_public_id'=>str_repeat('I',26),'display_name'=>'Inactive User','employee_class'=>'manager','employment_status'=>'inactive','user_id'=>12,'user_public_id'=>str_repeat('W',26),'user_status'=>'active']];}
 public function activeProperties():array{return [['id'=>101,'public_id'=>str_repeat('A',26),'property_code'=>'AP','display_name'=>'Alpha Property','slug'=>'alpha'],['id'=>102,'public_id'=>str_repeat('B',26),'property_code'=>'BP','display_name'=>'Beta Property','slug'=>'beta'],['id'=>103,'public_id'=>str_repeat('C',26),'property_code'=>'CO','display_name'=>'Corporate','slug'=>'corporate']];}
 public function memberships():array{$rows=[];foreach($this->members as $user=>$properties)foreach($properties as $property=>$yes)$rows[]=['user_id'=>$user,'property_id'=>$property];return $rows;}
 public function grant(array $grant):void{$this->members[$grant['user_id']][$grant['property_id']]=true;}
 public function revoke(int $userId,int $propertyId):void{unset($this->members[$userId][$propertyId]);}
}
