<?php declare(strict_types=1);namespace NpmGateway\Tests\Unit;use NpmGateway\Services\{RmAuditRichTextSanitizer,RmAuditStatus};use PHPUnit\Framework\TestCase;
final class RmAuditsWorkflowTest extends TestCase{
 public function testSanitizerKeepsApprovedFormattingAndRemovesActiveContentAndMedia():void{$r=(new RmAuditRichTextSanitizer())->sanitize('<p onclick="x()"><strong>Lease</strong><img src="data:x"><script>x</script><a href="javascript:x">bad</a><a href="https://example.com/a">safe</a></p>');self::assertStringContainsString('<strong>Lease</strong>',$r['html']);self::assertStringNotContainsString('onclick',$r['html']);self::assertStringNotContainsString('<img',$r['html']);self::assertStringNotContainsString('<script',$r['html']);self::assertStringNotContainsString('javascript:',$r['html']);self::assertStringContainsString('rel="noopener noreferrer"',$r['html']);self::assertSame('Leasebadsafe',$r['text']);}
 public function testStatusLanguageIsCentralized():void{self::assertSame(['open'=>'Open','completed'=>'Completed','returned'=>'Returned'],RmAuditStatus::LABELS);self::assertSame(['warning','success','danger'],array_values(RmAuditStatus::BADGES));}
 public function testRoutesAndMigrationExpressScopedImmutableLifecycle():void{$root=dirname(__DIR__,2);$routes=require$root.'/routes/web.php';foreach(['/corporate/rm-audits','/corporate/rm-audits/create','/corporate/rm-audits/{auditPublicId}','/corporate/rm-audits/{auditPublicId}/return']as$p)self::assertContains('rm-audit-access',$routes[$p]['middleware']);foreach(['/community-actions/{propertySlug}/rm-audits','/community-actions/{propertySlug}/rm-audits/{auditPublicId}','/community-actions/{propertySlug}/rm-audits/{auditPublicId}/complete']as$p)self::assertSame(['authentication'],$routes[$p]['middleware']);$m=(string)file_get_contents($root.'/database/migrations/202608070019_rm_audits.php');foreach(['rm_audits','rm_audit_history','ON DELETE RESTRICT',"'open','completed','returned'",'Cannot roll back RM Audits']as$v)self::assertStringContainsString($v,$m);}
 public function testViewsHaveNoInlineScriptsStylesOrNumericRoutes():void{$root=dirname(__DIR__,2);$files=array_merge(glob($root.'/resources/views/corporate/rm-audits/*.php')?:[],glob($root.'/resources/views/community-actions/rm-audits/*.php')?:[]);$html='';foreach($files as$f)$html.=file_get_contents($f);self::assertStringNotContainsString('<script',$html);self::assertStringNotContainsString('<style',$html);self::assertStringNotContainsString('property_id',$html);self::assertStringContainsString('data-processing-form',$html);}
 public function testAttentionCountQueryAndGenericCardContract():void{$root=dirname(__DIR__,2);$repo=(string)file_get_contents($root.'/app/Repositories/RmAuditRepository.php');self::assertStringContainsString("status IN ('open','returned')",$repo);self::assertStringContainsString('property_id=?',$repo);self::assertStringContainsString("bind_param('i'",$repo);self::assertStringNotContainsString('attention_count',$repo);$view=(string)file_get_contents($root.'/resources/views/community-actions/show.php');foreach(['rm_audits','SELECT ','<script']as$v)self::assertStringNotContainsString($v,$view);$toolCard=new \NpmGateway\ValueObjects\ToolCard('test','Test','Description','Category','Open','/test',true,1,null,'Open Test','test.index',2,'Need Attention','warning');ob_start();require$root.'/resources/views/components/tool-card.php';$html=(string)ob_get_clean();self::assertStringContainsString('2 Need Attention',$html);self::assertStringContainsString('gateway-status--warning',$html);self::assertStringContainsString('href="/test"',$html);}
 public function testCardWithoutAttentionRendersNoPill():void{$root=dirname(__DIR__,2);$toolCard=new \NpmGateway\ValueObjects\ToolCard('test','Test','Description','Category','Open','/test',true,1,null,'Open Test','test.index');ob_start();require$root.'/resources/views/components/tool-card.php';self::assertStringNotContainsString('Need Attention',(string)ob_get_clean());}
 public function testZeroAndUnapprovedSemanticsAreRejected():void{$this->expectException(\InvalidArgumentException::class);new \NpmGateway\ValueObjects\ToolCard('test','Test','Description','Category','Open','/test',true,1,null,null,'test.index',0,'Need Attention','danger');}
}
