<?php declare(strict_types=1);namespace NpmGateway\Tests\Unit;use PHPUnit\Framework\TestCase;
final class RmAuditCreationPresentationTest extends TestCase{
 public function testIdentificationFieldsUseResponsiveDesktopRow():void{$view=$this->view();self::assertStringContainsString('gateway-rm-audit-form__identity-row',$view);self::assertSame(3,substr_count($view,'col-12 col-lg-'));foreach(['col-12 col-lg-4','col-12 col-lg-5','col-12 col-lg-3']as$class)self::assertStringContainsString($class,$view);foreach(['Property','Tenant Name','Unit #']as$label)self::assertStringContainsString('>'.$label.'<',$view);}
 public function testFindingsRemainFullWidthDominantAndProgressive():void{$view=$this->view();$css=$this->css();self::assertStringContainsString('gateway-rm-audit-form__findings',$view);self::assertStringContainsString('class="gateway-rm-audit-form__editor" id="rm-audit-editor"',$view);self::assertStringContainsString('gateway-rm-audit-form__fallback',$view);self::assertStringContainsString('.gateway-rm-audit-form #rm-audit-editor.gateway-rm-audit-form__editor.ql-container > .ql-editor[contenteditable="true"]',$css);self::assertStringContainsString('height:auto;min-height:15rem;max-height:28rem',$css);self::assertStringContainsString('#rm-audit-editor.gateway-rm-audit-form__editor.ql-container { height:auto; }',$css);self::assertStringNotContainsString("\n.ql-editor { min-height:15rem",$css);self::assertStringNotContainsString('style=',$view);self::assertStringContainsString('<textarea class="form-control gateway-rm-audit-form__fallback" required rows="10"',$view);self::assertStringContainsString('data-rm-audit-editor',$view);}
 public function testFormUsesGatewayCardAndApprovedActions():void{$view=$this->view();foreach(['gateway-card gateway-property-form-card gateway-rm-audit-form','gateway-card__body','gateway-form-actions gateway-form-actions--primary-first','gateway-button--primary','Create RM Audit']as$value)self::assertStringContainsString($value,$view);self::assertStringContainsString('<a class="btn gateway-button gateway-button--secondary" href="/corporate/rm-audits">Cancel</a>',$view);self::assertSame(1,substr_count($view,'<form '));self::assertStringNotContainsString('action="/corporate/rm-audits">Cancel',$view);}
 public function testRequiredFieldsAndToolbarRemainRestricted():void{$view=$this->view();foreach(['property_public_id','tenant_name','unit_identifier','audit_findings_html']as$id){self::assertMatchesRegularExpression('/(?:select|input|textarea)[^>]+id="'.$id.'"[^>]+required|(?:select|input|textarea)[^>]+required[^>]+id="'.$id.'"/',$view);}$js=(string)file_get_contents(dirname(__DIR__,2).'/public/assets/js/rm-audit-editor.js');foreach(["'bold'","'italic'","'underline'","list:'ordered'","list:'bullet'","indent:'-1'","indent:'+1'","'link'","'clean'"]as$control)self::assertStringContainsString($control,$js);foreach(["'image'","'video'","'header'","'color'","'font'","'size'","'code-block'"]as$forbidden)self::assertStringNotContainsString($forbidden,$js);}
 public function testEnhancedValidationTargetsVisibleEditorAndServerFieldContract():void{$root=dirname(__DIR__,2);$view=$this->view();$js=(string)file_get_contents($root.'/public/assets/js/rm-audit-editor.js');$validator=(string)file_get_contents($root.'/app/Services/RmAuditValidator.php');self::assertStringContainsString('name="audit_findings_html"',$view);self::assertStringContainsString("\$p['audit_findings_html']",$validator);self::assertStringContainsString('data-rm-audit-findings-error',$view);self::assertStringContainsString("quill.on('text-change', synchronize)",$js);self::assertStringContainsString("field.removeAttribute('required')",$js);self::assertStringContainsString("event.preventDefault()",$js);self::assertStringContainsString('quill.focus()',$js);self::assertStringContainsString("{ capture: true }",$js);self::assertStringNotContainsString('<script',$view);}
 private function view():string{return(string)file_get_contents(dirname(__DIR__,2).'/resources/views/corporate/rm-audits/create.php');}private function css():string{return(string)file_get_contents(dirname(__DIR__,2).'/public/assets/css/gateway.css');}
}
