<?php declare(strict_types=1);namespace Tests\Unit;use NpmGateway\Exceptions\Domain\InvalidSupplyOrderException;use NpmGateway\Notifications\SupplyOrderEmailSender;use NpmGateway\Services\{RmAuditRichTextSanitizer,SupplyOrderValidator};use PHPUnit\Framework\TestCase;
final class SupplyOrdersWorkflowTest extends TestCase
{
 private string$root;protected function setUp():void{$this->root=dirname(__DIR__,2);}
 public function testRoutesArePropertyScopedAndExposeNoMutationAfterCreation():void{$routes=require$this->root.'/routes/web.php';foreach(['/community-actions/{propertySlug}/supply-orders','/community-actions/{propertySlug}/supply-orders/create','/community-actions/{propertySlug}/supply-orders/{supplyOrderPublicId}']as$path)self::assertSame(['authentication'],$routes[$path]['middleware']);self::assertSame(['GET','POST'],$routes['/community-actions/{propertySlug}/supply-orders']['methods']);foreach(array_keys($routes)as$path){self::assertStringNotContainsString('supply-orders/{supplyOrderPublicId}/edit',$path);self::assertStringNotContainsString('supply-orders/{supplyOrderPublicId}/delete',$path);}self::assertStringNotContainsString('{supplyOrderId}',(string)file_get_contents($this->root.'/routes/web.php'));}
 public function testSanitizerPreservesFormattingAndSafeLinksOnly():void{$validator=new SupplyOrderValidator(new RmAuditRichTextSanitizer());$data=$validator->validate(['request_html'=>'<p class="x" onclick="bad()"><strong>Filters</strong></p><ul><li><a href="https://vendor.example/item">Buy</a></li></ul><img src="x"><iframe src="x"></iframe><a href="javascript:bad()">bad</a><a href="data:text/plain,x">data</a>']);foreach(['<strong>Filters</strong>','<ul>','<li>','href="https://vendor.example/item"','rel="noopener noreferrer"']as$value)self::assertStringContainsString($value,$data['request_html']);foreach(['class=','onclick','<img','<iframe','javascript:','data:text']as$value)self::assertStringNotContainsString($value,$data['request_html']);self::assertStringContainsString('Filters',$data['request_text']);}
 public function testEmptyQuillFailsAuthoritatively():void{$this->expectException(InvalidSupplyOrderException::class);(new SupplyOrderValidator(new RmAuditRichTextSanitizer()))->validate(['request_html'=>'<p><br></p>']);}
 public function testEmailUsesConfiguredRecipientFormattingAndAuthoritativeCta():void{$sent=[];$sender=new SupplyOrderEmailSender(['recipient_email'=>'noc@npmparks.com','test_mode'=>false,'test_email'=>'','app_url'=>'https://gateway.example.test'],function(...$args)use(&$sent){$sent=$args;return true;});self::assertTrue($sender->submitted($this->order()));self::assertSame('noc@npmparks.com',$sent[0]);foreach(['Supply Order Submitted','Pine Hill','Amanda Watson','<strong>Filters</strong>','https://vendor.example/item','/community-actions/pine-hill/supply-orders/'.str_repeat('A',26)]as$value)self::assertStringContainsString($value,$sent[2]);self::assertStringNotContainsString('<strong>',$sent[3]);}
 public function testEmailTestModeAndInvalidRecipientsFailClosed():void{$recipients=[];$test=new SupplyOrderEmailSender(['recipient_email'=>'noc@npmparks.com','test_mode'=>true,'test_email'=>'safe@example.test','app_url'=>'https://gateway.example.test'],function($to)use(&$recipients){$recipients[]=$to;return true;});self::assertTrue($test->submitted($this->order()));self::assertSame(['safe@example.test'],$recipients);foreach(['','invalid']as$email){$called=false;$sender=new SupplyOrderEmailSender(['recipient_email'=>'noc@npmparks.com','test_mode'=>true,'test_email'=>$email,'app_url'=>''],function()use(&$called){$called=true;return true;});self::assertFalse($sender->submitted($this->order()));self::assertFalse($called);}}
 public function testMigrationAndViewsHaveImmutableOneEventDesign():void{$migration=(string)file_get_contents($this->root.'/database/migrations/202608090020_supply_orders.php');foreach(['supply_orders','request_html','request_text','submitted_at','ON DELETE RESTRICT','idx_supply_orders_property_submitted']as$value)self::assertStringContainsString($value,$migration);foreach(['status','supply_order_history']as$value)self::assertStringNotContainsString($value,$migration);$controller=(string)file_get_contents($this->root.'/app/Http/Controllers/SupplyOrderController.php');foreach(['CommunityActionContextResolver','propertyId','private, no-store']as$value)self::assertStringContainsString($value,$controller);foreach(['CorporateAccessService','status','delete(','edit(']as$value)self::assertStringNotContainsString($value,$controller);$show=(string)file_get_contents($this->root.'/resources/views/community-actions/supply-orders/show.php');foreach(['Property','Submitted By','Submitted At','Supplies Requested','request_html','Back to Supply Orders']as$value)self::assertStringContainsString($value,$show);foreach(['Status','History','Edit','Delete']as$value)self::assertStringNotContainsString($value,$show);}
 private function order():array{return['public_id'=>str_repeat('A',26),'property_name'=>'Pine Hill','property_slug'=>'pine-hill','submitted_by_name'=>'Amanda Watson','submitted_at'=>'2026-08-09 00:34:00','request_html'=>'<p><strong>Filters</strong> <a href="https://vendor.example/item">Buy</a></p>','request_text'=>'Filters Buy'];}
}
