<?php
declare(strict_types=1);
use NpmGateway\Database\Migration\ZillowComSchema;use NpmGateway\Exceptions\Domain\InvalidZillowWorkbookException;use NpmGateway\Repositories\ZillowRepository;use NpmGateway\Services\{ZillowPhoneNormalizer,ZillowReportCriteriaFactory,ZillowWorkbookParser};use PhpOffice\PhpSpreadsheet\{Spreadsheet,Writer\Xls};use PHPUnit\Framework\TestCase;
final class ZillowComTest extends TestCase
{
 private array$files=[];protected function tearDown():void{foreach($this->files as$f)if(is_file($f))unlink($f);}
 public function testPhoneNormalizationCoversObservedFormatsAndMalformedValues():void{$n=new ZillowPhoneNormalizer();self::assertSame('2295299939',$n->normalize('229-529-9939'));self::assertSame('6506865038',$n->normalize('+16506865038'));self::assertSame('6506865038',$n->normalize('16506865038'));self::assertNull($n->normalize('238'));self::assertNull($n->normalize('not a phone'));self::assertNull($n->normalize(''));}
 public function testParserAcceptsUnifiedLeadSemanticsAndDerivesCountsAndRange():void{$file=$this->book([['Boulder Trails','08/01/2026 00:26','phone','','+16506865038',''],['Maplewind MHP','08/07/2026 22:29','email','person@example.test','229-529-9939','Person']]);$p=(new ZillowWorkbookParser(new ZillowPhoneNormalizer()))->parse($this->upload($file));self::assertCount(2,$p['rows']);self::assertSame(['phone','email'],array_column($p['rows'],'lead_type'));self::assertNull($p['rows'][0]['prospect_name']);self::assertNull($p['rows'][0]['prospect_email']);self::assertSame('6506865038',$p['rows'][0]['prospect_phone_normalized']);self::assertSame('2295299939',$p['rows'][1]['prospect_phone_normalized']);self::assertSame('2026-08-01 00:26:00',$p['source_started_at']);self::assertSame('2026-08-07 22:29:00',$p['source_ended_at']);}
 public function testParserRejectsUnexpectedLeadTypeAndStructure():void{$file=$this->book([['Boulder Trails','08/01/2026 00:26','chat','','229-529-9939','Person']]);$this->expectException(InvalidZillowWorkbookException::class);(new ZillowWorkbookParser(new ZillowPhoneNormalizer()))->parse($this->upload($file));}
 public function testMappingsRosterRoutesAndMigrationContract():void{self::assertSame(['Boulder Trails'=>'BT','Crumley Farms'=>'CF','Flamingo Flats'=>'FF','Highridge'=>'HR','Maplewind MHP'=>'MW','Pearce Pointe'=>'PP','Pine Hill MHC'=>'PH','Wunderpark'=>'WP'],ZillowComSchema::MAPPINGS);self::assertSame(['BT','CF','FF','HR','MW','PP','PH','PM','SM','WP'],ZillowRepository::OWNER_PROPERTY_CODES);self::assertNotContains('SUB',ZillowRepository::OWNER_PROPERTY_CODES);$root=dirname(__DIR__,2);$routes=require$root.'/routes/web.php';foreach(['/admin/zillow','/admin/zillow/upload','/admin/zillow/import-history']as$route)self::assertSame(['authentication','protected-principal'],$routes[$route]['middleware']);$migration=(string)file_get_contents($root.'/database/migrations/202608160027_zillow_com_imports.php');foreach(ZillowComSchema::TABLES as$table)self::assertStringContainsString('CREATE TABLE '.$table,$migration);self::assertStringContainsString('file_sha256',$migration);}
 public function testReportCriteriaDefaultsFiltersAndPagination():void{$p=[['public_id'=>'BT']];$f=new ZillowReportCriteriaFactory();$c=$f->fromQuery([],$p,['source_started_at'=>'2026-08-01 00:26:00','source_ended_at'=>'2026-08-07 22:29:00']);self::assertSame('all',$c->type);self::assertSame('2026-08-01',$c->fromDate);self::assertSame('2026-08-08',$c->toExclusive);$phone=$f->fromQuery(['type'=>'phone','property'=>'BT','from'=>'2026-08-01','to'=>'2026-08-07','page'=>'2','per_page'=>'50'],$p,null);self::assertTrue($phone->valid());self::assertSame('phone',$phone->type);self::assertSame(2,$phone->page);self::assertSame(50,$phone->perPage);$bad=$f->fromQuery(['type'=>'email','from'=>'2026-08-08','to'=>'2026-08-07','property'=>'SUB'],$p,null);self::assertArrayHasKey('date_range',$bad->errors);self::assertArrayHasKey('property',$bad->errors);}
 public function testRealWorkbookStructureWhenAvailable():void{$path='C:/Users/chuck/Documents/Call Logs/Zillow_com/08-01-2026-thru-08-07-2026-Z.xls';if(!is_file($path))self::markTestSkipped('Real Zillow workbook is not available.');$p=(new ZillowWorkbookParser(new ZillowPhoneNormalizer()))->parse(['name'=>basename($path),'tmp_name'=>$path,'size'=>filesize($path),'error'=>UPLOAD_ERR_OK]);self::assertCount(186,$p['rows']);self::assertCount(46,array_filter($p['rows'],static fn(array$r):bool=>$r['lead_type']==='phone'));self::assertCount(140,array_filter($p['rows'],static fn(array$r):bool=>$r['lead_type']==='email'));self::assertCount(8,array_unique(array_column($p['rows'],'source_listing_name')));}
 private function upload(string$f):array{return['name'=>'zillow.xls','tmp_name'=>$f,'size'=>filesize($f),'error'=>UPLOAD_ERR_OK];}private function book(array$rows):string{$b=new Spreadsheet();$s=$b->getActiveSheet();$s->setTitle('Leads');$s->fromArray(ZillowWorkbookParser::HEADERS,null,'A1');$s->fromArray($rows,null,'A2');$f=tempnam(sys_get_temp_dir(),'zillow-').'.xls';$this->files[]=$f;(new Xls($b))->save($f);$b->disconnectWorksheets();return$f;}
}
