<?php
declare(strict_types=1);
$escape=static fn(string $value):string=>htmlspecialchars($value,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');
$old=static fn(string $key,string $default=''):string=>(string)($input[$key]??$default);
$formAction=isset($formAction)?(string)$formAction:'/human-resources/properties';$submitLabel=isset($submitLabel)?(string)$submitLabel:'Create Property';$validationHeading=isset($validationHeading)?(string)$validationHeading:'We could not create the property.';
$invalid=static fn(string $key):string=>isset($errors[$key])?' is-invalid':'';
$states=['AL','AK','AZ','AR','CA','CO','CT','DE','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA','ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR','PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY','DC'];
$field=static function(string $key,string $label,string $type='text',string $help='',string $width='col-md-6',bool $phoneMask=false,?string $autocomplete=null)use($old,$invalid,$errors,$escape):void{$described=[];if($help!=='')$described[]='property-'.$key.'-help';if(isset($errors[$key]))$described[]='property-'.$key.'-error'; ?>
<div class="<?= $width ?>"><label class="form-label" for="property-<?= $key ?>"><?= $escape($label) ?></label><input class="form-control<?= $invalid($key) ?>" id="property-<?= $key ?>" name="<?= $key ?>" type="<?= $type ?>" value="<?= $escape($old($key)) ?>" required<?= $phoneMask?' inputmode="tel" data-phone-mask maxlength="14"':'' ?><?= $autocomplete!==null?' autocomplete="'.$escape($autocomplete).'"':'' ?><?= $described!==[]?' aria-describedby="'.implode(' ',$described).'"':'' ?>><?php if($help!==''): ?><div class="form-text" id="property-<?= $key ?>-help"><?= $escape($help) ?></div><?php endif; ?><?php if(isset($errors[$key])): ?><div class="invalid-feedback" id="property-<?= $key ?>-error"><?= $escape((string)$errors[$key]) ?></div><?php endif; ?></div>
<?php }; ?>
<form method="post" action="<?= $escape($formAction) ?>" class="gateway-property-form" novalidate>
 <input type="hidden" name="_token" value="<?= $escape($csrfToken) ?>">
 <?php if($errors!==[]): ?><div class="alert gateway-alert gateway-alert--danger" role="alert" tabindex="-1" id="property-validation-summary"><strong><?= $escape($validationHeading) ?></strong><p class="mb-0"><?= isset($errors['form'])?$escape((string)$errors['form']):'Review the highlighted fields and try again.' ?></p></div><?php endif; ?>
 <section class="gateway-form-section" aria-labelledby="property-information-heading"><h2 class="gateway-form-section-title" id="property-information-heading">Property Information</h2><div class="row gateway-form-grid"><?php $field('prop_id','PropID','number','Existing properties use their permanent assigned PropID.');$field('property_code','Property Code','text','Enter the permanent two-letter NPM property code.');$field('display_name','Property Name');$field('slug','Slug','text','Lowercase URL-safe identifier, for example boulder-trails.'); ?><div class="col-md-6"><label class="form-label" for="property-status">Status</label><select class="form-select<?= $invalid('status') ?>" id="property-status" name="status" required><?php foreach(['active'=>'Active','inactive'=>'Inactive'] as $value=>$label): ?><option value="<?= $value ?>"<?= $old('status','active')===$value?' selected':'' ?>><?= $label ?></option><?php endforeach; ?></select><?php if(isset($errors['status'])): ?><div class="invalid-feedback"><?= $escape((string)$errors['status']) ?></div><?php endif; ?></div></div></section>
 <section class="gateway-form-section" aria-labelledby="property-address-heading"><h2 class="gateway-form-section-title" id="property-address-heading">Address</h2><div class="row gateway-form-grid"><?php $field('address_line_1','Street Address');$field('city','City'); ?><div class="col-md-6"><label class="form-label" for="property-state">State</label><select class="form-select<?= $invalid('state') ?>" id="property-state" name="state" required><option value="">Select state</option><?php foreach($states as $state): ?><option value="<?= $state ?>"<?= $old('state')===$state?' selected':'' ?>><?= $state ?></option><?php endforeach; ?></select><?php if(isset($errors['state'])): ?><div class="invalid-feedback"><?= $escape((string)$errors['state']) ?></div><?php endif; ?></div><?php $field('postal_code','ZIP Code'); ?><div class="col-md-6"><label class="form-label" for="property-timezone">Timezone</label><select class="form-select<?= $invalid('timezone') ?>" id="property-timezone" name="timezone" required><?php foreach(['America/New_York'=>'Eastern — America/New_York','America/Chicago'=>'Central — America/Chicago'] as $value=>$label): ?><option value="<?= $value ?>"<?= $old('timezone','America/New_York')===$value?' selected':'' ?>><?= $escape($label) ?></option><?php endforeach; ?></select><?php if(isset($errors['timezone'])): ?><div class="invalid-feedback"><?= $escape((string)$errors['timezone']) ?></div><?php endif; ?></div></div></section>
 <section class="gateway-form-section" aria-labelledby="property-contact-heading"><h2 class="gateway-form-section-title" id="property-contact-heading">Property Contact</h2><div class="row gateway-form-grid"><?php $field('office_phone','Phone','tel','Format: (000) 000-0000','col-md-6',true,'tel');$field('manager_email','Manager Email','email');$field('website_url','Website','url','', 'col-12'); ?></div></section>
 <section class="gateway-form-section" aria-labelledby="property-ivr-heading"><h2 class="gateway-form-section-title" id="property-ivr-heading">IVR Routing</h2><div class="row gateway-form-grid"><?php $field('ivr_number','IVR Phone','tel','Format: (000) 000-0000','col-md-6',true,'off');$field('ivr_routing_email','IVR Routing Email','email'); ?></div></section>
 <div class="gateway-form-actions" role="group" aria-label="Property form actions"><a class="btn gateway-button gateway-button--secondary" href="/human-resources/properties">Cancel</a><button class="btn gateway-button gateway-button--primary" type="submit"><?= $escape($submitLabel) ?></button></div>
</form>
