<?php
declare(strict_types=1);
namespace NpmGateway\Repositories;
use NpmGateway\ValueObjects\ApartmentsReportCriteria;
final readonly class ApartmentsRepository
{
 public const OWNER_PROPERTY_CODES=['BT','CF','FF','HR','MW','PP','PH','PM','SM','WP'];
 public function __construct(private \mysqli$db){}
 public function hashExists(string$hash):bool{$s=$this->db->prepare('SELECT 1 FROM apartments_imports WHERE file_sha256=? LIMIT 1');$s->bind_param('s',$hash);$s->execute();$found=$s->get_result()->fetch_row()!==null;$s->close();return$found;}
 public function mappings(array$names):array{if($names===[])return[];$marks=implode(',',array_fill(0,count($names),'?'));$s=$this->db->prepare("SELECT m.source_property_name,m.property_id FROM apartments_property_mappings m JOIN properties p ON p.id=m.property_id WHERE m.active=1 AND p.status='active' AND m.source_property_name IN ({$marks})");$types=str_repeat('s',count($names));$s->bind_param($types,...$names);$s->execute();$map=[];foreach($s->get_result()->fetch_all(MYSQLI_ASSOC)as$row)$map[$row['source_property_name']]=(int)$row['property_id'];$s->close();return$map;}
 public function insertImport(array$d):int{$s=$this->db->prepare('INSERT INTO apartments_imports(public_id,original_filename,file_sha256,uploaded_by_user_id,source_started_at,source_ended_at,phone_call_count,email_lead_count,imported_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)');$s->bind_param('sssissiiss',$d['public_id'],$d['original_filename'],$d['file_sha256'],$d['user_id'],$d['source_started_at'],$d['source_ended_at'],$d['call_count'],$d['email_count'],$d['at'],$d['at']);$s->execute();$id=(int)$this->db->insert_id;$s->close();return$id;}
 public function insertCalls(int$import,array$rows,array$map,string$at,callable$id):void{$sql='INSERT INTO apartments_calls(public_id,import_id,property_id,occurred_at,caller_phone_raw,caller_phone_normalized,ring_to_number_raw,ring_to_number_normalized,tracking_number_raw,tracking_number_normalized,call_duration_seconds,call_recording_value,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)';$s=$this->db->prepare($sql);foreach($rows as$row){$public=$id();$property=$map[$row['source_property_name']];$s->bind_param('siisssssssisss',$public,$import,$property,$row['occurred_at'],$row['caller_phone_raw'],$row['caller_phone_normalized'],$row['ring_to_number_raw'],$row['ring_to_number_normalized'],$row['tracking_number_raw'],$row['tracking_number_normalized'],$row['call_duration_seconds'],$row['call_recording_value'],$row['status'],$at);$s->execute();}$s->close();}
 public function insertEmails(int$import,array$rows,array$map,string$at,callable$id):void{$sql='INSERT INTO apartments_email_leads(public_id,import_id,property_id,occurred_at,renter_name,renter_phone_raw,renter_phone_normalized,renter_email,created_at) VALUES(?,?,?,?,?,?,?,?,?)';$s=$this->db->prepare($sql);foreach($rows as$row){$public=$id();$property=$map[$row['source_property_name']];$s->bind_param('siissssss',$public,$import,$property,$row['occurred_at'],$row['renter_name'],$row['renter_phone_raw'],$row['renter_phone_normalized'],$row['renter_email'],$at);$s->execute();}$s->close();}
 public function history():array{return$this->db->query('SELECT i.public_id,i.original_filename,i.source_started_at,i.source_ended_at,i.phone_call_count,i.email_lead_count,i.imported_at,e.first_name,e.last_name FROM apartments_imports i JOIN users u ON u.id=i.uploaded_by_user_id JOIN employees e ON e.id=u.employee_id ORDER BY i.imported_at DESC,i.id DESC')->fetch_all(MYSQLI_ASSOC);}
 public function mostRecentRange():?array{$row=$this->db->query('SELECT source_started_at,source_ended_at FROM apartments_imports ORDER BY source_ended_at DESC,source_started_at DESC,id DESC LIMIT 1')->fetch_assoc();return$row?:null;}
 public function reportProperties():array{$codes=self::OWNER_PROPERTY_CODES;$marks=implode(',',array_fill(0,count($codes),'?'));$order=[];foreach($codes as$i=>$code)$order[]='WHEN ? THEN '.($i+1);$values=[...$codes,...$codes];$s=$this->db->prepare("SELECT id,public_id,property_code,display_name FROM properties WHERE status='active' AND property_code IN ({$marks}) ORDER BY CASE property_code ".implode(' ',$order).' ELSE 999 END');$this->bind($s,str_repeat('s',count($values)),$values);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return$rows;}
 public function report(ApartmentsReportCriteria$c,array$properties):array
 {
  $table=$c->view==='email-leads'?'apartments_email_leads':'apartments_calls';[$where,$types,$values]=$this->predicate($c,'r');$aggregate=$this->db->prepare("SELECT r.property_id,COUNT(*) total".($c->view==='calls'?',COALESCE(SUM(r.call_duration_seconds),0) duration':'')." FROM {$table} r JOIN properties p ON p.id=r.property_id {$where} GROUP BY r.property_id");$this->bind($aggregate,$types,$values);$aggregate->execute();$byId=[];foreach($aggregate->get_result()->fetch_all(MYSQLI_ASSOC)as$row)$byId[(int)$row['property_id']]=$row;$aggregate->close();
  $rows=[];$total=0;$duration=0;foreach($properties as$property){$found=$byId[(int)$property['id']]??[];$count=(int)($found['total']??0);$seconds=(int)($found['duration']??0);$rows[]=$property+['total'=>$count,'duration'=>$seconds];$total+=$count;$duration+=$seconds;}
  $count=$this->db->prepare("SELECT COUNT(*) FROM {$table} r JOIN properties p ON p.id=r.property_id {$where}");$countValues=$values;$this->bind($count,$types,$countValues);$count->execute();$records=(int)$count->get_result()->fetch_row()[0];$count->close();$pages=max(1,(int)ceil($records/$c->perPage));$page=min($c->page,$pages);$offset=($page-1)*$c->perPage;
  $columns=$c->view==='calls'?'r.caller_phone_raw,r.ring_to_number_raw,r.tracking_number_raw,r.occurred_at,r.call_duration_seconds,r.status':'r.renter_name,r.renter_phone_raw,r.renter_email,r.occurred_at';$detail=$this->db->prepare("SELECT {$columns},p.display_name property_name FROM {$table} r JOIN properties p ON p.id=r.property_id {$where} ORDER BY r.occurred_at DESC,r.id DESC LIMIT ? OFFSET ?");$detailValues=[...$values,$c->perPage,$offset];$this->bind($detail,$types.'ii',$detailValues);$detail->execute();$details=$detail->get_result()->fetch_all(MYSQLI_ASSOC);$detail->close();return['rows'=>$rows,'totals'=>['count'=>$total,'duration'=>$duration],'details'=>$details,'page'=>$page,'pages'=>$pages,'per_page'=>$c->perPage,'records'=>$records,'from'=>$records===0?0:$offset+1,'to'=>min($records,$offset+count($details))];
 }
 private function predicate(ApartmentsReportCriteria$c,string$alias):array{$clauses=[];$types='';$values=[];if($c->fromDate!==''){$clauses[]="{$alias}.occurred_at>=?";$types.='s';$values[]=$c->fromDate;}if($c->toExclusive!==''){$clauses[]="{$alias}.occurred_at<?";$types.='s';$values[]=$c->toExclusive;}if($c->propertyPublicId!==''){$clauses[]='p.public_id=?';$types.='s';$values[]=$c->propertyPublicId;}return[$clauses===[]?'':'WHERE '.implode(' AND ',$clauses),$types,$values];}
 private function bind(\mysqli_stmt$s,string$types,array&$values):void{if($types==='')return;$refs=[];foreach($values as$key=>&$value)$refs[$key]=&$value;unset($value);$s->bind_param($types,...$refs);}
}
