<?php
declare(strict_types=1);
namespace NpmGateway\Repositories;
use mysqli;
final class ApplicationReviewRepository
{
 public function __construct(private readonly mysqli $db){}
 public function insert(array $r):int{$s=$this->db->prepare("INSERT INTO application_reviews(public_id,property_id,prospect_name,manager_comments,rm_documents_confirmed,status,submitted_by_user_id,submitted_at,reviewed_by_user_id,reviewed_at,reviewer_comments,created_at,updated_at) VALUES(?,?,?,?,1,'pending_review',?,?,NULL,NULL,NULL,?,?)");$s->bind_param('sississs',$r['public_id'],$r['property_id'],$r['prospect_name'],$r['manager_comments'],$r['submitted_by_user_id'],$r['timestamp'],$r['timestamp'],$r['timestamp']);$s->execute();$id=$this->db->insert_id;$s->close();return $id;}
 public function insertHistory(array $h):void{$s=$this->db->prepare('INSERT INTO application_review_history(public_id,application_review_id,event_type,from_status,to_status,acted_by_user_id,comments,created_at) VALUES(?,?,?,?,?,?,?,?)');$s->bind_param('sisssiss',$h['public_id'],$h['review_id'],$h['event_type'],$h['from_status'],$h['to_status'],$h['actor_id'],$h['comments'],$h['timestamp']);$s->execute();$s->close();}
 public function managerList(int $propertyId,string $status='',string $search=''):array{$sql="SELECT r.public_id,r.prospect_name,r.status,r.submitted_at,r.updated_at FROM application_reviews r WHERE r.property_id=?";$types='i';$params=[$propertyId];if(in_array($status,['pending_review','approved','denied'],true)){$sql.=' AND r.status=?';$types.='s';$params[]=$status;}if($search!==''){$sql.=' AND r.prospect_name LIKE ?';$types.='s';$params[]='%'.$search.'%';}$sql.=" ORDER BY CASE r.status WHEN 'pending_review' THEN 0 WHEN 'approved' THEN 1 WHEN 'denied' THEN 2 ELSE 3 END,CASE WHEN r.status='pending_review' THEN r.submitted_at END DESC,CASE WHEN r.status IN ('approved','denied') THEN COALESCE(r.reviewed_at,r.updated_at) END DESC,r.id DESC";$s=$this->db->prepare($sql);$s->bind_param($types,...$params);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return $rows;}
 public function managerDetail(string $publicId,int $propertyId):?array{return $this->detail($publicId,'r.property_id=?',$propertyId);}
 public function corporateDetail(string $publicId,bool $lock=false):?array{return $this->detail($publicId,'1=1',null,$lock);}
 private function detail(string $publicId,string $scope,mixed $scopeValue=null,bool $lock=false):?array{$sql="SELECT r.*,p.public_id property_public_id,p.slug property_slug,p.property_code,p.display_name property_name,CONCAT(se.first_name,' ',se.last_name) submitted_by_name,CONCAT(re.first_name,' ',re.last_name) reviewed_by_name FROM application_reviews r JOIN properties p ON p.id=r.property_id JOIN users su ON su.id=r.submitted_by_user_id JOIN employees se ON se.id=su.employee_id LEFT JOIN users ru ON ru.id=r.reviewed_by_user_id LEFT JOIN employees re ON re.id=ru.employee_id WHERE r.public_id=? AND {$scope} LIMIT 1".($lock?' FOR UPDATE':'');$s=$this->db->prepare($sql);if($scopeValue===null)$s->bind_param('s',$publicId);else $s->bind_param('si',$publicId,$scopeValue);$s->execute();$row=$s->get_result()->fetch_assoc();$s->close();if(!is_array($row))return null;$row['history']=$this->history((int)$row['id']);return $row;}
 public function history(int $reviewId):array{$s=$this->db->prepare("SELECT h.public_id,h.event_type,h.from_status,h.to_status,h.comments,h.created_at,CONCAT(e.first_name,' ',e.last_name) acted_by_name FROM application_review_history h JOIN users u ON u.id=h.acted_by_user_id JOIN employees e ON e.id=u.employee_id WHERE h.application_review_id=? ORDER BY h.created_at,h.id");$s->bind_param('i',$reviewId);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return $rows;}
 public function corporateQueue(string $status='',string $propertyPublicId='',string $search=''):array{$sql="SELECT r.public_id,r.prospect_name,r.status,r.submitted_at,r.reviewed_at,p.display_name property_name,CONCAT(e.first_name,' ',e.last_name) submitted_by_name FROM application_reviews r JOIN properties p ON p.id=r.property_id JOIN users u ON u.id=r.submitted_by_user_id JOIN employees e ON e.id=u.employee_id WHERE 1=1";$types='';$params=[];if(in_array($status,['pending_review','approved','denied'],true)){$sql.=' AND r.status=?';$types.='s';$params[]=$status;}if(preg_match('/^[0-9A-HJKMNP-TV-Z]{26}$/',$propertyPublicId)===1){$sql.=' AND p.public_id=?';$types.='s';$params[]=$propertyPublicId;}if($search!==''){$sql.=" AND (r.prospect_name LIKE ? OR CONCAT(e.first_name,' ',e.last_name) LIKE ?)";$types.='ss';$params[]='%'.$search.'%';$params[]='%'.$search.'%';}$sql.=" ORDER BY CASE r.status WHEN 'pending_review' THEN 0 ELSE 1 END,CASE WHEN r.status='pending_review' THEN r.submitted_at END ASC,r.reviewed_at DESC,r.id DESC";$s=$this->db->prepare($sql);if($types!=='')$s->bind_param($types,...$params);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return $rows;}
 public function counts():array{$rows=$this->db->query('SELECT status,COUNT(*) total FROM application_reviews GROUP BY status')->fetch_all(MYSQLI_ASSOC);$out=['pending_review'=>0,'approved'=>0,'denied'=>0];foreach($rows as $r)$out[$r['status']]=(int)$r['total'];return $out;}
 public function properties():array{return $this->db->query('SELECT public_id,display_name FROM properties ORDER BY display_name,id')->fetch_all(MYSQLI_ASSOC);}
 public function decide(int $id,string $status,int $reviewerId,string $comments,string $timestamp):bool{$s=$this->db->prepare("UPDATE application_reviews SET status=?,reviewed_by_user_id=?,reviewed_at=?,reviewer_comments=?,updated_at=? WHERE id=? AND status='pending_review'");$s->bind_param('sisssi',$status,$reviewerId,$timestamp,$comments,$timestamp,$id);$s->execute();$ok=$s->affected_rows===1;$s->close();return $ok;}
}
