<?php
declare(strict_types=1);
namespace NpmGateway\Repositories;
use NpmGateway\ValueObjects\CallLogFilterCriteria;
final readonly class CallLogRepository
{
 public function __construct(private \mysqli$db){}
 public function destinations(array$tns):array{if($tns===[])return[];$placeholders=implode(',',array_fill(0,count($tns),'?'));$s=$this->db->prepare("SELECT id,called_tn FROM call_log_destinations WHERE active=1 AND called_tn IN ({$placeholders})");$types=str_repeat('s',count($tns));$s->bind_param($types,...$tns);$s->execute();$map=[];foreach($s->get_result()->fetch_all(MYSQLI_ASSOC)as$row)$map[(string)$row['called_tn']]=(int)$row['id'];$s->close();return$map;}
 public function hashExists(string$hash):bool{$s=$this->db->prepare('SELECT 1 FROM call_log_imports WHERE file_sha256=? LIMIT 1');$s->bind_param('s',$hash);$s->execute();$found=$s->get_result()->fetch_row()!==null;$s->close();return$found;}
 public function insertImport(array$d):int{$s=$this->db->prepare('INSERT INTO call_log_imports(public_id,original_filename,file_sha256,uploaded_by_user_id,source_row_count,imported_row_count,source_started_at,source_ended_at,imported_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?)');$s->bind_param('sssiiissss',$d['public_id'],$d['original_filename'],$d['file_sha256'],$d['uploaded_by_user_id'],$d['row_count'],$d['row_count'],$d['source_started_at'],$d['source_ended_at'],$d['at'],$d['at']);$s->execute();$id=(int)$this->db->insert_id;$s->close();return$id;}
 public function insertCalls(int$importId,array$rows,array$destinations,string$at,callable$id):void{foreach(array_chunk($rows,250)as$batch){$placeholders=[];$types='';$values=[];foreach($batch as$row){$placeholders[]='(?,?,?,?,?,?,?,?,?)';$types.='siissssss';array_push($values,$id(),$importId,$destinations[$row['called_tn']],$row['calling_tn'],$row['called_tn'],$row['started_at'],$row['released_at'],$row['call_duration_seconds'],$at);}$s=$this->db->prepare('INSERT INTO call_logs(public_id,import_id,destination_id,calling_tn,called_tn,started_at,released_at,call_duration_seconds,created_at) VALUES '.implode(',',$placeholders));$this->bind($s,$types,$values);$s->execute();$s->close();}}
 public function activeDestinations():array{return$this->db->query("SELECT d.public_id,COALESCE(p.display_name,d.external_display_name) display_name FROM call_log_destinations d LEFT JOIN properties p ON p.id=d.property_id WHERE d.active=1 ORDER BY COALESCE(p.display_name,d.external_display_name) ASC,d.id ASC")->fetch_all(MYSQLI_ASSOC);}
 public function totalCalls():int{return(int)$this->db->query('SELECT COUNT(*) FROM call_logs')->fetch_row()[0];}
 public function page(CallLogFilterCriteria$criteria):array
 {
  [$where,$types,$values]=$this->predicate($criteria);$count=$this->db->prepare("SELECT COUNT(*) FROM call_logs l JOIN call_log_destinations d ON d.id=l.destination_id {$where}");$this->bind($count,$types,$values);$count->execute();$total=(int)$count->get_result()->fetch_row()[0];$count->close();$pages=max(1,(int)ceil($total/$criteria->perPage));$page=min($criteria->page,$pages);$offset=($page-1)*$criteria->perPage;$s=$this->db->prepare("SELECT l.id,COALESCE(p.display_name,d.external_display_name) property_name,l.calling_tn,l.called_tn,l.started_at,l.released_at,l.call_duration_seconds FROM call_logs l JOIN call_log_destinations d ON d.id=l.destination_id LEFT JOIN properties p ON p.id=d.property_id {$where} ORDER BY l.started_at DESC,l.id DESC LIMIT ? OFFSET ?");$pageValues=[...$values,$criteria->perPage,$offset];$this->bind($s,$types.'ii',$pageValues);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return['rows'=>$rows,'total'=>$total,'page'=>$page,'per_page'=>$criteria->perPage,'pages'=>$pages,'from'=>$total===0?0:$offset+1,'to'=>min($total,$offset+count($rows))];
 }
 private function predicate(CallLogFilterCriteria$criteria):array{$clauses=[];$types='';$values=[];if($criteria->fromDate!==''){$clauses[]='l.started_at>=?';$types.='s';$values[]=$criteria->fromDate;}if($criteria->toExclusive!==''){$clauses[]='l.started_at<?';$types.='s';$values[]=$criteria->toExclusive;}if($criteria->destinationPublicId!==''){$clauses[]='d.public_id=?';$types.='s';$values[]=$criteria->destinationPublicId;}return[$clauses===[]?'':'WHERE '.implode(' AND ',$clauses),$types,$values];}
 private function bind(\mysqli_stmt$statement,string$types,array&$values):void{if($types==='')return;$refs=[];foreach($values as$key=>&$value)$refs[$key]=&$value;unset($value);$statement->bind_param($types,...$refs);}
}
