<?php
declare(strict_types=1);
namespace NpmGateway\Repositories;
use mysqli;
use NpmGateway\ValueObjects\EmployeeEmergencyContact;
final class EmployeeEmergencyContactRepository
{
 public function __construct(private readonly mysqli $db){}
 public function findByEmployeeId(int $employeeId):?EmployeeEmergencyContact{$s=$this->db->prepare('SELECT public_id,first_name,last_name,relationship,primary_phone,alternate_phone,updated_at FROM employee_emergency_contacts WHERE employee_id=? LIMIT 1');$s->bind_param('i',$employeeId);$s->execute();$row=$s->get_result()->fetch_assoc();$s->close();return is_array($row)?EmployeeEmergencyContact::fromRow($row):null;}
 public function existsForEmployee(int $employeeId):bool{return $this->findByEmployeeId($employeeId)!==null;}
 public function insert(int $employeeId,string $publicId,array $data,string $at):void{$s=$this->db->prepare('INSERT INTO employee_emergency_contacts(public_id,employee_id,first_name,last_name,relationship,primary_phone,alternate_phone,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?)');$s->bind_param('sisssssss',$publicId,$employeeId,$data['first_name'],$data['last_name'],$data['relationship'],$data['primary_phone'],$data['alternate_phone'],$at,$at);$s->execute();$s->close();}
 public function update(int $employeeId,array $data,string $at):void{$s=$this->db->prepare('UPDATE employee_emergency_contacts SET first_name=?,last_name=?,relationship=?,primary_phone=?,alternate_phone=?,updated_at=? WHERE employee_id=?');$s->bind_param('ssssssi',$data['first_name'],$data['last_name'],$data['relationship'],$data['primary_phone'],$data['alternate_phone'],$at,$employeeId);$s->execute();$s->close();}
 public function findEmployeeByPublicId(string $publicId):?array{$s=$this->db->prepare("SELECT e.id,e.public_id,e.first_name,e.last_name,CONCAT(e.first_name,' ',e.last_name) display_name,e.employee_class,e.employment_status,e.business_email,u.id user_id,u.public_id user_public_id,u.status user_status,COALESCE((SELECT p.display_name FROM employee_property_assignments a JOIN properties p ON p.id=a.property_id WHERE a.employee_id=e.id AND a.is_primary=1 AND a.starts_on<=CURRENT_DATE AND a.ends_on IS NULL ORDER BY a.starts_on DESC LIMIT 1),CASE WHEN e.employee_class='corporate' THEN 'Corporate' ELSE '—' END) primary_property FROM employees e LEFT JOIN users u ON u.employee_id=e.id WHERE e.public_id=? LIMIT 1");$s->bind_param('s',$publicId);$s->execute();$row=$s->get_result()->fetch_assoc();$s->close();return is_array($row)?$row:null;}
 public function findAuthorizedMaintenanceForManager(int $managerEmployeeId,string $targetPublicId):?array{$s=$this->db->prepare("SELECT target.id,target.public_id,target.employee_class,target.employment_status,CONCAT(target.first_name,' ',target.last_name) display_name,p.id property_id,p.public_id property_public_id,p.display_name primary_property FROM employees target JOIN employee_property_assignments target_assignment ON target_assignment.employee_id=target.id AND target_assignment.is_primary=1 AND target_assignment.starts_on<=CURRENT_DATE AND target_assignment.ends_on IS NULL JOIN properties p ON p.id=target_assignment.property_id JOIN employee_property_assignments manager_assignment ON manager_assignment.property_id=p.id AND manager_assignment.employee_id=? AND manager_assignment.starts_on<=CURRENT_DATE AND manager_assignment.ends_on IS NULL JOIN employees manager ON manager.id=manager_assignment.employee_id AND manager.employee_class='manager' AND manager.employment_status='active' WHERE target.public_id=? AND target.employee_class='maintenance' AND target.employment_status='active' LIMIT 1");$s->bind_param('is',$managerEmployeeId,$targetPublicId);$s->execute();$row=$s->get_result()->fetch_assoc();$s->close();return is_array($row)?$row:null;}
 public function activeEmployees(string $status='all',string $class='all',string $search=''):array{$clauses=["e.employment_status='active'"];$types='';$params=[];if(in_array($status,['missing','completed'],true))$clauses[]=$status==='missing'?'c.id IS NULL':'c.id IS NOT NULL';if(in_array($class,['corporate','manager','maintenance'],true)){$clauses[]='e.employee_class=?';$types.='s';$params[]=$class;}if($search!==''){$clauses[]="CONCAT(e.first_name,' ',e.last_name) LIKE ?";$types.='s';$params[]='%'.$search.'%';}$sql="SELECT e.public_id employee_public_id,CONCAT(e.first_name,' ',e.last_name) display_name,e.employee_class,e.business_email,u.id user_id,u.status user_status,IF(c.id IS NULL,'missing','completed') eci_status,c.updated_at,COALESCE((SELECT p.display_name FROM employee_property_assignments a JOIN properties p ON p.id=a.property_id WHERE a.employee_id=e.id AND a.is_primary=1 AND a.starts_on<=CURRENT_DATE AND a.ends_on IS NULL ORDER BY a.starts_on DESC LIMIT 1),CASE WHEN e.employee_class='corporate' THEN 'Corporate' ELSE '—' END) primary_property FROM employees e LEFT JOIN employee_emergency_contacts c ON c.employee_id=e.id LEFT JOIN users u ON u.employee_id=e.id WHERE ".implode(' AND ',$clauses)." ORDER BY (c.id IS NOT NULL),e.last_name,e.first_name";$s=$this->db->prepare($sql);if($types!=='')$s->bind_param($types,...$params);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return $rows;}
 public function reminderRoutingCandidate(string $employeePublicId):?array{$s=$this->db->prepare("SELECT e.id,e.public_id,e.first_name,e.last_name,CONCAT(e.first_name,' ',e.last_name) display_name,e.employee_class,e.employment_status,e.business_email,u.id user_id,u.status user_status,p.public_id property_public_id,p.display_name primary_property,p.manager_email FROM employees e LEFT JOIN users u ON u.employee_id=e.id LEFT JOIN employee_property_assignments a ON a.id=(SELECT a2.id FROM employee_property_assignments a2 WHERE a2.employee_id=e.id AND a2.is_primary=1 AND a2.starts_on<=CURRENT_DATE AND a2.ends_on IS NULL ORDER BY a2.starts_on DESC,a2.id DESC LIMIT 1) LEFT JOIN properties p ON p.id=a.property_id WHERE e.public_id=? LIMIT 1");$s->bind_param('s',$employeePublicId);$s->execute();$row=$s->get_result()->fetch_assoc();$s->close();return is_array($row)?$row:null;}
}
