<?php declare(strict_types=1);namespace NpmGateway\Repositories;
final class MarketingFlyerRepository{
 public function __construct(private readonly \mysqli$db){}
 public function properties():array{return$this->db->query("SELECT id,public_id,property_code,display_name FROM properties WHERE status='active' AND NOT(prop_id=1 AND property_code='CO' AND slug='corporate') ORDER BY display_name,id")->fetch_all(MYSQLI_ASSOC);}
 public function property(string$public):?array{$s=$this->db->prepare("SELECT id,public_id,property_code,slug,display_name FROM properties WHERE public_id=? AND status='active' AND NOT(prop_id=1 AND property_code='CO' AND slug='corporate') LIMIT 1");$s->bind_param('s',$public);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();return is_array($r)?$r:null;}
 public function find(string$public):?array{$s=$this->db->prepare("SELECT f.*,p.public_id property_public_id,p.property_code,p.slug property_slug,p.display_name property_name,CONCAT(e.first_name,' ',e.last_name) uploaded_by_name FROM marketing_flyers f JOIN properties p ON p.id=f.property_id JOIN users u ON u.id=f.uploaded_by_user_id JOIN employees e ON e.id=u.employee_id WHERE f.public_id=? LIMIT 1");$s->bind_param('s',$public);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();return is_array($r)?$r:null;}
 public function managerAccessible(string$public,string$slug,int$employee):?array{$s=$this->db->prepare("SELECT f.*,p.slug property_slug,p.display_name property_name FROM marketing_flyers f JOIN properties p ON p.id=f.property_id WHERE f.public_id=? AND p.slug=? AND p.status='active' AND EXISTS(SELECT 1 FROM employee_property_assignments a WHERE a.property_id=f.property_id AND a.employee_id=? AND a.assignment_type IN('property_manager','assistant_manager') AND a.starts_on<=CURRENT_DATE AND(a.ends_on IS NULL OR a.ends_on>=CURRENT_DATE)) LIMIT 1");$s->bind_param('ssi',$public,$slug,$employee);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();return is_array($r)?$r:null;}
 public function logical(int$p,string$m,string$t):?array{$s=$this->db->prepare('SELECT * FROM marketing_flyers WHERE property_id=? AND flyer_month=? AND flyer_type=? LIMIT 1');$s->bind_param('iss',$p,$m,$t);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();return is_array($r)?$r:null;}
 public function list(string$m,?int$p):array{$sql="SELECT f.*,p.public_id property_public_id,p.slug property_slug,p.display_name property_name,CONCAT(e.first_name,' ',e.last_name) uploaded_by_name FROM marketing_flyers f JOIN properties p ON p.id=f.property_id JOIN users u ON u.id=f.uploaded_by_user_id JOIN employees e ON e.id=u.employee_id WHERE f.flyer_month=?".($p?' AND f.property_id=?':'')." ORDER BY f.uploaded_at DESC,f.id DESC";$s=$this->db->prepare($sql);if($p)$s->bind_param('si',$m,$p);else$s->bind_param('s',$m);$s->execute();$r=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return$r;}
 public function recipients(int$p):array{$s=$this->db->prepare("SELECT DISTINCT LOWER(e.business_email) email FROM employee_property_assignments a JOIN employees e ON e.id=a.employee_id LEFT JOIN users u ON u.employee_id=e.id WHERE a.property_id=? AND a.assignment_type IN('property_manager','assistant_manager') AND(a.ends_on IS NULL OR a.ends_on>=CURRENT_DATE) AND a.starts_on<=CURRENT_DATE AND e.employment_status='active' AND e.business_email IS NOT NULL AND e.business_email<>'' AND (u.id IS NULL OR u.status='active')");$s->bind_param('i',$p);$s->execute();$r=array_column($s->get_result()->fetch_all(MYSQLI_ASSOC),'email');$s->close();return$r;}
 public function db():\mysqli{return$this->db;}
}
