<?php declare(strict_types=1);namespace NpmGateway\Repositories;
final class MarketingFlyerNotificationOutboxRepository{
 public function __construct(private readonly \mysqli$db){}
 public function enqueue(array$event,array$recipients,string$at):int{$count=0;foreach($recipients as$email){$public=$event['delivery_public_id']();$identity=hash('sha256',strtolower($email));$key=hash('sha256','marketing-flyer:'.$event['flyer_public_id'].':'.$event['event_type'].':'.$event['content_hash'].':'.$identity);$s=$this->db->prepare("INSERT IGNORE INTO marketing_flyer_notification_outbox(public_id,flyer_id,event_public_id,event_type,recipient_email,idempotency_key,status,available_at,attachment_object_key,attachment_filename,attachment_mime_type,property_name,flyer_month,flyer_type,uploaded_by_name,uploaded_at,created_at,updated_at)VALUES(?,?,?,?,?,?,'pending',?,?,?,?,?,?,?,?,?,?,?)");$types='si'.str_repeat('s',15);$s->bind_param($types,$public,$event['flyer_id'],$event['event_public_id'],$event['event_type'],$email,$key,$at,$event['attachment_object_key'],$event['attachment_filename'],$event['attachment_mime_type'],$event['property_name'],$event['flyer_month'],$event['flyer_type'],$event['uploaded_by_name'],$event['uploaded_at'],$at,$at);$s->execute();$count+=$s->affected_rows;$s->close();}return$count;}
 public function claim(int$limit,string$token,string$now,string$expired):array{$s=$this->db->prepare("UPDATE marketing_flyer_notification_outbox SET status='processing',claim_token=?,claimed_at=?,updated_at=? WHERE ((status IN ('pending','retry') AND available_at<=?) OR (status='processing' AND claimed_at<?)) ORDER BY available_at,id LIMIT ?");$s->bind_param('sssssi',$token,$now,$now,$now,$expired,$limit);$s->execute();$s->close();$s=$this->db->prepare("SELECT o.*,p.slug property_slug FROM marketing_flyer_notification_outbox o LEFT JOIN marketing_flyers f ON f.id=o.flyer_id LEFT JOIN properties p ON p.id=f.property_id WHERE o.claim_token=? ORDER BY o.id");$s->bind_param('s',$token);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return$rows;}
 public function delivered(int$id,string$token,string$at):void{$s=$this->db->prepare("UPDATE marketing_flyer_notification_outbox SET status='delivered',attempt_count=attempt_count+1,last_attempt_at=?,delivered_at=?,claimed_at=NULL,claim_token=NULL,last_failure_code=NULL,updated_at=? WHERE id=? AND claim_token=? AND status='processing'");$s->bind_param('sssis',$at,$at,$at,$id,$token);$s->execute();$s->close();}
 public function failedAttempt(int$id,string$token,string$at,string$code,bool$terminal,string$available):void{$status=$terminal?'failed':'retry';$s=$this->db->prepare("UPDATE marketing_flyer_notification_outbox SET status=?,attempt_count=attempt_count+1,last_attempt_at=?,available_at=?,failed_at=IF(?='failed',?,NULL),last_failure_code=?,claimed_at=NULL,claim_token=NULL,updated_at=? WHERE id=? AND claim_token=? AND status='processing'");$s->bind_param('sssssssis',$status,$at,$available,$status,$at,$code,$at,$id,$token);$s->execute();$s->close();}
 public function cancelForFlyer(int$flyerId,string$at):void{$u=$this->db->prepare("UPDATE marketing_flyer_notification_outbox SET status='cancelled',claimed_at=NULL,claim_token=NULL,updated_at=? WHERE flyer_id=? AND status IN ('pending','retry','processing')");$u->bind_param('si',$at,$flyerId);$u->execute();$u->close();}
 public function heartbeatStart(string$name,string$at):void{$s=$this->db->prepare("INSERT INTO gateway_worker_heartbeats(worker_name,last_started_at,updated_at)VALUES(?,?,?) ON DUPLICATE KEY UPDATE last_started_at=VALUES(last_started_at),updated_at=VALUES(updated_at)");$s->bind_param('sss',$name,$at,$at);$s->execute();$s->close();}
 public function heartbeatFinish(string$name,string$at,int$code,int$count):void{$s=$this->db->prepare("UPDATE gateway_worker_heartbeats SET last_completed_at=?,last_success_at=IF(?=0,?,last_success_at),last_exit_code=?,last_processed_count=?,updated_at=? WHERE worker_name=?");$s->bind_param('sisiiss',$at,$code,$at,$code,$count,$at,$name);$s->execute();$s->close();}
 public function health(string$name):array{$s=$this->db->prepare('SELECT * FROM gateway_worker_heartbeats WHERE worker_name=?');$s->bind_param('s',$name);$s->execute();$heartbeat=$s->get_result()->fetch_assoc();$s->close();$counts=['pending'=>0,'retry'=>0,'failed'=>0];foreach($this->db->query("SELECT status,COUNT(*) total FROM marketing_flyer_notification_outbox WHERE status IN ('pending','retry','failed') GROUP BY status")->fetch_all(MYSQLI_ASSOC)as$row)$counts[$row['status']]=(int)$row['total'];$oldest=$this->db->query("SELECT MIN(available_at) FROM marketing_flyer_notification_outbox WHERE status IN ('pending','retry')")->fetch_row()[0]??null;return compact('heartbeat','counts','oldest');}
}
