<?php
declare(strict_types=1);
namespace NpmGateway\Repositories;
use mysqli;
final class NotificationRepository
{
 public function __construct(private readonly mysqli $db){}
 public function findBySource(string $type,string $source):?array{$s=$this->db->prepare('SELECT id,public_id FROM notifications WHERE notification_type=? AND source_entity_public_id=? LIMIT 1');$s->bind_param('ss',$type,$source);$s->execute();$row=$s->get_result()->fetch_assoc();$s->close();return is_array($row)?$row:null;}
 public function insert(array $n):int{$json=json_encode($n['payload'],JSON_THROW_ON_ERROR);$s=$this->db->prepare('INSERT INTO notifications(public_id,notification_type,title,summary,payload,requires_acknowledgment,priority,source_entity_type,source_entity_public_id,created_by_user_id,published_at,status,created_at) VALUES(?,?,?,?,?,1,?,?,?,?,?,\'published\',?)');$type='employee_created';$priority='normal';$entity='employee';$s->bind_param('ssssssssiss',$n['public_id'],$type,$n['title'],$n['summary'],$json,$priority,$entity,$n['source_public_id'],$n['actor_id'],$n['timestamp'],$n['timestamp']);$s->execute();$id=$this->db->insert_id;$s->close();return $id;}
 public function insertCompanyNotice(array $n):int{$json=json_encode($n['payload'],JSON_THROW_ON_ERROR);$type='company_notice';$entity='company_notice';$status='published';$s=$this->db->prepare('INSERT INTO notifications(public_id,notification_type,title,summary,payload,requires_acknowledgment,priority,source_entity_type,source_entity_public_id,created_by_user_id,published_at,status,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');$s->bind_param('sssssisssisss',$n['public_id'],$type,$n['title'],$n['summary'],$json,$n['requires_acknowledgment'],$n['priority'],$entity,$n['source_public_id'],$n['actor_id'],$n['timestamp'],$status,$n['timestamp']);$s->execute();$id=$this->db->insert_id;$s->close();return $id;}
 public function companyNoticeSummaries():array{return $this->db->query("SELECT n.public_id,n.title,n.priority,n.published_at,JSON_UNQUOTE(JSON_EXTRACT(n.payload,'$.published_by_name')) published_by,n.requires_acknowledgment,COUNT(r.id) recipients,SUM(r.acknowledged_at IS NOT NULL) acknowledged,SUM(n.requires_acknowledgment=1 AND r.acknowledged_at IS NULL) outstanding,SUM(r.email_status='sent') sent,SUM(r.email_status='failed') failed,SUM(r.email_status='skipped_no_email') skipped FROM notifications n LEFT JOIN notification_recipients r ON r.notification_id=n.id WHERE n.notification_type='company_notice' GROUP BY n.id ORDER BY n.published_at DESC")->fetch_all(MYSQLI_ASSOC);}
 public function companyNoticeDetail(string $publicId):?array{$s=$this->db->prepare("SELECT n.*,JSON_UNQUOTE(JSON_EXTRACT(n.payload,'$.published_by_name')) published_by FROM notifications n WHERE n.public_id=? AND n.notification_type='company_notice' LIMIT 1");$s->bind_param('s',$publicId);$s->execute();$row=$s->get_result()->fetch_assoc();$s->close();if(!is_array($row))return null;$row['payload']=json_decode($row['payload'],true,512,JSON_THROW_ON_ERROR);$s=$this->db->prepare("SELECT CONCAT(e.first_name,' ',e.last_name) employee,u.username,u.status,r.email_status,r.first_viewed_at,r.acknowledged_at FROM notification_recipients r JOIN users u ON u.id=r.user_id JOIN employees e ON e.id=u.employee_id WHERE r.notification_id=? ORDER BY e.last_name,e.first_name");$s->bind_param('i',$row['id']);$s->execute();$row['recipients']=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return $row;}
}
