<?php declare(strict_types=1);namespace NpmGateway\Repositories;use mysqli;
final class RmAuditRepository{public function __construct(private readonly mysqli$db){}
 public function property(string$public):?array{$s=$this->db->prepare("SELECT id,public_id,slug,display_name,manager_email FROM properties WHERE public_id=? AND status='active' AND slug<>'corporate' LIMIT 1");$s->bind_param('s',$public);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();return is_array($r)?$r:null;}
 public function properties():array{return$this->db->query("SELECT public_id,display_name FROM properties WHERE status='active' AND slug<>'corporate' ORDER BY display_name,id")->fetch_all(MYSQLI_ASSOC);}
 public function insert(array$r):int{$s=$this->db->prepare("INSERT INTO rm_audits(public_id,property_id,tenant_name,unit_identifier,audit_findings_html,audit_findings_text,status,submitted_by_user_id,submitted_at,updated_at)VALUES(?,?,?,?,?,?,'open',?,?,?)");$s->bind_param('sissssiss',$r['public_id'],$r['property_id'],$r['tenant'],$r['unit'],$r['findings_html'],$r['findings_text'],$r['actor_id'],$r['at'],$r['at']);$s->execute();$id=$this->db->insert_id;$s->close();return$id;}
 public function event(int$id,string$public,string$type,int$actor,?string$comments,string$at):void{$s=$this->db->prepare('INSERT INTO rm_audit_history(public_id,rm_audit_id,event_type,actor_user_id,comments,created_at)VALUES(?,?,?,?,?,?)');$s->bind_param('sisiss',$public,$id,$type,$actor,$comments,$at);$s->execute();$s->close();}
 public function detail(string$public,?int$property=null,bool$lock=false):?array{$sql="SELECT a.*,p.public_id property_public_id,p.slug property_slug,p.display_name property_name,p.manager_email,CONCAT(se.first_name,' ',se.last_name) submitted_by_name,CONCAT(ce.first_name,' ',ce.last_name) completed_by_name FROM rm_audits a JOIN properties p ON p.id=a.property_id JOIN users su ON su.id=a.submitted_by_user_id JOIN employees se ON se.id=su.employee_id LEFT JOIN users cu ON cu.id=a.completed_by_user_id LEFT JOIN employees ce ON ce.id=cu.employee_id WHERE a.public_id=? AND p.status='active' AND p.slug<>'corporate'".($property!==null?' AND a.property_id=?':'')." LIMIT 1".($lock?' FOR UPDATE':'');$s=$this->db->prepare($sql);if($property===null)$s->bind_param('s',$public);else$s->bind_param('si',$public,$property);$s->execute();$r=$s->get_result()->fetch_assoc();$s->close();if(!is_array($r))return null;$r['history']=$this->history((int)$r['id']);return$r;}
 public function history(int$id):array{$s=$this->db->prepare("SELECT h.event_type,h.comments,h.created_at,CONCAT(e.first_name,' ',e.last_name) actor_name FROM rm_audit_history h JOIN users u ON u.id=h.actor_user_id JOIN employees e ON e.id=u.employee_id WHERE h.rm_audit_id=? ORDER BY h.created_at,h.id");$s->bind_param('i',$id);$s->execute();$r=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return$r;}
 public function transition(int$id,array$from,string$to,int$actor,string$at):bool{$in=implode(',',array_fill(0,count($from),'?'));$sql="UPDATE rm_audits SET status=?,updated_at=?,completed_by_user_id=".($to==='completed'?'?':'NULL').",completed_at=".($to==='completed'?'?':'NULL')." WHERE id=? AND status IN ({$in})";$s=$this->db->prepare($sql);if($to==='completed'){$types='ssisi'.str_repeat('s',count($from));$params=[$to,$at,$actor,$at,$id,...$from];}else{$types='ssi'.str_repeat('s',count($from));$params=[$to,$at,$id,...$from];}$s->bind_param($types,...$params);$s->execute();$ok=$s->affected_rows===1;$s->close();return$ok;}
 public function list(?int$property,string$status,string$propertyPublic,string$search,bool$corporate):array{$where=["p.status='active'","p.slug<>'corporate'"];$types='';$params=[];if($property!==null){$where[]='a.property_id=?';$types.='i';$params[]=$property;}if(in_array($status,['open','completed','returned'],true)){$where[]='a.status=?';$types.='s';$params[]=$status;}if($corporate&&preg_match('/^[0-9A-HJKMNP-TV-Z]{26}$/D',$propertyPublic)){$where[]='p.public_id=?';$types.='s';$params[]=$propertyPublic;}if($search!==''){$q='%'.$search.'%';$where[]='(a.tenant_name LIKE ? OR a.unit_identifier LIKE ? OR a.audit_findings_text LIKE ?)';$types.='sss';array_push($params,$q,$q,$q);}$priority=$corporate?"WHEN 'open' THEN 0 WHEN 'returned' THEN 1":"WHEN 'returned' THEN 0 WHEN 'open' THEN 1";$sql="SELECT a.public_id,a.tenant_name,a.unit_identifier,a.status,a.submitted_at,a.updated_at,p.display_name property_name FROM rm_audits a JOIN properties p ON p.id=a.property_id WHERE ".implode(' AND ',$where)." ORDER BY CASE a.status {$priority} WHEN 'completed' THEN 2 ELSE 3 END,a.updated_at DESC,a.id DESC";$s=$this->db->prepare($sql);if($types!=='')$s->bind_param($types,...$params);$s->execute();$r=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return$r;}
 public function counts(?int$property,string$status='',string$propertyPublic='',string$search=''):array{$rows=$this->list($property,$status,$propertyPublic,$search,$property===null);$out=['total'=>count($rows),'open'=>0,'completed'=>0,'returned'=>0];foreach($rows as$r)$out[$r['status']]++;return$out;}
 public function actionableCount(int$propertyId):int{$s=$this->db->prepare("SELECT COUNT(*) FROM rm_audits WHERE property_id=? AND status IN ('open','returned')");$s->bind_param('i',$propertyId);$s->execute();$count=(int)$s->get_result()->fetch_row()[0];$s->close();return$count;}
 public function overviewList(string$start,string$end,string$propertyPublicId='',bool$openOnly=false):array{$sql="SELECT a.public_id,a.tenant_name,a.unit_identifier,a.audit_findings_html,a.status,a.submitted_at,p.public_id property_public_id,p.display_name property_name FROM rm_audits a JOIN properties p ON p.id=a.property_id WHERE p.status='active' AND p.slug<>'corporate' AND a.submitted_at>=? AND a.submitted_at<?";$types='ss';$params=[$start,$end];if($propertyPublicId!==''){$sql.=' AND p.public_id=?';$types.='s';$params[]=$propertyPublicId;}if($openOnly)$sql.=" AND a.status IN ('open','returned')";$sql.=' ORDER BY p.display_name,p.id,a.submitted_at DESC,a.id DESC';$s=$this->db->prepare($sql);$s->bind_param($types,...$params);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return$rows;}
}
