<?php
declare(strict_types=1);
namespace NpmGateway\Repositories;
use NpmGateway\Contracts\StorageObjectStoreInterface;
final class StorageObjectRepository implements StorageObjectStoreInterface
{
 public function __construct(private readonly \mysqli $db){}
 public function insertTemporary(array $m):int{$s=$this->db->prepare("INSERT INTO storage_objects(public_id,provider,provider_container,object_key,original_filename,display_filename,mime_type,byte_size,sha256_hex,lifecycle_state,uploaded_by_user_id,temporary_review_owner_user_id,created_at) VALUES (?,?,?,?,?,?,?,?,?,'temporary',?,?,?)");$s->bind_param('sssssssisiis',$m['public_id'],$m['provider'],$m['container'],$m['object_key'],$m['original_filename'],$m['display_filename'],$m['mime_type'],$m['byte_size'],$m['sha256'],$m['uploader_id'],$m['owner_id'],$m['created_at']);$s->execute();$id=$this->db->insert_id;$s->close();return $id;}
 public function findByPublicId(string $publicId):?array{$s=$this->db->prepare('SELECT * FROM storage_objects WHERE public_id=? LIMIT 1');$s->bind_param('s',$publicId);$s->execute();$row=$s->get_result()->fetch_assoc();$s->close();return is_array($row)?$row:null;}
 /** @return list<string> */
 public function keysRecordedUnderPrefix(string $container,string $prefix):array{$s=$this->db->prepare("SELECT object_key FROM storage_objects WHERE provider_container=? AND object_key LIKE ? ESCAPE '=' ORDER BY object_key");$pattern=str_replace(['=','%','_'],['==','=%','=_'],$prefix).'%';$s->bind_param('ss',$container,$pattern);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return array_values(array_map(static fn(array $row):string=>(string)$row['object_key'],$rows));}
 public function findOwnedTemporary(string $publicId,int $ownerId):?array{$s=$this->db->prepare("SELECT * FROM storage_objects WHERE public_id=? AND temporary_review_owner_user_id=? AND lifecycle_state='temporary' LIMIT 1");$s->bind_param('si',$publicId,$ownerId);$s->execute();$row=$s->get_result()->fetch_assoc();$s->close();return is_array($row)?$row:null;}
 public function markDeletedByUser(int $id,int $actorId,string $at):bool{$s=$this->db->prepare("UPDATE storage_objects SET lifecycle_state='deleted',temporary_review_owner_user_id=NULL,deleted_at=?,deleted_by_user_id=?,updated_at=? WHERE id=? AND lifecycle_state='temporary'");$s->bind_param('sisi',$at,$actorId,$at,$id);$s->execute();$ok=$s->affected_rows===1;$s->close();return $ok;}
 public function markDeletedBySystem(int $id,string $at):bool{$s=$this->db->prepare("UPDATE storage_objects SET lifecycle_state='deleted',temporary_review_owner_user_id=NULL,deleted_at=?,deleted_by_user_id=NULL,updated_at=? WHERE id=? AND lifecycle_state='temporary'");$s->bind_param('ssi',$at,$at,$id);$s->execute();$ok=$s->affected_rows===1;$s->close();return $ok;}
 public function markPublished(int $id,string $at):bool{$s=$this->db->prepare("UPDATE storage_objects SET lifecycle_state='published',temporary_review_owner_user_id=NULL,published_at=?,deleted_at=NULL,deleted_by_user_id=NULL,updated_at=? WHERE id=? AND lifecycle_state='temporary'");$s->bind_param('ssi',$at,$at,$id);$s->execute();$ok=$s->affected_rows===1;$s->close();return $ok;}
 public function cleanupCandidates(string $before,int $limit=100):array{$limit=max(1,min(500,$limit));$s=$this->db->prepare("SELECT s.* FROM storage_objects s WHERE s.lifecycle_state='temporary' AND s.created_at<? AND NOT EXISTS(SELECT 1 FROM notification_storage_objects n WHERE n.storage_object_id=s.id) ORDER BY s.created_at,s.id LIMIT ?");$s->bind_param('si',$before,$limit);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return $rows;}
 public function hasNotificationLink(int $id):bool{$s=$this->db->prepare('SELECT 1 FROM notification_storage_objects WHERE storage_object_id=? LIMIT 1');$s->bind_param('i',$id);$s->execute();$found=$s->get_result()->fetch_row()!==null;$s->close();return $found;}
 public function findPublishedAuthorized(string $publicId,int $userId,bool $publisher,string $role):?array{$sql="SELECT s.* FROM storage_objects s JOIN notification_storage_objects nso ON nso.storage_object_id=s.id JOIN notifications n ON n.id=nso.notification_id WHERE s.public_id=? AND s.lifecycle_state='published' AND nso.asset_role=? AND n.status='published' AND (EXISTS(SELECT 1 FROM notification_recipients nr WHERE nr.notification_id=n.id AND nr.user_id=?)".($publisher?' OR n.notification_type=\'company_notice\'':'').") LIMIT 1";$s=$this->db->prepare($sql);$s->bind_param('ssi',$publicId,$role,$userId);$s->execute();$row=$s->get_result()->fetch_assoc();$s->close();return is_array($row)?$row:null;}
}
