<?php
declare(strict_types=1);
namespace NpmGateway\Repositories;
use NpmGateway\ValueObjects\ZillowReportCriteria;
final readonly class ZillowRepository
{
 public const OWNER_PROPERTY_CODES=['BT','CF','FF','HR','MW','PP','PH','PM','SM','WP'];
 public function __construct(private \mysqli$db){}
 public function hashExists(string$hash):bool{$s=$this->db->prepare('SELECT 1 FROM zillow_imports WHERE file_sha256=? LIMIT 1');$s->bind_param('s',$hash);$s->execute();$found=$s->get_result()->fetch_row()!==null;$s->close();return$found;}
 public function mappings(array$names):array{if($names===[])return[];$marks=implode(',',array_fill(0,count($names),'?'));$s=$this->db->prepare("SELECT source_listing_name,property_id FROM zillow_property_mappings WHERE active=1 AND source_listing_name IN ({$marks})");$types=str_repeat('s',count($names));$s->bind_param($types,...$names);$s->execute();$map=[];foreach($s->get_result()->fetch_all(MYSQLI_ASSOC)as$row)$map[$row['source_listing_name']]=(int)$row['property_id'];$s->close();return$map;}
 public function insertImport(array$d):int{$s=$this->db->prepare('INSERT INTO zillow_imports(public_id,original_filename,file_sha256,uploaded_by_user_id,source_started_at,source_ended_at,total_lead_count,phone_lead_count,email_lead_count,imported_at,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)');$s->bind_param('sssissiiiss',$d['public_id'],$d['original_filename'],$d['file_sha256'],$d['user_id'],$d['source_started_at'],$d['source_ended_at'],$d['total'],$d['phone'],$d['email'],$d['at'],$d['at']);$s->execute();$id=(int)$this->db->insert_id;$s->close();return$id;}
 public function insertLeads(int$import,array$rows,array$map,string$at,callable$id):void{$sql='INSERT INTO zillow_leads(public_id,import_id,property_id,source_listing_name,occurred_at,lead_type,prospect_name,prospect_email,prospect_phone_raw,prospect_phone_normalized,created_at) VALUES(?,?,?,?,?,?,?,?,?,?,?)';$s=$this->db->prepare($sql);foreach($rows as$row){$public=$id();$property=$map[$row['source_listing_name']];$s->bind_param('siissssssss',$public,$import,$property,$row['source_listing_name'],$row['occurred_at'],$row['lead_type'],$row['prospect_name'],$row['prospect_email'],$row['prospect_phone_raw'],$row['prospect_phone_normalized'],$at);$s->execute();}$s->close();}
 public function history():array{return$this->db->query('SELECT i.*,e.first_name,e.last_name FROM zillow_imports i JOIN users u ON u.id=i.uploaded_by_user_id JOIN employees e ON e.id=u.employee_id ORDER BY i.imported_at DESC,i.id DESC')->fetch_all(MYSQLI_ASSOC);}
 public function mostRecentRange():?array{$row=$this->db->query('SELECT source_started_at,source_ended_at FROM zillow_imports ORDER BY source_ended_at DESC,source_started_at DESC,id DESC LIMIT 1')->fetch_assoc();return$row?:null;}
 public function reportProperties():array{$codes=self::OWNER_PROPERTY_CODES;$marks=implode(',',array_fill(0,count($codes),'?'));$order=[];foreach($codes as$i=>$code)$order[]='WHEN ? THEN '.($i+1);$values=[...$codes,...$codes];$s=$this->db->prepare("SELECT id,public_id,property_code,display_name FROM properties WHERE status='active' AND property_code IN ({$marks}) ORDER BY CASE property_code ".implode(' ',$order).' ELSE 999 END');$this->bind($s,str_repeat('s',count($values)),$values);$s->execute();$rows=$s->get_result()->fetch_all(MYSQLI_ASSOC);$s->close();return$rows;}
 public function report(ZillowReportCriteria$c,array$properties):array{[$where,$types,$values]=$this->predicate($c);$s=$this->db->prepare("SELECT l.property_id,COUNT(*) total,SUM(l.lead_type='phone') phone,SUM(l.lead_type='email') email FROM zillow_leads l JOIN properties p ON p.id=l.property_id {$where} GROUP BY l.property_id");$this->bind($s,$types,$values);$s->execute();$by=[];foreach($s->get_result()->fetch_all(MYSQLI_ASSOC)as$row)$by[(int)$row['property_id']]=$row;$s->close();$rows=[];$totals=['total'=>0,'phone'=>0,'email'=>0];foreach($properties as$p){$a=$by[(int)$p['id']]??[];$row=$p+['total'=>(int)($a['total']??0),'phone'=>(int)($a['phone']??0),'email'=>(int)($a['email']??0)];foreach($totals as$k=>$_)$totals[$k]+=$row[$k];$rows[]=$row;}foreach($rows as&$row)$row['percent']=$totals['total']===0?null:$row['total']/$totals['total']*100;unset($row);$count=$this->db->prepare("SELECT COUNT(*) FROM zillow_leads l JOIN properties p ON p.id=l.property_id {$where}");$countValues=$values;$this->bind($count,$types,$countValues);$count->execute();$records=(int)$count->get_result()->fetch_row()[0];$count->close();$pages=max(1,(int)ceil($records/$c->perPage));$page=min($c->page,$pages);$offset=($page-1)*$c->perPage;$detail=$this->db->prepare("SELECT p.display_name property_name,l.occurred_at,l.lead_type,l.prospect_name,l.prospect_email,l.prospect_phone_raw,l.prospect_phone_normalized FROM zillow_leads l JOIN properties p ON p.id=l.property_id {$where} ORDER BY l.occurred_at DESC,l.id DESC LIMIT ? OFFSET ?");$detailValues=[...$values,$c->perPage,$offset];$this->bind($detail,$types.'ii',$detailValues);$detail->execute();$details=$detail->get_result()->fetch_all(MYSQLI_ASSOC);$detail->close();return['rows'=>$rows,'totals'=>$totals,'details'=>$details,'records'=>$records,'page'=>$page,'pages'=>$pages,'per_page'=>$c->perPage,'from'=>$records===0?0:$offset+1,'to'=>min($records,$offset+count($details))];}
 private function predicate(ZillowReportCriteria$c):array{$clauses=[];$types='';$values=[];if($c->fromDate!==''){$clauses[]='l.occurred_at>=?';$types.='s';$values[]=$c->fromDate;}if($c->toExclusive!==''){$clauses[]='l.occurred_at<?';$types.='s';$values[]=$c->toExclusive;}if($c->propertyPublicId!==''){$clauses[]='p.public_id=?';$types.='s';$values[]=$c->propertyPublicId;}if($c->type!=='all'){$clauses[]='l.lead_type=?';$types.='s';$values[]=$c->type;}return[$clauses===[]?'':'WHERE '.implode(' AND ',$clauses),$types,$values];}
 private function bind(\mysqli_stmt$s,string$types,array&$values):void{if($types==='')return;$refs=[];foreach($values as$key=>&$value)$refs[$key]=&$value;unset($value);$s->bind_param($types,...$refs);}
}
