<?php
declare(strict_types=1);
$components=dirname(__DIR__,2).'/components';$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');$v=static fn($k)=>$e($input[$k]??'');$missing=!empty($input['receipt_missing']);$groups=['Managers'=>[],'Assistant Managers'=>[],'Maintenance'=>[]];foreach($employees as $employee)$groups[$employee['role_group']??'Maintenance'][]=$employee;ob_start();
$breadcrumbItems=[['label'=>'Community Actions','url'=>'/community-actions'],['label'=>$c->propertyDisplayName,'url'=>'/community-actions/'.$c->propertySlug],['label'=>'Credit Card Purchases','url'=>'/community-actions/'.$c->propertySlug.'/credit-card-purchases'],['label'=>'Post Purchase','current'=>true]];require $components.'/breadcrumb.php';$heading='Post Purchase';$description=$c->propertyDisplayName.' — Record a company credit card transaction.';$eyebrow='Credit Card Purchases';$actionsHtml='';require $components.'/page-header.php';
if($errors):?><div class="alert gateway-alert gateway-alert--danger" role="alert"><strong>Correct the highlighted fields.</strong></div><?php endif?>
<form method="post" enctype="multipart/form-data" action="/community-actions/<?=$e($c->propertySlug)?>/credit-card-purchases" data-processing-form data-processing-message="Posting purchase…" class="gateway-card gateway-property-form-card gateway-purchase-form"><input type="hidden" name="_token" value="<?=$e($csrfToken)?>"><div class="gateway-card__body">
 <p class="gateway-required-note"><span aria-hidden="true">*</span> Fields marked with <span aria-hidden="true">*</span><span class="visually-hidden">an asterisk</span> are required.</p>
 <section aria-labelledby="purchase-information-heading"><h2 class="gateway-form-section-title" id="purchase-information-heading">Purchase Information</h2><div class="row gateway-form-grid">
  <div class="col-12 col-md-4"><label class="form-label" for="card_last_four">Last Four Digits of Card <span class="gateway-required-indicator" aria-hidden="true">*</span><span class="visually-hidden"> required</span></label><input class="form-control" id="card_last_four" name="card_last_four" inputmode="numeric" maxlength="4" value="<?=$v('card_last_four')?>" required><?php if(isset($errors['card_last_four'])):?><div class="invalid-feedback d-block"><?=$e($errors['card_last_four'])?></div><?php endif?></div>
  <div class="col-12 col-md-4"><label class="form-label" for="purchase_date">Date of Purchase <span class="gateway-required-indicator" aria-hidden="true">*</span><span class="visually-hidden"> required</span></label><input class="form-control" type="date" id="purchase_date" name="purchase_date" value="<?=$v('purchase_date')?>" required></div>
  <div class="col-12 col-md-4"><label class="form-label" for="amount">Amount <span class="gateway-required-indicator" aria-hidden="true">*</span><span class="visually-hidden"> required</span></label><input class="form-control" id="amount" name="amount" inputmode="decimal" value="<?=$v('amount')?>" required></div>
  <div class="col-12 col-md-6"><label class="form-label" for="purchased_by">Purchased By <span class="gateway-required-indicator" aria-hidden="true">*</span><span class="visually-hidden"> required</span></label><select class="form-select" id="purchased_by" name="purchased_by_employee_public_id" required><option value="">Choose employee</option><?php foreach($groups as $label=>$members):?><optgroup label="<?=$e($label)?>"><?php foreach($members as $employee):?><option value="<?=$e($employee['public_id'])?>"<?=($input['purchased_by_employee_public_id']??'')===$employee['public_id']?' selected':''?>><?=$e($employee['display_name'])?></option><?php endforeach?></optgroup><?php endforeach?></select></div>
  <div class="col-12 col-md-6"><label class="form-label" for="vendor">Purchased At <span class="gateway-required-indicator" aria-hidden="true">*</span><span class="visually-hidden"> required</span></label><input class="form-control" id="vendor" name="vendor" maxlength="150" value="<?=$v('vendor')?>" required></div>
  <div class="col-12"><label class="form-label" for="description">Description <span class="gateway-required-indicator" aria-hidden="true">*</span><span class="visually-hidden"> required</span></label><textarea class="form-control" id="description" name="description" maxlength="2000" rows="4" aria-describedby="description-help" data-character-counter data-character-counter-max="2000" required><?=$v('description')?></textarea><div class="form-text" id="description-help">Describe the purchase. Include lot numbers or operational details when useful.</div></div>
 </div></section>
 <section class="gateway-form-section gateway-receipt-documentation" aria-labelledby="receipt-documentation-heading" data-receipt-documentation><h2 class="gateway-form-section-title" id="receipt-documentation-heading">Receipt Documentation</h2>
  <div class="gateway-receipt-upload"><label class="form-label" for="receipt">Receipt</label><input class="form-control" type="file" id="receipt" name="receipt" accept="application/pdf,image/jpeg,image/png"></div>
  <div class="gateway-receipt-separator" aria-hidden="true"><span>OR</span></div>
  <div class="form-check gateway-form-check--top-aligned"><input class="form-check-input" type="checkbox" id="receipt_missing" name="receipt_missing" value="1" aria-controls="missing-receipt-fields" aria-expanded="<?=$missing?'true':'false'?>"<?=$missing?' checked':''?>><label class="form-check-label" for="receipt_missing">I do not have the receipt</label></div>
  <div class="gateway-missing-receipt-fields" id="missing-receipt-fields" data-missing-receipt-fields><label class="form-label" for="missing_receipt_reason">Missing Receipt Explanation</label><textarea class="form-control" id="missing_receipt_reason" name="missing_receipt_reason" maxlength="1000" rows="3"<?=$missing?' required':''?>><?=$v('missing_receipt_reason')?></textarea><?php if(isset($errors['missing_receipt_reason'])):?><div class="invalid-feedback d-block"><?=$e($errors['missing_receipt_reason'])?></div><?php endif?></div>
  <?php if(isset($errors['receipt'])):?><div class="invalid-feedback d-block"><?=$e($errors['receipt'])?></div><?php endif?>
 </section>
 <div class="gateway-form-actions gateway-form-actions--primary-first"><button class="btn gateway-button gateway-button--primary" type="submit">Post Purchase</button><a class="btn gateway-button gateway-button--secondary" href="/community-actions/<?=$e($c->propertySlug)?>/credit-card-purchases">Cancel</a></div>
</div></form><?php $contentHtml=(string)ob_get_clean();$pageTitle='Post Purchase — NPM Gateway';$navbarItems=\NpmGateway\Support\Navigation::forRoute('/community-actions',dirname(__DIR__,4));$navbarUserLabel=$user->displayName;$navbarUserContext='@'.$user->username;$creditCardPurchaseAssets=true;require dirname(__DIR__,2).'/layouts/app.php';
