<?php
declare(strict_types=1);
$components=dirname(__DIR__,2).'/components';$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');$v=static fn($k)=>$e($input[$k]??'');$groups=['Managers'=>[],'Assistant Managers'=>[],'Maintenance'=>[]];foreach($employees as $employee)$groups[$employee['role_group']??'Maintenance'][]=$employee;ob_start();
$breadcrumbItems=[['label'=>'Community Actions','url'=>'/community-actions'],['label'=>$c->propertyDisplayName,'url'=>'/community-actions/'.$c->propertySlug],['label'=>'Credit Card Purchases','url'=>'/community-actions/'.$c->propertySlug.'/credit-card-purchases'],['label'=>'Credit Card Purchase','url'=>'/community-actions/'.$c->propertySlug.'/credit-card-purchases/'.$purchase['public_id']],['label'=>'Edit Purchase','current'=>true]];require $components.'/breadcrumb.php';$heading='Edit Purchase';$description=$c->propertyDisplayName.' — Correct submitted purchase information.';$eyebrow='Credit Card Purchases';$actionsHtml='';require $components.'/page-header.php';
if($errors):?><div class="alert gateway-alert gateway-alert--danger" role="alert"><strong>Correct the highlighted fields.</strong><?php if(isset($errors['general'])):?><div><?=$e($errors['general'])?></div><?php endif?><?php if(isset($errors['record_version'])):?><div><?=$e($errors['record_version'])?></div><?php endif?></div><?php endif?>
<form method="post" action="/community-actions/<?=$e($c->propertySlug)?>/credit-card-purchases/<?=$e($purchase['public_id'])?>" data-processing-form data-processing-message="Saving correction…" class="gateway-card gateway-property-form-card gateway-purchase-form"><input type="hidden" name="_token" value="<?=$e($csrfToken)?>"><input type="hidden" name="record_version" value="<?=$v('record_version')?>"><div class="gateway-card__body">
 <p class="gateway-required-note"><span aria-hidden="true">*</span> Fields marked with <span aria-hidden="true">*</span><span class="visually-hidden">an asterisk</span> are required.</p>
 <section aria-labelledby="purchase-information-heading"><h2 class="gateway-form-section-title" id="purchase-information-heading">Purchase Information</h2><div class="row gateway-form-grid">
  <div class="col-12 col-md-4"><label class="form-label" for="card_last_four">Last Four Digits of Card <span class="gateway-required-indicator" aria-hidden="true">*</span></label><input class="form-control" id="card_last_four" name="card_last_four" inputmode="numeric" maxlength="4" value="<?=$v('card_last_four')?>" required><?php if(isset($errors['card_last_four'])):?><div class="invalid-feedback d-block"><?=$e($errors['card_last_four'])?></div><?php endif?></div>
  <div class="col-12 col-md-4"><label class="form-label" for="purchase_date">Date of Purchase <span class="gateway-required-indicator" aria-hidden="true">*</span></label><input class="form-control" type="date" id="purchase_date" name="purchase_date" value="<?=$v('purchase_date')?>" required><?php if(isset($errors['purchase_date'])):?><div class="invalid-feedback d-block"><?=$e($errors['purchase_date'])?></div><?php endif?></div>
  <div class="col-12 col-md-4"><label class="form-label" for="amount">Amount <span class="gateway-required-indicator" aria-hidden="true">*</span></label><input class="form-control" id="amount" name="amount" inputmode="decimal" value="<?=$v('amount')?>" required><?php if(isset($errors['amount'])):?><div class="invalid-feedback d-block"><?=$e($errors['amount'])?></div><?php endif?></div>
  <div class="col-12 col-md-6"><label class="form-label" for="purchased_by">Purchased By <span class="gateway-required-indicator" aria-hidden="true">*</span></label><select class="form-select" id="purchased_by" name="purchased_by_employee_public_id" required><option value="">Choose employee</option><?php foreach($groups as $label=>$members):?><optgroup label="<?=$e($label)?>"><?php foreach($members as $employee):?><option value="<?=$e($employee['public_id'])?>"<?=($input['purchased_by_employee_public_id']??'')===$employee['public_id']?' selected':''?>><?=$e($employee['display_name'])?></option><?php endforeach?></optgroup><?php endforeach?></select><?php if(isset($errors['purchased_by_employee_public_id'])):?><div class="invalid-feedback d-block"><?=$e($errors['purchased_by_employee_public_id'])?></div><?php endif?></div>
  <div class="col-12 col-md-6"><label class="form-label" for="vendor">Purchased At <span class="gateway-required-indicator" aria-hidden="true">*</span></label><input class="form-control" id="vendor" name="vendor" maxlength="150" value="<?=$v('vendor')?>" required><?php if(isset($errors['vendor'])):?><div class="invalid-feedback d-block"><?=$e($errors['vendor'])?></div><?php endif?></div>
  <div class="col-12"><label class="form-label" for="description">Description <span class="gateway-required-indicator" aria-hidden="true">*</span></label><textarea class="form-control" id="description" name="description" maxlength="2000" rows="4" data-character-counter data-character-counter-max="2000" required><?=$v('description')?></textarea><?php if(isset($errors['description'])):?><div class="invalid-feedback d-block"><?=$e($errors['description'])?></div><?php endif?></div>
 </div></section>
 <?php if($purchase['receipt_status']==='missing'):?><section class="gateway-form-section" aria-labelledby="receipt-documentation-heading"><h2 class="gateway-form-section-title" id="receipt-documentation-heading">Receipt Documentation</h2><label class="form-label" for="missing_receipt_reason">Missing Receipt Explanation <span class="gateway-required-indicator" aria-hidden="true">*</span></label><textarea class="form-control" id="missing_receipt_reason" name="missing_receipt_reason" maxlength="1000" rows="3" required><?=$v('missing_receipt_reason')?></textarea><?php if(isset($errors['missing_receipt_reason'])):?><div class="invalid-feedback d-block"><?=$e($errors['missing_receipt_reason'])?></div><?php endif?></section><?php endif?>
 <section class="gateway-form-section" aria-labelledby="correction-heading"><h2 class="gateway-form-section-title" id="correction-heading">Correction Details</h2><label class="form-label" for="correction_reason">Reason for Correction <span class="gateway-required-indicator" aria-hidden="true">*</span></label><textarea class="form-control" id="correction_reason" name="correction_reason" maxlength="500" rows="3" aria-describedby="correction-reason-help" required><?=$v('correction_reason')?></textarea><div class="form-text" id="correction-reason-help">Briefly explain why this purchase record is being changed.</div><?php if(isset($errors['correction_reason'])):?><div class="invalid-feedback d-block"><?=$e($errors['correction_reason'])?></div><?php endif?></section>
 <div class="gateway-form-actions gateway-form-actions--primary-first"><button class="btn gateway-button gateway-button--primary" type="submit">Save Correction</button><a class="btn gateway-button gateway-button--secondary" href="/community-actions/<?=$e($c->propertySlug)?>/credit-card-purchases/<?=$e($purchase['public_id'])?>">Cancel</a></div>
</div></form>
<?php $contentHtml=(string)ob_get_clean();$pageTitle='Edit Credit Card Purchase — NPM Gateway';$navbarItems=\NpmGateway\Support\Navigation::forRoute('/community-actions',dirname(__DIR__,4));$navbarUserLabel=$user->displayName;$navbarUserContext='@'.$user->username;require dirname(__DIR__,2).'/layouts/app.php';
