<?php
declare(strict_types=1);
use NpmGateway\Support\CurrencyFormatter;
$components=dirname(__DIR__,2).'/components';$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');ob_start();
$breadcrumbItems=[['label'=>'Community Actions','url'=>'/community-actions'],['label'=>$c->propertyDisplayName,'url'=>'/community-actions/'.$c->propertySlug],['label'=>'Credit Card Purchases','current'=>true]];require $components.'/breadcrumb.php';
$heading='Credit Card Purchases';$description=$c->propertyDisplayName.' — Record company credit card purchases and receipt documentation.';$eyebrow='Community Actions';$actionsHtml='<a class="btn gateway-button gateway-button--primary" href="/community-actions/'.$e($c->propertySlug).'/credit-card-purchases/create">Post Purchase</a>';require $components.'/page-header.php';
if($success!==''):?><div class="alert gateway-alert gateway-alert--success" role="status"><?=$e($success)?></div><?php endif?>
<div class="gateway-review-summary d-flex flex-wrap gap-2" aria-label="Purchase summary">
 <span class="gateway-status gateway-status--neutral"><?=$summary['total']?> Purchases</span>
 <span class="gateway-status gateway-status--information" aria-label="<?= $e(CurrencyFormatter::usd($summary['total_posted']).' total posted') ?>"><?= $e(CurrencyFormatter::usd($summary['total_posted'])) ?> Total Posted</span>
 <span class="gateway-status gateway-status--success"><?=$summary['attached']?> Receipt Attached</span>
 <span class="gateway-status gateway-status--warning"><?=$summary['missing']?> Receipt Missing</span>
</div>
<form method="get" class="gateway-directory-toolbar gateway-purchase-filters">
 <div class="gateway-purchase-filter-field gateway-purchase-filter-field--search"><label class="form-label" for="purchase-search">Search</label><input class="form-control" id="purchase-search" name="search" value="<?=$e($search)?>"></div>
 <div class="gateway-purchase-filter-field"><label class="form-label" for="purchase-receipt-status">Receipt Status</label><select class="form-select" id="purchase-receipt-status" name="receipt_status"><option value="">All receipt statuses</option><option value="attached"<?=$receipt==='attached'?' selected':''?>>Receipt Attached</option><option value="missing"<?=$receipt==='missing'?' selected':''?>>Receipt Missing</option></select></div>
 <div class="gateway-purchase-filter-actions"><button class="btn gateway-button gateway-button--secondary" type="submit">Apply Filters</button></div>
</form>
<?php if($purchases):?><div class="table-responsive gateway-directory-table-wrap"><table class="table gateway-directory-table"><thead><tr><th>Date of Purchase</th><th>Card Last Four</th><th>Amount</th><th>Purchased By</th><th>Purchased At</th><th>Receipt Status</th><th>Last Updated</th><th>Action</th></tr></thead><tbody><?php foreach($purchases as $p):?><tr><td data-label="Date of Purchase"><?=$e($p['purchase_date'])?></td><td data-label="Card Last Four">•••• <?=$e($p['card_last_four'])?></td><td data-label="Amount"><?=$e(CurrencyFormatter::usd((string)$p['amount']))?></td><td data-label="Purchased By"><?=$e($p['purchased_by_name'])?></td><td data-label="Purchased At"><?=$e($p['vendor'])?></td><td data-label="Receipt Status"><span class="gateway-status <?=$p['receipt_status']==='attached'?'gateway-status--success':'gateway-status--warning'?>"><?=$p['receipt_status']==='attached'?'Receipt Attached':'Receipt Missing'?></span></td><td data-label="Last Updated"><?=$e($p['updated_at'])?></td><td data-label="Action"><a href="/community-actions/<?=$e($c->propertySlug)?>/credit-card-purchases/<?=$e($p['public_id'])?>">View</a></td></tr><?php endforeach?></tbody></table></div><?php else:$emptyTitle=$filtersActive?'No credit card purchases match these filters.':'No credit card purchases have been recorded.';$emptyMessage=$filtersActive?'':'Post your first purchase using the button above.';$emptyIconHtml='';$emptyActionHtml='';require $components.'/empty-state.php';endif;
$contentHtml=(string)ob_get_clean();$pageTitle='Credit Card Purchases — NPM Gateway';$navbarItems=\NpmGateway\Support\Navigation::forRoute('/community-actions',dirname(__DIR__,4));$navbarUserLabel=$user->displayName;$navbarUserContext='@'.$user->username;require dirname(__DIR__,2).'/layouts/app.php';
