<?php
declare(strict_types=1);
use NpmGateway\Support\CurrencyFormatter;
$components=dirname(__DIR__,2).'/components';$e=static fn($v)=>htmlspecialchars((string)$v,ENT_QUOTES|ENT_SUBSTITUTE,'UTF-8');ob_start();
$breadcrumbItems=[['label'=>'Community Actions','url'=>'/community-actions'],['label'=>$c->propertyDisplayName,'url'=>'/community-actions/'.$c->propertySlug],['label'=>'Credit Card Purchases','url'=>'/community-actions/'.$c->propertySlug.'/credit-card-purchases'],['label'=>'Credit Card Purchase','current'=>true]];require $components.'/breadcrumb.php';
$heading='Credit Card Purchase';$description=$c->propertyDisplayName;$eyebrow='Credit Card Purchases';$actionsHtml=in_array($purchase['status'],['posted','corrected'],true)?'<a class="btn gateway-button gateway-button--secondary" href="/community-actions/'.$e($c->propertySlug).'/credit-card-purchases/'.$e($purchase['public_id']).'/edit">Edit Purchase</a>':'';require $components.'/page-header.php';
if($success!==''):?><div class="alert gateway-alert gateway-alert--success" role="status"><?=$e($success)?></div><?php endif;if($error!==''):?><div class="alert gateway-alert gateway-alert--danger" role="alert"><?=$e($error)?></div><?php endif?>
<span class="gateway-status <?=$purchase['receipt_status']==='attached'?'gateway-status--success':'gateway-status--warning'?>"><?=$purchase['receipt_status']==='attached'?'Receipt Attached':'Receipt Missing'?></span>
<section class="gateway-card gateway-review-record mt-3"><div class="gateway-card__body"><h2 class="gateway-card__title">Purchase Summary</h2><dl class="row gateway-review-record__fields">
<?php foreach([['Card Last Four','•••• '.$purchase['card_last_four']],['Date of Purchase',$purchase['purchase_date']],['Amount',CurrencyFormatter::usd((string)$purchase['amount'])],['Purchased By',$purchase['purchased_by_name']],['Purchased At',$purchase['vendor']],['Description',$purchase['description']],['Property',$purchase['property_name']],['Submitted By',$purchase['submitted_by_name']],['Submitted At',$purchase['submitted_at']],['Last Updated',$purchase['updated_at']],['Record Status',ucfirst((string)$purchase['status'])]] as [$label,$value]):?><dt class="col-sm-4 gateway-review-record__label"><?=$e($label)?></dt><dd class="col-sm-8 gateway-review-record__value"><?=$label==='Description'?nl2br($e($value)):$e($value)?></dd><?php endforeach?>
</dl></div></section>
<section class="gateway-card mt-4"><div class="gateway-card__body"><h2 class="gateway-card__title">Receipt Documentation</h2>
<?php if($purchase['receipt_status']==='attached'):?><p><span class="gateway-status gateway-status--success">Receipt Attached</span></p><p><strong>Filename:</strong> <?=$e($purchase['receipt_filename'])?><br><strong>Uploaded By:</strong> <?=$e($purchase['receipt_uploaded_by_name'])?><br><strong>Uploaded At:</strong> <?=$e($purchase['receipt_uploaded_at'])?></p><?php $receiptBase='/community-actions/'.$c->propertySlug.'/credit-card-purchases/'.$purchase['public_id'].'/receipts/'.$purchase['receipt_public_id'];?><a class="btn gateway-button gateway-button--secondary" href="<?=$e($receiptBase.'/view')?>" data-document-viewer-trigger data-document-view-url="<?=$e($receiptBase.'/view')?>" data-document-download-url="<?=$e($receiptBase.'/download')?>" data-document-title="Credit Card Receipt" data-document-filename="<?=$e($purchase['receipt_filename'])?>" data-document-mime="<?=$e($purchase['receipt_mime'])?>" data-document-description="Credit card purchase receipt">View Receipt</a>
<?php else:?><p><strong>Missing Receipt Explanation</strong></p><p><?=nl2br($e($purchase['missing_receipt_reason']))?></p><form method="post" enctype="multipart/form-data" action="/community-actions/<?=$e($c->propertySlug)?>/credit-card-purchases/<?=$e($purchase['public_id'])?>/receipt" data-processing-form data-processing-message="Uploading receipt…"><input type="hidden" name="_token" value="<?=$e($csrfToken)?>"><label class="form-label" for="receipt">Upload Receipt</label><input class="form-control" type="file" id="receipt" name="receipt" accept="application/pdf,image/jpeg,image/png" required><button class="btn gateway-button gateway-button--primary mt-3" type="submit">Upload Receipt</button></form><?php endif?>
</div></section>
<section class="gateway-review-timeline"><h2>History</h2><ol class="gateway-review-timeline__events"><?php foreach($purchase['history'] as $event):?><li class="gateway-review-timeline__event"><strong class="gateway-review-timeline__label"><?=match($event['event_type']){'posted'=>'Posted','receipt_uploaded'=>'Receipt Uploaded','corrected'=>'Corrected','voided'=>'Voided',default=>'Updated'}?></strong><div class="gateway-review-timeline__meta"><time datetime="<?=$e($event['created_at'])?>"><?=$e($event['created_at'])?></time><span><?=$e($event['actor_name'])?></span></div>
<?php if($event['event_type']==='corrected'):?><ul><?php foreach((array)($event['metadata']['changes']??[]) as $field=>$change):?><li><?php if($field==='amount'):?>Amount changed from <?=$e(CurrencyFormatter::usd((string)$change['before']))?> to <?=$e(CurrencyFormatter::usd((string)$change['after']))?><?php elseif($field==='purchased_by'):?>Purchased By changed from <?=$e($change['before']['display_name'])?> to <?=$e($change['after']['display_name'])?><?php elseif($field==='vendor'):?>Purchased At changed from <?=$e($change['before'])?> to <?=$e($change['after'])?><?php elseif($field==='description_changed'):?>Description changed<?php elseif($field==='missing_receipt_reason_changed'):?>Missing Receipt Explanation changed<?php else:?><?=ucwords(str_replace('_',' ',$e($field)))?> changed from <?=$e($change['before'])?> to <?=$e($change['after'])?><?php endif?></li><?php endforeach?></ul><p><strong>Reason for Correction</strong><br><?=$e($event['comments'])?></p><?php endif?>
</li><?php endforeach?></ol></section>
<?php if($purchase['receipt_status']==='attached')require $components.'/document-viewer.php';$contentHtml=(string)ob_get_clean();$pageTitle='Credit Card Purchase — NPM Gateway';$navbarItems=\NpmGateway\Support\Navigation::forRoute('/community-actions',dirname(__DIR__,4));$navbarUserLabel=$user->displayName;$navbarUserContext='@'.$user->username;$documentViewerAssets=$purchase['receipt_status']==='attached';require dirname(__DIR__,2).'/layouts/app.php';
